/*
 * SPDX-License-Identifier: LicenseRef-CSSL-1.0
 */
/**
 * Nudm_SDM
 * Nudm Subscriber Data Management Service. � 2019, 3GPP Organizational Partners
 * (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 2.1.0.alpha-1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * PduSessionTypes.h
 *
 *
 */

#ifndef PduSessionTypes_H_
#define PduSessionTypes_H_

#include <nlohmann/json.hpp>
#include <vector>

#include "PduSessionType.h"

namespace oai::model::udm {

/// <summary>
///
/// </summary>
class PduSessionTypes {
 public:
  PduSessionTypes();
  virtual ~PduSessionTypes();

  void validate();

  /////////////////////////////////////////////
  /// PduSessionTypes members

  /// <summary>
  ///
  /// </summary>
  oai::model::common::PduSessionType getDefaultSessionType() const;
  void setDefaultSessionType(oai::model::common::PduSessionType const& value);
  /// <summary>
  ///
  /// </summary>
  std::vector<oai::model::common::PduSessionType>& getAllowedSessionTypes();
  bool allowedSessionTypesIsSet() const;
  void unsetAllowedSessionTypes();

  friend void to_json(nlohmann::json& j, const PduSessionTypes& o);
  friend void from_json(const nlohmann::json& j, PduSessionTypes& o);

 protected:
  oai::model::common::PduSessionType m_DefaultSessionType;

  std::vector<oai::model::common::PduSessionType> m_AllowedSessionTypes;
  bool m_AllowedSessionTypesIsSet;
};

}  // namespace oai::model::udm

#endif /* PduSessionTypes_H_ */
