/**
* Nudr_DataRepository API OpenAPI file
* Unified Data Repository Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
*
* The version of the OpenAPI document: 2.2.4
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "AccessAndMobilitySubscriptionData_1.h"
#include "Helpers.h"

#include <sstream>

namespace oai::model
{

AccessAndMobilitySubscriptionData_1::AccessAndMobilitySubscriptionData_1()
{
    m_SupportedFeatures = "";
    m_SupportedFeaturesIsSet = false;
    m_GpsisIsSet = false;
    m_HssGroupId = "";
    m_HssGroupIdIsSet = false;
    m_InternalGroupIdsIsSet = false;
    m_SharedVnGroupDataIdsIsSet = false;
    m_SubscribedUeAmbrIsSet = false;
    m_NssaiIsSet = false;
    m_RatRestrictionsIsSet = false;
    m_ForbiddenAreasIsSet = false;
    m_ServiceAreaRestrictionIsSet = false;
    m_CoreNetworkTypeRestrictionsIsSet = false;
    m_RfspIndex = 0;
    m_RfspIndexIsSet = false;
    m_SubsRegTimer = 0;
    m_SubsRegTimerIsSet = false;
    m_UeUsageType = 0;
    m_UeUsageTypeIsSet = false;
    m_MpsPriority = false;
    m_MpsPriorityIsSet = false;
    m_McsPriority = false;
    m_McsPriorityIsSet = false;
    m_ActiveTime = 0;
    m_ActiveTimeIsSet = false;
    m_SorInfoIsSet = false;
    m_SorInfoExpectInd = false;
    m_SorInfoExpectIndIsSet = false;
    m_SorafRetrieval = false;
    m_SorafRetrievalIsSet = false;
    m_SorUpdateIndicatorListIsSet = false;
    m_UpuInfoIsSet = false;
    m_RoutingIndicator = "";
    m_RoutingIndicatorIsSet = false;
    m_MicoAllowed = false;
    m_MicoAllowedIsSet = false;
    m_SharedAmDataIdsIsSet = false;
    m_OdbPacketServicesIsSet = false;
    m_SubscribedDnnListIsSet = false;
    m_ServiceGapTime = 0;
    m_ServiceGapTimeIsSet = false;
    m_MdtUserConsentIsSet = false;
    m_MdtConfigurationIsSet = false;
    m_TraceDataIsSet = false;
    m_CagDataIsSet = false;
    m_StnSr = "";
    m_StnSrIsSet = false;
    m_CMsisdn = "";
    m_CMsisdnIsSet = false;
    m_NbIoTUePriority = 0;
    m_NbIoTUePriorityIsSet = false;
    m_NssaiInclusionAllowed = false;
    m_NssaiInclusionAllowedIsSet = false;
    m_RgWirelineCharacteristicsIsSet = false;
    m_EcRestrictionDataWbIsSet = false;
    m_EcRestrictionDataNb = false;
    m_EcRestrictionDataNbIsSet = false;
    m_ExpectedUeBehaviourListIsSet = false;
    m_PrimaryRatRestrictionsIsSet = false;
    m_SecondaryRatRestrictionsIsSet = false;
    m_EdrxParametersListIsSet = false;
    m_PtwParametersListIsSet = false;
    m_IabOperationAllowed = false;
    m_IabOperationAllowedIsSet = false;
    m_AdjacentPlmnRestrictionsIsSet = false;
    m_WirelineForbiddenAreasIsSet = false;
    m_WirelineServiceAreaRestrictionIsSet = false;
    m_PcfSelectionAssistanceInfosIsSet = false;
    m_AerialUeSubInfoIsSet = false;
    m_RoamingRestrictionsIsSet = false;
    m_RemoteProvInd = false;
    m_RemoteProvIndIsSet = false;
    m_r_3gppChargingCharacteristics = "";
    m_r_3gppChargingCharacteristicsIsSet = false;
    
}

void AccessAndMobilitySubscriptionData_1::validate() const
{
    std::stringstream msg;
    if (!validate(msg))
    {
        throw org::openapitools::server::helpers::ValidationException(msg.str());
    }
}

bool AccessAndMobilitySubscriptionData_1::validate(std::stringstream& msg) const
{
    return validate(msg, "");
}

bool AccessAndMobilitySubscriptionData_1::validate(std::stringstream& msg, const std::string& pathPrefix) const
{
    bool success = true;
    const std::string _pathPrefix = pathPrefix.empty() ? "AccessAndMobilitySubscriptionData_1" : pathPrefix;

         
    if (supportedFeaturesIsSet())
    {
        const std::string& value = m_SupportedFeatures;
        const std::string currentValuePath = _pathPrefix + ".supportedFeatures";
                
        

    }
         
    if (gpsisIsSet())
    {
        const std::vector<std::string>& value = m_Gpsis;
        const std::string currentValuePath = _pathPrefix + ".gpsis";
                
        
        { // Recursive validation of array elements
            const std::string oldValuePath = currentValuePath;
            int i = 0;
            for (const std::string& value : value)
            { 
                const std::string currentValuePath = oldValuePath + "[" + std::to_string(i) + "]";
                        
        
 
                i++;
            }
        }

    }
             
    if (internalGroupIdsIsSet())
    {
        const std::vector<std::string>& value = m_InternalGroupIds;
        const std::string currentValuePath = _pathPrefix + ".internalGroupIds";
                
        
        if (value.size() < 1)
        {
            success = false;
            msg << currentValuePath << ": must have at least 1 elements;";
        }
        { // Recursive validation of array elements
            const std::string oldValuePath = currentValuePath;
            int i = 0;
            for (const std::string& value : value)
            { 
                const std::string currentValuePath = oldValuePath + "[" + std::to_string(i) + "]";
                        
        
 
                i++;
            }
        }

    }
         
    if (sharedVnGroupDataIdsIsSet())
    {
        const std::map<std::string, std::string>& value = m_SharedVnGroupDataIds;
        const std::string currentValuePath = _pathPrefix + ".sharedVnGroupDataIds";
                
        

    }
                 
    if (ratRestrictionsIsSet())
    {
        const std::set<oai::model::RatType>& value = m_RatRestrictions;
        const std::string currentValuePath = _pathPrefix + ".ratRestrictions";
                
        
        if (!org::openapitools::server::helpers::hasOnlyUniqueItems(value))
        {
            success = false;
            msg << currentValuePath << ": may not contain the same item more than once;";
        }
        { // Recursive validation of array elements
            const std::string oldValuePath = currentValuePath;
            int i = 0;
            for (const oai::model::RatType& value : value)
            { 
                const std::string currentValuePath = oldValuePath + "[" + std::to_string(i) + "]";
                        
        success = value.validate(msg, currentValuePath + ".ratRestrictions") && success;
 
                i++;
            }
        }

    }
         
    if (forbiddenAreasIsSet())
    {
        const std::vector<oai::model::Area_1>& value = m_ForbiddenAreas;
        const std::string currentValuePath = _pathPrefix + ".forbiddenAreas";
                
        
        { // Recursive validation of array elements
            const std::string oldValuePath = currentValuePath;
            int i = 0;
            for (const oai::model::Area_1& value : value)
            { 
                const std::string currentValuePath = oldValuePath + "[" + std::to_string(i) + "]";
                        
        success = value.validate(msg, currentValuePath + ".forbiddenAreas") && success;
 
                i++;
            }
        }

    }
             
    if (coreNetworkTypeRestrictionsIsSet())
    {
        const std::vector<oai::model::CoreNetworkType>& value = m_CoreNetworkTypeRestrictions;
        const std::string currentValuePath = _pathPrefix + ".coreNetworkTypeRestrictions";
                
        
        { // Recursive validation of array elements
            const std::string oldValuePath = currentValuePath;
            int i = 0;
            for (const oai::model::CoreNetworkType& value : value)
            { 
                const std::string currentValuePath = oldValuePath + "[" + std::to_string(i) + "]";
                        
        success = value.validate(msg, currentValuePath + ".coreNetworkTypeRestrictions") && success;
 
                i++;
            }
        }

    }
         
    if (rfspIndexIsSet())
    {
        const int32_t& value = m_RfspIndex;
        const std::string currentValuePath = _pathPrefix + ".rfspIndex";
                
        
        if (value < 1)
        {
            success = false;
            msg << currentValuePath << ": must be greater than or equal to 1;";
        }
        if (value > 256)
        {
            success = false;
            msg << currentValuePath << ": must be less than or equal to 256;";
        }

    }
                                         
    if (sorUpdateIndicatorListIsSet())
    {
        const std::vector<oai::model::SorUpdateIndicator>& value = m_SorUpdateIndicatorList;
        const std::string currentValuePath = _pathPrefix + ".sorUpdateIndicatorList";
                
        
        if (value.size() < 1)
        {
            success = false;
            msg << currentValuePath << ": must have at least 1 elements;";
        }
        { // Recursive validation of array elements
            const std::string oldValuePath = currentValuePath;
            int i = 0;
            for (const oai::model::SorUpdateIndicator& value : value)
            { 
                const std::string currentValuePath = oldValuePath + "[" + std::to_string(i) + "]";
                        
        success = value.validate(msg, currentValuePath + ".sorUpdateIndicatorList") && success;
 
                i++;
            }
        }

    }
             
    if (routingIndicatorIsSet())
    {
        const std::string& value = m_RoutingIndicator;
        const std::string currentValuePath = _pathPrefix + ".routingIndicator";
                
        

    }
             
    if (sharedAmDataIdsIsSet())
    {
        const std::vector<std::string>& value = m_SharedAmDataIds;
        const std::string currentValuePath = _pathPrefix + ".sharedAmDataIds";
                
        
        if (value.size() < 1)
        {
            success = false;
            msg << currentValuePath << ": must have at least 1 elements;";
        }
        { // Recursive validation of array elements
            const std::string oldValuePath = currentValuePath;
            int i = 0;
            for (const std::string& value : value)
            { 
                const std::string currentValuePath = oldValuePath + "[" + std::to_string(i) + "]";
                        
        
 
                i++;
            }
        }

    }
             
    if (subscribedDnnListIsSet())
    {
        const std::vector<oai::model::AccessAndMobilitySubscriptionData_subscribedDnnList_inner>& value = m_SubscribedDnnList;
        const std::string currentValuePath = _pathPrefix + ".subscribedDnnList";
                
        
        { // Recursive validation of array elements
            const std::string oldValuePath = currentValuePath;
            int i = 0;
            for (const oai::model::AccessAndMobilitySubscriptionData_subscribedDnnList_inner& value : value)
            { 
                const std::string currentValuePath = oldValuePath + "[" + std::to_string(i) + "]";
                        
        success = value.validate(msg, currentValuePath + ".subscribedDnnList") && success;
 
                i++;
            }
        }

    }
                                 
    if (cMsisdnIsSet())
    {
        const std::string& value = m_CMsisdn;
        const std::string currentValuePath = _pathPrefix + ".cMsisdn";
                
        

    }
         
    if (nbIoTUePriorityIsSet())
    {
        const int32_t& value = m_NbIoTUePriority;
        const std::string currentValuePath = _pathPrefix + ".nbIoTUePriority";
                
        
        if (value < 0)
        {
            success = false;
            msg << currentValuePath << ": must be greater than or equal to 0;";
        }
        if (value > 255)
        {
            success = false;
            msg << currentValuePath << ": must be less than or equal to 255;";
        }

    }
                             
    if (primaryRatRestrictionsIsSet())
    {
        const std::set<oai::model::RatType>& value = m_PrimaryRatRestrictions;
        const std::string currentValuePath = _pathPrefix + ".primaryRatRestrictions";
                
        
        if (!org::openapitools::server::helpers::hasOnlyUniqueItems(value))
        {
            success = false;
            msg << currentValuePath << ": may not contain the same item more than once;";
        }
        { // Recursive validation of array elements
            const std::string oldValuePath = currentValuePath;
            int i = 0;
            for (const oai::model::RatType& value : value)
            { 
                const std::string currentValuePath = oldValuePath + "[" + std::to_string(i) + "]";
                        
        success = value.validate(msg, currentValuePath + ".primaryRatRestrictions") && success;
 
                i++;
            }
        }

    }
         
    if (secondaryRatRestrictionsIsSet())
    {
        const std::set<oai::model::RatType>& value = m_SecondaryRatRestrictions;
        const std::string currentValuePath = _pathPrefix + ".secondaryRatRestrictions";
                
        
        if (!org::openapitools::server::helpers::hasOnlyUniqueItems(value))
        {
            success = false;
            msg << currentValuePath << ": may not contain the same item more than once;";
        }
        { // Recursive validation of array elements
            const std::string oldValuePath = currentValuePath;
            int i = 0;
            for (const oai::model::RatType& value : value)
            { 
                const std::string currentValuePath = oldValuePath + "[" + std::to_string(i) + "]";
                        
        success = value.validate(msg, currentValuePath + ".secondaryRatRestrictions") && success;
 
                i++;
            }
        }

    }
         
    if (edrxParametersListIsSet())
    {
        const std::vector<oai::model::EdrxParameters_1>& value = m_EdrxParametersList;
        const std::string currentValuePath = _pathPrefix + ".edrxParametersList";
                
        
        if (value.size() < 1)
        {
            success = false;
            msg << currentValuePath << ": must have at least 1 elements;";
        }
        { // Recursive validation of array elements
            const std::string oldValuePath = currentValuePath;
            int i = 0;
            for (const oai::model::EdrxParameters_1& value : value)
            { 
                const std::string currentValuePath = oldValuePath + "[" + std::to_string(i) + "]";
                        
        success = value.validate(msg, currentValuePath + ".edrxParametersList") && success;
 
                i++;
            }
        }

    }
         
    if (ptwParametersListIsSet())
    {
        const std::vector<oai::model::PtwParameters_1>& value = m_PtwParametersList;
        const std::string currentValuePath = _pathPrefix + ".ptwParametersList";
                
        
        if (value.size() < 1)
        {
            success = false;
            msg << currentValuePath << ": must have at least 1 elements;";
        }
        { // Recursive validation of array elements
            const std::string oldValuePath = currentValuePath;
            int i = 0;
            for (const oai::model::PtwParameters_1& value : value)
            { 
                const std::string currentValuePath = oldValuePath + "[" + std::to_string(i) + "]";
                        
        success = value.validate(msg, currentValuePath + ".ptwParametersList") && success;
 
                i++;
            }
        }

    }
             
    if (adjacentPlmnRestrictionsIsSet())
    {
        const std::map<std::string, oai::model::PlmnRestriction_1>& value = m_AdjacentPlmnRestrictions;
        const std::string currentValuePath = _pathPrefix + ".adjacentPlmnRestrictions";
                
        

    }
         
    if (wirelineForbiddenAreasIsSet())
    {
        const std::vector<oai::model::WirelineArea_1>& value = m_WirelineForbiddenAreas;
        const std::string currentValuePath = _pathPrefix + ".wirelineForbiddenAreas";
                
        
        { // Recursive validation of array elements
            const std::string oldValuePath = currentValuePath;
            int i = 0;
            for (const oai::model::WirelineArea_1& value : value)
            { 
                const std::string currentValuePath = oldValuePath + "[" + std::to_string(i) + "]";
                        
        success = value.validate(msg, currentValuePath + ".wirelineForbiddenAreas") && success;
 
                i++;
            }
        }

    }
             
    if (pcfSelectionAssistanceInfosIsSet())
    {
        const std::vector<oai::model::PcfSelectionAssistanceInfo_1>& value = m_PcfSelectionAssistanceInfos;
        const std::string currentValuePath = _pathPrefix + ".pcfSelectionAssistanceInfos";
                
        
        if (value.size() < 1)
        {
            success = false;
            msg << currentValuePath << ": must have at least 1 elements;";
        }
        { // Recursive validation of array elements
            const std::string oldValuePath = currentValuePath;
            int i = 0;
            for (const oai::model::PcfSelectionAssistanceInfo_1& value : value)
            { 
                const std::string currentValuePath = oldValuePath + "[" + std::to_string(i) + "]";
                        
        success = value.validate(msg, currentValuePath + ".pcfSelectionAssistanceInfos") && success;
 
                i++;
            }
        }

    }
                    
    return success;
}

bool AccessAndMobilitySubscriptionData_1::operator==(const AccessAndMobilitySubscriptionData_1& rhs) const
{
    return
    
    
    
    ((!supportedFeaturesIsSet() && !rhs.supportedFeaturesIsSet()) || (supportedFeaturesIsSet() && rhs.supportedFeaturesIsSet() && getSupportedFeatures() == rhs.getSupportedFeatures())) &&
    
    
    ((!gpsisIsSet() && !rhs.gpsisIsSet()) || (gpsisIsSet() && rhs.gpsisIsSet() && getGpsis() == rhs.getGpsis())) &&
    
    
    ((!hssGroupIdIsSet() && !rhs.hssGroupIdIsSet()) || (hssGroupIdIsSet() && rhs.hssGroupIdIsSet() && getHssGroupId() == rhs.getHssGroupId())) &&
    
    
    ((!internalGroupIdsIsSet() && !rhs.internalGroupIdsIsSet()) || (internalGroupIdsIsSet() && rhs.internalGroupIdsIsSet() && getInternalGroupIds() == rhs.getInternalGroupIds())) &&
    
    
    ((!sharedVnGroupDataIdsIsSet() && !rhs.sharedVnGroupDataIdsIsSet()) || (sharedVnGroupDataIdsIsSet() && rhs.sharedVnGroupDataIdsIsSet() && getSharedVnGroupDataIds() == rhs.getSharedVnGroupDataIds())) &&
    
    
    ((!subscribedUeAmbrIsSet() && !rhs.subscribedUeAmbrIsSet()) || (subscribedUeAmbrIsSet() && rhs.subscribedUeAmbrIsSet() && getSubscribedUeAmbr() == rhs.getSubscribedUeAmbr())) &&
    
    
    ((!nssaiIsSet() && !rhs.nssaiIsSet()) || (nssaiIsSet() && rhs.nssaiIsSet() && getNssai() == rhs.getNssai())) &&
    
    
    ((!ratRestrictionsIsSet() && !rhs.ratRestrictionsIsSet()) || (ratRestrictionsIsSet() && rhs.ratRestrictionsIsSet() && getRatRestrictions() == rhs.getRatRestrictions())) &&
    
    
    ((!forbiddenAreasIsSet() && !rhs.forbiddenAreasIsSet()) || (forbiddenAreasIsSet() && rhs.forbiddenAreasIsSet() && getForbiddenAreas() == rhs.getForbiddenAreas())) &&
    
    
    ((!serviceAreaRestrictionIsSet() && !rhs.serviceAreaRestrictionIsSet()) || (serviceAreaRestrictionIsSet() && rhs.serviceAreaRestrictionIsSet() && getServiceAreaRestriction() == rhs.getServiceAreaRestriction())) &&
    
    
    ((!coreNetworkTypeRestrictionsIsSet() && !rhs.coreNetworkTypeRestrictionsIsSet()) || (coreNetworkTypeRestrictionsIsSet() && rhs.coreNetworkTypeRestrictionsIsSet() && getCoreNetworkTypeRestrictions() == rhs.getCoreNetworkTypeRestrictions())) &&
    
    
    ((!rfspIndexIsSet() && !rhs.rfspIndexIsSet()) || (rfspIndexIsSet() && rhs.rfspIndexIsSet() && getRfspIndex() == rhs.getRfspIndex())) &&
    
    
    ((!subsRegTimerIsSet() && !rhs.subsRegTimerIsSet()) || (subsRegTimerIsSet() && rhs.subsRegTimerIsSet() && getSubsRegTimer() == rhs.getSubsRegTimer())) &&
    
    
    ((!ueUsageTypeIsSet() && !rhs.ueUsageTypeIsSet()) || (ueUsageTypeIsSet() && rhs.ueUsageTypeIsSet() && getUeUsageType() == rhs.getUeUsageType())) &&
    
    
    ((!mpsPriorityIsSet() && !rhs.mpsPriorityIsSet()) || (mpsPriorityIsSet() && rhs.mpsPriorityIsSet() && isMpsPriority() == rhs.isMpsPriority())) &&
    
    
    ((!mcsPriorityIsSet() && !rhs.mcsPriorityIsSet()) || (mcsPriorityIsSet() && rhs.mcsPriorityIsSet() && isMcsPriority() == rhs.isMcsPriority())) &&
    
    
    ((!activeTimeIsSet() && !rhs.activeTimeIsSet()) || (activeTimeIsSet() && rhs.activeTimeIsSet() && getActiveTime() == rhs.getActiveTime())) &&
    
    
    ((!sorInfoIsSet() && !rhs.sorInfoIsSet()) || (sorInfoIsSet() && rhs.sorInfoIsSet() && getSorInfo() == rhs.getSorInfo())) &&
    
    
    ((!sorInfoExpectIndIsSet() && !rhs.sorInfoExpectIndIsSet()) || (sorInfoExpectIndIsSet() && rhs.sorInfoExpectIndIsSet() && isSorInfoExpectInd() == rhs.isSorInfoExpectInd())) &&
    
    
    ((!sorafRetrievalIsSet() && !rhs.sorafRetrievalIsSet()) || (sorafRetrievalIsSet() && rhs.sorafRetrievalIsSet() && isSorafRetrieval() == rhs.isSorafRetrieval())) &&
    
    
    ((!sorUpdateIndicatorListIsSet() && !rhs.sorUpdateIndicatorListIsSet()) || (sorUpdateIndicatorListIsSet() && rhs.sorUpdateIndicatorListIsSet() && getSorUpdateIndicatorList() == rhs.getSorUpdateIndicatorList())) &&
    
    
    ((!upuInfoIsSet() && !rhs.upuInfoIsSet()) || (upuInfoIsSet() && rhs.upuInfoIsSet() && getUpuInfo() == rhs.getUpuInfo())) &&
    
    
    ((!routingIndicatorIsSet() && !rhs.routingIndicatorIsSet()) || (routingIndicatorIsSet() && rhs.routingIndicatorIsSet() && getRoutingIndicator() == rhs.getRoutingIndicator())) &&
    
    
    ((!micoAllowedIsSet() && !rhs.micoAllowedIsSet()) || (micoAllowedIsSet() && rhs.micoAllowedIsSet() && isMicoAllowed() == rhs.isMicoAllowed())) &&
    
    
    ((!sharedAmDataIdsIsSet() && !rhs.sharedAmDataIdsIsSet()) || (sharedAmDataIdsIsSet() && rhs.sharedAmDataIdsIsSet() && getSharedAmDataIds() == rhs.getSharedAmDataIds())) &&
    
    
    ((!odbPacketServicesIsSet() && !rhs.odbPacketServicesIsSet()) || (odbPacketServicesIsSet() && rhs.odbPacketServicesIsSet() && getOdbPacketServices() == rhs.getOdbPacketServices())) &&
    
    
    ((!subscribedDnnListIsSet() && !rhs.subscribedDnnListIsSet()) || (subscribedDnnListIsSet() && rhs.subscribedDnnListIsSet() && getSubscribedDnnList() == rhs.getSubscribedDnnList())) &&
    
    
    ((!serviceGapTimeIsSet() && !rhs.serviceGapTimeIsSet()) || (serviceGapTimeIsSet() && rhs.serviceGapTimeIsSet() && getServiceGapTime() == rhs.getServiceGapTime())) &&
    
    
    ((!mdtUserConsentIsSet() && !rhs.mdtUserConsentIsSet()) || (mdtUserConsentIsSet() && rhs.mdtUserConsentIsSet() && getMdtUserConsent() == rhs.getMdtUserConsent())) &&
    
    
    ((!mdtConfigurationIsSet() && !rhs.mdtConfigurationIsSet()) || (mdtConfigurationIsSet() && rhs.mdtConfigurationIsSet() && getMdtConfiguration() == rhs.getMdtConfiguration())) &&
    
    
    ((!traceDataIsSet() && !rhs.traceDataIsSet()) || (traceDataIsSet() && rhs.traceDataIsSet() && getTraceData() == rhs.getTraceData())) &&
    
    
    ((!cagDataIsSet() && !rhs.cagDataIsSet()) || (cagDataIsSet() && rhs.cagDataIsSet() && getCagData() == rhs.getCagData())) &&
    
    
    ((!stnSrIsSet() && !rhs.stnSrIsSet()) || (stnSrIsSet() && rhs.stnSrIsSet() && getStnSr() == rhs.getStnSr())) &&
    
    
    ((!cMsisdnIsSet() && !rhs.cMsisdnIsSet()) || (cMsisdnIsSet() && rhs.cMsisdnIsSet() && getCMsisdn() == rhs.getCMsisdn())) &&
    
    
    ((!nbIoTUePriorityIsSet() && !rhs.nbIoTUePriorityIsSet()) || (nbIoTUePriorityIsSet() && rhs.nbIoTUePriorityIsSet() && getNbIoTUePriority() == rhs.getNbIoTUePriority())) &&
    
    
    ((!nssaiInclusionAllowedIsSet() && !rhs.nssaiInclusionAllowedIsSet()) || (nssaiInclusionAllowedIsSet() && rhs.nssaiInclusionAllowedIsSet() && isNssaiInclusionAllowed() == rhs.isNssaiInclusionAllowed())) &&
    
    
    ((!rgWirelineCharacteristicsIsSet() && !rhs.rgWirelineCharacteristicsIsSet()) || (rgWirelineCharacteristicsIsSet() && rhs.rgWirelineCharacteristicsIsSet() && getRgWirelineCharacteristics() == rhs.getRgWirelineCharacteristics())) &&
    
    
    ((!ecRestrictionDataWbIsSet() && !rhs.ecRestrictionDataWbIsSet()) || (ecRestrictionDataWbIsSet() && rhs.ecRestrictionDataWbIsSet() && getEcRestrictionDataWb() == rhs.getEcRestrictionDataWb())) &&
    
    
    ((!ecRestrictionDataNbIsSet() && !rhs.ecRestrictionDataNbIsSet()) || (ecRestrictionDataNbIsSet() && rhs.ecRestrictionDataNbIsSet() && isEcRestrictionDataNb() == rhs.isEcRestrictionDataNb())) &&
    
    
    ((!expectedUeBehaviourListIsSet() && !rhs.expectedUeBehaviourListIsSet()) || (expectedUeBehaviourListIsSet() && rhs.expectedUeBehaviourListIsSet() && getExpectedUeBehaviourList() == rhs.getExpectedUeBehaviourList())) &&
    
    
    ((!primaryRatRestrictionsIsSet() && !rhs.primaryRatRestrictionsIsSet()) || (primaryRatRestrictionsIsSet() && rhs.primaryRatRestrictionsIsSet() && getPrimaryRatRestrictions() == rhs.getPrimaryRatRestrictions())) &&
    
    
    ((!secondaryRatRestrictionsIsSet() && !rhs.secondaryRatRestrictionsIsSet()) || (secondaryRatRestrictionsIsSet() && rhs.secondaryRatRestrictionsIsSet() && getSecondaryRatRestrictions() == rhs.getSecondaryRatRestrictions())) &&
    
    
    ((!edrxParametersListIsSet() && !rhs.edrxParametersListIsSet()) || (edrxParametersListIsSet() && rhs.edrxParametersListIsSet() && getEdrxParametersList() == rhs.getEdrxParametersList())) &&
    
    
    ((!ptwParametersListIsSet() && !rhs.ptwParametersListIsSet()) || (ptwParametersListIsSet() && rhs.ptwParametersListIsSet() && getPtwParametersList() == rhs.getPtwParametersList())) &&
    
    
    ((!iabOperationAllowedIsSet() && !rhs.iabOperationAllowedIsSet()) || (iabOperationAllowedIsSet() && rhs.iabOperationAllowedIsSet() && isIabOperationAllowed() == rhs.isIabOperationAllowed())) &&
    
    
    ((!adjacentPlmnRestrictionsIsSet() && !rhs.adjacentPlmnRestrictionsIsSet()) || (adjacentPlmnRestrictionsIsSet() && rhs.adjacentPlmnRestrictionsIsSet() && getAdjacentPlmnRestrictions() == rhs.getAdjacentPlmnRestrictions())) &&
    
    
    ((!wirelineForbiddenAreasIsSet() && !rhs.wirelineForbiddenAreasIsSet()) || (wirelineForbiddenAreasIsSet() && rhs.wirelineForbiddenAreasIsSet() && getWirelineForbiddenAreas() == rhs.getWirelineForbiddenAreas())) &&
    
    
    ((!wirelineServiceAreaRestrictionIsSet() && !rhs.wirelineServiceAreaRestrictionIsSet()) || (wirelineServiceAreaRestrictionIsSet() && rhs.wirelineServiceAreaRestrictionIsSet() && getWirelineServiceAreaRestriction() == rhs.getWirelineServiceAreaRestriction())) &&
    
    
    ((!pcfSelectionAssistanceInfosIsSet() && !rhs.pcfSelectionAssistanceInfosIsSet()) || (pcfSelectionAssistanceInfosIsSet() && rhs.pcfSelectionAssistanceInfosIsSet() && getPcfSelectionAssistanceInfos() == rhs.getPcfSelectionAssistanceInfos())) &&
    
    
    ((!aerialUeSubInfoIsSet() && !rhs.aerialUeSubInfoIsSet()) || (aerialUeSubInfoIsSet() && rhs.aerialUeSubInfoIsSet() && getAerialUeSubInfo() == rhs.getAerialUeSubInfo())) &&
    
    
    ((!roamingRestrictionsIsSet() && !rhs.roamingRestrictionsIsSet()) || (roamingRestrictionsIsSet() && rhs.roamingRestrictionsIsSet() && getRoamingRestrictions() == rhs.getRoamingRestrictions())) &&
    
    
    ((!remoteProvIndIsSet() && !rhs.remoteProvIndIsSet()) || (remoteProvIndIsSet() && rhs.remoteProvIndIsSet() && isRemoteProvInd() == rhs.isRemoteProvInd())) &&
    
    
    ((!r3gppChargingCharacteristicsIsSet() && !rhs.r3gppChargingCharacteristicsIsSet()) || (r3gppChargingCharacteristicsIsSet() && rhs.r3gppChargingCharacteristicsIsSet() && getR3gppChargingCharacteristics() == rhs.getR3gppChargingCharacteristics()))
    
    ;
}

bool AccessAndMobilitySubscriptionData_1::operator!=(const AccessAndMobilitySubscriptionData_1& rhs) const
{
    return !(*this == rhs);
}

void to_json(nlohmann::json& j, const AccessAndMobilitySubscriptionData_1& o)
{
    j = nlohmann::json::object();
    if(o.supportedFeaturesIsSet())
        j["supportedFeatures"] = o.m_SupportedFeatures;
    if(o.gpsisIsSet() || !o.m_Gpsis.empty())
        j["gpsis"] = o.m_Gpsis;
    if(o.hssGroupIdIsSet())
        j["hssGroupId"] = o.m_HssGroupId;
    if(o.internalGroupIdsIsSet() || !o.m_InternalGroupIds.empty())
        j["internalGroupIds"] = o.m_InternalGroupIds;
    if(o.sharedVnGroupDataIdsIsSet() || !o.m_SharedVnGroupDataIds.empty())
        j["sharedVnGroupDataIds"] = o.m_SharedVnGroupDataIds;
    if(o.subscribedUeAmbrIsSet())
        j["subscribedUeAmbr"] = o.m_SubscribedUeAmbr;
    if(o.nssaiIsSet())
        j["nssai"] = o.m_Nssai;
    if(o.ratRestrictionsIsSet() || !o.m_RatRestrictions.empty())
        j["ratRestrictions"] = o.m_RatRestrictions;
    if(o.forbiddenAreasIsSet() || !o.m_ForbiddenAreas.empty())
        j["forbiddenAreas"] = o.m_ForbiddenAreas;
    if(o.serviceAreaRestrictionIsSet())
        j["serviceAreaRestriction"] = o.m_ServiceAreaRestriction;
    if(o.coreNetworkTypeRestrictionsIsSet() || !o.m_CoreNetworkTypeRestrictions.empty())
        j["coreNetworkTypeRestrictions"] = o.m_CoreNetworkTypeRestrictions;
    if(o.rfspIndexIsSet())
        j["rfspIndex"] = o.m_RfspIndex;
    if(o.subsRegTimerIsSet())
        j["subsRegTimer"] = o.m_SubsRegTimer;
    if(o.ueUsageTypeIsSet())
        j["ueUsageType"] = o.m_UeUsageType;
    if(o.mpsPriorityIsSet())
        j["mpsPriority"] = o.m_MpsPriority;
    if(o.mcsPriorityIsSet())
        j["mcsPriority"] = o.m_McsPriority;
    if(o.activeTimeIsSet())
        j["activeTime"] = o.m_ActiveTime;
    if(o.sorInfoIsSet())
        j["sorInfo"] = o.m_SorInfo;
    if(o.sorInfoExpectIndIsSet())
        j["sorInfoExpectInd"] = o.m_SorInfoExpectInd;
    if(o.sorafRetrievalIsSet())
        j["sorafRetrieval"] = o.m_SorafRetrieval;
    if(o.sorUpdateIndicatorListIsSet() || !o.m_SorUpdateIndicatorList.empty())
        j["sorUpdateIndicatorList"] = o.m_SorUpdateIndicatorList;
    if(o.upuInfoIsSet())
        j["upuInfo"] = o.m_UpuInfo;
    if(o.routingIndicatorIsSet())
        j["routingIndicator"] = o.m_RoutingIndicator;
    if(o.micoAllowedIsSet())
        j["micoAllowed"] = o.m_MicoAllowed;
    if(o.sharedAmDataIdsIsSet() || !o.m_SharedAmDataIds.empty())
        j["sharedAmDataIds"] = o.m_SharedAmDataIds;
    if(o.odbPacketServicesIsSet())
        j["odbPacketServices"] = o.m_OdbPacketServices;
    if(o.subscribedDnnListIsSet() || !o.m_SubscribedDnnList.empty())
        j["subscribedDnnList"] = o.m_SubscribedDnnList;
    if(o.serviceGapTimeIsSet())
        j["serviceGapTime"] = o.m_ServiceGapTime;
    if(o.mdtUserConsentIsSet())
        j["mdtUserConsent"] = o.m_MdtUserConsent;
    if(o.mdtConfigurationIsSet())
        j["mdtConfiguration"] = o.m_MdtConfiguration;
    if(o.traceDataIsSet())
        j["traceData"] = o.m_TraceData;
    if(o.cagDataIsSet())
        j["cagData"] = o.m_CagData;
    if(o.stnSrIsSet())
        j["stnSr"] = o.m_StnSr;
    if(o.cMsisdnIsSet())
        j["cMsisdn"] = o.m_CMsisdn;
    if(o.nbIoTUePriorityIsSet())
        j["nbIoTUePriority"] = o.m_NbIoTUePriority;
    if(o.nssaiInclusionAllowedIsSet())
        j["nssaiInclusionAllowed"] = o.m_NssaiInclusionAllowed;
    if(o.rgWirelineCharacteristicsIsSet())
        j["rgWirelineCharacteristics"] = o.m_RgWirelineCharacteristics;
    if(o.ecRestrictionDataWbIsSet())
        j["ecRestrictionDataWb"] = o.m_EcRestrictionDataWb;
    if(o.ecRestrictionDataNbIsSet())
        j["ecRestrictionDataNb"] = o.m_EcRestrictionDataNb;
    if(o.expectedUeBehaviourListIsSet())
        j["expectedUeBehaviourList"] = o.m_ExpectedUeBehaviourList;
    if(o.primaryRatRestrictionsIsSet() || !o.m_PrimaryRatRestrictions.empty())
        j["primaryRatRestrictions"] = o.m_PrimaryRatRestrictions;
    if(o.secondaryRatRestrictionsIsSet() || !o.m_SecondaryRatRestrictions.empty())
        j["secondaryRatRestrictions"] = o.m_SecondaryRatRestrictions;
    if(o.edrxParametersListIsSet() || !o.m_EdrxParametersList.empty())
        j["edrxParametersList"] = o.m_EdrxParametersList;
    if(o.ptwParametersListIsSet() || !o.m_PtwParametersList.empty())
        j["ptwParametersList"] = o.m_PtwParametersList;
    if(o.iabOperationAllowedIsSet())
        j["iabOperationAllowed"] = o.m_IabOperationAllowed;
    if(o.adjacentPlmnRestrictionsIsSet() || !o.m_AdjacentPlmnRestrictions.empty())
        j["adjacentPlmnRestrictions"] = o.m_AdjacentPlmnRestrictions;
    if(o.wirelineForbiddenAreasIsSet() || !o.m_WirelineForbiddenAreas.empty())
        j["wirelineForbiddenAreas"] = o.m_WirelineForbiddenAreas;
    if(o.wirelineServiceAreaRestrictionIsSet())
        j["wirelineServiceAreaRestriction"] = o.m_WirelineServiceAreaRestriction;
    if(o.pcfSelectionAssistanceInfosIsSet() || !o.m_PcfSelectionAssistanceInfos.empty())
        j["pcfSelectionAssistanceInfos"] = o.m_PcfSelectionAssistanceInfos;
    if(o.aerialUeSubInfoIsSet())
        j["aerialUeSubInfo"] = o.m_AerialUeSubInfo;
    if(o.roamingRestrictionsIsSet())
        j["roamingRestrictions"] = o.m_RoamingRestrictions;
    if(o.remoteProvIndIsSet())
        j["remoteProvInd"] = o.m_RemoteProvInd;
    if(o.r3gppChargingCharacteristicsIsSet())
        j["3gppChargingCharacteristics"] = o.m_r_3gppChargingCharacteristics;
    
}

void from_json(const nlohmann::json& j, AccessAndMobilitySubscriptionData_1& o)
{
    if(j.find("supportedFeatures") != j.end())
    {
        j.at("supportedFeatures").get_to(o.m_SupportedFeatures);
        o.m_SupportedFeaturesIsSet = true;
    } 
    if(j.find("gpsis") != j.end())
    {
        j.at("gpsis").get_to(o.m_Gpsis);
        o.m_GpsisIsSet = true;
    } 
    if(j.find("hssGroupId") != j.end())
    {
        j.at("hssGroupId").get_to(o.m_HssGroupId);
        o.m_HssGroupIdIsSet = true;
    } 
    if(j.find("internalGroupIds") != j.end())
    {
        j.at("internalGroupIds").get_to(o.m_InternalGroupIds);
        o.m_InternalGroupIdsIsSet = true;
    } 
    if(j.find("sharedVnGroupDataIds") != j.end())
    {
        j.at("sharedVnGroupDataIds").get_to(o.m_SharedVnGroupDataIds);
        o.m_SharedVnGroupDataIdsIsSet = true;
    } 
    if(j.find("subscribedUeAmbr") != j.end())
    {
        j.at("subscribedUeAmbr").get_to(o.m_SubscribedUeAmbr);
        o.m_SubscribedUeAmbrIsSet = true;
    } 
    if(j.find("nssai") != j.end())
    {
        j.at("nssai").get_to(o.m_Nssai);
        o.m_NssaiIsSet = true;
    } 
    if(j.find("ratRestrictions") != j.end())
    {
        j.at("ratRestrictions").get_to(o.m_RatRestrictions);
        o.m_RatRestrictionsIsSet = true;
    } 
    if(j.find("forbiddenAreas") != j.end())
    {
        j.at("forbiddenAreas").get_to(o.m_ForbiddenAreas);
        o.m_ForbiddenAreasIsSet = true;
    } 
    if(j.find("serviceAreaRestriction") != j.end())
    {
        j.at("serviceAreaRestriction").get_to(o.m_ServiceAreaRestriction);
        o.m_ServiceAreaRestrictionIsSet = true;
    } 
    if(j.find("coreNetworkTypeRestrictions") != j.end())
    {
        j.at("coreNetworkTypeRestrictions").get_to(o.m_CoreNetworkTypeRestrictions);
        o.m_CoreNetworkTypeRestrictionsIsSet = true;
    } 
    if(j.find("rfspIndex") != j.end())
    {
        j.at("rfspIndex").get_to(o.m_RfspIndex);
        o.m_RfspIndexIsSet = true;
    } 
    if(j.find("subsRegTimer") != j.end())
    {
        j.at("subsRegTimer").get_to(o.m_SubsRegTimer);
        o.m_SubsRegTimerIsSet = true;
    } 
    if(j.find("ueUsageType") != j.end())
    {
        j.at("ueUsageType").get_to(o.m_UeUsageType);
        o.m_UeUsageTypeIsSet = true;
    } 
    if(j.find("mpsPriority") != j.end())
    {
        j.at("mpsPriority").get_to(o.m_MpsPriority);
        o.m_MpsPriorityIsSet = true;
    } 
    if(j.find("mcsPriority") != j.end())
    {
        j.at("mcsPriority").get_to(o.m_McsPriority);
        o.m_McsPriorityIsSet = true;
    } 
    if(j.find("activeTime") != j.end())
    {
        j.at("activeTime").get_to(o.m_ActiveTime);
        o.m_ActiveTimeIsSet = true;
    } 
    if(j.find("sorInfo") != j.end())
    {
        j.at("sorInfo").get_to(o.m_SorInfo);
        o.m_SorInfoIsSet = true;
    } 
    if(j.find("sorInfoExpectInd") != j.end())
    {
        j.at("sorInfoExpectInd").get_to(o.m_SorInfoExpectInd);
        o.m_SorInfoExpectIndIsSet = true;
    } 
    if(j.find("sorafRetrieval") != j.end())
    {
        j.at("sorafRetrieval").get_to(o.m_SorafRetrieval);
        o.m_SorafRetrievalIsSet = true;
    } 
    if(j.find("sorUpdateIndicatorList") != j.end())
    {
        j.at("sorUpdateIndicatorList").get_to(o.m_SorUpdateIndicatorList);
        o.m_SorUpdateIndicatorListIsSet = true;
    } 
    if(j.find("upuInfo") != j.end())
    {
        j.at("upuInfo").get_to(o.m_UpuInfo);
        o.m_UpuInfoIsSet = true;
    } 
    if(j.find("routingIndicator") != j.end())
    {
        j.at("routingIndicator").get_to(o.m_RoutingIndicator);
        o.m_RoutingIndicatorIsSet = true;
    } 
    if(j.find("micoAllowed") != j.end())
    {
        j.at("micoAllowed").get_to(o.m_MicoAllowed);
        o.m_MicoAllowedIsSet = true;
    } 
    if(j.find("sharedAmDataIds") != j.end())
    {
        j.at("sharedAmDataIds").get_to(o.m_SharedAmDataIds);
        o.m_SharedAmDataIdsIsSet = true;
    } 
    if(j.find("odbPacketServices") != j.end())
    {
        j.at("odbPacketServices").get_to(o.m_OdbPacketServices);
        o.m_OdbPacketServicesIsSet = true;
    } 
    if(j.find("subscribedDnnList") != j.end())
    {
        j.at("subscribedDnnList").get_to(o.m_SubscribedDnnList);
        o.m_SubscribedDnnListIsSet = true;
    } 
    if(j.find("serviceGapTime") != j.end())
    {
        j.at("serviceGapTime").get_to(o.m_ServiceGapTime);
        o.m_ServiceGapTimeIsSet = true;
    } 
    if(j.find("mdtUserConsent") != j.end())
    {
        j.at("mdtUserConsent").get_to(o.m_MdtUserConsent);
        o.m_MdtUserConsentIsSet = true;
    } 
    if(j.find("mdtConfiguration") != j.end())
    {
        j.at("mdtConfiguration").get_to(o.m_MdtConfiguration);
        o.m_MdtConfigurationIsSet = true;
    } 
    if(j.find("traceData") != j.end())
    {
        j.at("traceData").get_to(o.m_TraceData);
        o.m_TraceDataIsSet = true;
    } 
    if(j.find("cagData") != j.end())
    {
        j.at("cagData").get_to(o.m_CagData);
        o.m_CagDataIsSet = true;
    } 
    if(j.find("stnSr") != j.end())
    {
        j.at("stnSr").get_to(o.m_StnSr);
        o.m_StnSrIsSet = true;
    } 
    if(j.find("cMsisdn") != j.end())
    {
        j.at("cMsisdn").get_to(o.m_CMsisdn);
        o.m_CMsisdnIsSet = true;
    } 
    if(j.find("nbIoTUePriority") != j.end())
    {
        j.at("nbIoTUePriority").get_to(o.m_NbIoTUePriority);
        o.m_NbIoTUePriorityIsSet = true;
    } 
    if(j.find("nssaiInclusionAllowed") != j.end())
    {
        j.at("nssaiInclusionAllowed").get_to(o.m_NssaiInclusionAllowed);
        o.m_NssaiInclusionAllowedIsSet = true;
    } 
    if(j.find("rgWirelineCharacteristics") != j.end())
    {
        j.at("rgWirelineCharacteristics").get_to(o.m_RgWirelineCharacteristics);
        o.m_RgWirelineCharacteristicsIsSet = true;
    } 
    if(j.find("ecRestrictionDataWb") != j.end())
    {
        j.at("ecRestrictionDataWb").get_to(o.m_EcRestrictionDataWb);
        o.m_EcRestrictionDataWbIsSet = true;
    } 
    if(j.find("ecRestrictionDataNb") != j.end())
    {
        j.at("ecRestrictionDataNb").get_to(o.m_EcRestrictionDataNb);
        o.m_EcRestrictionDataNbIsSet = true;
    } 
    if(j.find("expectedUeBehaviourList") != j.end())
    {
        j.at("expectedUeBehaviourList").get_to(o.m_ExpectedUeBehaviourList);
        o.m_ExpectedUeBehaviourListIsSet = true;
    } 
    if(j.find("primaryRatRestrictions") != j.end())
    {
        j.at("primaryRatRestrictions").get_to(o.m_PrimaryRatRestrictions);
        o.m_PrimaryRatRestrictionsIsSet = true;
    } 
    if(j.find("secondaryRatRestrictions") != j.end())
    {
        j.at("secondaryRatRestrictions").get_to(o.m_SecondaryRatRestrictions);
        o.m_SecondaryRatRestrictionsIsSet = true;
    } 
    if(j.find("edrxParametersList") != j.end())
    {
        j.at("edrxParametersList").get_to(o.m_EdrxParametersList);
        o.m_EdrxParametersListIsSet = true;
    } 
    if(j.find("ptwParametersList") != j.end())
    {
        j.at("ptwParametersList").get_to(o.m_PtwParametersList);
        o.m_PtwParametersListIsSet = true;
    } 
    if(j.find("iabOperationAllowed") != j.end())
    {
        j.at("iabOperationAllowed").get_to(o.m_IabOperationAllowed);
        o.m_IabOperationAllowedIsSet = true;
    } 
    if(j.find("adjacentPlmnRestrictions") != j.end())
    {
        j.at("adjacentPlmnRestrictions").get_to(o.m_AdjacentPlmnRestrictions);
        o.m_AdjacentPlmnRestrictionsIsSet = true;
    } 
    if(j.find("wirelineForbiddenAreas") != j.end())
    {
        j.at("wirelineForbiddenAreas").get_to(o.m_WirelineForbiddenAreas);
        o.m_WirelineForbiddenAreasIsSet = true;
    } 
    if(j.find("wirelineServiceAreaRestriction") != j.end())
    {
        j.at("wirelineServiceAreaRestriction").get_to(o.m_WirelineServiceAreaRestriction);
        o.m_WirelineServiceAreaRestrictionIsSet = true;
    } 
    if(j.find("pcfSelectionAssistanceInfos") != j.end())
    {
        j.at("pcfSelectionAssistanceInfos").get_to(o.m_PcfSelectionAssistanceInfos);
        o.m_PcfSelectionAssistanceInfosIsSet = true;
    } 
    if(j.find("aerialUeSubInfo") != j.end())
    {
        j.at("aerialUeSubInfo").get_to(o.m_AerialUeSubInfo);
        o.m_AerialUeSubInfoIsSet = true;
    } 
    if(j.find("roamingRestrictions") != j.end())
    {
        j.at("roamingRestrictions").get_to(o.m_RoamingRestrictions);
        o.m_RoamingRestrictionsIsSet = true;
    } 
    if(j.find("remoteProvInd") != j.end())
    {
        j.at("remoteProvInd").get_to(o.m_RemoteProvInd);
        o.m_RemoteProvIndIsSet = true;
    } 
    if(j.find("3gppChargingCharacteristics") != j.end())
    {
        j.at("3gppChargingCharacteristics").get_to(o.m_r_3gppChargingCharacteristics);
        o.m_r_3gppChargingCharacteristicsIsSet = true;
    } 
    
}

std::string AccessAndMobilitySubscriptionData_1::getSupportedFeatures() const
{
    return m_SupportedFeatures;
}
void AccessAndMobilitySubscriptionData_1::setSupportedFeatures(std::string const& value)
{
    m_SupportedFeatures = value;
    m_SupportedFeaturesIsSet = true;
}
bool AccessAndMobilitySubscriptionData_1::supportedFeaturesIsSet() const
{
    return m_SupportedFeaturesIsSet;
}
void AccessAndMobilitySubscriptionData_1::unsetSupportedFeatures()
{
    m_SupportedFeaturesIsSet = false;
}
std::vector<std::string> AccessAndMobilitySubscriptionData_1::getGpsis() const
{
    return m_Gpsis;
}
void AccessAndMobilitySubscriptionData_1::setGpsis(std::vector<std::string> const& value)
{
    m_Gpsis = value;
    m_GpsisIsSet = true;
}
bool AccessAndMobilitySubscriptionData_1::gpsisIsSet() const
{
    return m_GpsisIsSet;
}
void AccessAndMobilitySubscriptionData_1::unsetGpsis()
{
    m_GpsisIsSet = false;
}
std::string AccessAndMobilitySubscriptionData_1::getHssGroupId() const
{
    return m_HssGroupId;
}
void AccessAndMobilitySubscriptionData_1::setHssGroupId(std::string const& value)
{
    m_HssGroupId = value;
    m_HssGroupIdIsSet = true;
}
bool AccessAndMobilitySubscriptionData_1::hssGroupIdIsSet() const
{
    return m_HssGroupIdIsSet;
}
void AccessAndMobilitySubscriptionData_1::unsetHssGroupId()
{
    m_HssGroupIdIsSet = false;
}
std::vector<std::string> AccessAndMobilitySubscriptionData_1::getInternalGroupIds() const
{
    return m_InternalGroupIds;
}
void AccessAndMobilitySubscriptionData_1::setInternalGroupIds(std::vector<std::string> const& value)
{
    m_InternalGroupIds = value;
    m_InternalGroupIdsIsSet = true;
}
bool AccessAndMobilitySubscriptionData_1::internalGroupIdsIsSet() const
{
    return m_InternalGroupIdsIsSet;
}
void AccessAndMobilitySubscriptionData_1::unsetInternalGroupIds()
{
    m_InternalGroupIdsIsSet = false;
}
std::map<std::string, std::string> AccessAndMobilitySubscriptionData_1::getSharedVnGroupDataIds() const
{
    return m_SharedVnGroupDataIds;
}
void AccessAndMobilitySubscriptionData_1::setSharedVnGroupDataIds(std::map<std::string, std::string> const& value)
{
    m_SharedVnGroupDataIds = value;
    m_SharedVnGroupDataIdsIsSet = true;
}
bool AccessAndMobilitySubscriptionData_1::sharedVnGroupDataIdsIsSet() const
{
    return m_SharedVnGroupDataIdsIsSet;
}
void AccessAndMobilitySubscriptionData_1::unsetSharedVnGroupDataIds()
{
    m_SharedVnGroupDataIdsIsSet = false;
}
oai::model::Ambr AccessAndMobilitySubscriptionData_1::getSubscribedUeAmbr() const
{
    return m_SubscribedUeAmbr;
}
void AccessAndMobilitySubscriptionData_1::setSubscribedUeAmbr(oai::model::Ambr const& value)
{
    m_SubscribedUeAmbr = value;
    m_SubscribedUeAmbrIsSet = true;
}
bool AccessAndMobilitySubscriptionData_1::subscribedUeAmbrIsSet() const
{
    return m_SubscribedUeAmbrIsSet;
}
void AccessAndMobilitySubscriptionData_1::unsetSubscribedUeAmbr()
{
    m_SubscribedUeAmbrIsSet = false;
}
oai::model::Nssai_1 AccessAndMobilitySubscriptionData_1::getNssai() const
{
    return m_Nssai;
}
void AccessAndMobilitySubscriptionData_1::setNssai(oai::model::Nssai_1 const& value)
{
    m_Nssai = value;
    m_NssaiIsSet = true;
}
bool AccessAndMobilitySubscriptionData_1::nssaiIsSet() const
{
    return m_NssaiIsSet;
}
void AccessAndMobilitySubscriptionData_1::unsetNssai()
{
    m_NssaiIsSet = false;
}
std::set<oai::model::RatType> AccessAndMobilitySubscriptionData_1::getRatRestrictions() const
{
    return m_RatRestrictions;
}
void AccessAndMobilitySubscriptionData_1::setRatRestrictions(std::set<oai::model::RatType> const& value)
{
    m_RatRestrictions = value;
    m_RatRestrictionsIsSet = true;
}
bool AccessAndMobilitySubscriptionData_1::ratRestrictionsIsSet() const
{
    return m_RatRestrictionsIsSet;
}
void AccessAndMobilitySubscriptionData_1::unsetRatRestrictions()
{
    m_RatRestrictionsIsSet = false;
}
std::vector<oai::model::Area_1> AccessAndMobilitySubscriptionData_1::getForbiddenAreas() const
{
    return m_ForbiddenAreas;
}
void AccessAndMobilitySubscriptionData_1::setForbiddenAreas(std::vector<oai::model::Area_1> const& value)
{
    m_ForbiddenAreas = value;
    m_ForbiddenAreasIsSet = true;
}
bool AccessAndMobilitySubscriptionData_1::forbiddenAreasIsSet() const
{
    return m_ForbiddenAreasIsSet;
}
void AccessAndMobilitySubscriptionData_1::unsetForbiddenAreas()
{
    m_ForbiddenAreasIsSet = false;
}
oai::model::ServiceAreaRestriction_1 AccessAndMobilitySubscriptionData_1::getServiceAreaRestriction() const
{
    return m_ServiceAreaRestriction;
}
void AccessAndMobilitySubscriptionData_1::setServiceAreaRestriction(oai::model::ServiceAreaRestriction_1 const& value)
{
    m_ServiceAreaRestriction = value;
    m_ServiceAreaRestrictionIsSet = true;
}
bool AccessAndMobilitySubscriptionData_1::serviceAreaRestrictionIsSet() const
{
    return m_ServiceAreaRestrictionIsSet;
}
void AccessAndMobilitySubscriptionData_1::unsetServiceAreaRestriction()
{
    m_ServiceAreaRestrictionIsSet = false;
}
std::vector<oai::model::CoreNetworkType> AccessAndMobilitySubscriptionData_1::getCoreNetworkTypeRestrictions() const
{
    return m_CoreNetworkTypeRestrictions;
}
void AccessAndMobilitySubscriptionData_1::setCoreNetworkTypeRestrictions(std::vector<oai::model::CoreNetworkType> const& value)
{
    m_CoreNetworkTypeRestrictions = value;
    m_CoreNetworkTypeRestrictionsIsSet = true;
}
bool AccessAndMobilitySubscriptionData_1::coreNetworkTypeRestrictionsIsSet() const
{
    return m_CoreNetworkTypeRestrictionsIsSet;
}
void AccessAndMobilitySubscriptionData_1::unsetCoreNetworkTypeRestrictions()
{
    m_CoreNetworkTypeRestrictionsIsSet = false;
}
int32_t AccessAndMobilitySubscriptionData_1::getRfspIndex() const
{
    return m_RfspIndex;
}
void AccessAndMobilitySubscriptionData_1::setRfspIndex(int32_t const value)
{
    m_RfspIndex = value;
    m_RfspIndexIsSet = true;
}
bool AccessAndMobilitySubscriptionData_1::rfspIndexIsSet() const
{
    return m_RfspIndexIsSet;
}
void AccessAndMobilitySubscriptionData_1::unsetRfspIndex()
{
    m_RfspIndexIsSet = false;
}
int32_t AccessAndMobilitySubscriptionData_1::getSubsRegTimer() const
{
    return m_SubsRegTimer;
}
void AccessAndMobilitySubscriptionData_1::setSubsRegTimer(int32_t const value)
{
    m_SubsRegTimer = value;
    m_SubsRegTimerIsSet = true;
}
bool AccessAndMobilitySubscriptionData_1::subsRegTimerIsSet() const
{
    return m_SubsRegTimerIsSet;
}
void AccessAndMobilitySubscriptionData_1::unsetSubsRegTimer()
{
    m_SubsRegTimerIsSet = false;
}
int32_t AccessAndMobilitySubscriptionData_1::getUeUsageType() const
{
    return m_UeUsageType;
}
void AccessAndMobilitySubscriptionData_1::setUeUsageType(int32_t const value)
{
    m_UeUsageType = value;
    m_UeUsageTypeIsSet = true;
}
bool AccessAndMobilitySubscriptionData_1::ueUsageTypeIsSet() const
{
    return m_UeUsageTypeIsSet;
}
void AccessAndMobilitySubscriptionData_1::unsetUeUsageType()
{
    m_UeUsageTypeIsSet = false;
}
bool AccessAndMobilitySubscriptionData_1::isMpsPriority() const
{
    return m_MpsPriority;
}
void AccessAndMobilitySubscriptionData_1::setMpsPriority(bool const value)
{
    m_MpsPriority = value;
    m_MpsPriorityIsSet = true;
}
bool AccessAndMobilitySubscriptionData_1::mpsPriorityIsSet() const
{
    return m_MpsPriorityIsSet;
}
void AccessAndMobilitySubscriptionData_1::unsetMpsPriority()
{
    m_MpsPriorityIsSet = false;
}
bool AccessAndMobilitySubscriptionData_1::isMcsPriority() const
{
    return m_McsPriority;
}
void AccessAndMobilitySubscriptionData_1::setMcsPriority(bool const value)
{
    m_McsPriority = value;
    m_McsPriorityIsSet = true;
}
bool AccessAndMobilitySubscriptionData_1::mcsPriorityIsSet() const
{
    return m_McsPriorityIsSet;
}
void AccessAndMobilitySubscriptionData_1::unsetMcsPriority()
{
    m_McsPriorityIsSet = false;
}
int32_t AccessAndMobilitySubscriptionData_1::getActiveTime() const
{
    return m_ActiveTime;
}
void AccessAndMobilitySubscriptionData_1::setActiveTime(int32_t const value)
{
    m_ActiveTime = value;
    m_ActiveTimeIsSet = true;
}
bool AccessAndMobilitySubscriptionData_1::activeTimeIsSet() const
{
    return m_ActiveTimeIsSet;
}
void AccessAndMobilitySubscriptionData_1::unsetActiveTime()
{
    m_ActiveTimeIsSet = false;
}
oai::model::SorInfo_1 AccessAndMobilitySubscriptionData_1::getSorInfo() const
{
    return m_SorInfo;
}
void AccessAndMobilitySubscriptionData_1::setSorInfo(oai::model::SorInfo_1 const& value)
{
    m_SorInfo = value;
    m_SorInfoIsSet = true;
}
bool AccessAndMobilitySubscriptionData_1::sorInfoIsSet() const
{
    return m_SorInfoIsSet;
}
void AccessAndMobilitySubscriptionData_1::unsetSorInfo()
{
    m_SorInfoIsSet = false;
}
bool AccessAndMobilitySubscriptionData_1::isSorInfoExpectInd() const
{
    return m_SorInfoExpectInd;
}
void AccessAndMobilitySubscriptionData_1::setSorInfoExpectInd(bool const value)
{
    m_SorInfoExpectInd = value;
    m_SorInfoExpectIndIsSet = true;
}
bool AccessAndMobilitySubscriptionData_1::sorInfoExpectIndIsSet() const
{
    return m_SorInfoExpectIndIsSet;
}
void AccessAndMobilitySubscriptionData_1::unsetSorInfoExpectInd()
{
    m_SorInfoExpectIndIsSet = false;
}
bool AccessAndMobilitySubscriptionData_1::isSorafRetrieval() const
{
    return m_SorafRetrieval;
}
void AccessAndMobilitySubscriptionData_1::setSorafRetrieval(bool const value)
{
    m_SorafRetrieval = value;
    m_SorafRetrievalIsSet = true;
}
bool AccessAndMobilitySubscriptionData_1::sorafRetrievalIsSet() const
{
    return m_SorafRetrievalIsSet;
}
void AccessAndMobilitySubscriptionData_1::unsetSorafRetrieval()
{
    m_SorafRetrievalIsSet = false;
}
std::vector<oai::model::SorUpdateIndicator> AccessAndMobilitySubscriptionData_1::getSorUpdateIndicatorList() const
{
    return m_SorUpdateIndicatorList;
}
void AccessAndMobilitySubscriptionData_1::setSorUpdateIndicatorList(std::vector<oai::model::SorUpdateIndicator> const& value)
{
    m_SorUpdateIndicatorList = value;
    m_SorUpdateIndicatorListIsSet = true;
}
bool AccessAndMobilitySubscriptionData_1::sorUpdateIndicatorListIsSet() const
{
    return m_SorUpdateIndicatorListIsSet;
}
void AccessAndMobilitySubscriptionData_1::unsetSorUpdateIndicatorList()
{
    m_SorUpdateIndicatorListIsSet = false;
}
oai::model::UpuInfo_1 AccessAndMobilitySubscriptionData_1::getUpuInfo() const
{
    return m_UpuInfo;
}
void AccessAndMobilitySubscriptionData_1::setUpuInfo(oai::model::UpuInfo_1 const& value)
{
    m_UpuInfo = value;
    m_UpuInfoIsSet = true;
}
bool AccessAndMobilitySubscriptionData_1::upuInfoIsSet() const
{
    return m_UpuInfoIsSet;
}
void AccessAndMobilitySubscriptionData_1::unsetUpuInfo()
{
    m_UpuInfoIsSet = false;
}
std::string AccessAndMobilitySubscriptionData_1::getRoutingIndicator() const
{
    return m_RoutingIndicator;
}
void AccessAndMobilitySubscriptionData_1::setRoutingIndicator(std::string const& value)
{
    m_RoutingIndicator = value;
    m_RoutingIndicatorIsSet = true;
}
bool AccessAndMobilitySubscriptionData_1::routingIndicatorIsSet() const
{
    return m_RoutingIndicatorIsSet;
}
void AccessAndMobilitySubscriptionData_1::unsetRoutingIndicator()
{
    m_RoutingIndicatorIsSet = false;
}
bool AccessAndMobilitySubscriptionData_1::isMicoAllowed() const
{
    return m_MicoAllowed;
}
void AccessAndMobilitySubscriptionData_1::setMicoAllowed(bool const value)
{
    m_MicoAllowed = value;
    m_MicoAllowedIsSet = true;
}
bool AccessAndMobilitySubscriptionData_1::micoAllowedIsSet() const
{
    return m_MicoAllowedIsSet;
}
void AccessAndMobilitySubscriptionData_1::unsetMicoAllowed()
{
    m_MicoAllowedIsSet = false;
}
std::vector<std::string> AccessAndMobilitySubscriptionData_1::getSharedAmDataIds() const
{
    return m_SharedAmDataIds;
}
void AccessAndMobilitySubscriptionData_1::setSharedAmDataIds(std::vector<std::string> const& value)
{
    m_SharedAmDataIds = value;
    m_SharedAmDataIdsIsSet = true;
}
bool AccessAndMobilitySubscriptionData_1::sharedAmDataIdsIsSet() const
{
    return m_SharedAmDataIdsIsSet;
}
void AccessAndMobilitySubscriptionData_1::unsetSharedAmDataIds()
{
    m_SharedAmDataIdsIsSet = false;
}
oai::model::OdbPacketServices AccessAndMobilitySubscriptionData_1::getOdbPacketServices() const
{
    return m_OdbPacketServices;
}
void AccessAndMobilitySubscriptionData_1::setOdbPacketServices(oai::model::OdbPacketServices const& value)
{
    m_OdbPacketServices = value;
    m_OdbPacketServicesIsSet = true;
}
bool AccessAndMobilitySubscriptionData_1::odbPacketServicesIsSet() const
{
    return m_OdbPacketServicesIsSet;
}
void AccessAndMobilitySubscriptionData_1::unsetOdbPacketServices()
{
    m_OdbPacketServicesIsSet = false;
}
std::vector<oai::model::AccessAndMobilitySubscriptionData_subscribedDnnList_inner> AccessAndMobilitySubscriptionData_1::getSubscribedDnnList() const
{
    return m_SubscribedDnnList;
}
void AccessAndMobilitySubscriptionData_1::setSubscribedDnnList(std::vector<oai::model::AccessAndMobilitySubscriptionData_subscribedDnnList_inner> const& value)
{
    m_SubscribedDnnList = value;
    m_SubscribedDnnListIsSet = true;
}
bool AccessAndMobilitySubscriptionData_1::subscribedDnnListIsSet() const
{
    return m_SubscribedDnnListIsSet;
}
void AccessAndMobilitySubscriptionData_1::unsetSubscribedDnnList()
{
    m_SubscribedDnnListIsSet = false;
}
int32_t AccessAndMobilitySubscriptionData_1::getServiceGapTime() const
{
    return m_ServiceGapTime;
}
void AccessAndMobilitySubscriptionData_1::setServiceGapTime(int32_t const value)
{
    m_ServiceGapTime = value;
    m_ServiceGapTimeIsSet = true;
}
bool AccessAndMobilitySubscriptionData_1::serviceGapTimeIsSet() const
{
    return m_ServiceGapTimeIsSet;
}
void AccessAndMobilitySubscriptionData_1::unsetServiceGapTime()
{
    m_ServiceGapTimeIsSet = false;
}
oai::model::MdtUserConsent AccessAndMobilitySubscriptionData_1::getMdtUserConsent() const
{
    return m_MdtUserConsent;
}
void AccessAndMobilitySubscriptionData_1::setMdtUserConsent(oai::model::MdtUserConsent const& value)
{
    m_MdtUserConsent = value;
    m_MdtUserConsentIsSet = true;
}
bool AccessAndMobilitySubscriptionData_1::mdtUserConsentIsSet() const
{
    return m_MdtUserConsentIsSet;
}
void AccessAndMobilitySubscriptionData_1::unsetMdtUserConsent()
{
    m_MdtUserConsentIsSet = false;
}
oai::model::MdtConfiguration_1 AccessAndMobilitySubscriptionData_1::getMdtConfiguration() const
{
    return m_MdtConfiguration;
}
void AccessAndMobilitySubscriptionData_1::setMdtConfiguration(oai::model::MdtConfiguration_1 const& value)
{
    m_MdtConfiguration = value;
    m_MdtConfigurationIsSet = true;
}
bool AccessAndMobilitySubscriptionData_1::mdtConfigurationIsSet() const
{
    return m_MdtConfigurationIsSet;
}
void AccessAndMobilitySubscriptionData_1::unsetMdtConfiguration()
{
    m_MdtConfigurationIsSet = false;
}
oai::model::TraceData AccessAndMobilitySubscriptionData_1::getTraceData() const
{
    return m_TraceData;
}
void AccessAndMobilitySubscriptionData_1::setTraceData(oai::model::TraceData const& value)
{
    m_TraceData = value;
    m_TraceDataIsSet = true;
}
bool AccessAndMobilitySubscriptionData_1::traceDataIsSet() const
{
    return m_TraceDataIsSet;
}
void AccessAndMobilitySubscriptionData_1::unsetTraceData()
{
    m_TraceDataIsSet = false;
}
oai::model::CagData_1 AccessAndMobilitySubscriptionData_1::getCagData() const
{
    return m_CagData;
}
void AccessAndMobilitySubscriptionData_1::setCagData(oai::model::CagData_1 const& value)
{
    m_CagData = value;
    m_CagDataIsSet = true;
}
bool AccessAndMobilitySubscriptionData_1::cagDataIsSet() const
{
    return m_CagDataIsSet;
}
void AccessAndMobilitySubscriptionData_1::unsetCagData()
{
    m_CagDataIsSet = false;
}
std::string AccessAndMobilitySubscriptionData_1::getStnSr() const
{
    return m_StnSr;
}
void AccessAndMobilitySubscriptionData_1::setStnSr(std::string const& value)
{
    m_StnSr = value;
    m_StnSrIsSet = true;
}
bool AccessAndMobilitySubscriptionData_1::stnSrIsSet() const
{
    return m_StnSrIsSet;
}
void AccessAndMobilitySubscriptionData_1::unsetStnSr()
{
    m_StnSrIsSet = false;
}
std::string AccessAndMobilitySubscriptionData_1::getCMsisdn() const
{
    return m_CMsisdn;
}
void AccessAndMobilitySubscriptionData_1::setCMsisdn(std::string const& value)
{
    m_CMsisdn = value;
    m_CMsisdnIsSet = true;
}
bool AccessAndMobilitySubscriptionData_1::cMsisdnIsSet() const
{
    return m_CMsisdnIsSet;
}
void AccessAndMobilitySubscriptionData_1::unsetCMsisdn()
{
    m_CMsisdnIsSet = false;
}
int32_t AccessAndMobilitySubscriptionData_1::getNbIoTUePriority() const
{
    return m_NbIoTUePriority;
}
void AccessAndMobilitySubscriptionData_1::setNbIoTUePriority(int32_t const value)
{
    m_NbIoTUePriority = value;
    m_NbIoTUePriorityIsSet = true;
}
bool AccessAndMobilitySubscriptionData_1::nbIoTUePriorityIsSet() const
{
    return m_NbIoTUePriorityIsSet;
}
void AccessAndMobilitySubscriptionData_1::unsetNbIoTUePriority()
{
    m_NbIoTUePriorityIsSet = false;
}
bool AccessAndMobilitySubscriptionData_1::isNssaiInclusionAllowed() const
{
    return m_NssaiInclusionAllowed;
}
void AccessAndMobilitySubscriptionData_1::setNssaiInclusionAllowed(bool const value)
{
    m_NssaiInclusionAllowed = value;
    m_NssaiInclusionAllowedIsSet = true;
}
bool AccessAndMobilitySubscriptionData_1::nssaiInclusionAllowedIsSet() const
{
    return m_NssaiInclusionAllowedIsSet;
}
void AccessAndMobilitySubscriptionData_1::unsetNssaiInclusionAllowed()
{
    m_NssaiInclusionAllowedIsSet = false;
}
std::string AccessAndMobilitySubscriptionData_1::getRgWirelineCharacteristics() const
{
    return m_RgWirelineCharacteristics;
}
void AccessAndMobilitySubscriptionData_1::setRgWirelineCharacteristics(std::string const& value)
{
    m_RgWirelineCharacteristics = value;
    m_RgWirelineCharacteristicsIsSet = true;
}
bool AccessAndMobilitySubscriptionData_1::rgWirelineCharacteristicsIsSet() const
{
    return m_RgWirelineCharacteristicsIsSet;
}
void AccessAndMobilitySubscriptionData_1::unsetRgWirelineCharacteristics()
{
    m_RgWirelineCharacteristicsIsSet = false;
}
oai::model::EcRestrictionDataWb AccessAndMobilitySubscriptionData_1::getEcRestrictionDataWb() const
{
    return m_EcRestrictionDataWb;
}
void AccessAndMobilitySubscriptionData_1::setEcRestrictionDataWb(oai::model::EcRestrictionDataWb const& value)
{
    m_EcRestrictionDataWb = value;
    m_EcRestrictionDataWbIsSet = true;
}
bool AccessAndMobilitySubscriptionData_1::ecRestrictionDataWbIsSet() const
{
    return m_EcRestrictionDataWbIsSet;
}
void AccessAndMobilitySubscriptionData_1::unsetEcRestrictionDataWb()
{
    m_EcRestrictionDataWbIsSet = false;
}
bool AccessAndMobilitySubscriptionData_1::isEcRestrictionDataNb() const
{
    return m_EcRestrictionDataNb;
}
void AccessAndMobilitySubscriptionData_1::setEcRestrictionDataNb(bool const value)
{
    m_EcRestrictionDataNb = value;
    m_EcRestrictionDataNbIsSet = true;
}
bool AccessAndMobilitySubscriptionData_1::ecRestrictionDataNbIsSet() const
{
    return m_EcRestrictionDataNbIsSet;
}
void AccessAndMobilitySubscriptionData_1::unsetEcRestrictionDataNb()
{
    m_EcRestrictionDataNbIsSet = false;
}
oai::model::ExpectedUeBehaviourData_1 AccessAndMobilitySubscriptionData_1::getExpectedUeBehaviourList() const
{
    return m_ExpectedUeBehaviourList;
}
void AccessAndMobilitySubscriptionData_1::setExpectedUeBehaviourList(oai::model::ExpectedUeBehaviourData_1 const& value)
{
    m_ExpectedUeBehaviourList = value;
    m_ExpectedUeBehaviourListIsSet = true;
}
bool AccessAndMobilitySubscriptionData_1::expectedUeBehaviourListIsSet() const
{
    return m_ExpectedUeBehaviourListIsSet;
}
void AccessAndMobilitySubscriptionData_1::unsetExpectedUeBehaviourList()
{
    m_ExpectedUeBehaviourListIsSet = false;
}
std::set<oai::model::RatType> AccessAndMobilitySubscriptionData_1::getPrimaryRatRestrictions() const
{
    return m_PrimaryRatRestrictions;
}
void AccessAndMobilitySubscriptionData_1::setPrimaryRatRestrictions(std::set<oai::model::RatType> const& value)
{
    m_PrimaryRatRestrictions = value;
    m_PrimaryRatRestrictionsIsSet = true;
}
bool AccessAndMobilitySubscriptionData_1::primaryRatRestrictionsIsSet() const
{
    return m_PrimaryRatRestrictionsIsSet;
}
void AccessAndMobilitySubscriptionData_1::unsetPrimaryRatRestrictions()
{
    m_PrimaryRatRestrictionsIsSet = false;
}
std::set<oai::model::RatType> AccessAndMobilitySubscriptionData_1::getSecondaryRatRestrictions() const
{
    return m_SecondaryRatRestrictions;
}
void AccessAndMobilitySubscriptionData_1::setSecondaryRatRestrictions(std::set<oai::model::RatType> const& value)
{
    m_SecondaryRatRestrictions = value;
    m_SecondaryRatRestrictionsIsSet = true;
}
bool AccessAndMobilitySubscriptionData_1::secondaryRatRestrictionsIsSet() const
{
    return m_SecondaryRatRestrictionsIsSet;
}
void AccessAndMobilitySubscriptionData_1::unsetSecondaryRatRestrictions()
{
    m_SecondaryRatRestrictionsIsSet = false;
}
std::vector<oai::model::EdrxParameters_1> AccessAndMobilitySubscriptionData_1::getEdrxParametersList() const
{
    return m_EdrxParametersList;
}
void AccessAndMobilitySubscriptionData_1::setEdrxParametersList(std::vector<oai::model::EdrxParameters_1> const& value)
{
    m_EdrxParametersList = value;
    m_EdrxParametersListIsSet = true;
}
bool AccessAndMobilitySubscriptionData_1::edrxParametersListIsSet() const
{
    return m_EdrxParametersListIsSet;
}
void AccessAndMobilitySubscriptionData_1::unsetEdrxParametersList()
{
    m_EdrxParametersListIsSet = false;
}
std::vector<oai::model::PtwParameters_1> AccessAndMobilitySubscriptionData_1::getPtwParametersList() const
{
    return m_PtwParametersList;
}
void AccessAndMobilitySubscriptionData_1::setPtwParametersList(std::vector<oai::model::PtwParameters_1> const& value)
{
    m_PtwParametersList = value;
    m_PtwParametersListIsSet = true;
}
bool AccessAndMobilitySubscriptionData_1::ptwParametersListIsSet() const
{
    return m_PtwParametersListIsSet;
}
void AccessAndMobilitySubscriptionData_1::unsetPtwParametersList()
{
    m_PtwParametersListIsSet = false;
}
bool AccessAndMobilitySubscriptionData_1::isIabOperationAllowed() const
{
    return m_IabOperationAllowed;
}
void AccessAndMobilitySubscriptionData_1::setIabOperationAllowed(bool const value)
{
    m_IabOperationAllowed = value;
    m_IabOperationAllowedIsSet = true;
}
bool AccessAndMobilitySubscriptionData_1::iabOperationAllowedIsSet() const
{
    return m_IabOperationAllowedIsSet;
}
void AccessAndMobilitySubscriptionData_1::unsetIabOperationAllowed()
{
    m_IabOperationAllowedIsSet = false;
}
std::map<std::string, oai::model::PlmnRestriction_1> AccessAndMobilitySubscriptionData_1::getAdjacentPlmnRestrictions() const
{
    return m_AdjacentPlmnRestrictions;
}
void AccessAndMobilitySubscriptionData_1::setAdjacentPlmnRestrictions(std::map<std::string, oai::model::PlmnRestriction_1> const& value)
{
    m_AdjacentPlmnRestrictions = value;
    m_AdjacentPlmnRestrictionsIsSet = true;
}
bool AccessAndMobilitySubscriptionData_1::adjacentPlmnRestrictionsIsSet() const
{
    return m_AdjacentPlmnRestrictionsIsSet;
}
void AccessAndMobilitySubscriptionData_1::unsetAdjacentPlmnRestrictions()
{
    m_AdjacentPlmnRestrictionsIsSet = false;
}
std::vector<oai::model::WirelineArea_1> AccessAndMobilitySubscriptionData_1::getWirelineForbiddenAreas() const
{
    return m_WirelineForbiddenAreas;
}
void AccessAndMobilitySubscriptionData_1::setWirelineForbiddenAreas(std::vector<oai::model::WirelineArea_1> const& value)
{
    m_WirelineForbiddenAreas = value;
    m_WirelineForbiddenAreasIsSet = true;
}
bool AccessAndMobilitySubscriptionData_1::wirelineForbiddenAreasIsSet() const
{
    return m_WirelineForbiddenAreasIsSet;
}
void AccessAndMobilitySubscriptionData_1::unsetWirelineForbiddenAreas()
{
    m_WirelineForbiddenAreasIsSet = false;
}
oai::model::WirelineServiceAreaRestriction_1 AccessAndMobilitySubscriptionData_1::getWirelineServiceAreaRestriction() const
{
    return m_WirelineServiceAreaRestriction;
}
void AccessAndMobilitySubscriptionData_1::setWirelineServiceAreaRestriction(oai::model::WirelineServiceAreaRestriction_1 const& value)
{
    m_WirelineServiceAreaRestriction = value;
    m_WirelineServiceAreaRestrictionIsSet = true;
}
bool AccessAndMobilitySubscriptionData_1::wirelineServiceAreaRestrictionIsSet() const
{
    return m_WirelineServiceAreaRestrictionIsSet;
}
void AccessAndMobilitySubscriptionData_1::unsetWirelineServiceAreaRestriction()
{
    m_WirelineServiceAreaRestrictionIsSet = false;
}
std::vector<oai::model::PcfSelectionAssistanceInfo_1> AccessAndMobilitySubscriptionData_1::getPcfSelectionAssistanceInfos() const
{
    return m_PcfSelectionAssistanceInfos;
}
void AccessAndMobilitySubscriptionData_1::setPcfSelectionAssistanceInfos(std::vector<oai::model::PcfSelectionAssistanceInfo_1> const& value)
{
    m_PcfSelectionAssistanceInfos = value;
    m_PcfSelectionAssistanceInfosIsSet = true;
}
bool AccessAndMobilitySubscriptionData_1::pcfSelectionAssistanceInfosIsSet() const
{
    return m_PcfSelectionAssistanceInfosIsSet;
}
void AccessAndMobilitySubscriptionData_1::unsetPcfSelectionAssistanceInfos()
{
    m_PcfSelectionAssistanceInfosIsSet = false;
}
oai::model::AerialUeSubscriptionInfo_1 AccessAndMobilitySubscriptionData_1::getAerialUeSubInfo() const
{
    return m_AerialUeSubInfo;
}
void AccessAndMobilitySubscriptionData_1::setAerialUeSubInfo(oai::model::AerialUeSubscriptionInfo_1 const& value)
{
    m_AerialUeSubInfo = value;
    m_AerialUeSubInfoIsSet = true;
}
bool AccessAndMobilitySubscriptionData_1::aerialUeSubInfoIsSet() const
{
    return m_AerialUeSubInfoIsSet;
}
void AccessAndMobilitySubscriptionData_1::unsetAerialUeSubInfo()
{
    m_AerialUeSubInfoIsSet = false;
}
oai::model::RoamingRestrictions AccessAndMobilitySubscriptionData_1::getRoamingRestrictions() const
{
    return m_RoamingRestrictions;
}
void AccessAndMobilitySubscriptionData_1::setRoamingRestrictions(oai::model::RoamingRestrictions const& value)
{
    m_RoamingRestrictions = value;
    m_RoamingRestrictionsIsSet = true;
}
bool AccessAndMobilitySubscriptionData_1::roamingRestrictionsIsSet() const
{
    return m_RoamingRestrictionsIsSet;
}
void AccessAndMobilitySubscriptionData_1::unsetRoamingRestrictions()
{
    m_RoamingRestrictionsIsSet = false;
}
bool AccessAndMobilitySubscriptionData_1::isRemoteProvInd() const
{
    return m_RemoteProvInd;
}
void AccessAndMobilitySubscriptionData_1::setRemoteProvInd(bool const value)
{
    m_RemoteProvInd = value;
    m_RemoteProvIndIsSet = true;
}
bool AccessAndMobilitySubscriptionData_1::remoteProvIndIsSet() const
{
    return m_RemoteProvIndIsSet;
}
void AccessAndMobilitySubscriptionData_1::unsetRemoteProvInd()
{
    m_RemoteProvIndIsSet = false;
}
std::string AccessAndMobilitySubscriptionData_1::getR3gppChargingCharacteristics() const
{
    return m_r_3gppChargingCharacteristics;
}
void AccessAndMobilitySubscriptionData_1::setR3gppChargingCharacteristics(std::string const& value)
{
    m_r_3gppChargingCharacteristics = value;
    m_r_3gppChargingCharacteristicsIsSet = true;
}
bool AccessAndMobilitySubscriptionData_1::r3gppChargingCharacteristicsIsSet() const
{
    return m_r_3gppChargingCharacteristicsIsSet;
}
void AccessAndMobilitySubscriptionData_1::unsetr_3gppChargingCharacteristics()
{
    m_r_3gppChargingCharacteristicsIsSet = false;
}


} // namespace oai::model

