/**
* Unified Data Repository Service API file for Application Data
* The API version is defined in 3GPP TS 29.504   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
*
* The version of the OpenAPI document: -
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "AccessRightStatus.h"
#include "Helpers.h"

#include <sstream>

namespace oai::model
{

AccessRightStatus::AccessRightStatus()
{
    
}

void AccessRightStatus::validate() const
{
    std::stringstream msg;
    if (!validate(msg))
    {
        throw org::openapitools::server::helpers::ValidationException(msg.str());
    }
}

bool AccessRightStatus::validate(std::stringstream& msg) const
{
    return validate(msg, "");
}

bool AccessRightStatus::validate(std::stringstream& msg, const std::string& pathPrefix) const
{
    bool success = true;
    const std::string _pathPrefix = pathPrefix.empty() ? "AccessRightStatus" : pathPrefix;

    
    return success;
}

bool AccessRightStatus::operator==(const AccessRightStatus& rhs) const
{
    return
    
    
    ;
}

bool AccessRightStatus::operator!=(const AccessRightStatus& rhs) const
{
    return !(*this == rhs);
}

void to_json(nlohmann::json& j, const AccessRightStatus& o)
{
    j = nlohmann::json::object();
    
}

void from_json(const nlohmann::json& j, AccessRightStatus& o)
{
    
}



} // namespace oai::model

