/**
* Nudr_DataRepository API OpenAPI file
* Unified Data Repository Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
*
* The version of the OpenAPI document: 2.2.4
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "AdditionalSnssaiData_1.h"
#include "Helpers.h"

#include <sstream>

namespace oai::model
{

AdditionalSnssaiData_1::AdditionalSnssaiData_1()
{
    m_RequiredAuthnAuthz = false;
    m_RequiredAuthnAuthzIsSet = false;
    m_SubscribedUeSliceMbrIsSet = false;
    m_SubscribedNsSrgListIsSet = false;
    
}

void AdditionalSnssaiData_1::validate() const
{
    std::stringstream msg;
    if (!validate(msg))
    {
        throw org::openapitools::server::helpers::ValidationException(msg.str());
    }
}

bool AdditionalSnssaiData_1::validate(std::stringstream& msg) const
{
    return validate(msg, "");
}

bool AdditionalSnssaiData_1::validate(std::stringstream& msg, const std::string& pathPrefix) const
{
    bool success = true;
    const std::string _pathPrefix = pathPrefix.empty() ? "AdditionalSnssaiData_1" : pathPrefix;

                 
    if (subscribedNsSrgListIsSet())
    {
        const std::vector<std::string>& value = m_SubscribedNsSrgList;
        const std::string currentValuePath = _pathPrefix + ".subscribedNsSrgList";
                
        
        if (value.size() < 1)
        {
            success = false;
            msg << currentValuePath << ": must have at least 1 elements;";
        }
        { // Recursive validation of array elements
            const std::string oldValuePath = currentValuePath;
            int i = 0;
            for (const std::string& value : value)
            { 
                const std::string currentValuePath = oldValuePath + "[" + std::to_string(i) + "]";
                        
        
 
                i++;
            }
        }

    }
    
    return success;
}

bool AdditionalSnssaiData_1::operator==(const AdditionalSnssaiData_1& rhs) const
{
    return
    
    
    
    ((!requiredAuthnAuthzIsSet() && !rhs.requiredAuthnAuthzIsSet()) || (requiredAuthnAuthzIsSet() && rhs.requiredAuthnAuthzIsSet() && isRequiredAuthnAuthz() == rhs.isRequiredAuthnAuthz())) &&
    
    
    ((!subscribedUeSliceMbrIsSet() && !rhs.subscribedUeSliceMbrIsSet()) || (subscribedUeSliceMbrIsSet() && rhs.subscribedUeSliceMbrIsSet() && getSubscribedUeSliceMbr() == rhs.getSubscribedUeSliceMbr())) &&
    
    
    ((!subscribedNsSrgListIsSet() && !rhs.subscribedNsSrgListIsSet()) || (subscribedNsSrgListIsSet() && rhs.subscribedNsSrgListIsSet() && getSubscribedNsSrgList() == rhs.getSubscribedNsSrgList()))
    
    ;
}

bool AdditionalSnssaiData_1::operator!=(const AdditionalSnssaiData_1& rhs) const
{
    return !(*this == rhs);
}

void to_json(nlohmann::json& j, const AdditionalSnssaiData_1& o)
{
    j = nlohmann::json::object();
    if(o.requiredAuthnAuthzIsSet())
        j["requiredAuthnAuthz"] = o.m_RequiredAuthnAuthz;
    if(o.subscribedUeSliceMbrIsSet())
        j["subscribedUeSliceMbr"] = o.m_SubscribedUeSliceMbr;
    if(o.subscribedNsSrgListIsSet() || !o.m_SubscribedNsSrgList.empty())
        j["subscribedNsSrgList"] = o.m_SubscribedNsSrgList;
    
}

void from_json(const nlohmann::json& j, AdditionalSnssaiData_1& o)
{
    if(j.find("requiredAuthnAuthz") != j.end())
    {
        j.at("requiredAuthnAuthz").get_to(o.m_RequiredAuthnAuthz);
        o.m_RequiredAuthnAuthzIsSet = true;
    } 
    if(j.find("subscribedUeSliceMbr") != j.end())
    {
        j.at("subscribedUeSliceMbr").get_to(o.m_SubscribedUeSliceMbr);
        o.m_SubscribedUeSliceMbrIsSet = true;
    } 
    if(j.find("subscribedNsSrgList") != j.end())
    {
        j.at("subscribedNsSrgList").get_to(o.m_SubscribedNsSrgList);
        o.m_SubscribedNsSrgListIsSet = true;
    } 
    
}

bool AdditionalSnssaiData_1::isRequiredAuthnAuthz() const
{
    return m_RequiredAuthnAuthz;
}
void AdditionalSnssaiData_1::setRequiredAuthnAuthz(bool const value)
{
    m_RequiredAuthnAuthz = value;
    m_RequiredAuthnAuthzIsSet = true;
}
bool AdditionalSnssaiData_1::requiredAuthnAuthzIsSet() const
{
    return m_RequiredAuthnAuthzIsSet;
}
void AdditionalSnssaiData_1::unsetRequiredAuthnAuthz()
{
    m_RequiredAuthnAuthzIsSet = false;
}
oai::model::SliceMbr AdditionalSnssaiData_1::getSubscribedUeSliceMbr() const
{
    return m_SubscribedUeSliceMbr;
}
void AdditionalSnssaiData_1::setSubscribedUeSliceMbr(oai::model::SliceMbr const& value)
{
    m_SubscribedUeSliceMbr = value;
    m_SubscribedUeSliceMbrIsSet = true;
}
bool AdditionalSnssaiData_1::subscribedUeSliceMbrIsSet() const
{
    return m_SubscribedUeSliceMbrIsSet;
}
void AdditionalSnssaiData_1::unsetSubscribedUeSliceMbr()
{
    m_SubscribedUeSliceMbrIsSet = false;
}
std::vector<std::string> AdditionalSnssaiData_1::getSubscribedNsSrgList() const
{
    return m_SubscribedNsSrgList;
}
void AdditionalSnssaiData_1::setSubscribedNsSrgList(std::vector<std::string> const& value)
{
    m_SubscribedNsSrgList = value;
    m_SubscribedNsSrgListIsSet = true;
}
bool AdditionalSnssaiData_1::subscribedNsSrgListIsSet() const
{
    return m_SubscribedNsSrgListIsSet;
}
void AdditionalSnssaiData_1::unsetSubscribedNsSrgList()
{
    m_SubscribedNsSrgListIsSet = false;
}


} // namespace oai::model

