# SPDX-License-Identifier: LicenseRef-CSSL-1.0

SET(AMF_MODEL_DIR ${SRC_TOP_DIR}/${MOUNTED_COMMON}/model)

include_directories(${AMF_MODEL_DIR})

file(GLOB AMF_MODEL_SRC_FILES
    ${AMF_MODEL_DIR}/AanfInfo.cpp
    ${AMF_MODEL_DIR}/AbnormalBehaviour.cpp
    ${AMF_MODEL_DIR}/AccessAndMobilitySubscriptionData.cpp
    ${AMF_MODEL_DIR}/AccessAndMobilitySubscriptionData_subscribedDnnList_inner.cpp
    ${AMF_MODEL_DIR}/AccessStateTransitionType.cpp
    ${AMF_MODEL_DIR}/AccessStateTransitionType_anyOf.cpp
    ${AMF_MODEL_DIR}/AccessTech.cpp
    ${AMF_MODEL_DIR}/AccessTech_anyOf.cpp
    ${AMF_MODEL_DIR}/AccessTokenErr.cpp
    ${AMF_MODEL_DIR}/AccessTokenReq.cpp
    ${AMF_MODEL_DIR}/AccessType.cpp
    ${AMF_MODEL_DIR}/Accuracy.cpp
    ${AMF_MODEL_DIR}/AccuracyFulfilmentIndicator.cpp
    ${AMF_MODEL_DIR}/AccuracyFulfilmentIndicator_anyOf.cpp
    ${AMF_MODEL_DIR}/Accuracy_anyOf.cpp
    ${AMF_MODEL_DIR}/AdditionInfoEnableUeReachability.cpp
    ${AMF_MODEL_DIR}/AdditionalMeasurement.cpp
    ${AMF_MODEL_DIR}/AdditionalSnssaiData.cpp
    ${AMF_MODEL_DIR}/AddrFqdn.cpp
    ${AMF_MODEL_DIR}/AddressList.cpp
    ${AMF_MODEL_DIR}/AerialUeIndication.cpp
    ${AMF_MODEL_DIR}/AerialUeIndication_anyOf.cpp
    ${AMF_MODEL_DIR}/AerialUeSubscriptionInfo.cpp
    ${AMF_MODEL_DIR}/AfEvent.cpp
    ${AMF_MODEL_DIR}/AfEventExposureData.cpp
    ${AMF_MODEL_DIR}/AfEvent_anyOf.cpp
    ${AMF_MODEL_DIR}/AlertLimit.cpp
    ${AMF_MODEL_DIR}/AllowedNssai.cpp
    ${AMF_MODEL_DIR}/AllowedSnssai.cpp
    ${AMF_MODEL_DIR}/AmRequestedValueRep.cpp
    ${AMF_MODEL_DIR}/Ambr.cpp
    ${AMF_MODEL_DIR}/AmbrRm.cpp
    ${AMF_MODEL_DIR}/Amf3GppAccessRegistration.cpp
    ${AMF_MODEL_DIR}/AmfCreateEventSubscription.cpp
    ${AMF_MODEL_DIR}/AmfCreatedEventSubscription.cpp
    ${AMF_MODEL_DIR}/AmfEvent.cpp
    ${AMF_MODEL_DIR}/AmfEventArea.cpp
    ${AMF_MODEL_DIR}/AmfEventMode.cpp
    ${AMF_MODEL_DIR}/AmfEventNotification.cpp
    ${AMF_MODEL_DIR}/AmfEventReport.cpp
    ${AMF_MODEL_DIR}/AmfEventState.cpp
    ${AMF_MODEL_DIR}/AmfEventSubsSyncInfo.cpp
    ${AMF_MODEL_DIR}/AmfEventSubscription.cpp
    ${AMF_MODEL_DIR}/AmfEventSubscriptionAddInfo.cpp
    ${AMF_MODEL_DIR}/AmfEventSubscriptionInfo.cpp
    ${AMF_MODEL_DIR}/AmfEventTrigger.cpp
    ${AMF_MODEL_DIR}/AmfEventTrigger_anyOf.cpp
    ${AMF_MODEL_DIR}/AmfEventType.cpp
    ${AMF_MODEL_DIR}/AmfEventType_anyOf.cpp
    ${AMF_MODEL_DIR}/AmfInfo.cpp
    ${AMF_MODEL_DIR}/AmfStatusChangeNotification.cpp
    ${AMF_MODEL_DIR}/AmfStatusInfo.cpp
    ${AMF_MODEL_DIR}/AmfUpdateEventOptionItem.cpp
    ${AMF_MODEL_DIR}/AmfUpdateEventSubscriptionItem.cpp
    ${AMF_MODEL_DIR}/AmfUpdatedEventSubscription.cpp
    ${AMF_MODEL_DIR}/AnNodeType.cpp
    ${AMF_MODEL_DIR}/AnNodeType_anyOf.cpp
    ${AMF_MODEL_DIR}/AnalyticsMetadata.cpp
    ${AMF_MODEL_DIR}/AnalyticsMetadataIndication.cpp
    ${AMF_MODEL_DIR}/AnalyticsMetadataInfo.cpp
    ${AMF_MODEL_DIR}/AnalyticsMetadata_anyOf.cpp
    ${AMF_MODEL_DIR}/AnalyticsSubscription.cpp
    ${AMF_MODEL_DIR}/AnalyticsSubset.cpp
    ${AMF_MODEL_DIR}/AnalyticsSubset_anyOf.cpp
    ${AMF_MODEL_DIR}/ApnRateStatus.cpp
    ${AMF_MODEL_DIR}/AppListForUeComm.cpp
    ${AMF_MODEL_DIR}/ApplicationVolume.cpp
    ${AMF_MODEL_DIR}/Area.cpp
    ${AMF_MODEL_DIR}/AreaEventInfo.cpp
    ${AMF_MODEL_DIR}/AreaOfInterestEventState.cpp
    ${AMF_MODEL_DIR}/AreaOfValidity.cpp
    ${AMF_MODEL_DIR}/AreaScope.cpp
    ${AMF_MODEL_DIR}/Arp.cpp
    ${AMF_MODEL_DIR}/AsTimeDistributionParam.cpp
    ${AMF_MODEL_DIR}/AssignEbiData.cpp
    ${AMF_MODEL_DIR}/AssignEbiError.cpp
    ${AMF_MODEL_DIR}/AssignEbiFailed.cpp
    ${AMF_MODEL_DIR}/AssignedEbiData.cpp
    ${AMF_MODEL_DIR}/AtsssCapability.cpp
    ${AMF_MODEL_DIR}/AusfInfo.cpp
    ${AMF_MODEL_DIR}/AuthResult.cpp
    ${AMF_MODEL_DIR}/AuthStatus.cpp
    ${AMF_MODEL_DIR}/AuthStatus_anyOf.cpp
    ${AMF_MODEL_DIR}/AuthType.cpp
    ${AMF_MODEL_DIR}/AuthType_anyOf.cpp
    ${AMF_MODEL_DIR}/AuthenticationInfo.cpp
    ${AMF_MODEL_DIR}/AuthorizedNetworkSliceInfo.cpp
    ${AMF_MODEL_DIR}/Av5gAka.cpp
    ${AMF_MODEL_DIR}/BackupAmfInfo.cpp
    ${AMF_MODEL_DIR}/BatteryIndication.cpp
    ${AMF_MODEL_DIR}/BsfInfo.cpp
    ${AMF_MODEL_DIR}/BwRequirement.cpp
    ${AMF_MODEL_DIR}/CagData.cpp
    ${AMF_MODEL_DIR}/CagInfo.cpp
    ${AMF_MODEL_DIR}/CancelPosInfo.cpp
    ${AMF_MODEL_DIR}/CandidateForReplacement.cpp
    ${AMF_MODEL_DIR}/Cause.cpp
    ${AMF_MODEL_DIR}/Cause_anyOf.cpp
    ${AMF_MODEL_DIR}/CeModeBInd.cpp
    ${AMF_MODEL_DIR}/CellGlobalId.cpp
    ${AMF_MODEL_DIR}/ChangeItem.cpp
    ${AMF_MODEL_DIR}/ChangeType.cpp
    ${AMF_MODEL_DIR}/ChangeType_anyOf.cpp
    ${AMF_MODEL_DIR}/ChfInfo.cpp
    ${AMF_MODEL_DIR}/CipheringAlgorithm.cpp
    ${AMF_MODEL_DIR}/CipheringAlgorithm_anyOf.cpp
    ${AMF_MODEL_DIR}/CircumstanceDescription.cpp
    ${AMF_MODEL_DIR}/CivicAddress.cpp
    ${AMF_MODEL_DIR}/ClassCriterion.cpp
    ${AMF_MODEL_DIR}/CmInfo.cpp
    ${AMF_MODEL_DIR}/CmState.cpp
    ${AMF_MODEL_DIR}/CmState_anyOf.cpp
    ${AMF_MODEL_DIR}/CnAssistedRanPara.cpp
    ${AMF_MODEL_DIR}/CollectionPeriodRmmLteMdt.cpp
    ${AMF_MODEL_DIR}/CollectionPeriodRmmLteMdt_anyOf.cpp
    ${AMF_MODEL_DIR}/CollectionPeriodRmmNrMdt.cpp
    ${AMF_MODEL_DIR}/CollectionPeriodRmmNrMdt_anyOf.cpp
    ${AMF_MODEL_DIR}/CollocatedNfInstance.cpp
    ${AMF_MODEL_DIR}/CollocatedNfType.cpp
    ${AMF_MODEL_DIR}/CollocatedNfType_anyOf.cpp
    ${AMF_MODEL_DIR}/CommunicationFailure.cpp
    ${AMF_MODEL_DIR}/ConfiguredSnssai.cpp
    ${AMF_MODEL_DIR}/ConfirmationData.cpp
    ${AMF_MODEL_DIR}/ConfirmationDataResponse.cpp
    ${AMF_MODEL_DIR}/CongestionInfo.cpp
    ${AMF_MODEL_DIR}/CongestionType.cpp
    ${AMF_MODEL_DIR}/CongestionType_anyOf.cpp
    ${AMF_MODEL_DIR}/ConsumerNfInformation.cpp
    ${AMF_MODEL_DIR}/ContextCreateReqData.cpp
    ${AMF_MODEL_DIR}/ContextCreateRspData.cpp
    ${AMF_MODEL_DIR}/ContextInfo.cpp
    ${AMF_MODEL_DIR}/ContextStatusNotification.cpp
    ${AMF_MODEL_DIR}/ContextUpdateReqData.cpp
    ${AMF_MODEL_DIR}/ContextUpdateRspData.cpp
    ${AMF_MODEL_DIR}/CoreNetworkType.cpp
    ${AMF_MODEL_DIR}/CoreNetworkType_anyOf.cpp
    ${AMF_MODEL_DIR}/DataSetId.cpp
    ${AMF_MODEL_DIR}/DataSetId_anyOf.cpp
    ${AMF_MODEL_DIR}/DatasetStatisticalProperty.cpp
    ${AMF_MODEL_DIR}/DatasetStatisticalProperty_anyOf.cpp
    ${AMF_MODEL_DIR}/DccfInfo.cpp
    ${AMF_MODEL_DIR}/DddTrafficDescriptor.cpp
    ${AMF_MODEL_DIR}/DefSubServiceInfo.cpp
    ${AMF_MODEL_DIR}/DefaultNotificationSubscription.cpp
    ${AMF_MODEL_DIR}/DispersionArea.cpp
    ${AMF_MODEL_DIR}/DispersionClass.cpp
    ${AMF_MODEL_DIR}/DispersionClass_oneOf.cpp
    ${AMF_MODEL_DIR}/DispersionCollection.cpp
    ${AMF_MODEL_DIR}/DispersionInfo.cpp
    ${AMF_MODEL_DIR}/DispersionOrderingCriterion.cpp
    ${AMF_MODEL_DIR}/DispersionOrderingCriterion_anyOf.cpp
    ${AMF_MODEL_DIR}/DispersionRequirement.cpp
    ${AMF_MODEL_DIR}/DispersionType.cpp
    ${AMF_MODEL_DIR}/DispersionType_oneOf.cpp
    ${AMF_MODEL_DIR}/DnPerf.cpp
    ${AMF_MODEL_DIR}/DnPerfInfo.cpp
    ${AMF_MODEL_DIR}/DnPerfOrderingCriterion.cpp
    ${AMF_MODEL_DIR}/DnPerfOrderingCriterion_anyOf.cpp
    ${AMF_MODEL_DIR}/DnPerformanceReq.cpp
    ${AMF_MODEL_DIR}/DnnEasdfInfoItem.cpp
    ${AMF_MODEL_DIR}/DnnInfoItem.cpp
    ${AMF_MODEL_DIR}/DnnMbSmfInfoItem.cpp
    ${AMF_MODEL_DIR}/DnnSmfInfoItem.cpp
    ${AMF_MODEL_DIR}/DnnSmfInfoItem_dnaiList_inner.cpp
    ${AMF_MODEL_DIR}/DnnSmfInfoItem_dnn.cpp
    ${AMF_MODEL_DIR}/DnnTsctsfInfoItem.cpp
    ${AMF_MODEL_DIR}/DnnUpfInfoItem.cpp
    ${AMF_MODEL_DIR}/EasdfInfo.cpp
    ${AMF_MODEL_DIR}/EbiArpMapping.cpp
    ${AMF_MODEL_DIR}/EcRestrictionDataWb.cpp
    ${AMF_MODEL_DIR}/Ecgi.cpp
    ${AMF_MODEL_DIR}/EdrxParameters.cpp
    ${AMF_MODEL_DIR}/EllipsoidArc.cpp
    ${AMF_MODEL_DIR}/EmergencyInfo.cpp
    ${AMF_MODEL_DIR}/EnableGroupReachabilityReqData.cpp
    ${AMF_MODEL_DIR}/EnableGroupReachabilityRspData.cpp
    ${AMF_MODEL_DIR}/EnableUeReachabilityReqData.cpp
    ${AMF_MODEL_DIR}/EnableUeReachabilityRspData.cpp
    ${AMF_MODEL_DIR}/EpsInterworkingInfo.cpp
    ${AMF_MODEL_DIR}/EpsIwkPgw.cpp
    ${AMF_MODEL_DIR}/EpsNasCipheringAlgorithm.cpp
    ${AMF_MODEL_DIR}/EpsNasCipheringAlgorithm_anyOf.cpp
    ${AMF_MODEL_DIR}/EpsNasIntegrityAlgorithm.cpp
    ${AMF_MODEL_DIR}/EpsNasIntegrityAlgorithm_anyOf.cpp
    ${AMF_MODEL_DIR}/EpsNasSecurityMode.cpp
    ${AMF_MODEL_DIR}/EthFlowDescription.cpp
    ${AMF_MODEL_DIR}/EutraLocation.cpp
    ${AMF_MODEL_DIR}/EventForMdt.cpp
    ${AMF_MODEL_DIR}/EventForMdt_anyOf.cpp
    ${AMF_MODEL_DIR}/EventId.cpp
    ${AMF_MODEL_DIR}/EventId_anyOf.cpp
    ${AMF_MODEL_DIR}/EventNotification.cpp
    ${AMF_MODEL_DIR}/EventReportingRequirement.cpp
    ${AMF_MODEL_DIR}/EventSubscription.cpp
    ${AMF_MODEL_DIR}/Exception.cpp
    ${AMF_MODEL_DIR}/ExceptionId.cpp
    ${AMF_MODEL_DIR}/ExceptionId_anyOf.cpp
    ${AMF_MODEL_DIR}/ExceptionTrend.cpp
    ${AMF_MODEL_DIR}/ExceptionTrend_anyOf.cpp
    ${AMF_MODEL_DIR}/ExpectedAnalyticsType.cpp
    ${AMF_MODEL_DIR}/ExpectedAnalyticsType_anyOf.cpp
    ${AMF_MODEL_DIR}/ExpectedUeBehavior.cpp
    ${AMF_MODEL_DIR}/ExpectedUeBehaviourData.cpp
    ${AMF_MODEL_DIR}/ExtAmfEventSubscription.cpp
    ${AMF_MODEL_DIR}/ExtSnssai.cpp
    ${AMF_MODEL_DIR}/ExternalClientType.cpp
    ${AMF_MODEL_DIR}/ExternalClientType_anyOf.cpp
    ${AMF_MODEL_DIR}/ExternalMbsServiceArea.cpp
    ${AMF_MODEL_DIR}/FailureEventInfo.cpp
    ${AMF_MODEL_DIR}/FixType.cpp
    ${AMF_MODEL_DIR}/FixType_anyOf.cpp
    ${AMF_MODEL_DIR}/FlowDirection.cpp
    ${AMF_MODEL_DIR}/FlowDirection_anyOf.cpp
    ${AMF_MODEL_DIR}/FlowInfo.cpp
    ${AMF_MODEL_DIR}/GADShape.cpp
    ${AMF_MODEL_DIR}/GNbId.cpp
    ${AMF_MODEL_DIR}/GeographicArea.cpp
    ${AMF_MODEL_DIR}/GeographicalCoordinates.cpp
    ${AMF_MODEL_DIR}/GeraLocation.cpp
    ${AMF_MODEL_DIR}/GlobalRanNodeId.cpp
    ${AMF_MODEL_DIR}/GmlcInfo.cpp
    ${AMF_MODEL_DIR}/GnssId.cpp
    ${AMF_MODEL_DIR}/GnssId_anyOf.cpp
    ${AMF_MODEL_DIR}/GnssPositioningMethodAndUsage.cpp
    ${AMF_MODEL_DIR}/Guami.cpp
    ${AMF_MODEL_DIR}/HfcNodeId.cpp
    ${AMF_MODEL_DIR}/HighAccuracyGnssMetrics.cpp
    ${AMF_MODEL_DIR}/HorizontalVelocity.cpp
    ${AMF_MODEL_DIR}/HorizontalVelocityWithUncertainty.cpp
    ${AMF_MODEL_DIR}/HorizontalWithVerticalVelocity.cpp
    ${AMF_MODEL_DIR}/HorizontalWithVerticalVelocityAndUncertainty.cpp
    ${AMF_MODEL_DIR}/HssInfo.cpp
    ${AMF_MODEL_DIR}/IdentityRange.cpp
    ${AMF_MODEL_DIR}/IdleStatusIndication.cpp
    ${AMF_MODEL_DIR}/ImmediateMdtConf.cpp
    ${AMF_MODEL_DIR}/ImmediateReport.cpp
    ${AMF_MODEL_DIR}/ImsVoPs.cpp
    ${AMF_MODEL_DIR}/ImsVoPs_anyOf.cpp
    ${AMF_MODEL_DIR}/ImsiRange.cpp
    ${AMF_MODEL_DIR}/Inline_object.cpp
    ${AMF_MODEL_DIR}/IntegrityAlgorithm.cpp
    ${AMF_MODEL_DIR}/IntegrityAlgorithm_anyOf.cpp
    ${AMF_MODEL_DIR}/IntegrityRequirements.cpp
    ${AMF_MODEL_DIR}/InterFreqTargetInfo.cpp
    ${AMF_MODEL_DIR}/InterfaceUpfInfoItem.cpp
    ${AMF_MODEL_DIR}/InternalGroupIdRange.cpp
    ${AMF_MODEL_DIR}/InvalidParam.cpp
    ${AMF_MODEL_DIR}/IpAddr.cpp
    ${AMF_MODEL_DIR}/IpAddress.cpp
    ${AMF_MODEL_DIR}/IpEndPoint.cpp
    ${AMF_MODEL_DIR}/IpEthFlowDescription.cpp
    ${AMF_MODEL_DIR}/IpIndex.cpp
    ${AMF_MODEL_DIR}/IpReachability.cpp
    ${AMF_MODEL_DIR}/IpReachability_anyOf.cpp
    ${AMF_MODEL_DIR}/Ipv4AddressRange.cpp
    ${AMF_MODEL_DIR}/Ipv6Addr.cpp
    ${AMF_MODEL_DIR}/Ipv6Prefix.cpp
    ${AMF_MODEL_DIR}/Ipv6PrefixRange.cpp
    ${AMF_MODEL_DIR}/IwmscInfo.cpp
    ${AMF_MODEL_DIR}/JobType.cpp
    ${AMF_MODEL_DIR}/JobType_anyOf.cpp
    ${AMF_MODEL_DIR}/KeyAmf.cpp
    ${AMF_MODEL_DIR}/KeyAmfType.cpp
    ${AMF_MODEL_DIR}/KeyAmfType_anyOf.cpp
    ${AMF_MODEL_DIR}/LadnInfo.cpp
    ${AMF_MODEL_DIR}/LcsPriority.cpp
    ${AMF_MODEL_DIR}/LcsPriority_anyOf.cpp
    ${AMF_MODEL_DIR}/LcsQosClass.cpp
    ${AMF_MODEL_DIR}/LcsQosClass_anyOf.cpp
    ${AMF_MODEL_DIR}/LcsServiceAuth.cpp
    ${AMF_MODEL_DIR}/LcsServiceAuth_anyOf.cpp
    ${AMF_MODEL_DIR}/LdrType.cpp
    ${AMF_MODEL_DIR}/LdrType_anyOf.cpp
    ${AMF_MODEL_DIR}/LineType.cpp
    ${AMF_MODEL_DIR}/LineType_anyOf.cpp
    ${AMF_MODEL_DIR}/Link.cpp
    ${AMF_MODEL_DIR}/LinksValueSchema.cpp
    ${AMF_MODEL_DIR}/LmfInfo.cpp
    ${AMF_MODEL_DIR}/Local2dPointUncertaintyEllipse.cpp
    ${AMF_MODEL_DIR}/Local3dPointUncertaintyEllipsoid.cpp
    ${AMF_MODEL_DIR}/LocalArea.cpp
    ${AMF_MODEL_DIR}/LocalOrigin.cpp
    ${AMF_MODEL_DIR}/LocationArea.cpp
    ${AMF_MODEL_DIR}/LocationAreaId.cpp
    ${AMF_MODEL_DIR}/LocationEvent.cpp
    ${AMF_MODEL_DIR}/LocationEvent_anyOf.cpp
    ${AMF_MODEL_DIR}/LocationFilter.cpp
    ${AMF_MODEL_DIR}/LocationFilter_anyOf.cpp
    ${AMF_MODEL_DIR}/LocationInfo.cpp
    ${AMF_MODEL_DIR}/LocationPrivacyVerResult.cpp
    ${AMF_MODEL_DIR}/LocationPrivacyVerResult_anyOf.cpp
    ${AMF_MODEL_DIR}/LocationQoS.cpp
    ${AMF_MODEL_DIR}/LocationType.cpp
    ${AMF_MODEL_DIR}/LocationType_anyOf.cpp
    ${AMF_MODEL_DIR}/LoggingDurationMdt.cpp
    ${AMF_MODEL_DIR}/LoggingDurationMdt_anyOf.cpp
    ${AMF_MODEL_DIR}/LoggingDurationNrMdt.cpp
    ${AMF_MODEL_DIR}/LoggingIntervalMdt.cpp
    ${AMF_MODEL_DIR}/LoggingIntervalMdt_anyOf.cpp
    ${AMF_MODEL_DIR}/LoggingIntervalNrMdt.cpp
    ${AMF_MODEL_DIR}/LoggingIntervalNrMdt_anyOf.cpp
    ${AMF_MODEL_DIR}/LossOfConnectivityReason.cpp
    ${AMF_MODEL_DIR}/LossOfConnectivityReason_anyOf.cpp
    ${AMF_MODEL_DIR}/LteMInd.cpp
    ${AMF_MODEL_DIR}/LteV2xAuth.cpp
    ${AMF_MODEL_DIR}/MappingOfSnssai.cpp
    ${AMF_MODEL_DIR}/MatchingDirection.cpp
    ${AMF_MODEL_DIR}/MatchingDirection_anyOf.cpp
    ${AMF_MODEL_DIR}/MbSmfInfo.cpp
    ${AMF_MODEL_DIR}/MbUpfInfo.cpp
    ${AMF_MODEL_DIR}/MbsMediaComp.cpp
    ${AMF_MODEL_DIR}/MbsMediaCompRm.cpp
    ${AMF_MODEL_DIR}/MbsMediaInfo.cpp
    ${AMF_MODEL_DIR}/MbsN2MessageTransferReqData.cpp
    ${AMF_MODEL_DIR}/MbsN2MessageTransferRspData.cpp
    ${AMF_MODEL_DIR}/MbsNgapIeType.cpp
    ${AMF_MODEL_DIR}/MbsNgapIeType_anyOf.cpp
    ${AMF_MODEL_DIR}/MbsQoSReq.cpp
    ${AMF_MODEL_DIR}/MbsServiceArea.cpp
    ${AMF_MODEL_DIR}/MbsServiceAreaInfo.cpp
    ${AMF_MODEL_DIR}/MbsServiceInfo.cpp
    ${AMF_MODEL_DIR}/MbsServiceType.cpp
    ${AMF_MODEL_DIR}/MbsServiceType_anyOf.cpp
    ${AMF_MODEL_DIR}/MbsSession.cpp
    ${AMF_MODEL_DIR}/MbsSessionActivityStatus.cpp
    ${AMF_MODEL_DIR}/MbsSessionActivityStatus_anyOf.cpp
    ${AMF_MODEL_DIR}/MbsSessionEvent.cpp
    ${AMF_MODEL_DIR}/MbsSessionEventType.cpp
    ${AMF_MODEL_DIR}/MbsSessionEventType_anyOf.cpp
    ${AMF_MODEL_DIR}/MbsSessionId.cpp
    ${AMF_MODEL_DIR}/MbsSessionSubscription.cpp
    ${AMF_MODEL_DIR}/MbsfnArea.cpp
    ${AMF_MODEL_DIR}/MdtConfiguration.cpp
    ${AMF_MODEL_DIR}/MdtUserConsent.cpp
    ${AMF_MODEL_DIR}/MdtUserConsent_anyOf.cpp
    ${AMF_MODEL_DIR}/MeasurementLteForMdt.cpp
    ${AMF_MODEL_DIR}/MeasurementLteForMdt_anyOf.cpp
    ${AMF_MODEL_DIR}/MeasurementNrForMdt.cpp
    ${AMF_MODEL_DIR}/MeasurementPeriodLteMdt.cpp
    ${AMF_MODEL_DIR}/MediaType.cpp
    ${AMF_MODEL_DIR}/MediaType_anyOf.cpp
    ${AMF_MODEL_DIR}/MfafInfo.cpp
    ${AMF_MODEL_DIR}/MinorLocationQoS.cpp
    ${AMF_MODEL_DIR}/MlAnalyticsInfo.cpp
    ${AMF_MODEL_DIR}/MmContext.cpp
    ${AMF_MODEL_DIR}/MmTransactionLocationReportItem.cpp
    ${AMF_MODEL_DIR}/MmTransactionSliceReportItem.cpp
    ${AMF_MODEL_DIR}/MnpfInfo.cpp
    ${AMF_MODEL_DIR}/ModificationNotification.cpp
    ${AMF_MODEL_DIR}/MoExpDataCounter.cpp
    ${AMF_MODEL_DIR}/MotionEventInfo.cpp
    ${AMF_MODEL_DIR}/N1MessageClass.cpp
    ${AMF_MODEL_DIR}/N1MessageClass_anyOf.cpp
    ${AMF_MODEL_DIR}/N1MessageContainer.cpp
    ${AMF_MODEL_DIR}/N1MessageNotification.cpp
    ${AMF_MODEL_DIR}/N1N2MessageTransferCause.cpp
    ${AMF_MODEL_DIR}/N1N2MessageTransferCause_anyOf.cpp
    ${AMF_MODEL_DIR}/N1N2MessageTransferError.cpp
    ${AMF_MODEL_DIR}/N1N2MessageTransferReqData.cpp
    ${AMF_MODEL_DIR}/N1N2MessageTransferRspData.cpp
    ${AMF_MODEL_DIR}/N1N2MsgTxfrErrDetail.cpp
    ${AMF_MODEL_DIR}/N1N2MsgTxfrFailureNotification.cpp
    ${AMF_MODEL_DIR}/N2InfoContainer.cpp
    ${AMF_MODEL_DIR}/N2InfoContent.cpp
    ${AMF_MODEL_DIR}/N2InfoNotificationRspData.cpp
    ${AMF_MODEL_DIR}/N2InfoNotifyReason.cpp
    ${AMF_MODEL_DIR}/N2InfoNotifyReason_anyOf.cpp
    ${AMF_MODEL_DIR}/N2InformationClass.cpp
    ${AMF_MODEL_DIR}/N2InformationClass_anyOf.cpp
    ${AMF_MODEL_DIR}/N2InformationNotification.cpp
    ${AMF_MODEL_DIR}/N2InformationTransferError.cpp
    ${AMF_MODEL_DIR}/N2InformationTransferReqData.cpp
    ${AMF_MODEL_DIR}/N2InformationTransferResult.cpp
    ${AMF_MODEL_DIR}/N2InformationTransferResult_anyOf.cpp
    ${AMF_MODEL_DIR}/N2InformationTransferRspData.cpp
    ${AMF_MODEL_DIR}/N2InterfaceAmfInfo.cpp
    ${AMF_MODEL_DIR}/N2MbsSmInfo.cpp
    ${AMF_MODEL_DIR}/N2RanInformation.cpp
    ${AMF_MODEL_DIR}/N2SmInformation.cpp
    ${AMF_MODEL_DIR}/N3gaLocation.cpp
    ${AMF_MODEL_DIR}/NFProfile.cpp
    ${AMF_MODEL_DIR}/NFService.cpp
    ${AMF_MODEL_DIR}/NFServiceStatus.cpp
    ${AMF_MODEL_DIR}/NFServiceVersion.cpp
    ${AMF_MODEL_DIR}/NFStatus.cpp
    ${AMF_MODEL_DIR}/NFStatus_anyOf.cpp
    ${AMF_MODEL_DIR}/NFType.cpp
    ${AMF_MODEL_DIR}/NFType_anyOf.cpp
    ${AMF_MODEL_DIR}/NasSecurityMode.cpp
    ${AMF_MODEL_DIR}/Ncgi.cpp
    ${AMF_MODEL_DIR}/NcgiTai.cpp
    ${AMF_MODEL_DIR}/NefInfo.cpp
    ${AMF_MODEL_DIR}/NetworkAreaInfo.cpp
    ${AMF_MODEL_DIR}/NetworkNodeDiameterAddress.cpp
    ${AMF_MODEL_DIR}/NetworkPerfInfo.cpp
    ${AMF_MODEL_DIR}/NetworkPerfRequirement.cpp
    ${AMF_MODEL_DIR}/NetworkPerfType.cpp
    ${AMF_MODEL_DIR}/NetworkPerfType_anyOf.cpp
    ${AMF_MODEL_DIR}/NfInfo.cpp
    ${AMF_MODEL_DIR}/NfInstanceInfo.cpp
    ${AMF_MODEL_DIR}/NfLoadLevelInformation.cpp
    ${AMF_MODEL_DIR}/NfStatus.cpp
    ${AMF_MODEL_DIR}/NgApCause.cpp
    ${AMF_MODEL_DIR}/NgKsi.cpp
    ${AMF_MODEL_DIR}/NgRanTargetId.cpp
    ${AMF_MODEL_DIR}/NgapIeType.cpp
    ${AMF_MODEL_DIR}/NgapIeType_anyOf.cpp
    ${AMF_MODEL_DIR}/NgranFailureEvent.cpp
    ${AMF_MODEL_DIR}/NgranFailureIndication.cpp
    ${AMF_MODEL_DIR}/NgranFailureIndication_anyOf.cpp
    ${AMF_MODEL_DIR}/NnwdafEventsSubscription.cpp
    ${AMF_MODEL_DIR}/NoProfileMatchInfo.cpp
    ${AMF_MODEL_DIR}/NoProfileMatchReason.cpp
    ${AMF_MODEL_DIR}/NoProfileMatchReason_anyOf.cpp
    ${AMF_MODEL_DIR}/NonUeN2InfoSubscriptionCreateData.cpp
    ${AMF_MODEL_DIR}/NonUeN2InfoSubscriptionCreatedData.cpp
    ${AMF_MODEL_DIR}/NotificationFlag.cpp
    ${AMF_MODEL_DIR}/NotificationFlag_anyOf.cpp
    ${AMF_MODEL_DIR}/NotificationMethod.cpp
    ${AMF_MODEL_DIR}/NotificationMethod_anyOf.cpp
    ${AMF_MODEL_DIR}/NotificationType.cpp
    ${AMF_MODEL_DIR}/NotificationType_anyOf.cpp
    ${AMF_MODEL_DIR}/NotifiedPosInfo.cpp
    ${AMF_MODEL_DIR}/NotifyItem.cpp
    ${AMF_MODEL_DIR}/NpnAccessInfo.cpp
    ${AMF_MODEL_DIR}/NrLocation.cpp
    ${AMF_MODEL_DIR}/NrV2xAuth.cpp
    ${AMF_MODEL_DIR}/NrfInfo.cpp
    ${AMF_MODEL_DIR}/NrfInfo_servedAanfInfoList_value_value.cpp
    ${AMF_MODEL_DIR}/NrfInfo_servedAmfInfo_value.cpp
    ${AMF_MODEL_DIR}/NrfInfo_servedAusfInfo_value.cpp
    ${AMF_MODEL_DIR}/NrfInfo_servedBsfInfo_value.cpp
    ${AMF_MODEL_DIR}/NrfInfo_servedChfInfo_value.cpp
    ${AMF_MODEL_DIR}/NrfInfo_servedGmlcInfo_value.cpp
    ${AMF_MODEL_DIR}/NrfInfo_servedHssInfoList_value_value.cpp
    ${AMF_MODEL_DIR}/NrfInfo_servedLmfInfo_value.cpp
    ${AMF_MODEL_DIR}/NrfInfo_servedMbSmfInfoList_value_value.cpp
    ${AMF_MODEL_DIR}/NrfInfo_servedNefInfo_value.cpp
    ${AMF_MODEL_DIR}/NrfInfo_servedNwdafInfo_value.cpp
    ${AMF_MODEL_DIR}/NrfInfo_servedPcfInfo_value.cpp
    ${AMF_MODEL_DIR}/NrfInfo_servedPcscfInfoList_value_value.cpp
    ${AMF_MODEL_DIR}/NrfInfo_servedScpInfoList_value.cpp
    ${AMF_MODEL_DIR}/NrfInfo_servedSeppInfoList_value.cpp
    ${AMF_MODEL_DIR}/NrfInfo_servedSmfInfo_value.cpp
    ${AMF_MODEL_DIR}/NrfInfo_servedUdmInfo_value.cpp
    ${AMF_MODEL_DIR}/NrfInfo_servedUdrInfo_value.cpp
    ${AMF_MODEL_DIR}/NrfInfo_servedUdsfInfo_value.cpp
    ${AMF_MODEL_DIR}/NrfInfo_servedUpfInfo_value.cpp
    ${AMF_MODEL_DIR}/NrppaInformation.cpp
    ${AMF_MODEL_DIR}/NsacfCapability.cpp
    ${AMF_MODEL_DIR}/NsacfInfo.cpp
    ${AMF_MODEL_DIR}/NsagInfo.cpp
    ${AMF_MODEL_DIR}/NsiIdInfo.cpp
    ${AMF_MODEL_DIR}/NsiInformation.cpp
    ${AMF_MODEL_DIR}/NsiLoadLevelInfo.cpp
    ${AMF_MODEL_DIR}/NssaaStatus.cpp
    ${AMF_MODEL_DIR}/NssaafInfo.cpp
    ${AMF_MODEL_DIR}/Nssai.cpp
    ${AMF_MODEL_DIR}/NssaiMapping.cpp
    ${AMF_MODEL_DIR}/NumberAverage.cpp
    ${AMF_MODEL_DIR}/NwdafCapability.cpp
    ${AMF_MODEL_DIR}/NwdafData.cpp
    ${AMF_MODEL_DIR}/NwdafEvent.cpp
    ${AMF_MODEL_DIR}/NwdafEvent_anyOf.cpp
    ${AMF_MODEL_DIR}/NwdafFailureCode.cpp
    ${AMF_MODEL_DIR}/NwdafFailureCode_anyOf.cpp
    ${AMF_MODEL_DIR}/NwdafInfo.cpp
    ${AMF_MODEL_DIR}/NwdafSubscription.cpp
    ${AMF_MODEL_DIR}/ObservedRedundantTransExp.cpp
    ${AMF_MODEL_DIR}/OccurrenceInfo.cpp
    ${AMF_MODEL_DIR}/OccurrenceInfo_anyOf.cpp
    ${AMF_MODEL_DIR}/OdbPacketServices.cpp
    ${AMF_MODEL_DIR}/OpEventType.cpp
    ${AMF_MODEL_DIR}/OpEventType_anyOf.cpp
    ${AMF_MODEL_DIR}/OperationEvent.cpp
    ${AMF_MODEL_DIR}/OperationMode.cpp
    ${AMF_MODEL_DIR}/OperationMode_anyOf.cpp
    ${AMF_MODEL_DIR}/OperationStatus.cpp
    ${AMF_MODEL_DIR}/OperationStatus_anyOf.cpp
    ${AMF_MODEL_DIR}/OutputStrategy.cpp
    ${AMF_MODEL_DIR}/OutputStrategy_anyOf.cpp
    ${AMF_MODEL_DIR}/PWSErrorData.cpp
    ${AMF_MODEL_DIR}/PWSResponseData.cpp
    ${AMF_MODEL_DIR}/PartitioningCriteria.cpp
    ${AMF_MODEL_DIR}/PartitioningCriteria_anyOf.cpp
    ${AMF_MODEL_DIR}/PatchItem.cpp
    ${AMF_MODEL_DIR}/PatchOperation.cpp
    ${AMF_MODEL_DIR}/PatchOperation_anyOf.cpp
    ${AMF_MODEL_DIR}/Pc5FlowBitRates.cpp
    ${AMF_MODEL_DIR}/Pc5QoSPara.cpp
    ${AMF_MODEL_DIR}/Pc5QosFlowItem.cpp
    ${AMF_MODEL_DIR}/PcfInfo.cpp
    ${AMF_MODEL_DIR}/PcfSelectionAssistanceInfo.cpp
    ${AMF_MODEL_DIR}/PcfUeCallbackInfo.cpp
    ${AMF_MODEL_DIR}/PcscfInfo.cpp
    ${AMF_MODEL_DIR}/PduSession.cpp
    ${AMF_MODEL_DIR}/PduSessionContext.cpp
    ${AMF_MODEL_DIR}/PduSessionInfo.cpp
    ${AMF_MODEL_DIR}/PduSessionType.cpp
    ${AMF_MODEL_DIR}/PduSessionType_anyOf.cpp
    ${AMF_MODEL_DIR}/PerfData.cpp
    ${AMF_MODEL_DIR}/PeriodicCommunicationIndicator.cpp
    ${AMF_MODEL_DIR}/PeriodicCommunicationIndicator_anyOf.cpp
    ${AMF_MODEL_DIR}/PeriodicEventInfo.cpp
    ${AMF_MODEL_DIR}/PfdData.cpp
    ${AMF_MODEL_DIR}/PgwInfo.cpp
    ${AMF_MODEL_DIR}/PlmnId.cpp
    ${AMF_MODEL_DIR}/PlmnIdNid.cpp
    ${AMF_MODEL_DIR}/PlmnOauth2.cpp
    ${AMF_MODEL_DIR}/PlmnRange.cpp
    ${AMF_MODEL_DIR}/PlmnRestriction.cpp
    ${AMF_MODEL_DIR}/PlmnSnssai.cpp
    ${AMF_MODEL_DIR}/Point.cpp
    ${AMF_MODEL_DIR}/PointAltitude.cpp
    ${AMF_MODEL_DIR}/PointAltitudeUncertainty.cpp
    ${AMF_MODEL_DIR}/PointUncertaintyCircle.cpp
    ${AMF_MODEL_DIR}/PointUncertaintyEllipse.cpp
    ${AMF_MODEL_DIR}/PolicyAssociation.cpp
    ${AMF_MODEL_DIR}/PolicyAssociationRequest.cpp
    ${AMF_MODEL_DIR}/PolicyAssociationUpdateRequest.cpp
    ${AMF_MODEL_DIR}/PolicyReqTrigger.cpp
    ${AMF_MODEL_DIR}/PolicyReqTrigger_anyOf.cpp
    ${AMF_MODEL_DIR}/PolicyUpdate.cpp
    ${AMF_MODEL_DIR}/Polygon.cpp
    ${AMF_MODEL_DIR}/PositioningMethod.cpp
    ${AMF_MODEL_DIR}/PositioningMethodAndUsage.cpp
    ${AMF_MODEL_DIR}/PositioningMethodMdt.cpp
    ${AMF_MODEL_DIR}/PositioningMethodMdt_anyOf.cpp
    ${AMF_MODEL_DIR}/PositioningMethod_anyOf.cpp
    ${AMF_MODEL_DIR}/PositioningMode.cpp
    ${AMF_MODEL_DIR}/PositioningMode_anyOf.cpp
    ${AMF_MODEL_DIR}/PreemptionCapability.cpp
    ${AMF_MODEL_DIR}/PreemptionCapability_anyOf.cpp
    ${AMF_MODEL_DIR}/PreemptionVulnerability.cpp
    ${AMF_MODEL_DIR}/PreemptionVulnerability_anyOf.cpp
    ${AMF_MODEL_DIR}/PreferredSearch.cpp
    ${AMF_MODEL_DIR}/PresenceInfo.cpp
    ${AMF_MODEL_DIR}/PresenceInfoRm.cpp
    ${AMF_MODEL_DIR}/PresenceState.cpp
    ${AMF_MODEL_DIR}/PresenceState_anyOf.cpp
    ${AMF_MODEL_DIR}/PrevSubInfo.cpp
    ${AMF_MODEL_DIR}/ProSeCapability.cpp
    ${AMF_MODEL_DIR}/ProSeInformation.cpp
    ${AMF_MODEL_DIR}/ProblemDetails.cpp
    ${AMF_MODEL_DIR}/ProblemDetailsEnableUeReachability.cpp
    ${AMF_MODEL_DIR}/ProseContext.cpp
    ${AMF_MODEL_DIR}/ProvideLocInfo.cpp
    ${AMF_MODEL_DIR}/ProvidePosInfo.cpp
    ${AMF_MODEL_DIR}/PtwParameters.cpp
    ${AMF_MODEL_DIR}/PwsInformation.cpp
    ${AMF_MODEL_DIR}/QosRequirement.cpp
    ${AMF_MODEL_DIR}/QosResourceType.cpp
    ${AMF_MODEL_DIR}/QosResourceType_anyOf.cpp
    ${AMF_MODEL_DIR}/QosSustainabilityInfo.cpp
    ${AMF_MODEL_DIR}/QueryParamCombination.cpp
    ${AMF_MODEL_DIR}/QueryParameter.cpp
    ${AMF_MODEL_DIR}/RankingCriterion.cpp
    ${AMF_MODEL_DIR}/RatFreqInformation.cpp
    ${AMF_MODEL_DIR}/RatSelector.cpp
    ${AMF_MODEL_DIR}/RatSelector_anyOf.cpp
    ${AMF_MODEL_DIR}/RatType.cpp
    ${AMF_MODEL_DIR}/RatType_anyOf.cpp
    ${AMF_MODEL_DIR}/ReachabilityFilter.cpp
    ${AMF_MODEL_DIR}/ReachabilityFilter_anyOf.cpp
    ${AMF_MODEL_DIR}/ReachabilityNotificationData.cpp
    ${AMF_MODEL_DIR}/ReachableUeInfo.cpp
    ${AMF_MODEL_DIR}/RedTransExpOrderingCriterion.cpp
    ${AMF_MODEL_DIR}/RedTransExpOrderingCriterion_anyOf.cpp
    ${AMF_MODEL_DIR}/RedirectResponse.cpp
    ${AMF_MODEL_DIR}/RedundantTransmissionExpInfo.cpp
    ${AMF_MODEL_DIR}/RedundantTransmissionExpPerTS.cpp
    ${AMF_MODEL_DIR}/RedundantTransmissionExpReq.cpp
    ${AMF_MODEL_DIR}/RefToBinaryData.cpp
    ${AMF_MODEL_DIR}/RegistrationContextContainer.cpp
    ${AMF_MODEL_DIR}/RelativeCartesianLocation.cpp
    ${AMF_MODEL_DIR}/ReleaseCause.cpp
    ${AMF_MODEL_DIR}/ReleaseCause_anyOf.cpp
    ${AMF_MODEL_DIR}/ReleaseSessionInfo.cpp
    ${AMF_MODEL_DIR}/ReportAmountMdt.cpp
    ${AMF_MODEL_DIR}/ReportAmountMdt_anyOf.cpp
    ${AMF_MODEL_DIR}/ReportIntervalMdt.cpp
    ${AMF_MODEL_DIR}/ReportIntervalMdt_anyOf.cpp
    ${AMF_MODEL_DIR}/ReportIntervalNrMdt.cpp
    ${AMF_MODEL_DIR}/ReportIntervalNrMdt_anyOf.cpp
    ${AMF_MODEL_DIR}/ReportTypeMdt.cpp
    ${AMF_MODEL_DIR}/ReportTypeMdt_anyOf.cpp
    ${AMF_MODEL_DIR}/ReportingArea.cpp
    ${AMF_MODEL_DIR}/ReportingAreaType.cpp
    ${AMF_MODEL_DIR}/ReportingAreaType_anyOf.cpp
    ${AMF_MODEL_DIR}/ReportingInformation.cpp
    ${AMF_MODEL_DIR}/ReportingTrigger.cpp
    ${AMF_MODEL_DIR}/ReportingTrigger_anyOf.cpp
    ${AMF_MODEL_DIR}/RequestLocInfo.cpp
    ${AMF_MODEL_DIR}/RequestPosInfo.cpp
    ${AMF_MODEL_DIR}/RequestTrigger.cpp
    ${AMF_MODEL_DIR}/RequestTrigger_anyOf.cpp
    ${AMF_MODEL_DIR}/ReservPriority.cpp
    ${AMF_MODEL_DIR}/ReservPriority_anyOf.cpp
    ${AMF_MODEL_DIR}/ResourceStatus.cpp
    ${AMF_MODEL_DIR}/ResourceStatus_anyOf.cpp
    ${AMF_MODEL_DIR}/ResourceUsage.cpp
    ${AMF_MODEL_DIR}/ResponseTime.cpp
    ${AMF_MODEL_DIR}/ResponseTime_anyOf.cpp
    ${AMF_MODEL_DIR}/RestrictionType.cpp
    ${AMF_MODEL_DIR}/RestrictionType_anyOf.cpp
    ${AMF_MODEL_DIR}/ResynchronizationInfo.cpp
    ${AMF_MODEL_DIR}/RetainabilityThreshold.cpp
    ${AMF_MODEL_DIR}/RmInfo.cpp
    ${AMF_MODEL_DIR}/RmState.cpp
    ${AMF_MODEL_DIR}/RmState_anyOf.cpp
    ${AMF_MODEL_DIR}/RoamingRestrictions.cpp
    ${AMF_MODEL_DIR}/RoutingAreaId.cpp
    ${AMF_MODEL_DIR}/SbiBindingLevel.cpp
    ${AMF_MODEL_DIR}/SbiBindingLevel_anyOf.cpp
    ${AMF_MODEL_DIR}/ScType.cpp
    ${AMF_MODEL_DIR}/ScType_anyOf.cpp
    ${AMF_MODEL_DIR}/ScheduledCommunicationTime.cpp
    ${AMF_MODEL_DIR}/ScheduledCommunicationType.cpp
    ${AMF_MODEL_DIR}/ScheduledCommunicationType_anyOf.cpp
    ${AMF_MODEL_DIR}/ScpCapability.cpp
    ${AMF_MODEL_DIR}/ScpCapability_anyOf.cpp
    ${AMF_MODEL_DIR}/ScpDomainInfo.cpp
    ${AMF_MODEL_DIR}/ScpInfo.cpp
    ${AMF_MODEL_DIR}/SdRange.cpp
    ${AMF_MODEL_DIR}/SdmSubscription.cpp
    ${AMF_MODEL_DIR}/SeafData.cpp
    ${AMF_MODEL_DIR}/SearchResult.cpp
    ${AMF_MODEL_DIR}/SensorMeasurement.cpp
    ${AMF_MODEL_DIR}/SensorMeasurement_anyOf.cpp
    ${AMF_MODEL_DIR}/SeppInfo.cpp
    ${AMF_MODEL_DIR}/ServerAddressingInfo.cpp
    ${AMF_MODEL_DIR}/ServiceAreaId.cpp
    ${AMF_MODEL_DIR}/ServiceAreaRestriction.cpp
    ${AMF_MODEL_DIR}/ServiceExperienceInfo.cpp
    ${AMF_MODEL_DIR}/ServiceExperienceType.cpp
    ${AMF_MODEL_DIR}/ServiceExperienceType_anyOf.cpp
    ${AMF_MODEL_DIR}/ServiceName.cpp
    ${AMF_MODEL_DIR}/ServiceName_anyOf.cpp
    ${AMF_MODEL_DIR}/SessInactTimerForUeComm.cpp
    ${AMF_MODEL_DIR}/SharedDataIdRange.cpp
    ${AMF_MODEL_DIR}/SliceInfoForRegistration.cpp
    ${AMF_MODEL_DIR}/SliceLoadLevelInformation.cpp
    ${AMF_MODEL_DIR}/SliceMbr.cpp
    ${AMF_MODEL_DIR}/SliceMbrRm.cpp
    ${AMF_MODEL_DIR}/SmContextStatus.cpp
    ${AMF_MODEL_DIR}/SmContextStatusNotification.cpp
    ${AMF_MODEL_DIR}/SmContextStatus_anyOf.cpp
    ${AMF_MODEL_DIR}/SmPolicyAssociationReleaseCause.cpp
    ${AMF_MODEL_DIR}/SmPolicyAssociationReleaseCause_anyOf.cpp
    ${AMF_MODEL_DIR}/SmallDataRateStatus.cpp
    ${AMF_MODEL_DIR}/SmallDataRateStatusInfo.cpp
    ${AMF_MODEL_DIR}/SmcceInfo.cpp
    ${AMF_MODEL_DIR}/SmcceUeList.cpp
    ${AMF_MODEL_DIR}/SmfChangeIndication.cpp
    ${AMF_MODEL_DIR}/SmfChangeIndication_anyOf.cpp
    ${AMF_MODEL_DIR}/SmfChangeInfo.cpp
    ${AMF_MODEL_DIR}/SmfInfo.cpp
    ${AMF_MODEL_DIR}/SmfSelectionData.cpp
    ${AMF_MODEL_DIR}/SmfSelectionSubscriptionData.cpp
    ${AMF_MODEL_DIR}/Snssai.cpp
    ${AMF_MODEL_DIR}/SnssaiEasdfInfoItem.cpp
    ${AMF_MODEL_DIR}/SnssaiExtension.cpp
    ${AMF_MODEL_DIR}/SnssaiInfo.cpp
    ${AMF_MODEL_DIR}/SnssaiInfoItem.cpp
    ${AMF_MODEL_DIR}/SnssaiMbSmfInfoItem.cpp
    ${AMF_MODEL_DIR}/SnssaiSmfInfoItem.cpp
    ${AMF_MODEL_DIR}/SnssaiTaiMapping.cpp
    ${AMF_MODEL_DIR}/SnssaiTsctsfInfoItem.cpp
    ${AMF_MODEL_DIR}/SnssaiUpfInfoItem.cpp
    ${AMF_MODEL_DIR}/SorInfo.cpp
    ${AMF_MODEL_DIR}/SorUpdateIndicator.cpp
    ${AMF_MODEL_DIR}/SorUpdateIndicator_anyOf.cpp
    ${AMF_MODEL_DIR}/Ssm.cpp
    ${AMF_MODEL_DIR}/StationaryIndication.cpp
    ${AMF_MODEL_DIR}/StationaryIndication_anyOf.cpp
    ${AMF_MODEL_DIR}/StatusChange.cpp
    ${AMF_MODEL_DIR}/StatusChange_anyOf.cpp
    ${AMF_MODEL_DIR}/StatusInfo.cpp
    ${AMF_MODEL_DIR}/SteeringContainer.cpp
    ${AMF_MODEL_DIR}/SteeringInfo.cpp
    ${AMF_MODEL_DIR}/SubscribedSnssai.cpp
    ${AMF_MODEL_DIR}/SubscriptionData.cpp
    ${AMF_MODEL_DIR}/SuciInfo.cpp
    ${AMF_MODEL_DIR}/SupiRange.cpp
    ${AMF_MODEL_DIR}/SupportedGADShapes.cpp
    ${AMF_MODEL_DIR}/SupportedGADShapes_anyOf.cpp
    ${AMF_MODEL_DIR}/SupportedSnssai.cpp
    ${AMF_MODEL_DIR}/SvcExperience.cpp
    ${AMF_MODEL_DIR}/TacInfo.cpp
    ${AMF_MODEL_DIR}/TacRange.cpp
    ${AMF_MODEL_DIR}/Tai.cpp
    ${AMF_MODEL_DIR}/TaiRange.cpp
    ${AMF_MODEL_DIR}/TargetArea.cpp
    ${AMF_MODEL_DIR}/TargetUeInformation.cpp
    ${AMF_MODEL_DIR}/TerminationCause.cpp
    ${AMF_MODEL_DIR}/TerminationCause_anyOf.cpp
    ${AMF_MODEL_DIR}/TerminationNotification.cpp
    ${AMF_MODEL_DIR}/ThresholdLevel.cpp
    ${AMF_MODEL_DIR}/TimeUnit.cpp
    ${AMF_MODEL_DIR}/TimeUnit_anyOf.cpp
    ${AMF_MODEL_DIR}/TimeWindow.cpp
    ${AMF_MODEL_DIR}/Tmgi.cpp
    ${AMF_MODEL_DIR}/TmgiRange.cpp
    ${AMF_MODEL_DIR}/TnapId.cpp
    ${AMF_MODEL_DIR}/TngfInfo.cpp
    ${AMF_MODEL_DIR}/TopApplication.cpp
    ${AMF_MODEL_DIR}/TraceData.cpp
    ${AMF_MODEL_DIR}/TraceDepth.cpp
    ${AMF_MODEL_DIR}/TraceDepth_anyOf.cpp
    ${AMF_MODEL_DIR}/TrafficCharacterization.cpp
    ${AMF_MODEL_DIR}/TrafficDescriptor.cpp
    ${AMF_MODEL_DIR}/TrafficInformation.cpp
    ${AMF_MODEL_DIR}/TrafficProfile.cpp
    ${AMF_MODEL_DIR}/TrafficProfile_anyOf.cpp
    ${AMF_MODEL_DIR}/TransferReason.cpp
    ${AMF_MODEL_DIR}/TransferReason_anyOf.cpp
    ${AMF_MODEL_DIR}/TransportProtocol.cpp
    ${AMF_MODEL_DIR}/TransportProtocol_anyOf.cpp
    ${AMF_MODEL_DIR}/TrustAfInfo.cpp
    ${AMF_MODEL_DIR}/TsctsfInfo.cpp
    ${AMF_MODEL_DIR}/TunnelAddress.cpp
    ${AMF_MODEL_DIR}/TwapId.cpp
    ${AMF_MODEL_DIR}/TwifInfo.cpp
    ${AMF_MODEL_DIR}/UEAuthenticationCtx.cpp
    ${AMF_MODEL_DIR}/UEAuthenticationCtx_5gAuthData.cpp
    ${AMF_MODEL_DIR}/UEContextRelease.cpp
    ${AMF_MODEL_DIR}/UEIdExt.cpp
    ${AMF_MODEL_DIR}/UPInterfaceType.cpp
    ${AMF_MODEL_DIR}/UPInterfaceType_anyOf.cpp
    ${AMF_MODEL_DIR}/UdmInfo.cpp
    ${AMF_MODEL_DIR}/UdrInfo.cpp
    ${AMF_MODEL_DIR}/UdsfInfo.cpp
    ${AMF_MODEL_DIR}/UeAccessBehaviorReportItem.cpp
    ${AMF_MODEL_DIR}/UeAnalyticsContextDescriptor.cpp
    ${AMF_MODEL_DIR}/UeAuth.cpp
    ${AMF_MODEL_DIR}/UeAuth_anyOf.cpp
    ${AMF_MODEL_DIR}/UeCommunication.cpp
    ${AMF_MODEL_DIR}/UeContext.cpp
    ${AMF_MODEL_DIR}/UeContextCancelRelocateData.cpp
    ${AMF_MODEL_DIR}/UeContextCreateData.cpp
    ${AMF_MODEL_DIR}/UeContextCreateError.cpp
    ${AMF_MODEL_DIR}/UeContextCreatedData.cpp
    ${AMF_MODEL_DIR}/UeContextInSmfData.cpp
    ${AMF_MODEL_DIR}/UeContextInfo.cpp
    ${AMF_MODEL_DIR}/UeContextInfoClass.cpp
    ${AMF_MODEL_DIR}/UeContextInfoClass_anyOf.cpp
    ${AMF_MODEL_DIR}/UeContextRelocateData.cpp
    ${AMF_MODEL_DIR}/UeContextRelocatedData.cpp
    ${AMF_MODEL_DIR}/UeContextTransferReqData.cpp
    ${AMF_MODEL_DIR}/UeContextTransferRspData.cpp
    ${AMF_MODEL_DIR}/UeContextTransferStatus.cpp
    ${AMF_MODEL_DIR}/UeContextTransferStatus_anyOf.cpp
    ${AMF_MODEL_DIR}/UeDifferentiationInfo.cpp
    ${AMF_MODEL_DIR}/UeInAreaFilter.cpp
    ${AMF_MODEL_DIR}/UeInfo.cpp
    ${AMF_MODEL_DIR}/UeLocationTrendsReportItem.cpp
    ${AMF_MODEL_DIR}/UeMobility.cpp
    ${AMF_MODEL_DIR}/UeN1N2InfoSubscriptionCreateData.cpp
    ${AMF_MODEL_DIR}/UeN1N2InfoSubscriptionCreatedData.cpp
    ${AMF_MODEL_DIR}/UePrivacyRequirements.cpp
    ${AMF_MODEL_DIR}/UeReachability.cpp
    ${AMF_MODEL_DIR}/UeReachability_anyOf.cpp
    ${AMF_MODEL_DIR}/UeReachableInd.cpp
    ${AMF_MODEL_DIR}/UeReachableInd_anyOf.cpp
    ${AMF_MODEL_DIR}/UeRegStatusUpdateReqData.cpp
    ${AMF_MODEL_DIR}/UeRegStatusUpdateRspData.cpp
    ${AMF_MODEL_DIR}/UeSliceMbr.cpp
    ${AMF_MODEL_DIR}/UeType.cpp
    ${AMF_MODEL_DIR}/UeType_anyOf.cpp
    ${AMF_MODEL_DIR}/UmtTime.cpp
    ${AMF_MODEL_DIR}/UnTrustAfInfo.cpp
    ${AMF_MODEL_DIR}/UncertaintyEllipse.cpp
    ${AMF_MODEL_DIR}/UncertaintyEllipsoid.cpp
    ${AMF_MODEL_DIR}/UpdpSubscriptionData.cpp
    ${AMF_MODEL_DIR}/UpfInfo.cpp
    ${AMF_MODEL_DIR}/UpfInformation.cpp
    ${AMF_MODEL_DIR}/UpuData.cpp
    ${AMF_MODEL_DIR}/UpuInfo.cpp
    ${AMF_MODEL_DIR}/UriScheme.cpp
    ${AMF_MODEL_DIR}/UriScheme_anyOf.cpp
    ${AMF_MODEL_DIR}/Usage.cpp
    ${AMF_MODEL_DIR}/Usage_anyOf.cpp
    ${AMF_MODEL_DIR}/UserDataCongestionInfo.cpp
    ${AMF_MODEL_DIR}/UserLocation.cpp
    ${AMF_MODEL_DIR}/UtraLocation.cpp
    ${AMF_MODEL_DIR}/UuaaMmStatus.cpp
    ${AMF_MODEL_DIR}/UuaaMmStatus_anyOf.cpp
    ${AMF_MODEL_DIR}/V2xCapability.cpp
    ${AMF_MODEL_DIR}/V2xContext.cpp
    ${AMF_MODEL_DIR}/V2xInformation.cpp
    ${AMF_MODEL_DIR}/VelocityEstimate.cpp
    ${AMF_MODEL_DIR}/VelocityRequested.cpp
    ${AMF_MODEL_DIR}/VelocityRequested_anyOf.cpp
    ${AMF_MODEL_DIR}/VendorSpecificFeature.cpp
    ${AMF_MODEL_DIR}/VerticalDirection.cpp
    ${AMF_MODEL_DIR}/VgmlcAddress.cpp
    ${AMF_MODEL_DIR}/WAgfInfo.cpp
    ${AMF_MODEL_DIR}/WirelineArea.cpp
    ${AMF_MODEL_DIR}/WirelineServiceAreaRestriction.cpp
    ${AMF_MODEL_DIR}/WlanOrderingCriterion.cpp
    ${AMF_MODEL_DIR}/WlanOrderingCriterion_anyOf.cpp
    ${AMF_MODEL_DIR}/WlanPerSsIdPerformanceInfo.cpp
    ${AMF_MODEL_DIR}/WlanPerTsPerformanceInfo.cpp
    ${AMF_MODEL_DIR}/WlanPerformanceInfo.cpp
    ${AMF_MODEL_DIR}/WlanPerformanceReq.cpp
    ${AMF_MODEL_DIR}/_5GsUserState_anyOf.cpp
    ${AMF_MODEL_DIR}/r_5GDdnmfInfo.cpp
    ${AMF_MODEL_DIR}/r_5GsUserState.cpp
    ${AMF_MODEL_DIR}/r_5GsUserStateInfo.cpp
    ${AMF_MODEL_DIR}/Helpers.cpp
    ${AMF_MODEL_DIR}/AcsInfo.cpp
    ${AMF_MODEL_DIR}/AfExternal.cpp
    ${AMF_MODEL_DIR}/AppDescriptor.cpp
    ${AMF_MODEL_DIR}/CodeWordInd.cpp
    ${AMF_MODEL_DIR}/CodeWordInd_anyOf.cpp
    ${AMF_MODEL_DIR}/DefaultUnrelatedClass.cpp
    ${AMF_MODEL_DIR}/DnnConfiguration.cpp
    ${AMF_MODEL_DIR}/EcsAddrConfigInfo.cpp
    ${AMF_MODEL_DIR}/EcsServerAddr.cpp
    ${AMF_MODEL_DIR}/ExtendedSmSubsData.cpp
    ${AMF_MODEL_DIR}/ExternalUnrelatedClass.cpp
    ${AMF_MODEL_DIR}/FrameRouteInfo.cpp
    ${AMF_MODEL_DIR}/GeoServiceArea.cpp
    ${AMF_MODEL_DIR}/LcsBroadcastAssistanceTypesData.cpp
    ${AMF_MODEL_DIR}/LcsClientClass.cpp
    ${AMF_MODEL_DIR}/LcsClientClass_anyOf.cpp
    ${AMF_MODEL_DIR}/LcsClientExternal.cpp
    ${AMF_MODEL_DIR}/LcsClientGroupExternal.cpp
    ${AMF_MODEL_DIR}/LcsMoData.cpp
    ${AMF_MODEL_DIR}/LcsMoServiceClass.cpp
    ${AMF_MODEL_DIR}/LcsMoServiceClass_anyOf.cpp
    ${AMF_MODEL_DIR}/LcsPrivacyData.cpp
    ${AMF_MODEL_DIR}/LocationPrivacyInd.cpp
    ${AMF_MODEL_DIR}/LocationPrivacyInd_anyOf.cpp
    ${AMF_MODEL_DIR}/Lpi.cpp
    ${AMF_MODEL_DIR}/MbsSubscriptionData.cpp
    ${AMF_MODEL_DIR}/NiddInformation.cpp
    ${AMF_MODEL_DIR}/PduSessionContinuityInd.cpp
    ${AMF_MODEL_DIR}/PduSessionContinuityInd_anyOf.cpp
    ${AMF_MODEL_DIR}/PduSessionTypes.cpp
    ${AMF_MODEL_DIR}/PlmnOperatorClass.cpp
    ${AMF_MODEL_DIR}/PrivacyCheckRelatedAction.cpp
    ${AMF_MODEL_DIR}/PrivacyCheckRelatedAction_anyOf.cpp
    ${AMF_MODEL_DIR}/ProSeAllowedPlmn.cpp
    ${AMF_MODEL_DIR}/ProseDirectAllowed.cpp
    ${AMF_MODEL_DIR}/ProseDirectAllowed_anyOf.cpp
    ${AMF_MODEL_DIR}/ProseServiceAuth.cpp
    ${AMF_MODEL_DIR}/ProseSubscriptionData.cpp
    ${AMF_MODEL_DIR}/ServiceTypeUnrelatedClass.cpp
    ${AMF_MODEL_DIR}/SessionManagementSubscriptionData.cpp
    ${AMF_MODEL_DIR}/SharedData.cpp
    ${AMF_MODEL_DIR}/SharedDataTreatmentInstruction.cpp
    ${AMF_MODEL_DIR}/SharedDataTreatmentInstruction_anyOf.cpp
    ${AMF_MODEL_DIR}/SmSubsData.cpp
    ${AMF_MODEL_DIR}/SmsManagementSubscriptionData.cpp
    ${AMF_MODEL_DIR}/SmsSubscriptionData.cpp
    ${AMF_MODEL_DIR}/SmsfInfo.cpp
    ${AMF_MODEL_DIR}/SpatialValidityCond.cpp
    ${AMF_MODEL_DIR}/SscMode.cpp
    ${AMF_MODEL_DIR}/SscMode_anyOf.cpp
    ${AMF_MODEL_DIR}/SscModes.cpp
    ${AMF_MODEL_DIR}/SubscribedDefaultQos.cpp
    ${AMF_MODEL_DIR}/SubscriptionDataSets.cpp
    ${AMF_MODEL_DIR}/SuggestedPacketNumDl.cpp
    ${AMF_MODEL_DIR}/UcSubscriptionData.cpp
    ${AMF_MODEL_DIR}/UeContextInAmfData.cpp
    ${AMF_MODEL_DIR}/UeContextInSmfDataSubFilter.cpp
    ${AMF_MODEL_DIR}/UeContextInSmsfData.cpp
    ${AMF_MODEL_DIR}/UnrelatedClass.cpp
    ${AMF_MODEL_DIR}/UpConfidentiality.cpp
    ${AMF_MODEL_DIR}/UpIntegrity.cpp
    ${AMF_MODEL_DIR}/UpIntegrity_anyOf.cpp
    ${AMF_MODEL_DIR}/UpSecurity.cpp
    ${AMF_MODEL_DIR}/UserConsent.cpp
    ${AMF_MODEL_DIR}/V2xSubscriptionData.cpp
    ${AMF_MODEL_DIR}/ValidTimePeriod.cpp
    ${AMF_MODEL_DIR}/VnGroupData.cpp
)

## CONFIG used in NF_TARGET (main)
if (TARGET ${NF_TARGET})
    target_include_directories(${NF_TARGET} PUBLIC ${AMF_MODEL_DIR})
    target_sources(${NF_TARGET} PRIVATE
            ${AMF_MODEL_SRC_FILES}
    )
endif()
