/**
* Namf_EventExposure
* AMF Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
*
* The version of the OpenAPI document: 1.2.3
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * AmfEvent.h
 *
 * Describes an event to be subscribed
 */

#ifndef AmfEvent_H_
#define AmfEvent_H_


#include "ExtSnssai.h"
#include "LocationFilter.h"
#include <string>
#include "ReachabilityFilter.h"
#include "TrafficDescriptor.h"
#include "PresenceInfo.h"
#include "UeInAreaFilter.h"
#include <vector>
#include "AmfEventType.h"
#include "DispersionArea.h"
#include "AmfEventArea.h"
#include "TargetArea.h"
#include <map>
#include <nlohmann/json.hpp>

namespace oai::model
{

/// <summary>
/// Describes an event to be subscribed
/// </summary>
class  AmfEvent
{
public:
    AmfEvent();
    virtual ~AmfEvent() = default;


    /// <summary>
    /// Validate the current data in the model. Throws a ValidationException on failure.
    /// </summary>
    void validate() const;

    /// <summary>
    /// Validate the current data in the model. Returns false on error and writes an error
    /// message into the given stringstream.
    /// </summary>
    bool validate(std::stringstream& msg) const;

    /// <summary>
    /// Helper overload for validate. Used when one model stores another model and calls it's validate.
    /// Not meant to be called outside that case.
    /// </summary>
    bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

    bool operator==(const AmfEvent& rhs) const;
    bool operator!=(const AmfEvent& rhs) const;

    /////////////////////////////////////////////
    /// AmfEvent members

    /// <summary>
    /// 
    /// </summary>
    oai::model::AmfEventType getType() const;
    void setType(oai::model::AmfEventType const& value);
    /// <summary>
    /// 
    /// </summary>
    bool isImmediateFlag() const;
    void setImmediateFlag(bool const value);
    bool immediateFlagIsSet() const;
    void unsetImmediateFlag();
    /// <summary>
    /// 
    /// </summary>
    std::vector<oai::model::AmfEventArea> getAreaList() const;
    void setAreaList(std::vector<oai::model::AmfEventArea> const& value);
    bool areaListIsSet() const;
    void unsetAreaList();
    /// <summary>
    /// 
    /// </summary>
    std::vector<oai::model::LocationFilter> getLocationFilterList() const;
    void setLocationFilterList(std::vector<oai::model::LocationFilter> const& value);
    bool locationFilterListIsSet() const;
    void unsetLocationFilterList();
    /// <summary>
    /// 
    /// </summary>
    int32_t getRefId() const;
    void setRefId(int32_t const value);
    bool refIdIsSet() const;
    void unsetRefId();
    /// <summary>
    /// 
    /// </summary>
    std::vector<oai::model::TrafficDescriptor> getTrafficDescriptorList() const;
    void setTrafficDescriptorList(std::vector<oai::model::TrafficDescriptor> const& value);
    bool trafficDescriptorListIsSet() const;
    void unsetTrafficDescriptorList();
    /// <summary>
    /// 
    /// </summary>
    bool isReportUeReachable() const;
    void setReportUeReachable(bool const value);
    bool reportUeReachableIsSet() const;
    void unsetReportUeReachable();
    /// <summary>
    /// 
    /// </summary>
    oai::model::ReachabilityFilter getReachabilityFilter() const;
    void setReachabilityFilter(oai::model::ReachabilityFilter const& value);
    bool reachabilityFilterIsSet() const;
    void unsetReachabilityFilter();
    /// <summary>
    /// 
    /// </summary>
    bool isUdmDetectInd() const;
    void setUdmDetectInd(bool const value);
    bool udmDetectIndIsSet() const;
    void unsetUdmDetectInd();
    /// <summary>
    /// 
    /// </summary>
    int32_t getMaxReports() const;
    void setMaxReports(int32_t const value);
    bool maxReportsIsSet() const;
    void unsetMaxReports();
    /// <summary>
    /// A map(list of key-value pairs) where praId serves as key.
    /// </summary>
    std::map<std::string, oai::model::PresenceInfo> getPresenceInfoList() const;
    void setPresenceInfoList(std::map<std::string, oai::model::PresenceInfo> const& value);
    bool presenceInfoListIsSet() const;
    void unsetPresenceInfoList();
    /// <summary>
    /// indicating a time in seconds.
    /// </summary>
    int32_t getMaxResponseTime() const;
    void setMaxResponseTime(int32_t const value);
    bool maxResponseTimeIsSet() const;
    void unsetMaxResponseTime();
    /// <summary>
    /// 
    /// </summary>
    oai::model::TargetArea getTargetArea() const;
    void setTargetArea(oai::model::TargetArea const& value);
    bool targetAreaIsSet() const;
    void unsetTargetArea();
    /// <summary>
    /// 
    /// </summary>
    std::vector<oai::model::ExtSnssai> getSnssaiFilter() const;
    void setSnssaiFilter(std::vector<oai::model::ExtSnssai> const& value);
    bool snssaiFilterIsSet() const;
    void unsetSnssaiFilter();
    /// <summary>
    /// 
    /// </summary>
    oai::model::UeInAreaFilter getUeInAreaFilter() const;
    void setUeInAreaFilter(oai::model::UeInAreaFilter const& value);
    bool ueInAreaFilterIsSet() const;
    void unsetUeInAreaFilter();
    /// <summary>
    /// indicating a time in seconds.
    /// </summary>
    int32_t getMinInterval() const;
    void setMinInterval(int32_t const value);
    bool minIntervalIsSet() const;
    void unsetMinInterval();
    /// <summary>
    /// string with format &#39;date-time&#39; as defined in OpenAPI.
    /// </summary>
    std::string getNextReport() const;
    void setNextReport(std::string const& value);
    bool nextReportIsSet() const;
    void unsetNextReport();
    /// <summary>
    /// 
    /// </summary>
    bool isIdleStatusInd() const;
    void setIdleStatusInd(bool const value);
    bool idleStatusIndIsSet() const;
    void unsetIdleStatusInd();
    /// <summary>
    /// 
    /// </summary>
    oai::model::DispersionArea getDispersionArea() const;
    void setDispersionArea(oai::model::DispersionArea const& value);
    bool dispersionAreaIsSet() const;
    void unsetDispersionArea();
    /// <summary>
    /// string with format &#39;date-time&#39; as defined in OpenAPI.
    /// </summary>
    std::string getNextPeriodicReportTime() const;
    void setNextPeriodicReportTime(std::string const& value);
    bool nextPeriodicReportTimeIsSet() const;
    void unsetNextPeriodicReportTime();

    friend  void to_json(nlohmann::json& j, const AmfEvent& o);
    friend  void from_json(const nlohmann::json& j, AmfEvent& o);
protected:
    oai::model::AmfEventType m_Type;

    bool m_ImmediateFlag;
    bool m_ImmediateFlagIsSet;
    std::vector<oai::model::AmfEventArea> m_AreaList;
    bool m_AreaListIsSet;
    std::vector<oai::model::LocationFilter> m_LocationFilterList;
    bool m_LocationFilterListIsSet;
    int32_t m_RefId;
    bool m_RefIdIsSet;
    std::vector<oai::model::TrafficDescriptor> m_TrafficDescriptorList;
    bool m_TrafficDescriptorListIsSet;
    bool m_ReportUeReachable;
    bool m_ReportUeReachableIsSet;
    oai::model::ReachabilityFilter m_ReachabilityFilter;
    bool m_ReachabilityFilterIsSet;
    bool m_UdmDetectInd;
    bool m_UdmDetectIndIsSet;
    int32_t m_MaxReports;
    bool m_MaxReportsIsSet;
    std::map<std::string, oai::model::PresenceInfo> m_PresenceInfoList;
    bool m_PresenceInfoListIsSet;
    int32_t m_MaxResponseTime;
    bool m_MaxResponseTimeIsSet;
    oai::model::TargetArea m_TargetArea;
    bool m_TargetAreaIsSet;
    std::vector<oai::model::ExtSnssai> m_SnssaiFilter;
    bool m_SnssaiFilterIsSet;
    oai::model::UeInAreaFilter m_UeInAreaFilter;
    bool m_UeInAreaFilterIsSet;
    int32_t m_MinInterval;
    bool m_MinIntervalIsSet;
    std::string m_NextReport;
    bool m_NextReportIsSet;
    bool m_IdleStatusInd;
    bool m_IdleStatusIndIsSet;
    oai::model::DispersionArea m_DispersionArea;
    bool m_DispersionAreaIsSet;
    std::string m_NextPeriodicReportTime;
    bool m_NextPeriodicReportTimeIsSet;
    
};

} // namespace oai::model

#endif /* AmfEvent_H_ */
