/**
* N32 Handshake API
* N32-c Handshake Service.   © 2025, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
*
* The version of the OpenAPI document: 1.4.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "ApiSignature.h"
#include "Helpers.h"

#include <sstream>

namespace oai::_3gpp::model {

ApiSignature::ApiSignature()
{
    m_CallbackType = "";
    
}

ApiSignature::~ApiSignature() = default;

void ApiSignature::validate() const
{
    std::stringstream msg;
    // if (!validate(msg))
    // {
    //     throw org::openapitools::server::helpers::ValidationException(msg.str());
    // }
}

bool ApiSignature::validate(std::stringstream& msg) const
{
    return validate(msg, "");
}

bool ApiSignature::validate(std::stringstream& msg, const std::string& pathPrefix) const
{
    bool success = true;
    const std::string _pathPrefix = pathPrefix.empty() ? "ApiSignature" : pathPrefix;

        
    return success;
}

bool ApiSignature::operator==(const ApiSignature& rhs) const
{
    return
    
    
    (getCallbackType() == rhs.getCallbackType())
    
    
    ;
}

bool ApiSignature::operator!=(const ApiSignature& rhs) const
{
    return !(*this == rhs);
}

void to_json(nlohmann::json& j, const ApiSignature& o)
{
    j = nlohmann::json::object();
    j["callbackType"] = o.m_CallbackType;
    
}

void from_json(const nlohmann::json& j, ApiSignature& o)
{
    j.at("callbackType").get_to(o.m_CallbackType);
    
}

std::string ApiSignature::getCallbackType() const
{
    return m_CallbackType;
}
void ApiSignature::setCallbackType(std::string const& value)
{
    m_CallbackType = value;
}


}  // namespace oai::_3gpp::model

