/**
 * 3gpp-as-session-with-qos
 * API for setting us an AS session with required QoS.   © 2023, 3GPP
 * Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All
 * rights reserved.
 *
 * The version of the OpenAPI document: 1.2.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * AsSessionWithQoSSubscription.h
 *
 * Represents an individual AS session with required QoS subscription resource.
 */

#ifndef AsSessionWithQoSSubscription_H_
#define AsSessionWithQoSSubscription_H_

#include "TscQosRequirement.h"
#include "EthFlowDescription.h"
#include <string>
#include "Snssai.h"
#include <vector>
#include "EthFlowInfo.h"
#include "AlternativeServiceRequirementsData.h"
#include "FlowInfo.h"
#include "WebsockNotifConfig.h"
#include "UsageThreshold.h"
#include "UserPlaneEvent.h"
#include "QosMonitoringInformation.h"
#include "SponsorInformation.h"
#include <nlohmann/json.hpp>

namespace oai::_3gpp::model {

/// <summary>
/// Represents an individual AS session with required QoS subscription resource.
/// </summary>
class AsSessionWithQoSSubscription {
 public:
  AsSessionWithQoSSubscription();
  virtual ~AsSessionWithQoSSubscription() = default;

  /// <summary>
  /// Validate the current data in the model. Throws a ValidationException on
  /// failure.
  /// </summary>
  void validate() const;

  /// <summary>
  /// Validate the current data in the model. Returns false on error and writes
  /// an error message into the given stringstream.
  /// </summary>
  bool validate(std::stringstream& msg) const;

  /// <summary>
  /// Helper overload for validate. Used when one model stores another model and
  /// calls it's validate. Not meant to be called outside that case.
  /// </summary>
  bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

  bool operator==(const AsSessionWithQoSSubscription& rhs) const;
  bool operator!=(const AsSessionWithQoSSubscription& rhs) const;

  /////////////////////////////////////////////
  /// AsSessionWithQoSSubscription members

  /// <summary>
  /// string formatted according to IETF RFC 3986 identifying a referenced
  /// resource.
  /// </summary>
  std::string getSelf() const;
  void setSelf(std::string const& value);
  bool selfIsSet() const;
  void unsetSelf();
  /// <summary>
  /// A string used to indicate the features supported by an API that is used as
  /// defined in clause  6.6 in 3GPP TS 29.500. The string shall contain a
  /// bitmask indicating supported features in  hexadecimal representation Each
  /// character in the string shall take a value of \&quot;0\&quot; to
  /// \&quot;9\&quot;,  \&quot;a\&quot; to \&quot;f\&quot; or \&quot;A\&quot; to
  /// \&quot;F\&quot; and shall represent the support of 4 features as described
  /// in  table 5.2.2-3. The most significant character representing the
  /// highest-numbered features shall  appear first in the string, and the
  /// character representing features 1 to 4 shall appear last  in the string.
  /// The list of features and their numbering (starting with 1) are defined
  /// separately for each API. If the string contains a lower number of
  /// characters than there are  defined features for an API, all features that
  /// would be represented by characters that are not  present in the string are
  /// not supported.
  /// </summary>
  std::string getSupportedFeatures() const;
  void setSupportedFeatures(std::string const& value);
  bool supportedFeaturesIsSet() const;
  void unsetSupportedFeatures();
  /// <summary>
  /// String representing a Data Network as defined in clause 9A of 3GPP
  /// TS 23.003;  it shall contain either a DNN Network Identifier, or a full
  /// DNN with both the Network  Identifier and Operator Identifier, as
  /// specified in 3GPP TS 23.003 clause 9.1.1 and 9.1.2. It shall be coded as
  /// string in which the labels are separated by dots  (e.g.
  /// \&quot;Label1.Label2.Label3\&quot;).
  /// </summary>
  std::string getDnn() const;
  void setDnn(std::string const& value);
  bool dnnIsSet() const;
  void unsetDnn();
  /// <summary>
  ///
  /// </summary>
  oai::_3gpp::model::Snssai getSnssai() const;
  void setSnssai(oai::_3gpp::model::Snssai const& value);
  bool snssaiIsSet() const;
  void unsetSnssai();
  /// <summary>
  /// string formatted according to IETF RFC 3986 identifying a referenced
  /// resource.
  /// </summary>
  std::string getNotificationDestination() const;
  void setNotificationDestination(std::string const& value);
  /// <summary>
  /// Identifies the external Application Identifier.
  /// </summary>
  std::string getExterAppId() const;
  void setExterAppId(std::string const& value);
  bool exterAppIdIsSet() const;
  void unsetExterAppId();
  /// <summary>
  /// Describe the data flow which requires QoS.
  /// </summary>
  std::vector<oai::_3gpp::model::FlowInfo> getFlowInfo() const;
  void setFlowInfo(std::vector<oai::_3gpp::model::FlowInfo> const& value);
  bool flowInfoIsSet() const;
  void unsetFlowInfo();
  /// <summary>
  /// Identifies Ethernet packet flows.
  /// </summary>
  std::vector<oai::_3gpp::model::EthFlowDescription> getEthFlowInfo() const;
  void setEthFlowInfo(
      std::vector<oai::_3gpp::model::EthFlowDescription> const& value);
  bool ethFlowInfoIsSet() const;
  void unsetEthFlowInfo();
  /// <summary>
  /// Identifies the Ethernet flows which require QoS. Each Ethernet flow
  /// consists of a flow idenifer and the corresponding UL and/or DL flows.
  /// </summary>
  std::vector<oai::_3gpp::model::EthFlowInfo> getEnEthFlowInfo() const;
  void setEnEthFlowInfo(
      std::vector<oai::_3gpp::model::EthFlowInfo> const& value);
  bool enEthFlowInfoIsSet() const;
  void unsetEnEthFlowInfo();
  /// <summary>
  /// Identifies a pre-defined QoS information
  /// </summary>
  std::string getQosReference() const;
  void setQosReference(std::string const& value);
  bool qosReferenceIsSet() const;
  void unsetQosReference();
  /// <summary>
  /// Identifies an ordered list of pre-defined QoS information. The lower the
  /// index of the array for a given entry, the higher the priority.
  /// </summary>
  std::vector<std::string> getAltQoSReferences() const;
  void setAltQoSReferences(std::vector<std::string> const& value);
  bool altQoSReferencesIsSet() const;
  void unsetAltQoSReferences();
  /// <summary>
  /// Identifies an ordered list of alternative service requirements that
  /// include individual QoS parameter sets. The lower the index of the array
  /// for a given entry, the higher the priority.
  /// </summary>
  std::vector<oai::_3gpp::model::AlternativeServiceRequirementsData>
  getAltQosReqs() const;
  void setAltQosReqs(
      std::vector<oai::_3gpp::model::AlternativeServiceRequirementsData> const&
          value);
  bool altQosReqsIsSet() const;
  void unsetAltQosReqs();
  /// <summary>
  /// Indicates whether the QoS flow parameters signalling to the UE when the
  /// SMF is notified by the NG-RAN of changes in the fulfilled QoS situation is
  /// disabled (true) or not (false). Default value is false. The fulfilled
  /// situation is either the QoS profile or an Alternative QoS Profile.
  /// </summary>
  bool isDisUeNotif() const;
  void setDisUeNotif(bool const value);
  bool disUeNotifIsSet() const;
  void unsetDisUeNotif();
  /// <summary>
  /// string identifying a Ipv4 address formatted in the \&quot;dotted
  /// decimal\&quot; notation as defined in IETF RFC 1166.
  /// </summary>
  std::string getUeIpv4Addr() const;
  void setUeIpv4Addr(std::string const& value);
  bool ueIpv4AddrIsSet() const;
  void unsetUeIpv4Addr();
  /// <summary>
  ///
  /// </summary>
  std::string getIpDomain() const;
  void setIpDomain(std::string const& value);
  bool ipDomainIsSet() const;
  void unsetIpDomain();
  /// <summary>
  /// string identifying a Ipv6 address formatted according to clause 4 in IETF
  /// RFC 5952. The mixed Ipv4 Ipv6 notation according to clause 5 of IETF RFC
  /// 5952 shall not be used.
  /// </summary>
  std::string getUeIpv6Addr() const;
  void setUeIpv6Addr(std::string const& value);
  bool ueIpv6AddrIsSet() const;
  void unsetUeIpv6Addr();
  /// <summary>
  /// String identifying a MAC address formatted in the hexadecimal notation
  /// according to clause 1.1 and clause 2.1 of RFC 7042.
  /// </summary>
  std::string getMacAddr() const;
  void setMacAddr(std::string const& value);
  bool macAddrIsSet() const;
  void unsetMacAddr();
  /// <summary>
  ///
  /// </summary>
  oai::_3gpp::model::UsageThreshold getUsageThreshold() const;
  void setUsageThreshold(oai::_3gpp::model::UsageThreshold const& value);
  bool usageThresholdIsSet() const;
  void unsetUsageThreshold();
  /// <summary>
  ///
  /// </summary>
  oai::_3gpp::model::SponsorInformation getSponsorInfo() const;
  void setSponsorInfo(oai::_3gpp::model::SponsorInformation const& value);
  bool sponsorInfoIsSet() const;
  void unsetSponsorInfo();
  /// <summary>
  ///
  /// </summary>
  oai::_3gpp::model::QosMonitoringInformation getQosMonInfo() const;
  void setQosMonInfo(oai::_3gpp::model::QosMonitoringInformation const& value);
  bool qosMonInfoIsSet() const;
  void unsetQosMonInfo();
  /// <summary>
  /// Indicates whether the direct event notification is requested (true) or not
  /// (false). Default value is false.
  /// </summary>
  bool isDirectNotifInd() const;
  void setDirectNotifInd(bool const value);
  bool directNotifIndIsSet() const;
  void unsetDirectNotifInd();
  /// <summary>
  ///
  /// </summary>
  oai::_3gpp::model::TscQosRequirement getTscQosReq() const;
  void setTscQosReq(oai::_3gpp::model::TscQosRequirement const& value);
  bool tscQosReqIsSet() const;
  void unsetTscQosReq();
  /// <summary>
  /// Set to true by the SCS/AS to request the SCEF to send a test notification
  /// as defined in clause 5.2.5.3. Set to false or omitted otherwise.
  /// </summary>
  bool isRequestTestNotification() const;
  void setRequestTestNotification(bool const value);
  bool requestTestNotificationIsSet() const;
  void unsetRequestTestNotification();
  /// <summary>
  ///
  /// </summary>
  oai::_3gpp::model::WebsockNotifConfig getWebsockNotifConfig() const;
  void setWebsockNotifConfig(
      oai::_3gpp::model::WebsockNotifConfig const& value);
  bool websockNotifConfigIsSet() const;
  void unsetWebsockNotifConfig();
  /// <summary>
  /// Represents the list of user plane event(s) to which the SCS/AS requests to
  /// subscribe to.
  /// </summary>
  std::vector<oai::_3gpp::model::UserPlaneEvent> getEvents() const;
  void setEvents(std::vector<oai::_3gpp::model::UserPlaneEvent> const& value);
  bool eventsIsSet() const;
  void unsetEvents();

  friend void to_json(nlohmann::json& j, const AsSessionWithQoSSubscription& o);
  friend void from_json(
      const nlohmann::json& j, AsSessionWithQoSSubscription& o);

 protected:
  std::string m_Self;
  bool m_SelfIsSet;
  std::string m_SupportedFeatures;
  bool m_SupportedFeaturesIsSet;
  std::string m_Dnn;
  bool m_DnnIsSet;
  oai::_3gpp::model::Snssai m_Snssai;
  bool m_SnssaiIsSet;
  std::string m_NotificationDestination;

  std::string m_ExterAppId;
  bool m_ExterAppIdIsSet;
  std::vector<oai::_3gpp::model::FlowInfo> m_FlowInfo;
  bool m_FlowInfoIsSet;
  std::vector<oai::_3gpp::model::EthFlowDescription> m_EthFlowInfo;
  bool m_EthFlowInfoIsSet;
  std::vector<oai::_3gpp::model::EthFlowInfo> m_EnEthFlowInfo;
  bool m_EnEthFlowInfoIsSet;
  std::string m_QosReference;
  bool m_QosReferenceIsSet;
  std::vector<std::string> m_AltQoSReferences;
  bool m_AltQoSReferencesIsSet;
  std::vector<oai::_3gpp::model::AlternativeServiceRequirementsData>
      m_AltQosReqs;
  bool m_AltQosReqsIsSet;
  bool m_DisUeNotif;
  bool m_DisUeNotifIsSet;
  std::string m_UeIpv4Addr;
  bool m_UeIpv4AddrIsSet;
  std::string m_IpDomain;
  bool m_IpDomainIsSet;
  std::string m_UeIpv6Addr;
  bool m_UeIpv6AddrIsSet;
  std::string m_MacAddr;
  bool m_MacAddrIsSet;
  oai::_3gpp::model::UsageThreshold m_UsageThreshold;
  bool m_UsageThresholdIsSet;
  oai::_3gpp::model::SponsorInformation m_SponsorInfo;
  bool m_SponsorInfoIsSet;
  oai::_3gpp::model::QosMonitoringInformation m_QosMonInfo;
  bool m_QosMonInfoIsSet;
  bool m_DirectNotifInd;
  bool m_DirectNotifIndIsSet;
  oai::_3gpp::model::TscQosRequirement m_TscQosReq;
  bool m_TscQosReqIsSet;
  bool m_RequestTestNotification;
  bool m_RequestTestNotificationIsSet;
  oai::_3gpp::model::WebsockNotifConfig m_WebsockNotifConfig;
  bool m_WebsockNotifConfigIsSet;
  std::vector<oai::_3gpp::model::UserPlaneEvent> m_Events;
  bool m_EventsIsSet;
};

}  // namespace oai::_3gpp::model

#endif /* AsSessionWithQoSSubscription_H_ */
