/**
* Nudm_UEAU
* UDM UE Authentication Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
*
* The version of the OpenAPI document: 1.2.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "AvType.h"
#include "Helpers.h"

#include <sstream>

namespace oai::model
{

AvType::AvType()
{
    
}

void AvType::validate() const
{
    std::stringstream msg;
    if (!validate(msg))
    {
        throw org::openapitools::server::helpers::ValidationException(msg.str());
    }
}

bool AvType::validate(std::stringstream& msg) const
{
    return validate(msg, "");
}

bool AvType::validate(std::stringstream& msg, const std::string& pathPrefix) const
{
    bool success = true;
    const std::string _pathPrefix = pathPrefix.empty() ? "AvType" : pathPrefix;

    
    return success;
}

bool AvType::operator==(const AvType& rhs) const
{
    return
    
    
    ;
}

bool AvType::operator!=(const AvType& rhs) const
{
    return !(*this == rhs);
}

void to_json(nlohmann::json& j, const AvType& o)
{
    j = nlohmann::json::object();
    
}

void from_json(const nlohmann::json& j, AvType& o)
{
    
}



} // namespace oai::model

