/**
* Nudr_DataRepository API OpenAPI file
* Unified Data Repository Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
*
* The version of the OpenAPI document: 2.2.4
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "CagInfo_1.h"
#include "Helpers.h"

#include <sstream>

namespace oai::_3gpp::model
{

CagInfo_1::CagInfo_1()
{
    m_CagOnlyIndicator = false;
    m_CagOnlyIndicatorIsSet = false;
    
}

void CagInfo_1::validate() const
{
    std::stringstream msg;
    if (!validate(msg))
    {
        throw oai::_3gpp::model::helpers::ValidationException(msg.str());
    }
}

bool CagInfo_1::validate(std::stringstream& msg) const
{
    return validate(msg, "");
}

bool CagInfo_1::validate(std::stringstream& msg, const std::string& pathPrefix) const
{
    bool success = true;
    const std::string _pathPrefix = pathPrefix.empty() ? "CagInfo_1" : pathPrefix;

         
    
    /* AllowedCagList */ {
        const std::vector<oai::_3gpp::model::std::string>& value = m_AllowedCagList;
        const std::string currentValuePath = _pathPrefix + ".allowedCagList";
                
        
        { // Recursive validation of array elements
            const std::string oldValuePath = currentValuePath;
            int i = 0;
            for (const std::string& value : value)
            { 
                const std::string currentValuePath = oldValuePath + "[" + std::to_string(i) + "]";
                        
        
 
                i++;
            }
        }

    }
        
    return success;
}

bool CagInfo_1::operator==(const CagInfo_1& rhs) const
{
    return
    
    
    (getAllowedCagList() == rhs.getAllowedCagList())
     &&
    
    
    ((!cagOnlyIndicatorIsSet() && !rhs.cagOnlyIndicatorIsSet()) || (cagOnlyIndicatorIsSet() && rhs.cagOnlyIndicatorIsSet() && isCagOnlyIndicator() == rhs.isCagOnlyIndicator()))
    
    ;
}

bool CagInfo_1::operator!=(const CagInfo_1& rhs) const
{
    return !(*this == rhs);
}

void to_json(nlohmann::json& j, const CagInfo_1& o)
{
    j = nlohmann::json();
    j["allowedCagList"] = o.m_AllowedCagList;
    if(o.cagOnlyIndicatorIsSet())
        j["cagOnlyIndicator"] = o.m_CagOnlyIndicator;
    
}

void from_json(const nlohmann::json& j, CagInfo_1& o)
{
    j.at("allowedCagList").get_to(o.m_AllowedCagList);
    if(j.find("cagOnlyIndicator") != j.end())
    {
        j.at("cagOnlyIndicator").get_to(o.m_CagOnlyIndicator);
        o.m_CagOnlyIndicatorIsSet = true;
    } 
    
}

std::vector<oai::_3gpp::model::std::string> CagInfo_1::getAllowedCagList() const
{
    return m_AllowedCagList;
}
void CagInfo_1::setAllowedCagList(std::vector<oai::_3gpp::model::std::string> const& value)
{
    m_AllowedCagList = value;
}
bool CagInfo_1::isCagOnlyIndicator() const
{
    return m_CagOnlyIndicator;
}
void CagInfo_1::setCagOnlyIndicator(bool const value)
{
    m_CagOnlyIndicator = value;
    m_CagOnlyIndicatorIsSet = true;
}
bool CagInfo_1::cagOnlyIndicatorIsSet() const
{
    return m_CagOnlyIndicatorIsSet;
}
void CagInfo_1::unsetCagOnlyIndicator()
{
    m_CagOnlyIndicatorIsSet = false;
}


} // namespace oai::_3gpp::model

