/**
* Nudr_DataRepository API OpenAPI file
* Unified Data Repository Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
*
* The version of the OpenAPI document: 2.2.4
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * CommunicationCharacteristics.h
 *
 * 
 */

#ifndef CommunicationCharacteristics_H_
#define CommunicationCharacteristics_H_


#include "PpMaximumLatency.h"
#include "PpSubsRegTimer.h"
#include "PpActiveTime.h"
#include "PpDlPacketCountExt.h"
#include "PpMaximumResponseTime.h"
#include <nlohmann/json.hpp>

namespace oai::model
{

/// <summary>
/// 
/// </summary>
class  CommunicationCharacteristics
{
public:
    CommunicationCharacteristics();
    virtual ~CommunicationCharacteristics() = default;


    /// <summary>
    /// Validate the current data in the model. Throws a ValidationException on failure.
    /// </summary>
    void validate() const;

    /// <summary>
    /// Validate the current data in the model. Returns false on error and writes an error
    /// message into the given stringstream.
    /// </summary>
    bool validate(std::stringstream& msg) const;

    /// <summary>
    /// Helper overload for validate. Used when one model stores another model and calls it's validate.
    /// Not meant to be called outside that case.
    /// </summary>
    bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

    bool operator==(const CommunicationCharacteristics& rhs) const;
    bool operator!=(const CommunicationCharacteristics& rhs) const;

    /////////////////////////////////////////////
    /// CommunicationCharacteristics members

    /// <summary>
    /// 
    /// </summary>
    oai::model::PpSubsRegTimer getPpSubsRegTimer() const;
    void setPpSubsRegTimer(oai::model::PpSubsRegTimer const& value);
    bool ppSubsRegTimerIsSet() const;
    void unsetPpSubsRegTimer();
    /// <summary>
    /// 
    /// </summary>
    oai::model::PpActiveTime getPpActiveTime() const;
    void setPpActiveTime(oai::model::PpActiveTime const& value);
    bool ppActiveTimeIsSet() const;
    void unsetPpActiveTime();
    /// <summary>
    /// 
    /// </summary>
    int32_t getPpDlPacketCount() const;
    void setPpDlPacketCount(int32_t const value);
    bool ppDlPacketCountIsSet() const;
    void unsetPpDlPacketCount();
    /// <summary>
    /// 
    /// </summary>
    oai::model::PpDlPacketCountExt getPpDlPacketCountExt() const;
    void setPpDlPacketCountExt(oai::model::PpDlPacketCountExt const& value);
    bool ppDlPacketCountExtIsSet() const;
    void unsetPpDlPacketCountExt();
    /// <summary>
    /// 
    /// </summary>
    oai::model::PpMaximumResponseTime getPpMaximumResponseTime() const;
    void setPpMaximumResponseTime(oai::model::PpMaximumResponseTime const& value);
    bool ppMaximumResponseTimeIsSet() const;
    void unsetPpMaximumResponseTime();
    /// <summary>
    /// 
    /// </summary>
    oai::model::PpMaximumLatency getPpMaximumLatency() const;
    void setPpMaximumLatency(oai::model::PpMaximumLatency const& value);
    bool ppMaximumLatencyIsSet() const;
    void unsetPpMaximumLatency();

    friend  void to_json(nlohmann::json& j, const CommunicationCharacteristics& o);
    friend  void from_json(const nlohmann::json& j, CommunicationCharacteristics& o);
protected:
    oai::model::PpSubsRegTimer m_PpSubsRegTimer;
    bool m_PpSubsRegTimerIsSet;
    oai::model::PpActiveTime m_PpActiveTime;
    bool m_PpActiveTimeIsSet;
    int32_t m_PpDlPacketCount;
    bool m_PpDlPacketCountIsSet;
    oai::model::PpDlPacketCountExt m_PpDlPacketCountExt;
    bool m_PpDlPacketCountExtIsSet;
    oai::model::PpMaximumResponseTime m_PpMaximumResponseTime;
    bool m_PpMaximumResponseTimeIsSet;
    oai::model::PpMaximumLatency m_PpMaximumLatency;
    bool m_PpMaximumLatencyIsSet;
    
};

} // namespace oai::model

#endif /* CommunicationCharacteristics_H_ */
