/**
* Npcf_SMPolicyControl API
* Session Management Policy Control Service   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
*
* The version of the OpenAPI document: 1.2.4
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "CreditManagementStatus.h"
#include "Helpers.h"

#include <sstream>

namespace oai::model
{

CreditManagementStatus::CreditManagementStatus()
{
    
}

void CreditManagementStatus::validate() const
{
    std::stringstream msg;
    if (!validate(msg))
    {
        throw org::openapitools::server::helpers::ValidationException(msg.str());
    }
}

bool CreditManagementStatus::validate(std::stringstream& msg) const
{
    return validate(msg, "");
}

bool CreditManagementStatus::validate(std::stringstream& msg, const std::string& pathPrefix) const
{
    bool success = true;
    const std::string _pathPrefix = pathPrefix.empty() ? "CreditManagementStatus" : pathPrefix;

    
    return success;
}

bool CreditManagementStatus::operator==(const CreditManagementStatus& rhs) const
{
    return
    
    
    ;
}

bool CreditManagementStatus::operator!=(const CreditManagementStatus& rhs) const
{
    return !(*this == rhs);
}

void to_json(nlohmann::json& j, const CreditManagementStatus& o)
{
    j = nlohmann::json::object();
    
}

void from_json(const nlohmann::json& j, CreditManagementStatus& o)
{
    
}



} // namespace oai::model

