/**
* JOSE Protected Message Forwarding API
* N32-f Message Forwarding Service.   © 2025, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
*
* The version of the OpenAPI document: 1.4.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * DataToIntegrityProtectBlock.h
 *
 * Data to be integrity protected
 */

#ifndef DataToIntegrityProtectBlock_H_
#define DataToIntegrityProtectBlock_H_


#include "MetaData.h"
#include "HttpHeader.h"
#include "HttpPayload.h"
#include <string>
#include "RequestLine.h"
#include <vector>
#include <nlohmann/json.hpp>

namespace oai::_3gpp::model {

/// <summary>
/// Data to be integrity protected
/// </summary>
class  DataToIntegrityProtectBlock
{
public:
    DataToIntegrityProtectBlock();
    virtual ~DataToIntegrityProtectBlock();


    /// <summary>
    /// Validate the current data in the model. Throws a ValidationException on failure.
    /// </summary>
    void validate() const;

    /// <summary>
    /// Validate the current data in the model. Returns false on error and writes an error
    /// message into the given stringstream.
    /// </summary>
    bool validate(std::stringstream& msg) const;

    /// <summary>
    /// Helper overload for validate. Used when one model stores another model and calls it's validate.
    /// Not meant to be called outside that case.
    /// </summary>
    bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

    bool operator==(const DataToIntegrityProtectBlock& rhs) const;
    bool operator!=(const DataToIntegrityProtectBlock& rhs) const;

    /////////////////////////////////////////////
    /// DataToIntegrityProtectBlock members

    /// <summary>
    /// 
    /// </summary>
    oai::_3gpp::model::MetaData getMetaData() const;
    void setMetaData(oai::_3gpp::model::MetaData const& value);
    bool metaDataIsSet() const;
    void unsetMetaData();
    /// <summary>
    /// 
    /// </summary>
    oai::_3gpp::model::RequestLine getRequestLine() const;
    void setRequestLine(oai::_3gpp::model::RequestLine const& value);
    bool requestLineIsSet() const;
    void unsetRequestLine();
    /// <summary>
    /// 
    /// </summary>
    std::string getStatusLine() const;
    void setStatusLine(std::string const& value);
    bool statusLineIsSet() const;
    void unsetStatusLine();
    /// <summary>
    /// 
    /// </summary>
    std::vector<oai::_3gpp::model::HttpHeader> getHeaders() const;
    void setHeaders(std::vector<oai::_3gpp::model::HttpHeader> const& value);
    bool headersIsSet() const;
    void unsetHeaders();
    /// <summary>
    /// 
    /// </summary>
    std::vector<oai::_3gpp::model::HttpPayload> getPayload() const;
    void setPayload(std::vector<oai::_3gpp::model::HttpPayload> const& value);
    bool payloadIsSet() const;
    void unsetPayload();

    friend  void to_json(nlohmann::json& j, const DataToIntegrityProtectBlock& o);
    friend  void from_json(const nlohmann::json& j, DataToIntegrityProtectBlock& o);
protected:
    oai::_3gpp::model::MetaData m_MetaData;
    bool m_MetaDataIsSet;
    oai::_3gpp::model::RequestLine m_RequestLine;
    bool m_RequestLineIsSet;
    std::string m_StatusLine;
    bool m_StatusLineIsSet;
    std::vector<oai::_3gpp::model::HttpHeader> m_Headers;
    bool m_HeadersIsSet;
    std::vector<oai::_3gpp::model::HttpPayload> m_Payload;
    bool m_PayloadIsSet;
    
};

}  // namespace oai::_3gpp::model

#endif /* DataToIntegrityProtectBlock_H_ */
