/**
* Unified Data Repository Service API file for Application Data
* The API version is defined in 3GPP TS 29.504   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
*
* The version of the OpenAPI document: -
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * DomainNameProtocol.h
 *
 * Possible values are - DNS_QNAME: Identifies the DNS protocol and the question name in DNS query. - TLS_SNI: Identifies the Server Name Indication in TLS ClientHello message. - TLS_SAN: Identifies the Subject Alternative Name in TLS ServerCertificate message. - TSL_SCN: Identifies the Subject Common Name in TLS ServerCertificate message. 
 */

#ifndef DomainNameProtocol_H_
#define DomainNameProtocol_H_


#include <nlohmann/json.hpp>

namespace oai::model
{

/// <summary>
/// Possible values are - DNS_QNAME: Identifies the DNS protocol and the question name in DNS query. - TLS_SNI: Identifies the Server Name Indication in TLS ClientHello message. - TLS_SAN: Identifies the Subject Alternative Name in TLS ServerCertificate message. - TSL_SCN: Identifies the Subject Common Name in TLS ServerCertificate message. 
/// </summary>
class  DomainNameProtocol
{
public:
    DomainNameProtocol();
    virtual ~DomainNameProtocol() = default;


    /// <summary>
    /// Validate the current data in the model. Throws a ValidationException on failure.
    /// </summary>
    void validate() const;

    /// <summary>
    /// Validate the current data in the model. Returns false on error and writes an error
    /// message into the given stringstream.
    /// </summary>
    bool validate(std::stringstream& msg) const;

    /// <summary>
    /// Helper overload for validate. Used when one model stores another model and calls it's validate.
    /// Not meant to be called outside that case.
    /// </summary>
    bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

    bool operator==(const DomainNameProtocol& rhs) const;
    bool operator!=(const DomainNameProtocol& rhs) const;

    /////////////////////////////////////////////
    /// DomainNameProtocol members


    friend  void to_json(nlohmann::json& j, const DomainNameProtocol& o);
    friend  void from_json(const nlohmann::json& j, DomainNameProtocol& o);
protected:
    
};

} // namespace oai::model

#endif /* DomainNameProtocol_H_ */
