/**
* Nudr_DataRepository API OpenAPI file
* Unified Data Repository Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
*
* The version of the OpenAPI document: 2.2.4
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * EcsAddrConfigInfo_1.h
 *
 * 
 */

#ifndef EcsAddrConfigInfo_1_H_
#define EcsAddrConfigInfo_1_H_


#include "EcsServerAddr.h"
#include "SpatialValidityCond_1.h"
#include <nlohmann/json.hpp>

namespace oai::model
{

/// <summary>
/// 
/// </summary>
class  EcsAddrConfigInfo_1
{
public:
    EcsAddrConfigInfo_1();
    virtual ~EcsAddrConfigInfo_1() = default;


    /// <summary>
    /// Validate the current data in the model. Throws a ValidationException on failure.
    /// </summary>
    void validate() const;

    /// <summary>
    /// Validate the current data in the model. Returns false on error and writes an error
    /// message into the given stringstream.
    /// </summary>
    bool validate(std::stringstream& msg) const;

    /// <summary>
    /// Helper overload for validate. Used when one model stores another model and calls it's validate.
    /// Not meant to be called outside that case.
    /// </summary>
    bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

    bool operator==(const EcsAddrConfigInfo_1& rhs) const;
    bool operator!=(const EcsAddrConfigInfo_1& rhs) const;

    /////////////////////////////////////////////
    /// EcsAddrConfigInfo_1 members

    /// <summary>
    /// 
    /// </summary>
    oai::model::EcsServerAddr getEcsServerAddr() const;
    void setEcsServerAddr(oai::model::EcsServerAddr const& value);
    bool ecsServerAddrIsSet() const;
    void unsetEcsServerAddr();
    /// <summary>
    /// 
    /// </summary>
    oai::model::SpatialValidityCond_1 getSpatialValidityCond() const;
    void setSpatialValidityCond(oai::model::SpatialValidityCond_1 const& value);
    bool spatialValidityCondIsSet() const;
    void unsetSpatialValidityCond();

    friend  void to_json(nlohmann::json& j, const EcsAddrConfigInfo_1& o);
    friend  void from_json(const nlohmann::json& j, EcsAddrConfigInfo_1& o);
protected:
    oai::model::EcsServerAddr m_EcsServerAddr;
    bool m_EcsServerAddrIsSet;
    oai::model::SpatialValidityCond_1 m_SpatialValidityCond;
    bool m_SpatialValidityCondIsSet;
    
};

} // namespace oai::model

#endif /* EcsAddrConfigInfo_1_H_ */
