/**
* Unified Data Repository Service API file for Application Data
* The API version is defined in 3GPP TS 29.504   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
*
* The version of the OpenAPI document: -
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * Event.h
 *
 * Possible values are: - SUCCESS_UE_POL_DEL_SP: Successful UE Policy Delivery related to    the invocation of AF provisioned Service Parameters. - UNSUCCESS_UE_POL_DEL_SP: Unsuccessful UE Policy Delivery related to the invocation of AF    provisioned Service Parameters. 
 */

#ifndef Event_H_
#define Event_H_


#include <nlohmann/json.hpp>

namespace oai::model
{

/// <summary>
/// Possible values are: - SUCCESS_UE_POL_DEL_SP: Successful UE Policy Delivery related to    the invocation of AF provisioned Service Parameters. - UNSUCCESS_UE_POL_DEL_SP: Unsuccessful UE Policy Delivery related to the invocation of AF    provisioned Service Parameters. 
/// </summary>
class  Event
{
public:
    Event();
    virtual ~Event() = default;


    /// <summary>
    /// Validate the current data in the model. Throws a ValidationException on failure.
    /// </summary>
    void validate() const;

    /// <summary>
    /// Validate the current data in the model. Returns false on error and writes an error
    /// message into the given stringstream.
    /// </summary>
    bool validate(std::stringstream& msg) const;

    /// <summary>
    /// Helper overload for validate. Used when one model stores another model and calls it's validate.
    /// Not meant to be called outside that case.
    /// </summary>
    bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

    bool operator==(const Event& rhs) const;
    bool operator!=(const Event& rhs) const;

    /////////////////////////////////////////////
    /// Event members


    friend  void to_json(nlohmann::json& j, const Event& o);
    friend  void from_json(const nlohmann::json& j, Event& o);
protected:
    
};

} // namespace oai::model

#endif /* Event_H_ */
