/**
* Npcf_SMPolicyControl API
* Session Management Policy Control Service   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
*
* The version of the OpenAPI document: 1.2.4
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * FailureCause.h
 *
 * Indicates the cause of the failure in a Partial Success Report.
 */

#ifndef FailureCause_H_
#define FailureCause_H_


#include <nlohmann/json.hpp>

namespace oai::model
{

/// <summary>
/// Indicates the cause of the failure in a Partial Success Report.
/// </summary>
class  FailureCause
{
public:
    FailureCause();
    virtual ~FailureCause() = default;


    /// <summary>
    /// Validate the current data in the model. Throws a ValidationException on failure.
    /// </summary>
    void validate() const;

    /// <summary>
    /// Validate the current data in the model. Returns false on error and writes an error
    /// message into the given stringstream.
    /// </summary>
    bool validate(std::stringstream& msg) const;

    /// <summary>
    /// Helper overload for validate. Used when one model stores another model and calls it's validate.
    /// Not meant to be called outside that case.
    /// </summary>
    bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

    bool operator==(const FailureCause& rhs) const;
    bool operator!=(const FailureCause& rhs) const;

    /////////////////////////////////////////////
    /// FailureCause members


    friend  void to_json(nlohmann::json& j, const FailureCause& o);
    friend  void from_json(const nlohmann::json& j, FailureCause& o);
protected:
    
};

} // namespace oai::model

#endif /* FailureCause_H_ */
