/**
* Nudm_UEAU
* UDM UE Authentication Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
*
* The version of the OpenAPI document: 1.2.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "HssAvType.h"
#include "Helpers.h"

#include <sstream>

namespace oai::model
{

HssAvType::HssAvType()
{
    
}

void HssAvType::validate() const
{
    std::stringstream msg;
    if (!validate(msg))
    {
        throw org::openapitools::server::helpers::ValidationException(msg.str());
    }
}

bool HssAvType::validate(std::stringstream& msg) const
{
    return validate(msg, "");
}

bool HssAvType::validate(std::stringstream& msg, const std::string& pathPrefix) const
{
    bool success = true;
    const std::string _pathPrefix = pathPrefix.empty() ? "HssAvType" : pathPrefix;

    
    return success;
}

bool HssAvType::operator==(const HssAvType& rhs) const
{
    return
    
    
    ;
}

bool HssAvType::operator!=(const HssAvType& rhs) const
{
    return !(*this == rhs);
}

void to_json(nlohmann::json& j, const HssAvType& o)
{
    j = nlohmann::json::object();
    
}

void from_json(const nlohmann::json& j, HssAvType& o)
{
    
}



} // namespace oai::model

