/**
* N32 Handshake API
* N32-c Handshake Service.   © 2025, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
*
* The version of the OpenAPI document: 1.4.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "IeInfo.h"
#include "Helpers.h"

#include <sstream>

namespace oai::_3gpp::model {

IeInfo::IeInfo()
{
    m_ReqIe = "";
    m_ReqIeIsSet = false;
    m_RspIe = "";
    m_RspIeIsSet = false;
    m_IsModifiable = false;
    m_IsModifiableIsSet = false;
    m_IsModifiableByIpxIsSet = false;
    m_AncestorIe = "";
    m_AncestorIeIsSet = false;
    
}

IeInfo::~IeInfo() = default;

void IeInfo::validate() const
{
    std::stringstream msg;
    // if (!validate(msg))
    // {
    //     throw org::openapitools::server::helpers::ValidationException(msg.str());
    // }
}

bool IeInfo::validate(std::stringstream& msg) const
{
    return validate(msg, "");
}

bool IeInfo::validate(std::stringstream& msg, const std::string& pathPrefix) const
{
    bool success = true;
    const std::string _pathPrefix = pathPrefix.empty() ? "IeInfo" : pathPrefix;

        
    if (!m_IeLoc.validate(msg, _pathPrefix + ".ieLoc")) {
        msg << _pathPrefix << ": IeLoc is invalid;";
        success = false;
    }    
    if (!m_IeType.validate(msg, _pathPrefix + ".ieType")) {
        msg << _pathPrefix << ": IeType is invalid;";
        success = false;
    }                 
    if (isModifiableByIpxIsSet())
    {
        const std::map<std::string, bool>& value = m_IsModifiableByIpx;
        const std::string currentValuePath = _pathPrefix + ".isModifiableByIpx";
                
        

    }
        
    return success;
}

bool IeInfo::operator==(const IeInfo& rhs) const
{
    return
    
    
    (getIeLoc() == rhs.getIeLoc())
     &&
    
    (getIeType() == rhs.getIeType())
     &&
    
    
    ((!reqIeIsSet() && !rhs.reqIeIsSet()) || (reqIeIsSet() && rhs.reqIeIsSet() && getReqIe() == rhs.getReqIe())) &&
    
    
    ((!rspIeIsSet() && !rhs.rspIeIsSet()) || (rspIeIsSet() && rhs.rspIeIsSet() && getRspIe() == rhs.getRspIe())) &&
    
    
    ((!isModifiableIsSet() && !rhs.isModifiableIsSet()) || (isModifiableIsSet() && rhs.isModifiableIsSet() && isIsModifiable() == rhs.isIsModifiable())) &&
    
    
    ((!isModifiableByIpxIsSet() && !rhs.isModifiableByIpxIsSet()) || (isModifiableByIpxIsSet() && rhs.isModifiableByIpxIsSet() && getIsModifiableByIpx() == rhs.getIsModifiableByIpx())) &&
    
    
    ((!ancestorIeIsSet() && !rhs.ancestorIeIsSet()) || (ancestorIeIsSet() && rhs.ancestorIeIsSet() && getAncestorIe() == rhs.getAncestorIe()))
    
    ;
}

bool IeInfo::operator!=(const IeInfo& rhs) const
{
    return !(*this == rhs);
}

void to_json(nlohmann::json& j, const IeInfo& o)
{
    j = nlohmann::json::object();
    j["ieLoc"] = o.m_IeLoc;
    j["ieType"] = o.m_IeType;
    if(o.reqIeIsSet())
        j["reqIe"] = o.m_ReqIe;
    if(o.rspIeIsSet())
        j["rspIe"] = o.m_RspIe;
    if(o.isModifiableIsSet())
        j["isModifiable"] = o.m_IsModifiable;
    if(o.isModifiableByIpxIsSet() || !o.m_IsModifiableByIpx.empty())
        j["isModifiableByIpx"] = o.m_IsModifiableByIpx;
    if(o.ancestorIeIsSet())
        j["ancestorIe"] = o.m_AncestorIe;
    
}

void from_json(const nlohmann::json& j, IeInfo& o)
{
    j.at("ieLoc").get_to(o.m_IeLoc);
    j.at("ieType").get_to(o.m_IeType);
    if(j.find("reqIe") != j.end())
    {
        j.at("reqIe").get_to(o.m_ReqIe);
        o.m_ReqIeIsSet = true;
    } 
    if(j.find("rspIe") != j.end())
    {
        j.at("rspIe").get_to(o.m_RspIe);
        o.m_RspIeIsSet = true;
    } 
    if(j.find("isModifiable") != j.end())
    {
        j.at("isModifiable").get_to(o.m_IsModifiable);
        o.m_IsModifiableIsSet = true;
    } 
    if(j.find("isModifiableByIpx") != j.end())
    {
        j.at("isModifiableByIpx").get_to(o.m_IsModifiableByIpx);
        o.m_IsModifiableByIpxIsSet = true;
    } 
    if(j.find("ancestorIe") != j.end())
    {
        j.at("ancestorIe").get_to(o.m_AncestorIe);
        o.m_AncestorIeIsSet = true;
    } 
    
}

oai::_3gpp::model::IeLocation IeInfo::getIeLoc() const
{
    return m_IeLoc;
}
void IeInfo::setIeLoc(oai::_3gpp::model::IeLocation const& value)
{
    m_IeLoc = value;
}
oai::_3gpp::model::IeType IeInfo::getIeType() const
{
    return m_IeType;
}
void IeInfo::setIeType(oai::_3gpp::model::IeType const& value)
{
    m_IeType = value;
}
std::string IeInfo::getReqIe() const
{
    return m_ReqIe;
}
void IeInfo::setReqIe(std::string const& value)
{
    m_ReqIe = value;
    m_ReqIeIsSet = true;
}
bool IeInfo::reqIeIsSet() const
{
    return m_ReqIeIsSet;
}
void IeInfo::unsetReqIe()
{
    m_ReqIeIsSet = false;
}
std::string IeInfo::getRspIe() const
{
    return m_RspIe;
}
void IeInfo::setRspIe(std::string const& value)
{
    m_RspIe = value;
    m_RspIeIsSet = true;
}
bool IeInfo::rspIeIsSet() const
{
    return m_RspIeIsSet;
}
void IeInfo::unsetRspIe()
{
    m_RspIeIsSet = false;
}
bool IeInfo::isIsModifiable() const
{
    return m_IsModifiable;
}
void IeInfo::setIsModifiable(bool const value)
{
    m_IsModifiable = value;
    m_IsModifiableIsSet = true;
}
bool IeInfo::isModifiableIsSet() const
{
    return m_IsModifiableIsSet;
}
void IeInfo::unsetIsModifiable()
{
    m_IsModifiableIsSet = false;
}
std::map<std::string, bool> IeInfo::getIsModifiableByIpx() const
{
    return m_IsModifiableByIpx;
}
void IeInfo::setIsModifiableByIpx(std::map<std::string, bool> const value)
{
    m_IsModifiableByIpx = value;
    m_IsModifiableByIpxIsSet = true;
}
bool IeInfo::isModifiableByIpxIsSet() const
{
    return m_IsModifiableByIpxIsSet;
}
void IeInfo::unsetIsModifiableByIpx()
{
    m_IsModifiableByIpxIsSet = false;
}
std::string IeInfo::getAncestorIe() const
{
    return m_AncestorIe;
}
void IeInfo::setAncestorIe(std::string const& value)
{
    m_AncestorIe = value;
    m_AncestorIeIsSet = true;
}
bool IeInfo::ancestorIeIsSet() const
{
    return m_AncestorIeIsSet;
}
void IeInfo::unsetAncestorIe()
{
    m_AncestorIeIsSet = false;
}


}  // namespace oai::_3gpp::model

