/**
* Nudm_SSAU
* Nudm Service Specific Authorization Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
*
* The version of the OpenAPI document: 1.0.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "InvalidCause.h"
#include "Helpers.h"

#include <sstream>

namespace oai::model
{

InvalidCause::InvalidCause()
{
    
}

void InvalidCause::validate() const
{
    std::stringstream msg;
    if (!validate(msg))
    {
        throw org::openapitools::server::helpers::ValidationException(msg.str());
    }
}

bool InvalidCause::validate(std::stringstream& msg) const
{
    return validate(msg, "");
}

bool InvalidCause::validate(std::stringstream& msg, const std::string& pathPrefix) const
{
    bool success = true;
    const std::string _pathPrefix = pathPrefix.empty() ? "InvalidCause" : pathPrefix;

    
    return success;
}

bool InvalidCause::operator==(const InvalidCause& rhs) const
{
    return
    
    
    ;
}

bool InvalidCause::operator!=(const InvalidCause& rhs) const
{
    return !(*this == rhs);
}

void to_json(nlohmann::json& j, const InvalidCause& o)
{
    j = nlohmann::json::object();
    
}

void from_json(const nlohmann::json& j, InvalidCause& o)
{
    
}



} // namespace oai::model

