/**
* Common Data Types
* Common Data Types for Service Based Interfaces.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.   
*
* The version of the OpenAPI document: 1.4.4
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * JobType.h
 *
 * The enumeration JobType defines Job Type in the trace. See 3GPP TS 32.422 for further  description of the values. It shall comply with the provisions defined in table 5.6.3.3-1. 
 */

#ifndef JobType_H_
#define JobType_H_


#include <nlohmann/json.hpp>

namespace oai::model
{

/// <summary>
/// The enumeration JobType defines Job Type in the trace. See 3GPP TS 32.422 for further  description of the values. It shall comply with the provisions defined in table 5.6.3.3-1. 
/// </summary>
class  JobType
{
public:
    JobType();
    virtual ~JobType() = default;


    /// <summary>
    /// Validate the current data in the model. Throws a ValidationException on failure.
    /// </summary>
    void validate() const;

    /// <summary>
    /// Validate the current data in the model. Returns false on error and writes an error
    /// message into the given stringstream.
    /// </summary>
    bool validate(std::stringstream& msg) const;

    /// <summary>
    /// Helper overload for validate. Used when one model stores another model and calls it's validate.
    /// Not meant to be called outside that case.
    /// </summary>
    bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

    bool operator==(const JobType& rhs) const;
    bool operator!=(const JobType& rhs) const;

    /////////////////////////////////////////////
    /// JobType members


    friend  void to_json(nlohmann::json& j, const JobType& o);
    friend  void from_json(const nlohmann::json& j, JobType& o);
protected:
    
};

} // namespace oai::model

#endif /* JobType_H_ */
