/**
* Nudr_DataRepository API OpenAPI file
* Unified Data Repository Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
*
* The version of the OpenAPI document: 2.2.4
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * LcsClientExternal.h
 *
 * 
 */

#ifndef LcsClientExternal_H_
#define LcsClientExternal_H_


#include "GeographicArea.h"
#include "ValidTimePeriod.h"
#include "PrivacyCheckRelatedAction.h"
#include <vector>
#include <nlohmann/json.hpp>

namespace oai::model
{

/// <summary>
/// 
/// </summary>
class  LcsClientExternal
{
public:
    LcsClientExternal();
    virtual ~LcsClientExternal() = default;


    /// <summary>
    /// Validate the current data in the model. Throws a ValidationException on failure.
    /// </summary>
    void validate() const;

    /// <summary>
    /// Validate the current data in the model. Returns false on error and writes an error
    /// message into the given stringstream.
    /// </summary>
    bool validate(std::stringstream& msg) const;

    /// <summary>
    /// Helper overload for validate. Used when one model stores another model and calls it's validate.
    /// Not meant to be called outside that case.
    /// </summary>
    bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

    bool operator==(const LcsClientExternal& rhs) const;
    bool operator!=(const LcsClientExternal& rhs) const;

    /////////////////////////////////////////////
    /// LcsClientExternal members

    /// <summary>
    /// 
    /// </summary>
    std::vector<oai::model::GeographicArea> getAllowedGeographicArea() const;
    void setAllowedGeographicArea(std::vector<oai::model::GeographicArea> const& value);
    bool allowedGeographicAreaIsSet() const;
    void unsetAllowedGeographicArea();
    /// <summary>
    /// 
    /// </summary>
    oai::model::PrivacyCheckRelatedAction getPrivacyCheckRelatedAction() const;
    void setPrivacyCheckRelatedAction(oai::model::PrivacyCheckRelatedAction const& value);
    bool privacyCheckRelatedActionIsSet() const;
    void unsetPrivacyCheckRelatedAction();
    /// <summary>
    /// 
    /// </summary>
    oai::model::ValidTimePeriod getValidTimePeriod() const;
    void setValidTimePeriod(oai::model::ValidTimePeriod const& value);
    bool validTimePeriodIsSet() const;
    void unsetValidTimePeriod();

    friend  void to_json(nlohmann::json& j, const LcsClientExternal& o);
    friend  void from_json(const nlohmann::json& j, LcsClientExternal& o);
protected:
    std::vector<oai::model::GeographicArea> m_AllowedGeographicArea;
    bool m_AllowedGeographicAreaIsSet;
    oai::model::PrivacyCheckRelatedAction m_PrivacyCheckRelatedAction;
    bool m_PrivacyCheckRelatedActionIsSet;
    oai::model::ValidTimePeriod m_ValidTimePeriod;
    bool m_ValidTimePeriodIsSet;
    
};

} // namespace oai::model

#endif /* LcsClientExternal_H_ */
