/**
* Namf_MBSCommunication
* AMF Communication Service for MBS.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
*
* The version of the OpenAPI document: 1.0.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * MbsNgapIeType.h
 *
 * NGAP Information Element Type
 */

#ifndef MbsNgapIeType_H_
#define MbsNgapIeType_H_


#include <nlohmann/json.hpp>

namespace oai::model
{

/// <summary>
/// NGAP Information Element Type
/// </summary>
class  MbsNgapIeType
{
public:
    MbsNgapIeType();
    virtual ~MbsNgapIeType() = default;


    /// <summary>
    /// Validate the current data in the model. Throws a ValidationException on failure.
    /// </summary>
    void validate() const;

    /// <summary>
    /// Validate the current data in the model. Returns false on error and writes an error
    /// message into the given stringstream.
    /// </summary>
    bool validate(std::stringstream& msg) const;

    /// <summary>
    /// Helper overload for validate. Used when one model stores another model and calls it's validate.
    /// Not meant to be called outside that case.
    /// </summary>
    bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

    bool operator==(const MbsNgapIeType& rhs) const;
    bool operator!=(const MbsNgapIeType& rhs) const;

    /////////////////////////////////////////////
    /// MbsNgapIeType members


    friend  void to_json(nlohmann::json& j, const MbsNgapIeType& o);
    friend  void from_json(const nlohmann::json& j, MbsNgapIeType& o);
protected:
    
};

} // namespace oai::model

#endif /* MbsNgapIeType_H_ */
