/**
* Nudr_DataRepository API OpenAPI file
* Unified Data Repository Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
*
* The version of the OpenAPI document: 2.2.4
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "MbsSubscriptionData_1.h"
#include "Helpers.h"

#include <sstream>

namespace oai::_3gpp::model
{

MbsSubscriptionData_1::MbsSubscriptionData_1()
{
    m_MbsAllowed = false;
    m_MbsAllowedIsSet = false;
    m_MbsSessionIdListIsSet = false;
    
}

void MbsSubscriptionData_1::validate() const
{
    std::stringstream msg;
    if (!validate(msg))
    {
        throw oai::_3gpp::model::helpers::ValidationException(msg.str());
    }
}

bool MbsSubscriptionData_1::validate(std::stringstream& msg) const
{
    return validate(msg, "");
}

bool MbsSubscriptionData_1::validate(std::stringstream& msg, const std::string& pathPrefix) const
{
    bool success = true;
    const std::string _pathPrefix = pathPrefix.empty() ? "MbsSubscriptionData_1" : pathPrefix;

             
    if (mbsSessionIdListIsSet())
    {
        const std::vector<oai::_3gpp::model::MbsSessionId_1>& value = m_MbsSessionIdList;
        const std::string currentValuePath = _pathPrefix + ".mbsSessionIdList";
                
        
        if (value.size() < 1)
        {
            success = false;
            msg << currentValuePath << ": must have at least 1 elements;";
        }
        { // Recursive validation of array elements
            const std::string oldValuePath = currentValuePath;
            int i = 0;
            for (const oai::_3gpp::model::MbsSessionId_1& value : value)
            { 
                const std::string currentValuePath = oldValuePath + "[" + std::to_string(i) + "]";
                        
        success = value.validate(msg, currentValuePath + ".mbsSessionIdList") && success;
 
                i++;
            }
        }

    }
    
    return success;
}

bool MbsSubscriptionData_1::operator==(const MbsSubscriptionData_1& rhs) const
{
    return
    
    
    
    ((!mbsAllowedIsSet() && !rhs.mbsAllowedIsSet()) || (mbsAllowedIsSet() && rhs.mbsAllowedIsSet() && isMbsAllowed() == rhs.isMbsAllowed())) &&
    
    
    ((!mbsSessionIdListIsSet() && !rhs.mbsSessionIdListIsSet()) || (mbsSessionIdListIsSet() && rhs.mbsSessionIdListIsSet() && getMbsSessionIdList() == rhs.getMbsSessionIdList()))
    
    ;
}

bool MbsSubscriptionData_1::operator!=(const MbsSubscriptionData_1& rhs) const
{
    return !(*this == rhs);
}

void to_json(nlohmann::json& j, const MbsSubscriptionData_1& o)
{
    j = nlohmann::json();
    if(o.mbsAllowedIsSet())
        j["mbsAllowed"] = o.m_MbsAllowed;
    if(o.mbsSessionIdListIsSet() || !o.m_MbsSessionIdList.empty())
        j["mbsSessionIdList"] = o.m_MbsSessionIdList;
    
}

void from_json(const nlohmann::json& j, MbsSubscriptionData_1& o)
{
    if(j.find("mbsAllowed") != j.end())
    {
        j.at("mbsAllowed").get_to(o.m_MbsAllowed);
        o.m_MbsAllowedIsSet = true;
    } 
    if(j.find("mbsSessionIdList") != j.end())
    {
        j.at("mbsSessionIdList").get_to(o.m_MbsSessionIdList);
        o.m_MbsSessionIdListIsSet = true;
    } 
    
}

bool MbsSubscriptionData_1::isMbsAllowed() const
{
    return m_MbsAllowed;
}
void MbsSubscriptionData_1::setMbsAllowed(bool const value)
{
    m_MbsAllowed = value;
    m_MbsAllowedIsSet = true;
}
bool MbsSubscriptionData_1::mbsAllowedIsSet() const
{
    return m_MbsAllowedIsSet;
}
void MbsSubscriptionData_1::unsetMbsAllowed()
{
    m_MbsAllowedIsSet = false;
}
std::vector<oai::_3gpp::model::MbsSessionId_1> MbsSubscriptionData_1::getMbsSessionIdList() const
{
    return m_MbsSessionIdList;
}
void MbsSubscriptionData_1::setMbsSessionIdList(std::vector<oai::_3gpp::model::MbsSessionId_1> const& value)
{
    m_MbsSessionIdList = value;
    m_MbsSessionIdListIsSet = true;
}
bool MbsSubscriptionData_1::mbsSessionIdListIsSet() const
{
    return m_MbsSessionIdListIsSet;
}
void MbsSubscriptionData_1::unsetMbsSessionIdList()
{
    m_MbsSessionIdListIsSet = false;
}


} // namespace oai::_3gpp::model

