/**
* Common Data Types
* Common Data Types for Service Based Interfaces.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.   
*
* The version of the OpenAPI document: 1.4.4
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * MdtConfiguration.h
 *
 * contains contain MDT configuration data.
 */

#ifndef MdtConfiguration_H_
#define MdtConfiguration_H_


#include "LoggingDurationNrMdt.h"
#include "MeasurementPeriodLteMdt.h"
#include "ReportingTrigger.h"
#include "PositioningMethodMdt.h"
#include "LoggingIntervalMdt.h"
#include "LoggingIntervalNrMdt.h"
#include "PlmnId.h"
#include "CollectionPeriodRmmNrMdt.h"
#include "JobType.h"
#include <vector>
#include "ReportTypeMdt.h"
#include "SensorMeasurement.h"
#include "ReportIntervalMdt.h"
#include "CollectionPeriodRmmLteMdt.h"
#include "LoggingDurationMdt.h"
#include "MbsfnArea.h"
#include "MeasurementNrForMdt.h"
#include "InterFreqTargetInfo.h"
#include "ReportAmountMdt.h"
#include "EventForMdt.h"
#include "ReportIntervalNrMdt.h"
#include "AreaScope.h"
#include "MeasurementLteForMdt.h"
#include <nlohmann/json.hpp>

namespace oai::model
{

/// <summary>
/// contains contain MDT configuration data.
/// </summary>
class  MdtConfiguration
{
public:
    MdtConfiguration();
    virtual ~MdtConfiguration() = default;


    /// <summary>
    /// Validate the current data in the model. Throws a ValidationException on failure.
    /// </summary>
    void validate() const;

    /// <summary>
    /// Validate the current data in the model. Returns false on error and writes an error
    /// message into the given stringstream.
    /// </summary>
    bool validate(std::stringstream& msg) const;

    /// <summary>
    /// Helper overload for validate. Used when one model stores another model and calls it's validate.
    /// Not meant to be called outside that case.
    /// </summary>
    bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

    bool operator==(const MdtConfiguration& rhs) const;
    bool operator!=(const MdtConfiguration& rhs) const;

    /////////////////////////////////////////////
    /// MdtConfiguration members

    /// <summary>
    /// 
    /// </summary>
    oai::model::JobType getJobType() const;
    void setJobType(oai::model::JobType const& value);
    /// <summary>
    /// 
    /// </summary>
    oai::model::ReportTypeMdt getReportType() const;
    void setReportType(oai::model::ReportTypeMdt const& value);
    bool reportTypeIsSet() const;
    void unsetReportType();
    /// <summary>
    /// 
    /// </summary>
    oai::model::AreaScope getAreaScope() const;
    void setAreaScope(oai::model::AreaScope const& value);
    bool areaScopeIsSet() const;
    void unsetAreaScope();
    /// <summary>
    /// 
    /// </summary>
    std::vector<oai::model::MeasurementLteForMdt> getMeasurementLteList() const;
    void setMeasurementLteList(std::vector<oai::model::MeasurementLteForMdt> const& value);
    bool measurementLteListIsSet() const;
    void unsetMeasurementLteList();
    /// <summary>
    /// 
    /// </summary>
    std::vector<oai::model::MeasurementNrForMdt> getMeasurementNrList() const;
    void setMeasurementNrList(std::vector<oai::model::MeasurementNrForMdt> const& value);
    bool measurementNrListIsSet() const;
    void unsetMeasurementNrList();
    /// <summary>
    /// 
    /// </summary>
    std::vector<oai::model::SensorMeasurement> getSensorMeasurementList() const;
    void setSensorMeasurementList(std::vector<oai::model::SensorMeasurement> const& value);
    bool sensorMeasurementListIsSet() const;
    void unsetSensorMeasurementList();
    /// <summary>
    /// 
    /// </summary>
    std::vector<oai::model::ReportingTrigger> getReportingTriggerList() const;
    void setReportingTriggerList(std::vector<oai::model::ReportingTrigger> const& value);
    bool reportingTriggerListIsSet() const;
    void unsetReportingTriggerList();
    /// <summary>
    /// 
    /// </summary>
    oai::model::ReportIntervalMdt getReportInterval() const;
    void setReportInterval(oai::model::ReportIntervalMdt const& value);
    bool reportIntervalIsSet() const;
    void unsetReportInterval();
    /// <summary>
    /// 
    /// </summary>
    oai::model::ReportIntervalNrMdt getReportIntervalNr() const;
    void setReportIntervalNr(oai::model::ReportIntervalNrMdt const& value);
    bool reportIntervalNrIsSet() const;
    void unsetReportIntervalNr();
    /// <summary>
    /// 
    /// </summary>
    oai::model::ReportAmountMdt getReportAmount() const;
    void setReportAmount(oai::model::ReportAmountMdt const& value);
    bool reportAmountIsSet() const;
    void unsetReportAmount();
    /// <summary>
    /// This IE shall be present if the report trigger parameter is configured for A2 event reporting or A2 event triggered periodic reporting and the job type parameter is configured for Immediate MDT or combined Immediate MDT and Trace in LTE. When present, this IE shall indicate the Event Threshold for RSRP, and the value shall be between 0-97. 
    /// </summary>
    int32_t getEventThresholdRsrp() const;
    void setEventThresholdRsrp(int32_t const value);
    bool eventThresholdRsrpIsSet() const;
    void unsetEventThresholdRsrp();
    /// <summary>
    /// This IE shall be present if the report trigger parameter is configured for A2 event reporting or A2 event triggered periodic reporting and the job type parameter is configured for Immediate MDT or combined Immediate MDT and Trace in NR. When present, this IE shall indicate the Event Threshold for RSRP, and the value shall be between 0-127. 
    /// </summary>
    int32_t getEventThresholdRsrpNr() const;
    void setEventThresholdRsrpNr(int32_t const value);
    bool eventThresholdRsrpNrIsSet() const;
    void unsetEventThresholdRsrpNr();
    /// <summary>
    /// This IE shall be present if the report trigger parameter is configured for A2 event reporting or A2 event triggered periodic reporting and the job type parameter is configured for Immediate MDT or combined Immediate MDT and Trace in LTE.When present, this IE shall indicate the Event Threshold for RSRQ, and the value shall be between 0-34. 
    /// </summary>
    int32_t getEventThresholdRsrq() const;
    void setEventThresholdRsrq(int32_t const value);
    bool eventThresholdRsrqIsSet() const;
    void unsetEventThresholdRsrq();
    /// <summary>
    /// This IE shall be present if the report trigger parameter is configured for A2 event reporting or A2 event triggered periodic reporting and the job type parameter is configured for Immediate MDT or combined Immediate MDT and Trace in NR.When present, this IE shall indicate the Event Threshold for RSRQ, and the value shall be between 0-127. 
    /// </summary>
    int32_t getEventThresholdRsrqNr() const;
    void setEventThresholdRsrqNr(int32_t const value);
    bool eventThresholdRsrqNrIsSet() const;
    void unsetEventThresholdRsrqNr();
    /// <summary>
    /// 
    /// </summary>
    std::vector<oai::model::EventForMdt> getEventList() const;
    void setEventList(std::vector<oai::model::EventForMdt> const& value);
    bool eventListIsSet() const;
    void unsetEventList();
    /// <summary>
    /// 
    /// </summary>
    oai::model::LoggingIntervalMdt getLoggingInterval() const;
    void setLoggingInterval(oai::model::LoggingIntervalMdt const& value);
    bool loggingIntervalIsSet() const;
    void unsetLoggingInterval();
    /// <summary>
    /// 
    /// </summary>
    oai::model::LoggingIntervalNrMdt getLoggingIntervalNr() const;
    void setLoggingIntervalNr(oai::model::LoggingIntervalNrMdt const& value);
    bool loggingIntervalNrIsSet() const;
    void unsetLoggingIntervalNr();
    /// <summary>
    /// 
    /// </summary>
    oai::model::LoggingDurationMdt getLoggingDuration() const;
    void setLoggingDuration(oai::model::LoggingDurationMdt const& value);
    bool loggingDurationIsSet() const;
    void unsetLoggingDuration();
    /// <summary>
    /// 
    /// </summary>
    oai::model::LoggingDurationNrMdt getLoggingDurationNr() const;
    void setLoggingDurationNr(oai::model::LoggingDurationNrMdt const& value);
    bool loggingDurationNrIsSet() const;
    void unsetLoggingDurationNr();
    /// <summary>
    /// 
    /// </summary>
    oai::model::PositioningMethodMdt getPositioningMethod() const;
    void setPositioningMethod(oai::model::PositioningMethodMdt const& value);
    bool positioningMethodIsSet() const;
    void unsetPositioningMethod();
    /// <summary>
    /// 
    /// </summary>
    std::vector<oai::model::PositioningMethodMdt> getAddPositioningMethodList() const;
    void setAddPositioningMethodList(std::vector<oai::model::PositioningMethodMdt> const& value);
    bool addPositioningMethodListIsSet() const;
    void unsetAddPositioningMethodList();
    /// <summary>
    /// 
    /// </summary>
    oai::model::CollectionPeriodRmmLteMdt getCollectionPeriodRmmLte() const;
    void setCollectionPeriodRmmLte(oai::model::CollectionPeriodRmmLteMdt const& value);
    bool collectionPeriodRmmLteIsSet() const;
    void unsetCollectionPeriodRmmLte();
    /// <summary>
    /// 
    /// </summary>
    oai::model::CollectionPeriodRmmNrMdt getCollectionPeriodRmmNr() const;
    void setCollectionPeriodRmmNr(oai::model::CollectionPeriodRmmNrMdt const& value);
    bool collectionPeriodRmmNrIsSet() const;
    void unsetCollectionPeriodRmmNr();
    /// <summary>
    /// 
    /// </summary>
    oai::model::MeasurementPeriodLteMdt getMeasurementPeriodLte() const;
    void setMeasurementPeriodLte(oai::model::MeasurementPeriodLteMdt const& value);
    bool measurementPeriodLteIsSet() const;
    void unsetMeasurementPeriodLte();
    /// <summary>
    /// 
    /// </summary>
    std::vector<oai::model::PlmnId> getMdtAllowedPlmnIdList() const;
    void setMdtAllowedPlmnIdList(std::vector<oai::model::PlmnId> const& value);
    bool mdtAllowedPlmnIdListIsSet() const;
    void unsetMdtAllowedPlmnIdList();
    /// <summary>
    /// 
    /// </summary>
    std::vector<oai::model::MbsfnArea> getMbsfnAreaList() const;
    void setMbsfnAreaList(std::vector<oai::model::MbsfnArea> const& value);
    bool mbsfnAreaListIsSet() const;
    void unsetMbsfnAreaList();
    /// <summary>
    /// 
    /// </summary>
    std::vector<oai::model::InterFreqTargetInfo> getInterFreqTargetList() const;
    void setInterFreqTargetList(std::vector<oai::model::InterFreqTargetInfo> const& value);
    bool interFreqTargetListIsSet() const;
    void unsetInterFreqTargetList();

    friend  void to_json(nlohmann::json& j, const MdtConfiguration& o);
    friend  void from_json(const nlohmann::json& j, MdtConfiguration& o);
protected:
    oai::model::JobType m_JobType;

    oai::model::ReportTypeMdt m_ReportType;
    bool m_ReportTypeIsSet;
    oai::model::AreaScope m_AreaScope;
    bool m_AreaScopeIsSet;
    std::vector<oai::model::MeasurementLteForMdt> m_MeasurementLteList;
    bool m_MeasurementLteListIsSet;
    std::vector<oai::model::MeasurementNrForMdt> m_MeasurementNrList;
    bool m_MeasurementNrListIsSet;
    std::vector<oai::model::SensorMeasurement> m_SensorMeasurementList;
    bool m_SensorMeasurementListIsSet;
    std::vector<oai::model::ReportingTrigger> m_ReportingTriggerList;
    bool m_ReportingTriggerListIsSet;
    oai::model::ReportIntervalMdt m_ReportInterval;
    bool m_ReportIntervalIsSet;
    oai::model::ReportIntervalNrMdt m_ReportIntervalNr;
    bool m_ReportIntervalNrIsSet;
    oai::model::ReportAmountMdt m_ReportAmount;
    bool m_ReportAmountIsSet;
    int32_t m_EventThresholdRsrp;
    bool m_EventThresholdRsrpIsSet;
    int32_t m_EventThresholdRsrpNr;
    bool m_EventThresholdRsrpNrIsSet;
    int32_t m_EventThresholdRsrq;
    bool m_EventThresholdRsrqIsSet;
    int32_t m_EventThresholdRsrqNr;
    bool m_EventThresholdRsrqNrIsSet;
    std::vector<oai::model::EventForMdt> m_EventList;
    bool m_EventListIsSet;
    oai::model::LoggingIntervalMdt m_LoggingInterval;
    bool m_LoggingIntervalIsSet;
    oai::model::LoggingIntervalNrMdt m_LoggingIntervalNr;
    bool m_LoggingIntervalNrIsSet;
    oai::model::LoggingDurationMdt m_LoggingDuration;
    bool m_LoggingDurationIsSet;
    oai::model::LoggingDurationNrMdt m_LoggingDurationNr;
    bool m_LoggingDurationNrIsSet;
    oai::model::PositioningMethodMdt m_PositioningMethod;
    bool m_PositioningMethodIsSet;
    std::vector<oai::model::PositioningMethodMdt> m_AddPositioningMethodList;
    bool m_AddPositioningMethodListIsSet;
    oai::model::CollectionPeriodRmmLteMdt m_CollectionPeriodRmmLte;
    bool m_CollectionPeriodRmmLteIsSet;
    oai::model::CollectionPeriodRmmNrMdt m_CollectionPeriodRmmNr;
    bool m_CollectionPeriodRmmNrIsSet;
    oai::model::MeasurementPeriodLteMdt m_MeasurementPeriodLte;
    bool m_MeasurementPeriodLteIsSet;
    std::vector<oai::model::PlmnId> m_MdtAllowedPlmnIdList;
    bool m_MdtAllowedPlmnIdListIsSet;
    std::vector<oai::model::MbsfnArea> m_MbsfnAreaList;
    bool m_MbsfnAreaListIsSet;
    std::vector<oai::model::InterFreqTargetInfo> m_InterFreqTargetList;
    bool m_InterFreqTargetListIsSet;
    
};

} // namespace oai::model

#endif /* MdtConfiguration_H_ */
