/**
* Namf_Communication
* AMF Communication Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
*
* The version of the OpenAPI document: 1.2.4
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "N1MessageClass.h"
#include "Helpers.h"

#include <sstream>

namespace oai::model
{

N1MessageClass::N1MessageClass()
{
    
}

void N1MessageClass::validate() const
{
    std::stringstream msg;
    if (!validate(msg))
    {
        throw org::openapitools::server::helpers::ValidationException(msg.str());
    }
}

bool N1MessageClass::validate(std::stringstream& msg) const
{
    return validate(msg, "");
}

bool N1MessageClass::validate(std::stringstream& msg, const std::string& pathPrefix) const
{
    bool success = true;
    const std::string _pathPrefix = pathPrefix.empty() ? "N1MessageClass" : pathPrefix;

    
    return success;
}

bool N1MessageClass::operator==(const N1MessageClass& rhs) const
{
    return
    
    
    ;
}

bool N1MessageClass::operator!=(const N1MessageClass& rhs) const
{
    return !(*this == rhs);
}

void to_json(nlohmann::json& j, const N1MessageClass& o)
{
    j = nlohmann::json::object();
    
}

void from_json(const nlohmann::json& j, N1MessageClass& o)
{
    
}



} // namespace oai::model

