/**
* Namf_Communication
* AMF Communication Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
*
* The version of the OpenAPI document: 1.2.4
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * N1MessageNotification.h
 *
 * Data within a N1 message notification request
 */

#ifndef N1MessageNotification_H_
#define N1MessageNotification_H_


#include "Ecgi.h"
#include "Ncgi.h"
#include "RegistrationContextContainer.h"
#include "N1MessageContainer.h"
#include <string>
#include "Guami.h"
#include <nlohmann/json.hpp>

namespace oai::model
{

/// <summary>
/// Data within a N1 message notification request
/// </summary>
class  N1MessageNotification
{
public:
    N1MessageNotification();
    virtual ~N1MessageNotification() = default;


    /// <summary>
    /// Validate the current data in the model. Throws a ValidationException on failure.
    /// </summary>
    void validate() const;

    /// <summary>
    /// Validate the current data in the model. Returns false on error and writes an error
    /// message into the given stringstream.
    /// </summary>
    bool validate(std::stringstream& msg) const;

    /// <summary>
    /// Helper overload for validate. Used when one model stores another model and calls it's validate.
    /// Not meant to be called outside that case.
    /// </summary>
    bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

    bool operator==(const N1MessageNotification& rhs) const;
    bool operator!=(const N1MessageNotification& rhs) const;

    /////////////////////////////////////////////
    /// N1MessageNotification members

    /// <summary>
    /// 
    /// </summary>
    std::string getN1NotifySubscriptionId() const;
    void setN1NotifySubscriptionId(std::string const& value);
    bool n1NotifySubscriptionIdIsSet() const;
    void unsetN1NotifySubscriptionId();
    /// <summary>
    /// 
    /// </summary>
    oai::model::N1MessageContainer getN1MessageContainer() const;
    void setN1MessageContainer(oai::model::N1MessageContainer const& value);
    /// <summary>
    /// LCS Correlation ID.
    /// </summary>
    std::string getLcsCorrelationId() const;
    void setLcsCorrelationId(std::string const& value);
    bool lcsCorrelationIdIsSet() const;
    void unsetLcsCorrelationId();
    /// <summary>
    /// 
    /// </summary>
    oai::model::RegistrationContextContainer getRegistrationCtxtContainer() const;
    void setRegistrationCtxtContainer(oai::model::RegistrationContextContainer const& value);
    bool registrationCtxtContainerIsSet() const;
    void unsetRegistrationCtxtContainer();
    /// <summary>
    /// LMF identification.
    /// </summary>
    std::string getNewLmfIdentification() const;
    void setNewLmfIdentification(std::string const& value);
    bool newLmfIdentificationIsSet() const;
    void unsetNewLmfIdentification();
    /// <summary>
    /// 
    /// </summary>
    oai::model::Guami getGuami() const;
    void setGuami(oai::model::Guami const& value);
    bool guamiIsSet() const;
    void unsetGuami();
    /// <summary>
    /// 
    /// </summary>
    bool isCIoT5GSOptimisation() const;
    void setCIoT5GSOptimisation(bool const value);
    bool cIoT5GSOptimisationIsSet() const;
    void unsetCIoT5GSOptimisation();
    /// <summary>
    /// 
    /// </summary>
    oai::model::Ecgi getEcgi() const;
    void setEcgi(oai::model::Ecgi const& value);
    bool ecgiIsSet() const;
    void unsetEcgi();
    /// <summary>
    /// 
    /// </summary>
    oai::model::Ncgi getNcgi() const;
    void setNcgi(oai::model::Ncgi const& value);
    bool ncgiIsSet() const;
    void unsetNcgi();

    friend  void to_json(nlohmann::json& j, const N1MessageNotification& o);
    friend  void from_json(const nlohmann::json& j, N1MessageNotification& o);
protected:
    std::string m_N1NotifySubscriptionId;
    bool m_N1NotifySubscriptionIdIsSet;
    oai::model::N1MessageContainer m_N1MessageContainer;

    std::string m_LcsCorrelationId;
    bool m_LcsCorrelationIdIsSet;
    oai::model::RegistrationContextContainer m_RegistrationCtxtContainer;
    bool m_RegistrationCtxtContainerIsSet;
    std::string m_NewLmfIdentification;
    bool m_NewLmfIdentificationIsSet;
    oai::model::Guami m_Guami;
    bool m_GuamiIsSet;
    bool m_CIoT5GSOptimisation;
    bool m_CIoT5GSOptimisationIsSet;
    oai::model::Ecgi m_Ecgi;
    bool m_EcgiIsSet;
    oai::model::Ncgi m_Ncgi;
    bool m_NcgiIsSet;
    
};

} // namespace oai::model

#endif /* N1MessageNotification_H_ */
