/**
* JOSE Protected Message Forwarding API
* N32-f Message Forwarding Service.   © 2025, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
*
* The version of the OpenAPI document: 1.4.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "N32fReformattedReqMsg.h"
#include "Helpers.h"

#include <sstream>

namespace oai::_3gpp::model {

N32fReformattedReqMsg::N32fReformattedReqMsg()
{
    m_ModificationsBlockIsSet = false;
    
}

N32fReformattedReqMsg::~N32fReformattedReqMsg() = default;

void N32fReformattedReqMsg::validate() const
{
    std::stringstream msg;
    // if (!validate(msg))
    // {
    //     throw org::openapitools::server::helpers::ValidationException(msg.str());
    // }
}

bool N32fReformattedReqMsg::validate(std::stringstream& msg) const
{
    return validate(msg, "");
}

bool N32fReformattedReqMsg::validate(std::stringstream& msg, const std::string& pathPrefix) const
{
    bool success = true;
    const std::string _pathPrefix = pathPrefix.empty() ? "N32fReformattedReqMsg" : pathPrefix;

        
    if (!m_ReformattedData.validate(msg, _pathPrefix + ".reformattedData")) {
        msg << _pathPrefix << ": ReformattedData is invalid;";
        success = false;
    }     
    if (modificationsBlockIsSet())
    {
        const std::vector<oai::_3gpp::model::FlatJwsJson>& value = m_ModificationsBlock;
        const std::string currentValuePath = _pathPrefix + ".modificationsBlock";
                
        
        if (value.size() < 1)
        {
            success = false;
            msg << currentValuePath << ": must have at least 1 elements;";
        }
        { // Recursive validation of array elements
            const std::string oldValuePath = currentValuePath;
            int i = 0;
            for (const oai::_3gpp::model::FlatJwsJson& value : value)
            { 
                const std::string currentValuePath = oldValuePath + "[" + std::to_string(i) + "]";
                        
        success = value.validate(msg, currentValuePath + ".modificationsBlock") && success;
 
                i++;
            }
        }

    }
    
    return success;
}

bool N32fReformattedReqMsg::operator==(const N32fReformattedReqMsg& rhs) const
{
    return
    
    
    (getReformattedData() == rhs.getReformattedData())
     &&
    
    
    ((!modificationsBlockIsSet() && !rhs.modificationsBlockIsSet()) || (modificationsBlockIsSet() && rhs.modificationsBlockIsSet() && getModificationsBlock() == rhs.getModificationsBlock()))
    
    ;
}

bool N32fReformattedReqMsg::operator!=(const N32fReformattedReqMsg& rhs) const
{
    return !(*this == rhs);
}

void to_json(nlohmann::json& j, const N32fReformattedReqMsg& o)
{
    j = nlohmann::json::object();
    j["reformattedData"] = o.m_ReformattedData;
    if(o.modificationsBlockIsSet() || !o.m_ModificationsBlock.empty())
        j["modificationsBlock"] = o.m_ModificationsBlock;
    
}

void from_json(const nlohmann::json& j, N32fReformattedReqMsg& o)
{
    j.at("reformattedData").get_to(o.m_ReformattedData);
    if(j.find("modificationsBlock") != j.end())
    {
        j.at("modificationsBlock").get_to(o.m_ModificationsBlock);
        o.m_ModificationsBlockIsSet = true;
    } 
    
}

oai::_3gpp::model::FlatJweJson N32fReformattedReqMsg::getReformattedData() const
{
    return m_ReformattedData;
}
void N32fReformattedReqMsg::setReformattedData(oai::_3gpp::model::FlatJweJson const& value)
{
    m_ReformattedData = value;
}
std::vector<oai::_3gpp::model::FlatJwsJson> N32fReformattedReqMsg::getModificationsBlock() const
{
    return m_ModificationsBlock;
}
void N32fReformattedReqMsg::setModificationsBlock(std::vector<oai::_3gpp::model::FlatJwsJson> const& value)
{
    m_ModificationsBlock = value;
    m_ModificationsBlockIsSet = true;
}
bool N32fReformattedReqMsg::modificationsBlockIsSet() const
{
    return m_ModificationsBlockIsSet;
}
void N32fReformattedReqMsg::unsetModificationsBlock()
{
    m_ModificationsBlockIsSet = false;
}


}  // namespace oai::_3gpp::model

