# SPDX-License-Identifier: LicenseRef-CSSL-1.0

SET(NEF_MODEL_DIR ${SRC_TOP_DIR}/${MOUNTED_COMMON}/model)

include_directories(${NEF_MODEL_DIR})

file(GLOB NEF_MODEL_SRC_FILES
    ${NEF_MODEL_DIR}/_5GsUserState_anyOf.cpp
    ${NEF_MODEL_DIR}/AanfInfo.cpp
    ${NEF_MODEL_DIR}/AbnormalBehaviour.cpp
    ${NEF_MODEL_DIR}/AccessRightStatus_anyOf.cpp
    ${NEF_MODEL_DIR}/AccessRightStatus.cpp
    ${NEF_MODEL_DIR}/AccessStateTransitionType_anyOf.cpp
    ${NEF_MODEL_DIR}/AccessStateTransitionType.cpp
    ${NEF_MODEL_DIR}/AccessTokenErr.cpp
    ${NEF_MODEL_DIR}/AccessTokenReq.cpp
    ${NEF_MODEL_DIR}/AccessType.cpp
    ${NEF_MODEL_DIR}/AccumulatedUsage.cpp
    ${NEF_MODEL_DIR}/Accuracy_anyOf.cpp
    ${NEF_MODEL_DIR}/Accuracy.cpp
    ${NEF_MODEL_DIR}/AccuracyFulfilmentIndicator_anyOf.cpp
    ${NEF_MODEL_DIR}/AccuracyFulfilmentIndicator.cpp
    ${NEF_MODEL_DIR}/AdditionalMeasurement.cpp
    ${NEF_MODEL_DIR}/AddressList.cpp
    ${NEF_MODEL_DIR}/AddrFqdn.cpp
    ${NEF_MODEL_DIR}/AfEvent_anyOf.cpp
    ${NEF_MODEL_DIR}/AfEvent.cpp
    ${NEF_MODEL_DIR}/AfEventExposureData.cpp
    ${NEF_MODEL_DIR}/AfEventSubscription.cpp
    ${NEF_MODEL_DIR}/AfNotifMethod_anyOf.cpp
    ${NEF_MODEL_DIR}/AfNotifMethod.cpp
    ${NEF_MODEL_DIR}/AfRequestedData_anyOf.cpp
    ${NEF_MODEL_DIR}/AfRequestedData.cpp
    ${NEF_MODEL_DIR}/AfResultInfo.cpp
    ${NEF_MODEL_DIR}/AfResultStatus_anyOf.cpp
    ${NEF_MODEL_DIR}/AfResultStatus.cpp
    ${NEF_MODEL_DIR}/AfRoutingRequirement.cpp
    ${NEF_MODEL_DIR}/AfRoutingRequirementRm.cpp
    ${NEF_MODEL_DIR}/AfSigProtocol_anyOf.cpp
    ${NEF_MODEL_DIR}/AfSigProtocol.cpp
    ${NEF_MODEL_DIR}/AlternativeServiceRequirementsData.cpp
    ${NEF_MODEL_DIR}/AmEvent_anyOf.cpp
    ${NEF_MODEL_DIR}/AmEvent.cpp
    ${NEF_MODEL_DIR}/AmEventData.cpp
    ${NEF_MODEL_DIR}/AmEventNotification.cpp
    ${NEF_MODEL_DIR}/AmEventsNotification.cpp
    ${NEF_MODEL_DIR}/AmEventsSubscData.cpp
    ${NEF_MODEL_DIR}/AmEventsSubscDataRm.cpp
    ${NEF_MODEL_DIR}/AmEventsSubscRespData.cpp
    ${NEF_MODEL_DIR}/AmfCond.cpp
    ${NEF_MODEL_DIR}/AmfCreatedEventSubscription.cpp
    ${NEF_MODEL_DIR}/AmfCreateEventSubscription.cpp
    ${NEF_MODEL_DIR}/AmfEventArea.cpp
    ${NEF_MODEL_DIR}/AmfEvent.cpp
    ${NEF_MODEL_DIR}/AmfEventMode.cpp
    ${NEF_MODEL_DIR}/AmfEventReport.cpp
    ${NEF_MODEL_DIR}/AmfEventState.cpp
    ${NEF_MODEL_DIR}/AmfEventSubscription.cpp
    ${NEF_MODEL_DIR}/AmfEventTrigger_anyOf.cpp
    ${NEF_MODEL_DIR}/AmfEventTrigger.cpp
    ${NEF_MODEL_DIR}/AmfEventType_anyOf.cpp
    ${NEF_MODEL_DIR}/AmfEventType.cpp
    ${NEF_MODEL_DIR}/AmfInfo.cpp
    ${NEF_MODEL_DIR}/AmInfluEvent_anyOf.cpp
    ${NEF_MODEL_DIR}/AmInfluEvent.cpp
    ${NEF_MODEL_DIR}/AnalyticsMetadata_anyOf.cpp
    ${NEF_MODEL_DIR}/AnalyticsMetadata.cpp
    ${NEF_MODEL_DIR}/AnalyticsMetadataIndication.cpp
    ${NEF_MODEL_DIR}/AnalyticsMetadataInfo.cpp
    ${NEF_MODEL_DIR}/AnalyticsSubset_anyOf.cpp
    ${NEF_MODEL_DIR}/AnalyticsSubset.cpp
    ${NEF_MODEL_DIR}/AnNodeType_anyOf.cpp
    ${NEF_MODEL_DIR}/AnNodeType.cpp
    ${NEF_MODEL_DIR}/ApnRateStatus.cpp
    ${NEF_MODEL_DIR}/AppAmContextData.cpp
    ${NEF_MODEL_DIR}/AppDescriptor.cpp
    ${NEF_MODEL_DIR}/ApplicationForPfdRequest.cpp
    ${NEF_MODEL_DIR}/ApplicationVolume.cpp
    ${NEF_MODEL_DIR}/AppListForUeComm.cpp
    ${NEF_MODEL_DIR}/AppSessionContextReqData.cpp
    ${NEF_MODEL_DIR}/AppSessionContextUpdateData.cpp
    ${NEF_MODEL_DIR}/AppSessionContextUpdateDataPatch.cpp
    ${NEF_MODEL_DIR}/Arp.cpp
    ${NEF_MODEL_DIR}/AssociationType_anyOf.cpp
    ${NEF_MODEL_DIR}/AssociationType.cpp
    ${NEF_MODEL_DIR}/AsTimeDistributionParam.cpp
    ${NEF_MODEL_DIR}/Atom.cpp
    ${NEF_MODEL_DIR}/AtsssCapability.cpp
    ${NEF_MODEL_DIR}/AusfInfo.cpp
    ${NEF_MODEL_DIR}/BackupAmfInfo.cpp
    ${NEF_MODEL_DIR}/BaseRecord.cpp
    ${NEF_MODEL_DIR}/BatteryIndication.cpp
    ${NEF_MODEL_DIR}/BdtPolicy.cpp
    ${NEF_MODEL_DIR}/BdtPolicyData.cpp
    ${NEF_MODEL_DIR}/BdtReqData.cpp
    ${NEF_MODEL_DIR}/BridgeManagementContainer.cpp
    ${NEF_MODEL_DIR}/BroadcastDeliveryStatus_anyOf.cpp
    ${NEF_MODEL_DIR}/BroadcastDeliveryStatus.cpp
    ${NEF_MODEL_DIR}/BsfInfo.cpp
    ${NEF_MODEL_DIR}/BwRequirement.cpp
    ${NEF_MODEL_DIR}/CacheStatus_anyOf.cpp
    ${NEF_MODEL_DIR}/CacheStatus.cpp
    ${NEF_MODEL_DIR}/Cause_anyOf.cpp
    ${NEF_MODEL_DIR}/Cause.cpp
    ${NEF_MODEL_DIR}/CellGlobalId.cpp
    ${NEF_MODEL_DIR}/ChangeItem.cpp
    ${NEF_MODEL_DIR}/ChangeType_anyOf.cpp
    ${NEF_MODEL_DIR}/ChangeType.cpp
    ${NEF_MODEL_DIR}/ChfInfo.cpp
    ${NEF_MODEL_DIR}/CircumstanceDescription.cpp
    ${NEF_MODEL_DIR}/CivicAddress.cpp
    ${NEF_MODEL_DIR}/ClassCriterion.cpp
    ${NEF_MODEL_DIR}/CmInfo.cpp
    ${NEF_MODEL_DIR}/CmState_anyOf.cpp
    ${NEF_MODEL_DIR}/CmState.cpp
    ${NEF_MODEL_DIR}/Cnf.cpp
    ${NEF_MODEL_DIR}/CnfUnit.cpp
    ${NEF_MODEL_DIR}/CollectiveBehaviourFilter.cpp
    ${NEF_MODEL_DIR}/CollectiveBehaviourFilterType_anyOf.cpp
    ${NEF_MODEL_DIR}/CollectiveBehaviourFilterType.cpp
    ${NEF_MODEL_DIR}/CollectiveBehaviourInfo.cpp
    ${NEF_MODEL_DIR}/CollocatedNfInstance.cpp
    ${NEF_MODEL_DIR}/CollocatedNfType_anyOf.cpp
    ${NEF_MODEL_DIR}/CollocatedNfType.cpp
    ${NEF_MODEL_DIR}/CommunicationCollection.cpp
    ${NEF_MODEL_DIR}/CommunicationFailure.cpp
    ${NEF_MODEL_DIR}/ComplexQuery.cpp
    ${NEF_MODEL_DIR}/ConditionEventType_anyOf.cpp
    ${NEF_MODEL_DIR}/ConditionEventType.cpp
    ${NEF_MODEL_DIR}/CongestionInfo.cpp
    ${NEF_MODEL_DIR}/CongestionType_anyOf.cpp
    ${NEF_MODEL_DIR}/CongestionType.cpp
    ${NEF_MODEL_DIR}/ConnectionCapabilities_anyOf.cpp
    ${NEF_MODEL_DIR}/ConnectionCapabilities.cpp
    ${NEF_MODEL_DIR}/DataRestorationNotification.cpp
    ${NEF_MODEL_DIR}/DataSetId_anyOf.cpp
    ${NEF_MODEL_DIR}/DataSetId.cpp
    ${NEF_MODEL_DIR}/DatasetStatisticalProperty_anyOf.cpp
    ${NEF_MODEL_DIR}/DatasetStatisticalProperty.cpp
    ${NEF_MODEL_DIR}/DccfCond.cpp
    ${NEF_MODEL_DIR}/DccfInfo.cpp
    ${NEF_MODEL_DIR}/DddTrafficDescriptor.cpp
    ${NEF_MODEL_DIR}/DefaultNotificationSubscription.cpp
    ${NEF_MODEL_DIR}/DefSubServiceInfo.cpp
    ${NEF_MODEL_DIR}/DeliverReqData.cpp
    ${NEF_MODEL_DIR}/DispersionArea.cpp
    ${NEF_MODEL_DIR}/DispersionClass.cpp
    ${NEF_MODEL_DIR}/DispersionClass_oneOf.cpp
    ${NEF_MODEL_DIR}/DispersionCollection.cpp
    ${NEF_MODEL_DIR}/DispersionInfo.cpp
    ${NEF_MODEL_DIR}/DispersionOrderingCriterion_anyOf.cpp
    ${NEF_MODEL_DIR}/DispersionOrderingCriterion.cpp
    ${NEF_MODEL_DIR}/DispersionRequirement.cpp
    ${NEF_MODEL_DIR}/DispersionType.cpp
    ${NEF_MODEL_DIR}/DispersionType_oneOf.cpp
    ${NEF_MODEL_DIR}/DlDataDeliveryStatus_anyOf.cpp
    ${NEF_MODEL_DIR}/DlDataDeliveryStatus.cpp
    ${NEF_MODEL_DIR}/DnaiChangeType_anyOf.cpp
    ${NEF_MODEL_DIR}/DnaiChangeType.cpp
    ${NEF_MODEL_DIR}/DnaiInformation.cpp
    ${NEF_MODEL_DIR}/Dnf.cpp
    ${NEF_MODEL_DIR}/DnfUnit.cpp
    ${NEF_MODEL_DIR}/DnnEasdfInfoItem.cpp
    ${NEF_MODEL_DIR}/DnnInfoItem.cpp
    ${NEF_MODEL_DIR}/DnnMbSmfInfoItem.cpp
    ${NEF_MODEL_DIR}/DnnSelectionMode_anyOf.cpp
    ${NEF_MODEL_DIR}/DnnSelectionMode.cpp
    ${NEF_MODEL_DIR}/DnnSmfInfoItem.cpp
    ${NEF_MODEL_DIR}/DnnSmfInfoItem_dnn.cpp
    ${NEF_MODEL_DIR}/DnnSnssaiInformation.cpp
    ${NEF_MODEL_DIR}/DnnTsctsfInfoItem.cpp
    ${NEF_MODEL_DIR}/DnnUpfInfoItem.cpp
    ${NEF_MODEL_DIR}/DnPerf.cpp
    ${NEF_MODEL_DIR}/DnPerfInfo.cpp
    ${NEF_MODEL_DIR}/DnPerfOrderingCriterion_anyOf.cpp
    ${NEF_MODEL_DIR}/DnPerfOrderingCriterion.cpp
    ${NEF_MODEL_DIR}/DnPerformanceReq.cpp
    ${NEF_MODEL_DIR}/DnsServerIdentifier.cpp
    ${NEF_MODEL_DIR}/DomainNameProtocol_anyOf.cpp
    ${NEF_MODEL_DIR}/DomainNameProtocol.cpp
    ${NEF_MODEL_DIR}/DynamicPolicy.cpp
    ${NEF_MODEL_DIR}/EasDeployInfoData.cpp
    ${NEF_MODEL_DIR}/EasDeployInfoNotif.cpp
    ${NEF_MODEL_DIR}/EasDeploySubData.cpp
    ${NEF_MODEL_DIR}/EasDepNotification.cpp
    ${NEF_MODEL_DIR}/EasdfInfo.cpp
    ${NEF_MODEL_DIR}/EasEvent_anyOf.cpp
    ${NEF_MODEL_DIR}/EasEvent.cpp
    ${NEF_MODEL_DIR}/EasIpReplacementInfo.cpp
    ${NEF_MODEL_DIR}/EasServerAddress.cpp
    ${NEF_MODEL_DIR}/EbiArpMapping.cpp
    ${NEF_MODEL_DIR}/Ecgi.cpp
    ${NEF_MODEL_DIR}/EcRestrictionDataWb.cpp
    ${NEF_MODEL_DIR}/EllipsoidArc.cpp
    ${NEF_MODEL_DIR}/EndpointAddress.cpp
    ${NEF_MODEL_DIR}/EpsInterworkingIndication_anyOf.cpp
    ${NEF_MODEL_DIR}/EpsInterworkingIndication.cpp
    ${NEF_MODEL_DIR}/EthFlowDescription.cpp
    ${NEF_MODEL_DIR}/EutraLocation.cpp
    ${NEF_MODEL_DIR}/Event_anyOf.cpp
    ${NEF_MODEL_DIR}/Event.cpp
    ${NEF_MODEL_DIR}/EventFilter.cpp
    ${NEF_MODEL_DIR}/EventId_anyOf.cpp
    ${NEF_MODEL_DIR}/EventId.cpp
    ${NEF_MODEL_DIR}/EventNotification.cpp
    ${NEF_MODEL_DIR}/EventReportingRequirement.cpp
    ${NEF_MODEL_DIR}/EventsSubscReqData.cpp
    ${NEF_MODEL_DIR}/EventsSubscReqDataRm.cpp
    ${NEF_MODEL_DIR}/Exception.cpp
    ${NEF_MODEL_DIR}/ExceptionId_anyOf.cpp
    ${NEF_MODEL_DIR}/ExceptionId.cpp
    ${NEF_MODEL_DIR}/ExceptionInfo.cpp
    ${NEF_MODEL_DIR}/ExceptionTrend_anyOf.cpp
    ${NEF_MODEL_DIR}/ExceptionTrend.cpp
    ${NEF_MODEL_DIR}/ExemptionInd.cpp
    ${NEF_MODEL_DIR}/ExpectedAnalyticsType_anyOf.cpp
    ${NEF_MODEL_DIR}/ExpectedAnalyticsType.cpp
    ${NEF_MODEL_DIR}/ExpectedUeBehaviourData.cpp
    ${NEF_MODEL_DIR}/ExternalClientType_anyOf.cpp
    ${NEF_MODEL_DIR}/ExternalClientType.cpp
    ${NEF_MODEL_DIR}/ExternalMbsServiceArea.cpp
    ${NEF_MODEL_DIR}/ExtSnssai.cpp
    ${NEF_MODEL_DIR}/FailureCause_anyOf.cpp
    ${NEF_MODEL_DIR}/FailureCause.cpp
    ${NEF_MODEL_DIR}/Failure.cpp
    ${NEF_MODEL_DIR}/Failure_oneOf.cpp
    ${NEF_MODEL_DIR}/FlowDirection_anyOf.cpp
    ${NEF_MODEL_DIR}/FlowDirection.cpp
    ${NEF_MODEL_DIR}/FlowInfo.cpp
    ${NEF_MODEL_DIR}/Flows.cpp
    ${NEF_MODEL_DIR}/FlowStatus_anyOf.cpp
    ${NEF_MODEL_DIR}/FlowStatus.cpp
    ${NEF_MODEL_DIR}/FlowUsage_anyOf.cpp
    ${NEF_MODEL_DIR}/FlowUsage.cpp
    ${NEF_MODEL_DIR}/FqdnPatternMatchingRule.cpp
    ${NEF_MODEL_DIR}/GADShape.cpp
    ${NEF_MODEL_DIR}/GeographicalArea.cpp
    ${NEF_MODEL_DIR}/GeographicalCoordinates.cpp
    ${NEF_MODEL_DIR}/GeographicArea.cpp
    ${NEF_MODEL_DIR}/GeraLocation.cpp
    ${NEF_MODEL_DIR}/GlobalRanNodeId.cpp
    ${NEF_MODEL_DIR}/GmlcInfo.cpp
    ${NEF_MODEL_DIR}/GNbId.cpp
    ${NEF_MODEL_DIR}/Guami.cpp
    ${NEF_MODEL_DIR}/GuamiListCond.cpp
    ${NEF_MODEL_DIR}/Helpers.cpp
    ${NEF_MODEL_DIR}/HfcNodeId.cpp
    ${NEF_MODEL_DIR}/HorizontalVelocity.cpp
    ${NEF_MODEL_DIR}/HorizontalVelocityWithUncertainty.cpp
    ${NEF_MODEL_DIR}/HorizontalWithVerticalVelocityAndUncertainty.cpp
    ${NEF_MODEL_DIR}/HorizontalWithVerticalVelocity.cpp
    ${NEF_MODEL_DIR}/HoState_anyOf.cpp
    ${NEF_MODEL_DIR}/HoState.cpp
    ${NEF_MODEL_DIR}/HssInfo.cpp
    ${NEF_MODEL_DIR}/IdentityRange.cpp
    ${NEF_MODEL_DIR}/IdleStatusIndication.cpp
    ${NEF_MODEL_DIR}/ImsiRange.cpp
    ${NEF_MODEL_DIR}/IngressTunAddrInfo.cpp
    ${NEF_MODEL_DIR}/InterfaceUpfInfoItem.cpp
    ${NEF_MODEL_DIR}/InternalGroupIdRange.cpp
    ${NEF_MODEL_DIR}/InvalidParam.cpp
    ${NEF_MODEL_DIR}/IpAddr.cpp
    ${NEF_MODEL_DIR}/IpEndPoint.cpp
    ${NEF_MODEL_DIR}/IpEthFlowDescription.cpp
    ${NEF_MODEL_DIR}/IpIndex.cpp
    ${NEF_MODEL_DIR}/IpPacketFilterSet.cpp
    ${NEF_MODEL_DIR}/IpReachability_anyOf.cpp
    ${NEF_MODEL_DIR}/IpReachability.cpp
    ${NEF_MODEL_DIR}/IptvConfigData.cpp
    ${NEF_MODEL_DIR}/IptvConfigDataPatch.cpp
    ${NEF_MODEL_DIR}/Ipv4AddressRange.cpp
    ${NEF_MODEL_DIR}/Ipv6Addr.cpp
    ${NEF_MODEL_DIR}/Ipv6Prefix.cpp
    ${NEF_MODEL_DIR}/Ipv6PrefixRange.cpp
    ${NEF_MODEL_DIR}/IwmscInfo.cpp
    ${NEF_MODEL_DIR}/LadnInfo.cpp
    ${NEF_MODEL_DIR}/LcsQosClass_anyOf.cpp
    ${NEF_MODEL_DIR}/LcsQosClass.cpp
    ${NEF_MODEL_DIR}/LdrType_anyOf.cpp
    ${NEF_MODEL_DIR}/LdrType.cpp
    ${NEF_MODEL_DIR}/LineType_anyOf.cpp
    ${NEF_MODEL_DIR}/LineType.cpp
    ${NEF_MODEL_DIR}/Link.cpp
    ${NEF_MODEL_DIR}/LinkRm.cpp
    ${NEF_MODEL_DIR}/LinksValueSchema.cpp
    ${NEF_MODEL_DIR}/LmfInfo.cpp
    ${NEF_MODEL_DIR}/LocationArea5G.cpp
    ${NEF_MODEL_DIR}/LocationArea.cpp
    ${NEF_MODEL_DIR}/LocationAreaId.cpp
    ${NEF_MODEL_DIR}/LocationFilter_anyOf.cpp
    ${NEF_MODEL_DIR}/LocationFilter.cpp
    ${NEF_MODEL_DIR}/LocationInfo.cpp
    ${NEF_MODEL_DIR}/LocationQoS.cpp
    ${NEF_MODEL_DIR}/LocationRequestType_anyOf.cpp
    ${NEF_MODEL_DIR}/LocationRequestType.cpp
    ${NEF_MODEL_DIR}/LocationType_anyOf.cpp
    ${NEF_MODEL_DIR}/LocationType.cpp
    ${NEF_MODEL_DIR}/LocUpdateData.cpp
    ${NEF_MODEL_DIR}/LossOfConnectivityReason_anyOf.cpp
    ${NEF_MODEL_DIR}/LossOfConnectivityReason.cpp
    ${NEF_MODEL_DIR}/M5QoSSpecification.cpp
    ${NEF_MODEL_DIR}/MaReleaseIndication_anyOf.cpp
    ${NEF_MODEL_DIR}/MaReleaseIndication.cpp
    ${NEF_MODEL_DIR}/MatchingDirection_anyOf.cpp
    ${NEF_MODEL_DIR}/MatchingDirection.cpp
    ${NEF_MODEL_DIR}/MatchingOperator_anyOf.cpp
    ${NEF_MODEL_DIR}/MatchingOperator.cpp
    ${NEF_MODEL_DIR}/MbsMediaComp.cpp
    ${NEF_MODEL_DIR}/MbsMediaCompRm.cpp
    ${NEF_MODEL_DIR}/MbsMediaInfo.cpp
    ${NEF_MODEL_DIR}/MbSmfInfo.cpp
    ${NEF_MODEL_DIR}/MbsQoSReq.cpp
    ${NEF_MODEL_DIR}/MbsServiceArea.cpp
    ${NEF_MODEL_DIR}/MbsServiceAreaInfo.cpp
    ${NEF_MODEL_DIR}/MbsServiceInfo.cpp
    ${NEF_MODEL_DIR}/MbsServiceType_anyOf.cpp
    ${NEF_MODEL_DIR}/MbsServiceType.cpp
    ${NEF_MODEL_DIR}/MbsSessionActivityStatus_anyOf.cpp
    ${NEF_MODEL_DIR}/MbsSessionActivityStatus.cpp
    ${NEF_MODEL_DIR}/MbsSession.cpp
    ${NEF_MODEL_DIR}/MbsSessionEvent.cpp
    ${NEF_MODEL_DIR}/MbsSessionEventReport.cpp
    ${NEF_MODEL_DIR}/MbsSessionEventReportList.cpp
    ${NEF_MODEL_DIR}/MbsSessionEventType_anyOf.cpp
    ${NEF_MODEL_DIR}/MbsSessionEventType.cpp
    ${NEF_MODEL_DIR}/MbsSessionId.cpp
    ${NEF_MODEL_DIR}/MbsSessionSubscription.cpp
    ${NEF_MODEL_DIR}/MbUpfInfo.cpp
    ${NEF_MODEL_DIR}/MediaComponent.cpp
    ${NEF_MODEL_DIR}/MediaComponentRm.cpp
    ${NEF_MODEL_DIR}/MediaStreamingAccessRecord_allOf_connectionMetrics.cpp
    ${NEF_MODEL_DIR}/MediaStreamingAccessRecord_allOf_requestMessage.cpp
    ${NEF_MODEL_DIR}/MediaStreamingAccessRecord_allOf_responseMessage.cpp
    ${NEF_MODEL_DIR}/MediaStreamingAccessRecord.cpp
    ${NEF_MODEL_DIR}/MediaSubComponent.cpp
    ${NEF_MODEL_DIR}/MediaSubComponentRm.cpp
    ${NEF_MODEL_DIR}/MediaType_anyOf.cpp
    ${NEF_MODEL_DIR}/MediaType.cpp
    ${NEF_MODEL_DIR}/MfafInfo.cpp
    ${NEF_MODEL_DIR}/MinorLocationQoS.cpp
    ${NEF_MODEL_DIR}/MlAnalyticsInfo.cpp
    ${NEF_MODEL_DIR}/MmTransactionLocationReportItem.cpp
    ${NEF_MODEL_DIR}/MmTransactionSliceReportItem.cpp
    ${NEF_MODEL_DIR}/MnpfInfo.cpp
    ${NEF_MODEL_DIR}/MpsAction_anyOf.cpp
    ${NEF_MODEL_DIR}/MpsAction.cpp
    ${NEF_MODEL_DIR}/MSAccessActivityCollection.cpp
    ${NEF_MODEL_DIR}/MsConsumptionCollection.cpp
    ${NEF_MODEL_DIR}/MsDynPolicyInvocationCollection.cpp
    ${NEF_MODEL_DIR}/MsNetAssInvocationCollection.cpp
    ${NEF_MODEL_DIR}/MsQoeMetricsCollection.cpp
    ${NEF_MODEL_DIR}/MulticastAccessControl_anyOf.cpp
    ${NEF_MODEL_DIR}/MulticastAccessControl.cpp
    ${NEF_MODEL_DIR}/N1MessageClass_anyOf.cpp
    ${NEF_MODEL_DIR}/N1MessageClass.cpp
    ${NEF_MODEL_DIR}/N2InformationClass_anyOf.cpp
    ${NEF_MODEL_DIR}/N2InformationClass.cpp
    ${NEF_MODEL_DIR}/N2InterfaceAmfInfo.cpp
    ${NEF_MODEL_DIR}/N2SmInfoType_anyOf.cpp
    ${NEF_MODEL_DIR}/N2SmInfoType.cpp
    ${NEF_MODEL_DIR}/N3gaLocation.cpp
    ${NEF_MODEL_DIR}/Ncgi.cpp
    ${NEF_MODEL_DIR}/NcgiTai.cpp
    ${NEF_MODEL_DIR}/NefCond.cpp
    ${NEF_MODEL_DIR}/NefEvent_anyOf.cpp
    ${NEF_MODEL_DIR}/NefEvent.cpp
    ${NEF_MODEL_DIR}/NefEventExposureNotif.cpp
    ${NEF_MODEL_DIR}/NefEventExposureSubsc.cpp
    ${NEF_MODEL_DIR}/NefEventFilter.cpp
    ${NEF_MODEL_DIR}/NefEventNotification.cpp
    ${NEF_MODEL_DIR}/NefEventSubs.cpp
    ${NEF_MODEL_DIR}/NefInfo.cpp
    ${NEF_MODEL_DIR}/NetworkAreaInfo.cpp
    ${NEF_MODEL_DIR}/NetworkAssistanceSession.cpp
    ${NEF_MODEL_DIR}/NetworkNodeDiameterAddress.cpp
    ${NEF_MODEL_DIR}/NetworkPerfInfo.cpp
    ${NEF_MODEL_DIR}/NetworkPerfRequirement.cpp
    ${NEF_MODEL_DIR}/NetworkPerfType_anyOf.cpp
    ${NEF_MODEL_DIR}/NetworkPerfType.cpp
    ${NEF_MODEL_DIR}/NetworkSliceCond.cpp
    ${NEF_MODEL_DIR}/NfGroupCond.cpp
    ${NEF_MODEL_DIR}/NfGroupListCond.cpp
    ${NEF_MODEL_DIR}/NfInfo.cpp
    ${NEF_MODEL_DIR}/NfInstanceIdCond.cpp
    ${NEF_MODEL_DIR}/NfInstanceIdListCond.cpp
    ${NEF_MODEL_DIR}/NfInstanceInfo.cpp
    ${NEF_MODEL_DIR}/NfLoadLevelInformation.cpp
    ${NEF_MODEL_DIR}/NFProfile.cpp
    ${NEF_MODEL_DIR}/NFService.cpp
    ${NEF_MODEL_DIR}/NfServiceInstance.cpp
    ${NEF_MODEL_DIR}/NfServiceSetCond.cpp
    ${NEF_MODEL_DIR}/NFServiceStatus.cpp
    ${NEF_MODEL_DIR}/NFServiceVersion.cpp
    ${NEF_MODEL_DIR}/NfSetCond.cpp
    ${NEF_MODEL_DIR}/NFStatus_anyOf.cpp
    ${NEF_MODEL_DIR}/NfStatus.cpp
    ${NEF_MODEL_DIR}/NFStatus.cpp
    ${NEF_MODEL_DIR}/NFType_anyOf.cpp
    ${NEF_MODEL_DIR}/NfTypeCond.cpp
    ${NEF_MODEL_DIR}/NFType.cpp
    ${NEF_MODEL_DIR}/NgApCause.cpp
    ${NEF_MODEL_DIR}/NgRanTargetId.cpp
    ${NEF_MODEL_DIR}/NiddInformation.cpp
    ${NEF_MODEL_DIR}/NoProfileMatchInfo.cpp
    ${NEF_MODEL_DIR}/NoProfileMatchReason_anyOf.cpp
    ${NEF_MODEL_DIR}/NoProfileMatchReason.cpp
    ${NEF_MODEL_DIR}/NotifCondition.cpp
    ${NEF_MODEL_DIR}/NotificationData.cpp
    ${NEF_MODEL_DIR}/NotificationEventType_anyOf.cpp
    ${NEF_MODEL_DIR}/NotificationEventType.cpp
    ${NEF_MODEL_DIR}/NotificationFlag_anyOf.cpp
    ${NEF_MODEL_DIR}/NotificationFlag.cpp
    ${NEF_MODEL_DIR}/NotificationMethod_anyOf.cpp
    ${NEF_MODEL_DIR}/NotificationMethod.cpp
    ${NEF_MODEL_DIR}/NotificationPush.cpp
    ${NEF_MODEL_DIR}/NotificationType_anyOf.cpp
    ${NEF_MODEL_DIR}/NotificationType.cpp
    ${NEF_MODEL_DIR}/NrfInfo.cpp
    ${NEF_MODEL_DIR}/NrfInfo_servedAanfInfoList_value_value.cpp
    ${NEF_MODEL_DIR}/NrfInfo_servedAmfInfo_value.cpp
    ${NEF_MODEL_DIR}/NrfInfo_servedAusfInfo_value.cpp
    ${NEF_MODEL_DIR}/NrfInfo_servedBsfInfo_value.cpp
    ${NEF_MODEL_DIR}/NrfInfo_servedChfInfo_value.cpp
    ${NEF_MODEL_DIR}/NrfInfo_servedGmlcInfo_value.cpp
    ${NEF_MODEL_DIR}/NrfInfo_servedHssInfoList_value_value.cpp
    ${NEF_MODEL_DIR}/NrfInfo_servedLmfInfo_value.cpp
    ${NEF_MODEL_DIR}/NrfInfo_servedMbSmfInfoList_value_value.cpp
    ${NEF_MODEL_DIR}/NrfInfo_servedNefInfo_value.cpp
    ${NEF_MODEL_DIR}/NrfInfo_servedNwdafInfo_value.cpp
    ${NEF_MODEL_DIR}/NrfInfo_servedPcfInfo_value.cpp
    ${NEF_MODEL_DIR}/NrfInfo_servedPcscfInfoList_value_value.cpp
    ${NEF_MODEL_DIR}/NrfInfo_servedScpInfoList_value.cpp
    ${NEF_MODEL_DIR}/NrfInfo_servedSeppInfoList_value.cpp
    ${NEF_MODEL_DIR}/NrfInfo_servedSmfInfo_value.cpp
    ${NEF_MODEL_DIR}/NrfInfo_servedUdmInfo_value.cpp
    ${NEF_MODEL_DIR}/NrfInfo_servedUdrInfo_value.cpp
    ${NEF_MODEL_DIR}/NrfInfo_servedUdsfInfo_value.cpp
    ${NEF_MODEL_DIR}/NrfInfo_servedUpfInfo_value.cpp
    ${NEF_MODEL_DIR}/NrLocation.cpp
    ${NEF_MODEL_DIR}/NsacfCapability.cpp
    ${NEF_MODEL_DIR}/NsacfInfo.cpp
    ${NEF_MODEL_DIR}/NsiIdInfo.cpp
    ${NEF_MODEL_DIR}/NsiLoadLevelInfo.cpp
    ${NEF_MODEL_DIR}/NssaafInfo.cpp
    ${NEF_MODEL_DIR}/NullValue.cpp
    ${NEF_MODEL_DIR}/NumberAverage.cpp
    ${NEF_MODEL_DIR}/NwdafCapability.cpp
    ${NEF_MODEL_DIR}/NwdafCond.cpp
    ${NEF_MODEL_DIR}/NwdafEvent_anyOf.cpp
    ${NEF_MODEL_DIR}/NwdafEvent.cpp
    ${NEF_MODEL_DIR}/NwdafFailureCode_anyOf.cpp
    ${NEF_MODEL_DIR}/NwdafFailureCode.cpp
    ${NEF_MODEL_DIR}/NwdafInfo.cpp
    ${NEF_MODEL_DIR}/ObservedRedundantTransExp.cpp
    ${NEF_MODEL_DIR}/OptionsResponse.cpp
    ${NEF_MODEL_DIR}/OutputStrategy_anyOf.cpp
    ${NEF_MODEL_DIR}/OutputStrategy.cpp
    ${NEF_MODEL_DIR}/PartitioningCriteria_anyOf.cpp
    ${NEF_MODEL_DIR}/PartitioningCriteria.cpp
    ${NEF_MODEL_DIR}/PatchItem.cpp
    ${NEF_MODEL_DIR}/PatchOperation_anyOf.cpp
    ${NEF_MODEL_DIR}/PatchOperation.cpp
    ${NEF_MODEL_DIR}/PcfInfo.cpp
    ${NEF_MODEL_DIR}/PcscfInfo.cpp
    ${NEF_MODEL_DIR}/PduidInformation.cpp
    ${NEF_MODEL_DIR}/PduSessionType_anyOf.cpp
    ${NEF_MODEL_DIR}/PduSessionType.cpp
    ${NEF_MODEL_DIR}/PerfData.cpp
    ${NEF_MODEL_DIR}/PerformanceData.cpp
    ${NEF_MODEL_DIR}/PerformanceDataInfo.cpp
    ${NEF_MODEL_DIR}/PerUeAttribute.cpp
    ${NEF_MODEL_DIR}/PfdChangeNotification.cpp
    ${NEF_MODEL_DIR}/PfdChangeReport.cpp
    ${NEF_MODEL_DIR}/PfdContent.cpp
    ${NEF_MODEL_DIR}/PfdData.cpp
    ${NEF_MODEL_DIR}/PfdDataForApp.cpp
    ${NEF_MODEL_DIR}/PfdOperation_anyOf.cpp
    ${NEF_MODEL_DIR}/PfdOperation.cpp
    ${NEF_MODEL_DIR}/PfdSubscription.cpp
    ${NEF_MODEL_DIR}/PlmnId.cpp
    ${NEF_MODEL_DIR}/PlmnIdNid.cpp
    ${NEF_MODEL_DIR}/PlmnOauth2.cpp
    ${NEF_MODEL_DIR}/PlmnRange.cpp
    ${NEF_MODEL_DIR}/PlmnSnssai.cpp
    ${NEF_MODEL_DIR}/PointAltitude.cpp
    ${NEF_MODEL_DIR}/PointAltitudeUncertainty.cpp
    ${NEF_MODEL_DIR}/Point.cpp
    ${NEF_MODEL_DIR}/PointUncertaintyCircle.cpp
    ${NEF_MODEL_DIR}/PointUncertaintyEllipse.cpp
    ${NEF_MODEL_DIR}/Polygon.cpp
    ${NEF_MODEL_DIR}/PortManagementContainer.cpp
    ${NEF_MODEL_DIR}/PositioningMethod_anyOf.cpp
    ${NEF_MODEL_DIR}/PositioningMethod.cpp
    ${NEF_MODEL_DIR}/PreemptionCapability_anyOf.cpp
    ${NEF_MODEL_DIR}/PreemptionCapability.cpp
    ${NEF_MODEL_DIR}/PreemptionCapabilityRm.cpp
    ${NEF_MODEL_DIR}/PreemptionControlInformation_anyOf.cpp
    ${NEF_MODEL_DIR}/PreemptionControlInformation.cpp
    ${NEF_MODEL_DIR}/PreemptionControlInformationRm.cpp
    ${NEF_MODEL_DIR}/PreemptionVulnerability_anyOf.cpp
    ${NEF_MODEL_DIR}/PreemptionVulnerability.cpp
    ${NEF_MODEL_DIR}/PreemptionVulnerabilityRm.cpp
    ${NEF_MODEL_DIR}/PreferredSearch.cpp
    ${NEF_MODEL_DIR}/PresenceInfo.cpp
    ${NEF_MODEL_DIR}/PresenceState_anyOf.cpp
    ${NEF_MODEL_DIR}/PresenceState.cpp
    ${NEF_MODEL_DIR}/PrioritySharingIndicator_anyOf.cpp
    ${NEF_MODEL_DIR}/PrioritySharingIndicator.cpp
    ${NEF_MODEL_DIR}/ProblemDetails.cpp
    ${NEF_MODEL_DIR}/ProSeCapability.cpp
    ${NEF_MODEL_DIR}/PseudonymIndicator_anyOf.cpp
    ${NEF_MODEL_DIR}/PseudonymIndicator.cpp
    ${NEF_MODEL_DIR}/QosMonitoringInformation.cpp
    ${NEF_MODEL_DIR}/QosMonitoringInformationRm.cpp
    ${NEF_MODEL_DIR}/QosMonitoringReport.cpp
    ${NEF_MODEL_DIR}/QosRequirement.cpp
    ${NEF_MODEL_DIR}/QosResourceType_anyOf.cpp
    ${NEF_MODEL_DIR}/QosResourceType.cpp
    ${NEF_MODEL_DIR}/QosSustainabilityInfo.cpp
    ${NEF_MODEL_DIR}/QueryParamCombination.cpp
    ${NEF_MODEL_DIR}/QueryParameter.cpp
    ${NEF_MODEL_DIR}/r_5GDdnmfInfo.cpp
    ${NEF_MODEL_DIR}/r_5GsUserState.cpp
    ${NEF_MODEL_DIR}/r_5GsUserStateInfo.cpp
    ${NEF_MODEL_DIR}/r_5MbsAuthorizationInfo.cpp
    ${NEF_MODEL_DIR}/RankingCriterion.cpp
    ${NEF_MODEL_DIR}/RatFreqInformation.cpp
    ${NEF_MODEL_DIR}/RatType_anyOf.cpp
    ${NEF_MODEL_DIR}/RatType.cpp
    ${NEF_MODEL_DIR}/ReachabilityFilter_anyOf.cpp
    ${NEF_MODEL_DIR}/ReachabilityFilter.cpp
    ${NEF_MODEL_DIR}/RedirectResponse.cpp
    ${NEF_MODEL_DIR}/RedundantTransmissionExpInfo.cpp
    ${NEF_MODEL_DIR}/RedundantTransmissionExpPerTS.cpp
    ${NEF_MODEL_DIR}/RefToBinaryData.cpp
    ${NEF_MODEL_DIR}/ReleaseCause_anyOf.cpp
    ${NEF_MODEL_DIR}/ReleaseCause.cpp
    ${NEF_MODEL_DIR}/ReportingFrequency_anyOf.cpp
    ${NEF_MODEL_DIR}/ReportingFrequency.cpp
    ${NEF_MODEL_DIR}/ReportingInformation.cpp
    ${NEF_MODEL_DIR}/RequestedQosMonitoringParameter_anyOf.cpp
    ${NEF_MODEL_DIR}/RequestedQosMonitoringParameter.cpp
    ${NEF_MODEL_DIR}/RequestType_anyOf.cpp
    ${NEF_MODEL_DIR}/RequestType.cpp
    ${NEF_MODEL_DIR}/RequiredAccessInfo_anyOf.cpp
    ${NEF_MODEL_DIR}/RequiredAccessInfo.cpp
    ${NEF_MODEL_DIR}/ReservPriority_anyOf.cpp
    ${NEF_MODEL_DIR}/ReservPriority.cpp
    ${NEF_MODEL_DIR}/ResourceUsage.cpp
    ${NEF_MODEL_DIR}/ResponseTime_anyOf.cpp
    ${NEF_MODEL_DIR}/ResponseTime.cpp
    ${NEF_MODEL_DIR}/RetainabilityThreshold.cpp
    ${NEF_MODEL_DIR}/RmInfo.cpp
    ${NEF_MODEL_DIR}/RmState_anyOf.cpp
    ${NEF_MODEL_DIR}/RmState.cpp
    ${NEF_MODEL_DIR}/RouteInformation.cpp
    ${NEF_MODEL_DIR}/RouteSelectionParameterSet.cpp
    ${NEF_MODEL_DIR}/RouteToLocation.cpp
    ${NEF_MODEL_DIR}/RoutingAreaId.cpp
    ${NEF_MODEL_DIR}/SACEventStatus.cpp
    ${NEF_MODEL_DIR}/SACInfo.cpp
    ${NEF_MODEL_DIR}/ScheduledCommunicationTime.cpp
    ${NEF_MODEL_DIR}/ScheduledCommunicationType_anyOf.cpp
    ${NEF_MODEL_DIR}/ScheduledCommunicationType.cpp
    ${NEF_MODEL_DIR}/ScpCapability_anyOf.cpp
    ${NEF_MODEL_DIR}/ScpCapability.cpp
    ${NEF_MODEL_DIR}/ScpDomainCond.cpp
    ${NEF_MODEL_DIR}/ScpDomainConnectivity.cpp
    ${NEF_MODEL_DIR}/ScpDomainInfo.cpp
    ${NEF_MODEL_DIR}/ScpDomainRoutingInfoNotification.cpp
    ${NEF_MODEL_DIR}/ScpDomainRoutingInformation.cpp
    ${NEF_MODEL_DIR}/ScpDomainRoutingInfoSubscription.cpp
    ${NEF_MODEL_DIR}/ScpInfo.cpp
    ${NEF_MODEL_DIR}/SdRange.cpp
    ${NEF_MODEL_DIR}/SearchResult.cpp
    ${NEF_MODEL_DIR}/SeppInfo.cpp
    ${NEF_MODEL_DIR}/ServAuthInfo_anyOf.cpp
    ${NEF_MODEL_DIR}/ServAuthInfo.cpp
    ${NEF_MODEL_DIR}/ServiceAreaCoverageInfo.cpp
    ${NEF_MODEL_DIR}/ServiceAreaId.cpp
    ${NEF_MODEL_DIR}/ServiceDataFlowDescription.cpp
    ${NEF_MODEL_DIR}/ServiceExperienceInfo.cpp
    ${NEF_MODEL_DIR}/ServiceExperienceInfoPerFlow.cpp
    ${NEF_MODEL_DIR}/ServiceExperienceType_anyOf.cpp
    ${NEF_MODEL_DIR}/ServiceExperienceType.cpp
    ${NEF_MODEL_DIR}/ServiceInfoStatus_anyOf.cpp
    ${NEF_MODEL_DIR}/ServiceInfoStatus.cpp
    ${NEF_MODEL_DIR}/ServiceName_anyOf.cpp
    ${NEF_MODEL_DIR}/ServiceNameCond.cpp
    ${NEF_MODEL_DIR}/ServiceName.cpp
    ${NEF_MODEL_DIR}/ServiceNameListCond.cpp
    ${NEF_MODEL_DIR}/ServiceParameterData.cpp
    ${NEF_MODEL_DIR}/ServiceParameterDataPatch.cpp
    ${NEF_MODEL_DIR}/SessInactTimerForUeComm.cpp
    ${NEF_MODEL_DIR}/SharedDataIdRange.cpp
    ${NEF_MODEL_DIR}/SipForkingIndication_anyOf.cpp
    ${NEF_MODEL_DIR}/SipForkingIndication.cpp
    ${NEF_MODEL_DIR}/SliceLoadLevelInformation.cpp
    ${NEF_MODEL_DIR}/SmallDataRateControl.cpp
    ${NEF_MODEL_DIR}/SmallDataRateControlTimeUnit_anyOf.cpp
    ${NEF_MODEL_DIR}/SmallDataRateControlTimeUnit.cpp
    ${NEF_MODEL_DIR}/SmallDataRateStatus.cpp
    ${NEF_MODEL_DIR}/SmcceInfo.cpp
    ${NEF_MODEL_DIR}/SmcceUeList.cpp
    ${NEF_MODEL_DIR}/SmContextConfiguration.cpp
    ${NEF_MODEL_DIR}/SmContextCreateData.cpp
    ${NEF_MODEL_DIR}/SmContextCreatedData.cpp
    ${NEF_MODEL_DIR}/SmContextReleaseData.cpp
    ${NEF_MODEL_DIR}/SmContextReleasedData.cpp
    ${NEF_MODEL_DIR}/SmContextStatus_anyOf.cpp
    ${NEF_MODEL_DIR}/SmContextStatus.cpp
    ${NEF_MODEL_DIR}/SmContextStatusNotification.cpp
    ${NEF_MODEL_DIR}/SmContextUpdateData.cpp
    ${NEF_MODEL_DIR}/SmfInfo.cpp
    ${NEF_MODEL_DIR}/SmsData.cpp
    ${NEF_MODEL_DIR}/SmsDeliveryData.cpp
    ${NEF_MODEL_DIR}/Snssai.cpp
    ${NEF_MODEL_DIR}/SnssaiEasdfInfoItem.cpp
    ${NEF_MODEL_DIR}/SnssaiExtension.cpp
    ${NEF_MODEL_DIR}/SnssaiInfoItem.cpp
    ${NEF_MODEL_DIR}/SnssaiMbSmfInfoItem.cpp
    ${NEF_MODEL_DIR}/SnssaiSmfInfoItem.cpp
    ${NEF_MODEL_DIR}/SnssaiTaiMapping.cpp
    ${NEF_MODEL_DIR}/SnssaiTsctsfInfoItem.cpp
    ${NEF_MODEL_DIR}/SnssaiUpfInfoItem.cpp
    ${NEF_MODEL_DIR}/SpatialValidity.cpp
    ${NEF_MODEL_DIR}/SpatialValidityRm.cpp
    ${NEF_MODEL_DIR}/SponsoringStatus_anyOf.cpp
    ${NEF_MODEL_DIR}/SponsoringStatus.cpp
    ${NEF_MODEL_DIR}/Ssm.cpp
    ${NEF_MODEL_DIR}/StationaryIndication_anyOf.cpp
    ${NEF_MODEL_DIR}/StationaryIndication.cpp
    ${NEF_MODEL_DIR}/StoredSearchResult.cpp
    ${NEF_MODEL_DIR}/StringMatchingCondition.cpp
    ${NEF_MODEL_DIR}/StringMatchingRule.cpp
    ${NEF_MODEL_DIR}/SubscrCond.cpp
    ${NEF_MODEL_DIR}/SubscribedEvent_anyOf.cpp
    ${NEF_MODEL_DIR}/SubscribedEvent.cpp
    ${NEF_MODEL_DIR}/SubscriptionContext.cpp
    ${NEF_MODEL_DIR}/SubscriptionData.cpp
    ${NEF_MODEL_DIR}/SuciInfo.cpp
    ${NEF_MODEL_DIR}/SupiRange.cpp
    ${NEF_MODEL_DIR}/SupportedGADShapes_anyOf.cpp
    ${NEF_MODEL_DIR}/SupportedGADShapes.cpp
    ${NEF_MODEL_DIR}/SupportedSnssai.cpp
    ${NEF_MODEL_DIR}/SvcExperience.cpp
    ${NEF_MODEL_DIR}/TacRange.cpp
    ${NEF_MODEL_DIR}/Tai.cpp
    ${NEF_MODEL_DIR}/TaiRange.cpp
    ${NEF_MODEL_DIR}/TargetArea.cpp
    ${NEF_MODEL_DIR}/TargetUeIdentification.cpp
    ${NEF_MODEL_DIR}/TemporalValidity.cpp
    ${NEF_MODEL_DIR}/ThresholdLevel.cpp
    ${NEF_MODEL_DIR}/TimeUnit_anyOf.cpp
    ${NEF_MODEL_DIR}/TimeUnit.cpp
    ${NEF_MODEL_DIR}/TimeWindow.cpp
    ${NEF_MODEL_DIR}/Tmgi.cpp
    ${NEF_MODEL_DIR}/TmgiRange.cpp
    ${NEF_MODEL_DIR}/TnapId.cpp
    ${NEF_MODEL_DIR}/TngfInfo.cpp
    ${NEF_MODEL_DIR}/TopApplication.cpp
    ${NEF_MODEL_DIR}/TraceData.cpp
    ${NEF_MODEL_DIR}/TraceDepth_anyOf.cpp
    ${NEF_MODEL_DIR}/TraceDepth.cpp
    ${NEF_MODEL_DIR}/TrafficCharacterization.cpp
    ${NEF_MODEL_DIR}/TrafficDescriptorComponents.cpp
    ${NEF_MODEL_DIR}/TrafficDescriptor.cpp
    ${NEF_MODEL_DIR}/TrafficInfluData.cpp
    ${NEF_MODEL_DIR}/TrafficInfluDataPatch.cpp
    ${NEF_MODEL_DIR}/TrafficInfluSub.cpp
    ${NEF_MODEL_DIR}/TrafficInformation.cpp
    ${NEF_MODEL_DIR}/TrafficProfile_anyOf.cpp
    ${NEF_MODEL_DIR}/TrafficProfile.cpp
    ${NEF_MODEL_DIR}/TransferPolicy.cpp
    ${NEF_MODEL_DIR}/TransportProtocol_anyOf.cpp
    ${NEF_MODEL_DIR}/TransportProtocol.cpp
    ${NEF_MODEL_DIR}/TrustAfInfo.cpp
    ${NEF_MODEL_DIR}/TscaiInputContainer.cpp
    ${NEF_MODEL_DIR}/TsctsfInfo.cpp
    ${NEF_MODEL_DIR}/TsnQosContainer.cpp
    ${NEF_MODEL_DIR}/TsnQosContainerRm.cpp
    ${NEF_MODEL_DIR}/TunnelAddress.cpp
    ${NEF_MODEL_DIR}/TwapId.cpp
    ${NEF_MODEL_DIR}/TwifInfo.cpp
    ${NEF_MODEL_DIR}/UcPurpose_anyOf.cpp
    ${NEF_MODEL_DIR}/UcPurpose.cpp
    ${NEF_MODEL_DIR}/UdmInfo.cpp
    ${NEF_MODEL_DIR}/UdrInfo.cpp
    ${NEF_MODEL_DIR}/UdsfInfo.cpp
    ${NEF_MODEL_DIR}/UeAccessBehaviorReportItem.cpp
    ${NEF_MODEL_DIR}/UeCommunication.cpp
    ${NEF_MODEL_DIR}/UeCommunicationInfo.cpp
    ${NEF_MODEL_DIR}/UeContextInfoClass_anyOf.cpp
    ${NEF_MODEL_DIR}/UeContextInfoClass.cpp
    ${NEF_MODEL_DIR}/UEIdExt.cpp
    ${NEF_MODEL_DIR}/UeInAreaFilter.cpp
    ${NEF_MODEL_DIR}/UeLocationTrendsReportItem.cpp
    ${NEF_MODEL_DIR}/UeMobility.cpp
    ${NEF_MODEL_DIR}/UeMobilityInfo.cpp
    ${NEF_MODEL_DIR}/UeReachability_anyOf.cpp
    ${NEF_MODEL_DIR}/UeReachability.cpp
    ${NEF_MODEL_DIR}/UeTrajectoryInfo.cpp
    ${NEF_MODEL_DIR}/UeType_anyOf.cpp
    ${NEF_MODEL_DIR}/UeType.cpp
    ${NEF_MODEL_DIR}/UmtTime.cpp
    ${NEF_MODEL_DIR}/UncertaintyEllipse.cpp
    ${NEF_MODEL_DIR}/UnTrustAfInfo.cpp
    ${NEF_MODEL_DIR}/UpCnxState_anyOf.cpp
    ${NEF_MODEL_DIR}/UpCnxState.cpp
    ${NEF_MODEL_DIR}/UpfCond.cpp
    ${NEF_MODEL_DIR}/UpfInfo.cpp
    ${NEF_MODEL_DIR}/UpfInformation.cpp
    ${NEF_MODEL_DIR}/UPInterfaceType_anyOf.cpp
    ${NEF_MODEL_DIR}/UPInterfaceType.cpp
    ${NEF_MODEL_DIR}/UpPathChgEvent.cpp
    ${NEF_MODEL_DIR}/UriList.cpp
    ${NEF_MODEL_DIR}/UriScheme_anyOf.cpp
    ${NEF_MODEL_DIR}/UriScheme.cpp
    ${NEF_MODEL_DIR}/UrspRuleRequest.cpp
    ${NEF_MODEL_DIR}/UsageThreshold.cpp
    ${NEF_MODEL_DIR}/UsageThresholdRm.cpp
    ${NEF_MODEL_DIR}/UserDataCongestionCollection.cpp
    ${NEF_MODEL_DIR}/UserDataCongestionInfo.cpp
    ${NEF_MODEL_DIR}/UserLocation.cpp
    ${NEF_MODEL_DIR}/UtraLocation.cpp
    ${NEF_MODEL_DIR}/V2xCapability.cpp
    ${NEF_MODEL_DIR}/VelocityEstimate.cpp
    ${NEF_MODEL_DIR}/VelocityRequested_anyOf.cpp
    ${NEF_MODEL_DIR}/VelocityRequested.cpp
    ${NEF_MODEL_DIR}/VendorSpecificFeature.cpp
    ${NEF_MODEL_DIR}/VerticalDirection.cpp
    ${NEF_MODEL_DIR}/WAgfInfo.cpp
    ${NEF_MODEL_DIR}/WlanPerformanceInfo.cpp
    ${NEF_MODEL_DIR}/WlanPerSsIdPerformanceInfo.cpp
    ${NEF_MODEL_DIR}/WlanPerTsPerformanceInfo.cpp
)

## CONFIG used in NF_TARGET (main)
if (TARGET ${NF_TARGET})
    target_include_directories(${NF_TARGET} PUBLIC ${NEF_MODEL_DIR})
    target_sources(${NF_TARGET} PRIVATE
        ${NEF_MODEL_SRC_FILES}
    )
endif()
