/**
* Npcf_PolicyAuthorization Service API
* PCF Policy Authorization Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
*
* The version of the OpenAPI document: 1.2.3
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * NetLocAccessSupport.h
 *
 * Possible values are - ANR_NOT_SUPPORTED: Indicates that the access network does not support the report of access network information. - TZR_NOT_SUPPORTED: Indicates that the access network does not support the report of UE time zone. - LOC_NOT_SUPPORTED: Indicates that the access network does not support the report of UE Location (or PLMN Id). 
 */

#ifndef NetLocAccessSupport_H_
#define NetLocAccessSupport_H_


#include <nlohmann/json.hpp>

namespace oai::model
{

/// <summary>
/// Possible values are - ANR_NOT_SUPPORTED: Indicates that the access network does not support the report of access network information. - TZR_NOT_SUPPORTED: Indicates that the access network does not support the report of UE time zone. - LOC_NOT_SUPPORTED: Indicates that the access network does not support the report of UE Location (or PLMN Id). 
/// </summary>
class  NetLocAccessSupport
{
public:
    NetLocAccessSupport();
    virtual ~NetLocAccessSupport() = default;


    /// <summary>
    /// Validate the current data in the model. Throws a ValidationException on failure.
    /// </summary>
    void validate() const;

    /// <summary>
    /// Validate the current data in the model. Returns false on error and writes an error
    /// message into the given stringstream.
    /// </summary>
    bool validate(std::stringstream& msg) const;

    /// <summary>
    /// Helper overload for validate. Used when one model stores another model and calls it's validate.
    /// Not meant to be called outside that case.
    /// </summary>
    bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

    bool operator==(const NetLocAccessSupport& rhs) const;
    bool operator!=(const NetLocAccessSupport& rhs) const;

    /////////////////////////////////////////////
    /// NetLocAccessSupport members


    friend  void to_json(nlohmann::json& j, const NetLocAccessSupport& o);
    friend  void from_json(const nlohmann::json& j, NetLocAccessSupport& o);
protected:
    
};

} // namespace oai::model

#endif /* NetLocAccessSupport_H_ */
