/**
* Nnef_EventExposure
* NEF Event Exposure Service.   © 2022 , 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
*
* The version of the OpenAPI document: 1.2.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * NetworkAssistanceSession.h
 *
 * A representation of a Network Assistance Session resource.
 */

#ifndef NetworkAssistanceSession_H_
#define NetworkAssistanceSession_H_


#include "M5QoSSpecification.h"
#include <string>
#include "MediaType.h"
#include "ServiceDataFlowDescription.h"
#include <vector>
#include <nlohmann/json.hpp>

namespace oai::model
{

/// <summary>
/// A representation of a Network Assistance Session resource.
/// </summary>
class  NetworkAssistanceSession
{
public:
    NetworkAssistanceSession();
    virtual ~NetworkAssistanceSession() = default;


    /// <summary>
    /// Validate the current data in the model. Throws a ValidationException on failure.
    /// </summary>
    void validate() const;

    /// <summary>
    /// Validate the current data in the model. Returns false on error and writes an error
    /// message into the given stringstream.
    /// </summary>
    bool validate(std::stringstream& msg) const;

    /// <summary>
    /// Helper overload for validate. Used when one model stores another model and calls it's validate.
    /// Not meant to be called outside that case.
    /// </summary>
    bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

    bool operator==(const NetworkAssistanceSession& rhs) const;
    bool operator!=(const NetworkAssistanceSession& rhs) const;

    /////////////////////////////////////////////
    /// NetworkAssistanceSession members

    /// <summary>
    /// String chosen by the 5GMS AF to serve as an identifier in a resource URI.
    /// </summary>
    std::string getNaSessionId() const;
    void setNaSessionId(std::string const& value);
    /// <summary>
    /// String chosen by the 5GMS AF to serve as an identifier in a resource URI.
    /// </summary>
    std::string getProvisioningSessionId() const;
    void setProvisioningSessionId(std::string const& value);
    /// <summary>
    /// 
    /// </summary>
    std::vector<oai::model::ServiceDataFlowDescription> getServiceDataFlowDescriptions() const;
    void setServiceDataFlowDescriptions(std::vector<oai::model::ServiceDataFlowDescription> const& value);
    /// <summary>
    /// 
    /// </summary>
    oai::model::MediaType getMediaType() const;
    void setMediaType(oai::model::MediaType const& value);
    bool mediaTypeIsSet() const;
    void unsetMediaType();
    /// <summary>
    /// String chosen by the 5GMS AF to serve as an identifier in a resource URI.
    /// </summary>
    std::string getPolicyTemplateId() const;
    void setPolicyTemplateId(std::string const& value);
    bool policyTemplateIdIsSet() const;
    void unsetPolicyTemplateId();
    /// <summary>
    /// 
    /// </summary>
    oai::model::M5QoSSpecification getRequestedQoS() const;
    void setRequestedQoS(oai::model::M5QoSSpecification const& value);
    bool requestedQoSIsSet() const;
    void unsetRequestedQoS();
    /// <summary>
    /// 
    /// </summary>
    oai::model::M5QoSSpecification getRecommendedQoS() const;
    void setRecommendedQoS(oai::model::M5QoSSpecification const& value);
    bool recommendedQoSIsSet() const;
    void unsetRecommendedQoS();
    /// <summary>
    /// Absolute Uniform Resource Locator, conforming with the \&quot;absolute-URI\&quot; production specified in IETF RFC 3986, section 4.3 in which the scheme part is \&quot;http\&quot; or \&quot;https\&quot;. Note that the \&quot;query\&quot; suffix is permitted by this production but the \&quot;fragment\&quot; suffix is not.
    /// </summary>
    std::string getNotficationURL() const;
    void setNotficationURL(std::string const& value);
    bool notficationURLIsSet() const;
    void unsetNotficationURL();

    friend  void to_json(nlohmann::json& j, const NetworkAssistanceSession& o);
    friend  void from_json(const nlohmann::json& j, NetworkAssistanceSession& o);
protected:
    std::string m_NaSessionId;

    std::string m_ProvisioningSessionId;

    std::vector<oai::model::ServiceDataFlowDescription> m_ServiceDataFlowDescriptions;

    oai::model::MediaType m_MediaType;
    bool m_MediaTypeIsSet;
    std::string m_PolicyTemplateId;
    bool m_PolicyTemplateIdIsSet;
    oai::model::M5QoSSpecification m_RequestedQoS;
    bool m_RequestedQoSIsSet;
    oai::model::M5QoSSpecification m_RecommendedQoS;
    bool m_RecommendedQoSIsSet;
    std::string m_NotficationURL;
    bool m_NotficationURLIsSet;
    
};

} // namespace oai::model

#endif /* NetworkAssistanceSession_H_ */
