/**
* Namf_MBSBroadcast
* AMF MBSBroadcast Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
*
* The version of the OpenAPI document: 1.0.4
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "NgranFailureEvent.h"
#include "Helpers.h"

#include <sstream>

namespace oai::model
{

NgranFailureEvent::NgranFailureEvent()
{
    
}

void NgranFailureEvent::validate() const
{
    std::stringstream msg;
    if (!validate(msg))
    {
        throw org::openapitools::server::helpers::ValidationException(msg.str());
    }
}

bool NgranFailureEvent::validate(std::stringstream& msg) const
{
    return validate(msg, "");
}

bool NgranFailureEvent::validate(std::stringstream& msg, const std::string& pathPrefix) const
{
    bool success = true;
    const std::string _pathPrefix = pathPrefix.empty() ? "NgranFailureEvent" : pathPrefix;

        
    if (!m_NgranId.validate(msg, _pathPrefix + ".ngranId")) {
        msg << _pathPrefix << ": NgranId is invalid;";
        success = false;
    }    
    if (!m_NgranFailureIndication.validate(msg, _pathPrefix + ".ngranFailureIndication")) {
        msg << _pathPrefix << ": NgranFailureIndication is invalid;";
        success = false;
    }
    return success;
}

bool NgranFailureEvent::operator==(const NgranFailureEvent& rhs) const
{
    return
    
    
    (getNgranId() == rhs.getNgranId())
     &&
    
    (getNgranFailureIndication() == rhs.getNgranFailureIndication())
    
    
    ;
}

bool NgranFailureEvent::operator!=(const NgranFailureEvent& rhs) const
{
    return !(*this == rhs);
}

void to_json(nlohmann::json& j, const NgranFailureEvent& o)
{
    j = nlohmann::json::object();
    j["ngranId"] = o.m_NgranId;
    j["ngranFailureIndication"] = o.m_NgranFailureIndication;
    
}

void from_json(const nlohmann::json& j, NgranFailureEvent& o)
{
    j.at("ngranId").get_to(o.m_NgranId);
    j.at("ngranFailureIndication").get_to(o.m_NgranFailureIndication);
    
}

oai::model::GlobalRanNodeId NgranFailureEvent::getNgranId() const
{
    return m_NgranId;
}
void NgranFailureEvent::setNgranId(oai::model::GlobalRanNodeId const& value)
{
    m_NgranId = value;
}
oai::model::NgranFailureIndication NgranFailureEvent::getNgranFailureIndication() const
{
    return m_NgranFailureIndication;
}
void NgranFailureEvent::setNgranFailureIndication(oai::model::NgranFailureIndication const& value)
{
    m_NgranFailureIndication = value;
}


} // namespace oai::model

