/**
* NRF NFManagement Service
* NRF NFManagement Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
*
* The version of the OpenAPI document: 1.2.7
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "NotificationType.h"
#include "Helpers.h"

#include <sstream>

namespace oai::model
{

NotificationType::NotificationType()
{
    
}

void NotificationType::validate() const
{
    std::stringstream msg;
    if (!validate(msg))
    {
        throw org::openapitools::server::helpers::ValidationException(msg.str());
    }
}

bool NotificationType::validate(std::stringstream& msg) const
{
    return validate(msg, "");
}

bool NotificationType::validate(std::stringstream& msg, const std::string& pathPrefix) const
{
    bool success = true;
    const std::string _pathPrefix = pathPrefix.empty() ? "NotificationType" : pathPrefix;

    
    return success;
}

bool NotificationType::operator==(const NotificationType& rhs) const
{
    return
    
    
    ;
}

bool NotificationType::operator!=(const NotificationType& rhs) const
{
    return !(*this == rhs);
}

void to_json(nlohmann::json& j, const NotificationType& o)
{
    j = nlohmann::json::object();
    
}

void from_json(const nlohmann::json& j, NotificationType& o)
{
    
}



} // namespace oai::model

