################################################################################
#Licensed to the OpenAirInterface(OAI) Software Alliance under one or more
#contributor license agreements.See the NOTICE file distributed with
#this work for additional information regarding copyright ownership.
#The OpenAirInterface Software Alliance licenses this file to You under
#the OAI Public License, Version 1.1(the "License"); you may not use this file
#except in compliance with the License.
#You may obtain a copy of the License at
#
#http:  // www.openairinterface.org/?page_id=698
#
#Unless required by applicable law or agreed to in writing, software
#distributed under the License is distributed on an "AS IS" BASIS,
#WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#See the License for the specific language governing permissions and
#limitations under the License.
#-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -
#For more information about the OpenAirInterface(OAI) Software Alliance:
#contact @openairinterface.org
################################################################################

include(${SRC_TOP_DIR}/${MOUNTED_COMMON}/model/common_model.cmake)

SET(NRF_MODEL_DIR ${SRC_TOP_DIR}/${MOUNTED_COMMON}/model)
set(COMMON_MODEL_DIR ${SRC_TOP_DIR}/${MOUNTED_COMMON}/model)

include_directories(${NRF_MODEL_DIR})

file(GLOB NRF_MODEL_SRC_FILES
        ${NRF_MODEL_DIR}/AccessTokenClaims.cpp
        ${NRF_MODEL_DIR}/AccessTokenRsp.cpp
        ${NRF_MODEL_DIR}/AmfCond.cpp
        ${NRF_MODEL_DIR}/AmfInfo.cpp
        ${NRF_MODEL_DIR}/AusfInfo.cpp
        ${NRF_MODEL_DIR}/BsfInfo.cpp
        ${NRF_MODEL_DIR}/ChfInfo.cpp
        ${NRF_MODEL_DIR}/ChfServiceInfo.cpp
        ${NRF_MODEL_DIR}/DataSetId.cpp
        ${NRF_MODEL_DIR}/DefaultNotificationSubscription.cpp
        ${NRF_MODEL_DIR}/DnnSmfInfoItem.cpp
        ${NRF_MODEL_DIR}/DnnUpfInfoItem.cpp
        ${NRF_MODEL_DIR}/EventId.cpp
        ${NRF_MODEL_DIR}/GuamiListCond.cpp
        ${NRF_MODEL_DIR}/IdentityRange.cpp
        ${NRF_MODEL_DIR}/Inline_response_200.cpp
        ${NRF_MODEL_DIR}/InterfaceUpfInfoItem.cpp
        ${NRF_MODEL_DIR}/IpEndPoint.cpp
        ${NRF_MODEL_DIR}/Ipv4AddressRange.cpp
        ${NRF_MODEL_DIR}/Ipv6PrefixRange.cpp
        ${NRF_MODEL_DIR}/N1MessageClass.cpp
        ${NRF_MODEL_DIR}/N2InformationClass.cpp
        ${NRF_MODEL_DIR}/N2InterfaceAmfInfo.cpp
        ${NRF_MODEL_DIR}/NetworkSliceCond.cpp
        ${NRF_MODEL_DIR}/NfGroupCond.cpp
        ${NRF_MODEL_DIR}/NfInstanceIdCond.cpp
        ${NRF_MODEL_DIR}/NFProfile.cpp
        ${NRF_MODEL_DIR}/NFService.cpp
        ${NRF_MODEL_DIR}/NFServiceStatus.cpp
        ${NRF_MODEL_DIR}/NFServiceVersion.cpp
        ${NRF_MODEL_DIR}/NFStatus.cpp
        ${NRF_MODEL_DIR}/NfTypeCond.cpp
        ${NRF_MODEL_DIR}/NotifCondition.cpp
        ${NRF_MODEL_DIR}/NotificationData.cpp
        ${NRF_MODEL_DIR}/NotificationEventType.cpp
        ${NRF_MODEL_DIR}/NotificationType.cpp
        ${NRF_MODEL_DIR}/NrfInfo.cpp
        ${NRF_MODEL_DIR}/NwdafEvent.cpp
        ${NRF_MODEL_DIR}/NwdafInfo.cpp
        ${NRF_MODEL_DIR}/PcfInfo.cpp
        ${NRF_MODEL_DIR}/PlmnRange.cpp
        ${NRF_MODEL_DIR}/PlmnSnssai.cpp
        ${NRF_MODEL_DIR}/SearchResult.cpp
        ${NRF_MODEL_DIR}/ServiceNameCond.cpp
        ${NRF_MODEL_DIR}/ServiceName.cpp
        ${NRF_MODEL_DIR}/SmfInfo.cpp
        ${NRF_MODEL_DIR}/SnssaiSmfInfoItem.cpp
        ${NRF_MODEL_DIR}/SnssaiUpfInfoItem.cpp
        ${NRF_MODEL_DIR}/StoredSearchResult.cpp
        ${NRF_MODEL_DIR}/SubscriptionData.cpp
        ${NRF_MODEL_DIR}/SupiRange.cpp
        ${NRF_MODEL_DIR}/TacRange.cpp
        ${NRF_MODEL_DIR}/TaiRange.cpp
        ${NRF_MODEL_DIR}/TngfInfo.cpp
        ${NRF_MODEL_DIR}/TwifInfo.cpp
        ${NRF_MODEL_DIR}/UdmInfo.cpp
        ${NRF_MODEL_DIR}/UdrInfo.cpp
        ${NRF_MODEL_DIR}/UpfInfo.cpp
        ${NRF_MODEL_DIR}/UPInterfaceType_anyOf.cpp
        ${NRF_MODEL_DIR}/UPInterfaceType.cpp
        ${NRF_MODEL_DIR}/WAgfInfo.cpp
        ${COMMON_MODEL_DIR}/ProblemDetails.cpp
        ${COMMON_MODEL_DIR}/InvalidParam.cpp
        ${COMMON_MODEL_DIR}/UriScheme.cpp
        ${COMMON_MODEL_DIR}/UriScheme_anyOf.cpp
        ${COMMON_MODEL_DIR}/ChangeItem.cpp
        ${COMMON_MODEL_DIR}/ChangeType.cpp
        ${COMMON_MODEL_DIR}/ChangeType_anyOf.cpp
        ${COMMON_MODEL_DIR}/Tai.cpp
        ${COMMON_MODEL_DIR}/Guami.cpp
        ${COMMON_MODEL_DIR}/PlmnId.cpp
        ${COMMON_MODEL_DIR}/PlmnIdNid.cpp
        ${COMMON_MODEL_DIR}/AccessType.cpp
        ${COMMON_MODEL_DIR}/RatType.cpp
        ${COMMON_MODEL_DIR}/RatType_anyOf.cpp
        ${COMMON_MODEL_DIR}/Snssai.cpp
        ${COMMON_MODEL_DIR}/Helpers.cpp
        ${COMMON_MODEL_DIR}/Ipv6Addr.cpp
        ${COMMON_MODEL_DIR}/Ipv6Prefix.cpp
        ${COMMON_MODEL_DIR}/PduSessionType.cpp
        ${COMMON_MODEL_DIR}/PduSessionType_anyOf.cpp
        ${COMMON_MODEL_DIR}/AtsssCapability.cpp
        ${COMMON_MODEL_DIR}/PatchOperation.cpp
        ${COMMON_MODEL_DIR}/PatchOperation_anyOf.cpp
        ${COMMON_MODEL_DIR}/PatchItem.cpp
        ${COMMON_MODEL_DIR}/AccessTokenErr.cpp
        ${COMMON_MODEL_DIR}/AccessTokenReq.cpp
        ${COMMON_MODEL_DIR}/NFType.cpp
        ${COMMON_MODEL_DIR}/NFType_anyOf.cpp
        ${COMMON_MODEL_DIR}/TransportProtocol.cpp
        ${COMMON_MODEL_DIR}/TransportProtocol_anyOf.cpp
        # dependencies from ComplexQuery
        ${COMMON_MODEL_DIR}/ComplexQuery.cpp
        ${COMMON_MODEL_DIR}/CnfUnit.cpp
        ${COMMON_MODEL_DIR}/DnfUnit.cpp
        ${COMMON_MODEL_DIR}/Atom.cpp  
        ${COMMON_MODEL_DIR}/LinksValueSchema.cpp

        ${COMMON_MODEL_DIR}/AccessTokenClaims_aud.cpp
        ${COMMON_MODEL_DIR}/SuciInfo.cpp
        ${COMMON_MODEL_DIR}/DataSetId_anyOf.cpp
        ${COMMON_MODEL_DIR}/DefSubServiceInfo.cpp
        ${COMMON_MODEL_DIR}/DnnSmfInfoItem_dnn.cpp
        ${COMMON_MODEL_DIR}/DnnSmfInfoItem_dnaiList_inner.cpp
        ${COMMON_MODEL_DIR}/IpIndex.cpp
        ${COMMON_MODEL_DIR}/EventId_anyOf.cpp
        ${COMMON_MODEL_DIR}/TransportProtocol_1.cpp
        ${COMMON_MODEL_DIR}/N1MessageClass_anyOf.cpp
        ${COMMON_MODEL_DIR}/N2InformationClass_anyOf.cpp
        ${COMMON_MODEL_DIR}/NefInfo.cpp
        ${COMMON_MODEL_DIR}/UdsfInfo.cpp
        ${COMMON_MODEL_DIR}/LmfInfo.cpp
        ${COMMON_MODEL_DIR}/GmlcInfo.cpp
        ${COMMON_MODEL_DIR}/ScpInfo.cpp
        ${COMMON_MODEL_DIR}/SeppInfo.cpp
        ${COMMON_MODEL_DIR}/r_5GDdnmfInfo.cpp
        ${COMMON_MODEL_DIR}/MfafInfo.cpp
        ${COMMON_MODEL_DIR}/DccfInfo.cpp
        ${COMMON_MODEL_DIR}/TrustAfInfo.cpp
       ${COMMON_MODEL_DIR}/NssaafInfo.cpp
        ${COMMON_MODEL_DIR}/IwmscInfo.cpp
        ${COMMON_MODEL_DIR}/MnpfInfo.cpp
        ${COMMON_MODEL_DIR}/CollocatedNfInstance.cpp
        ${COMMON_MODEL_DIR}/ExtSnssai.cpp
        ${COMMON_MODEL_DIR}/NefInfo.cpp
        ${COMMON_MODEL_DIR}/r_5GDdnmfInfo.cpp
        ${COMMON_MODEL_DIR}/CollocatedNfType.cpp
        ${COMMON_MODEL_DIR}/SdRange.cpp
        ${COMMON_MODEL_DIR}/ExternalClientType.cpp
        ${COMMON_MODEL_DIR}/AnNodeType.cpp
        ${COMMON_MODEL_DIR}/SupportedGADShapes.cpp
        ${COMMON_MODEL_DIR}/AnNodeType.cpp
        ${COMMON_MODEL_DIR}/HssInfo.cpp
        ${COMMON_MODEL_DIR}/PcscfInfo.cpp
        ${COMMON_MODEL_DIR}/AanfInfo.cpp
        ${COMMON_MODEL_DIR}/EasdfInfo.cpp
        ${COMMON_MODEL_DIR}/NsacfInfo.cpp
        ${COMMON_MODEL_DIR}/MbSmfInfo.cpp
        ${COMMON_MODEL_DIR}/TsctsfInfo.cpp
        ${COMMON_MODEL_DIR}/MbUpfInfo.cpp
        ${COMMON_MODEL_DIR}/PcscfInfo.cpp
        ${COMMON_MODEL_DIR}/HssInfo.cpp
        ${COMMON_MODEL_DIR}/VendorSpecificFeature.cpp
        ${COMMON_MODEL_DIR}/NFStatus_anyOf.cpp
        ${COMMON_MODEL_DIR}/AfEventExposureData.cpp
        ${COMMON_MODEL_DIR}/UnTrustAfInfo.cpp
        ${COMMON_MODEL_DIR}/ConditionEventType.cpp
        ${COMMON_MODEL_DIR}/NotificationEventType_anyOf.cpp
        ${COMMON_MODEL_DIR}/NrfInfo_servedUdrInfo_value.cpp
        ${COMMON_MODEL_DIR}/NfInfo.cpp
        ${COMMON_MODEL_DIR}/NrfInfo_servedUdsfInfo_value.cpp
        ${COMMON_MODEL_DIR}/AfEvent.cpp
        ${COMMON_MODEL_DIR}/AnNodeType_anyOf.cpp
        ${COMMON_MODEL_DIR}/CollocatedNfType_anyOf.cpp
        ${COMMON_MODEL_DIR}/ConditionEventType.cpp
        ${COMMON_MODEL_DIR}/ConditionEventType_anyOf.cpp
        ${COMMON_MODEL_DIR}/SnssaiEasdfInfoItem.cpp
        ${COMMON_MODEL_DIR}/IpAddr.cpp
        ${COMMON_MODEL_DIR}/ExternalClientType_anyOf.cpp
        ${COMMON_MODEL_DIR}/ImsiRange.cpp
        ${COMMON_MODEL_DIR}/TmgiRange.cpp
        ${COMMON_MODEL_DIR}/SnssaiMbSmfInfoItem.cpp
        ${COMMON_MODEL_DIR}/MbSmfInfo.cpp
        ${COMMON_MODEL_DIR}/MbsSession.cpp
        ${COMMON_MODEL_DIR}/PlmnOauth2.cpp
        ${COMMON_MODEL_DIR}/PfdData.cpp
        ${COMMON_MODEL_DIR}/SubscriptionContext.cpp
        ${COMMON_MODEL_DIR}/NotificationType_anyOf.cpp
        ${COMMON_MODEL_DIR}/NrfInfo_servedUdmInfo_value.cpp
        ${COMMON_MODEL_DIR}/NrfInfo_servedAusfInfo_value.cpp
        ${COMMON_MODEL_DIR}/NrfInfo_servedAmfInfo_value.cpp
        ${COMMON_MODEL_DIR}/NrfInfo_servedSmfInfo_value.cpp
        ${COMMON_MODEL_DIR}/NrfInfo_servedUpfInfo_value.cpp
        ${COMMON_MODEL_DIR}/NrfInfo_servedPcfInfo_value.cpp
        ${COMMON_MODEL_DIR}/NrfInfo_servedBsfInfo_value.cpp
        ${COMMON_MODEL_DIR}/NrfInfo_servedChfInfo_value.cpp
        ${COMMON_MODEL_DIR}/NrfInfo_servedNefInfo_value.cpp
        ${COMMON_MODEL_DIR}/NrfInfo_servedNwdafInfo_value.cpp
        ${COMMON_MODEL_DIR}/NrfInfo_servedGmlcInfo_value.cpp
        ${COMMON_MODEL_DIR}/NrfInfo_servedLmfInfo_value.cpp
        ${COMMON_MODEL_DIR}/NrfInfo_servedScpInfoList_value.cpp
        ${COMMON_MODEL_DIR}/NrfInfo_servedSeppInfoList_value.cpp
        ${COMMON_MODEL_DIR}/NrfInfo_servedUdmInfo_value.cpp
        ${COMMON_MODEL_DIR}/AfEvent_anyOf.cpp
        ${COMMON_MODEL_DIR}/MbsSessionId.cpp
        ${COMMON_MODEL_DIR}/Tmgi.cpp
        ${COMMON_MODEL_DIR}/Ssm.cpp
        ${COMMON_MODEL_DIR}/MbsServiceType.cpp
        ${COMMON_MODEL_DIR}/MbsServiceArea.cpp
        ${COMMON_MODEL_DIR}/ExternalMbsServiceArea.cpp
        ${COMMON_MODEL_DIR}/MbsSessionSubscription.cpp
        ${COMMON_MODEL_DIR}/TunnelAddress.cpp
        ${COMMON_MODEL_DIR}/NrfInfo_servedPcscfInfoList_value_value.cpp
        ${COMMON_MODEL_DIR}/NrfInfo_servedHssInfoList_value_value.cpp
        ${COMMON_MODEL_DIR}/NrfInfo_servedAanfInfoList_value_value.cpp
        ${COMMON_MODEL_DIR}/NrfInfo_servedMbSmfInfoList_value_value.cpp
        ${COMMON_MODEL_DIR}/NrfInfo_servedPcscfInfoList_value_value.cpp
        ${COMMON_MODEL_DIR}/NrfInfo_servedHssInfoList_value_value.cpp
        ${COMMON_MODEL_DIR}/NrfInfo_servedAanfInfoList_value_value.cpp
        ${COMMON_MODEL_DIR}/NrfInfo_servedMbSmfInfoList_value_value.cpp
        ${COMMON_MODEL_DIR}/NwdafCapability.cpp
        ${COMMON_MODEL_DIR}/NrfInfo_servedNwdafInfo_value.cpp
        ${COMMON_MODEL_DIR}/MlAnalyticsInfo.cpp
        ${COMMON_MODEL_DIR}/NrfInfo_servedPcfInfo_value.cpp
        ${COMMON_MODEL_DIR}/V2xCapability.cpp
        ${COMMON_MODEL_DIR}/ProSeCapability.cpp
        ${COMMON_MODEL_DIR}/ScpCapability.cpp
        ${COMMON_MODEL_DIR}/IpReachability.cpp
        ${COMMON_MODEL_DIR}/ScpDomainInfo.cpp
        ${COMMON_MODEL_DIR}/InternalGroupIdRange.cpp
        ${COMMON_MODEL_DIR}/SharedDataIdRange.cpp
        ${COMMON_MODEL_DIR}/NsacfCapability.cpp
        ${COMMON_MODEL_DIR}/NwdafEvent_anyOf.cpp
        ${COMMON_MODEL_DIR}/GeographicArea.cpp
        ${COMMON_MODEL_DIR}/CivicAddress.cpp
        ${COMMON_MODEL_DIR}/IpReachability_anyOf.cpp
        ${COMMON_MODEL_DIR}/NcgiTai.cpp
        ${COMMON_MODEL_DIR}/MbsServiceType_anyOf.cpp
        ${COMMON_MODEL_DIR}/MbsServiceInfo.cpp
        ${COMMON_MODEL_DIR}/MbsSessionActivityStatus.cpp
        ${COMMON_MODEL_DIR}/MbsSessionEvent.cpp
        ${COMMON_MODEL_DIR}/ScpCapability_anyOf.cpp
        ${COMMON_MODEL_DIR}/PreferredSearch.cpp
        ${COMMON_MODEL_DIR}/NfInstanceInfo.cpp
        ${COMMON_MODEL_DIR}/ServiceName_anyOf.cpp
        ${COMMON_MODEL_DIR}/DnnEasdfInfoItem.cpp
        ${COMMON_MODEL_DIR}/DnnMbSmfInfoItem.cpp
        ${COMMON_MODEL_DIR}/SupportedGADShapes_anyOf.cpp
        ${COMMON_MODEL_DIR}/TransportProtocol_1_anyOf.cpp
        ${COMMON_MODEL_DIR}/SnssaiInfoItem.cpp
        ${COMMON_MODEL_DIR}/SnssaiTsctsfInfoItem.cpp
        ${COMMON_MODEL_DIR}/MdtUserConsent.cpp
        ${COMMON_MODEL_DIR}/MdtConfiguration.cpp
        ${COMMON_MODEL_DIR}/EcRestrictionDataWb.cpp
        ${COMMON_MODEL_DIR}/ExpectedUeBehaviourData.cpp
        ${COMMON_MODEL_DIR}/WirelineServiceAreaRestriction.cpp
        ${COMMON_MODEL_DIR}/AerialUeSubscriptionInfo.cpp
        ${COMMON_MODEL_DIR}/RoamingRestrictions.cpp
        ${COMMON_MODEL_DIR}/SorUpdateIndicator.cpp
        ${COMMON_MODEL_DIR}/AccessAndMobilitySubscriptionData_subscribedDnnList_inner.cpp
        ${COMMON_MODEL_DIR}/PtwParameters.cpp
        ${COMMON_MODEL_DIR}/WirelineArea.cpp
        ${COMMON_MODEL_DIR}/MdtUserConsent.cpp
        ${COMMON_MODEL_DIR}/TraceData_1.cpp
        ${COMMON_MODEL_DIR}/CagData.cpp
        ${COMMON_MODEL_DIR}/WirelineServiceAreaRestriction.cpp
        ${COMMON_MODEL_DIR}/AerialUeIndication.cpp
        ${COMMON_MODEL_DIR}/CagInfo.cpp
        ${COMMON_MODEL_DIR}/StationaryIndication.cpp
        ${COMMON_MODEL_DIR}/ScheduledCommunicationTime.cpp
        ${COMMON_MODEL_DIR}/ScheduledCommunicationType.cpp
        ${COMMON_MODEL_DIR}/TrafficProfile.cpp
        ${COMMON_MODEL_DIR}/LocationArea.cpp
        ${COMMON_MODEL_DIR}/StationaryIndication.cpp
        ${COMMON_MODEL_DIR}/GeographicalCoordinates.cpp
        ${COMMON_MODEL_DIR}/ReservPriority.cpp
        ${COMMON_MODEL_DIR}/MbsMediaCompRm.cpp
        ${COMMON_MODEL_DIR}/MbsSessionActivityStatus_anyOf.cpp
        ${COMMON_MODEL_DIR}/MbsSessionEventType.cpp
        ${COMMON_MODEL_DIR}/ReportTypeMdt.cpp
        ${COMMON_MODEL_DIR}/AreaScope.cpp
        ${COMMON_MODEL_DIR}/ReportIntervalMdt.cpp
        ${COMMON_MODEL_DIR}/ReportIntervalNrMdt.cpp
        ${COMMON_MODEL_DIR}/ReportAmountMdt.cpp
        ${COMMON_MODEL_DIR}/LoggingIntervalMdt.cpp
        ${COMMON_MODEL_DIR}/LoggingIntervalNrMdt.cpp
        ${COMMON_MODEL_DIR}/LoggingDurationMdt.cpp
        ${COMMON_MODEL_DIR}/LoggingDurationNrMdt.cpp
        ${COMMON_MODEL_DIR}/PositioningMethodMdt.cpp
        ${COMMON_MODEL_DIR}/CollectionPeriodRmmLteMdt.cpp
        ${COMMON_MODEL_DIR}/CollectionPeriodRmmNrMdt.cpp
        ${COMMON_MODEL_DIR}/MeasurementPeriodLteMdt.cpp
        ${COMMON_MODEL_DIR}/SensorMeasurement.cpp
        ${COMMON_MODEL_DIR}/MeasurementLteForMdt.cpp
        ${COMMON_MODEL_DIR}/ReportingTrigger.cpp
        ${COMMON_MODEL_DIR}/EventForMdt.cpp
        ${COMMON_MODEL_DIR}/PositioningMethodMdt.cpp
        ${COMMON_MODEL_DIR}/MbsfnArea.cpp
        ${COMMON_MODEL_DIR}/JobType.cpp
        ${COMMON_MODEL_DIR}/AerialUeIndication_anyOf.cpp
        ${COMMON_MODEL_DIR}/TacInfo.cpp
        ${COMMON_MODEL_DIR}/CollectionPeriodRmmLteMdt_anyOf.cpp
        ${COMMON_MODEL_DIR}/CollectionPeriodRmmNrMdt_anyOf.cpp
	${COMMON_MODEL_DIR}/UncertaintyEllipse.cpp
	${COMMON_MODEL_DIR}/JobType_anyOf.cpp
	${COMMON_MODEL_DIR}/NetworkAreaInfo_1.cpp
	${COMMON_MODEL_DIR}/UmtTime.cpp
	${COMMON_MODEL_DIR}/LoggingDurationMdt_anyOf.cpp
	${COMMON_MODEL_DIR}/LoggingIntervalMdt_anyOf.cpp
	${COMMON_MODEL_DIR}/LoggingIntervalNrMdt_anyOf.cpp
	${COMMON_MODEL_DIR}/MbsMediaInfo.cpp
	${COMMON_MODEL_DIR}/MbsQoSReq.cpp
	${COMMON_MODEL_DIR}/MbsSessionEventType_anyOf.cpp
	${COMMON_MODEL_DIR}/MeasurementNrForMdt.cpp
	${COMMON_MODEL_DIR}/InterFreqTargetInfo.cpp
	${COMMON_MODEL_DIR}/MdtUserConsent_anyOf.cpp
	${COMMON_MODEL_DIR}/MeasurementLteForMdt_anyOf.cpp
	${COMMON_MODEL_DIR}/MeasurementPeriodLteMdt.cpp
	${COMMON_MODEL_DIR}/CollectionPeriodRmmLteMdt_anyOf.cpp
	${COMMON_MODEL_DIR}/Ncgi.cpp
	${COMMON_MODEL_DIR}/PositioningMethodMdt_anyOf.cpp
	${COMMON_MODEL_DIR}/OperationMode.cpp
	${COMMON_MODEL_DIR}/ReportAmountMdt_anyOf.cpp
	${COMMON_MODEL_DIR}/ReportIntervalMdt_anyOf.cpp
	${COMMON_MODEL_DIR}/ReservPriority_anyOf.cpp
	${COMMON_MODEL_DIR}/NrppaInformation.cpp
	${COMMON_MODEL_DIR}/RefToBinaryData.cpp
	${COMMON_MODEL_DIR}/N2InformationTransferReqData.cpp
	${COMMON_MODEL_DIR}/N1N2MessageTransferReqData.cpp
	${COMMON_MODEL_DIR}/N2InfoContent.cpp
	${COMMON_MODEL_DIR}/EventForMdt_anyOf.cpp
	${COMMON_MODEL_DIR}/BatteryIndication.cpp
	${COMMON_MODEL_DIR}/MediaType.cpp
	${COMMON_MODEL_DIR}/N1MessageContainer.cpp
	${COMMON_MODEL_DIR}/AreaOfValidity.cpp
	${COMMON_MODEL_DIR}/NgapIeType.cpp
	${COMMON_MODEL_DIR}/RatSelector.cpp
	${COMMON_MODEL_DIR}/OperationMode_anyOf.cpp
	${COMMON_MODEL_DIR}/ReportingTrigger_anyOf.cpp
	${COMMON_MODEL_DIR}/ScheduledCommunicationType_anyOf.cpp
	${COMMON_MODEL_DIR}/NoProfileMatchInfo.cpp
	${COMMON_MODEL_DIR}/SensorMeasurement_anyOf.cpp
	${COMMON_MODEL_DIR}/DnnInfoItem.cpp
	${COMMON_MODEL_DIR}/DnnTsctsfInfoItem.cpp
	${COMMON_MODEL_DIR}/SorUpdateIndicator_anyOf.cpp
	${COMMON_MODEL_DIR}/StationaryIndication_anyOf.cpp
	${COMMON_MODEL_DIR}/SubscrCond.cpp
	${COMMON_MODEL_DIR}/TrafficProfile_anyOf.cpp
	${COMMON_MODEL_DIR}/ServiceAreaRestriction.cpp
	${COMMON_MODEL_DIR}/PcfSelectionAssistanceInfo.cpp
	${COMMON_MODEL_DIR}/PlmnRestriction.cpp
	${COMMON_MODEL_DIR}/EdrxParameters.cpp
	${COMMON_MODEL_DIR}/PcfSelectionAssistanceInfo.cpp
	${COMMON_MODEL_DIR}/AccessNetworkId_anyOf.cpp
	${COMMON_MODEL_DIR}/AccessTech_anyOf.cpp
	${COMMON_MODEL_DIR}/UeReachableInd.cpp
	${COMMON_MODEL_DIR}/AuthType_anyOf.cpp
	${COMMON_MODEL_DIR}/ServerAddressingInfo.cpp
	${COMMON_MODEL_DIR}/AvType_anyOf.cpp
	${COMMON_MODEL_DIR}/CmInfo.cpp
	${COMMON_MODEL_DIR}/FailedMonitoringConfiguration.cpp
	${COMMON_MODEL_DIR}/DataSetName_anyOf.cpp
	${COMMON_MODEL_DIR}/DeregistrationReason_anyOf.cpp
	${COMMON_MODEL_DIR}/FrameRouteInfo.cpp
	${COMMON_MODEL_DIR}/AcsInfo.cpp
	${COMMON_MODEL_DIR}/EcsAddrConfigInfo.cpp
	${COMMON_MODEL_DIR}/UeId.cpp
	${COMMON_MODEL_DIR}/HssAuthType_anyOf.cpp
	${COMMON_MODEL_DIR}/HssAuthTypeInUri_anyOf.cpp
	${COMMON_MODEL_DIR}/HssAvType_anyOf.cpp
	${COMMON_MODEL_DIR}/HssAvType.cpp
	${COMMON_MODEL_DIR}/HssAvType_anyOf.cpp
	${COMMON_MODEL_DIR}/ImsVoPs_anyOf.cpp
	${COMMON_MODEL_DIR}/NodeType_anyOf.cpp
	${COMMON_MODEL_DIR}/AdditionalSnssaiData.cpp
	${COMMON_MODEL_DIR}/SliceMbrRm.cpp
	${COMMON_MODEL_DIR}/CmState.cpp
	${COMMON_MODEL_DIR}/EcsServerAddr.cpp
	${COMMON_MODEL_DIR}/FailedCause.cpp
	${COMMON_MODEL_DIR}/MediaType_anyOf.cpp
	${COMMON_MODEL_DIR}/N2InfoContainer.cpp
	${COMMON_MODEL_DIR}/GlobalRanNodeId.cpp
	${COMMON_MODEL_DIR}/Ecgi.cpp
	${COMMON_MODEL_DIR}/NgapIeType_anyOf.cpp
	${COMMON_MODEL_DIR}/NoProfileMatchReason.cpp
	${COMMON_MODEL_DIR}/QueryParamCombination.cpp
	${COMMON_MODEL_DIR}/RatSelector_anyOf.cpp
	${COMMON_MODEL_DIR}/ReportIntervalNrMdt_anyOf.cpp
	${COMMON_MODEL_DIR}/ReportTypeMdt_anyOf.cpp
	${COMMON_MODEL_DIR}/UeReachableInd_anyOf.cpp
	${COMMON_MODEL_DIR}/UserLocation.cpp
	${COMMON_MODEL_DIR}/PcscfAddress.cpp
	${COMMON_MODEL_DIR}/PduSessionContinuityInd_anyOf.cpp
	${COMMON_MODEL_DIR}/UeReachability.cpp
	${COMMON_MODEL_DIR}/RegistrationDataSetName_anyOf.cpp
	${COMMON_MODEL_DIR}/RegistrationReason_anyOf.cpp
	${COMMON_MODEL_DIR}/UserLocation.cpp
	${COMMON_MODEL_DIR}/LossOfConnectivityReason.cpp
	${COMMON_MODEL_DIR}/PdnConnectivityStatus.cpp
	${COMMON_MODEL_DIR}/AuthResult.cpp
	${COMMON_MODEL_DIR}/ImmediateReport.cpp
	${COMMON_MODEL_DIR}/SuggestedPacketNumDl.cpp
	${COMMON_MODEL_DIR}/AccessAndMobilitySubscriptionData_1.cpp
	${COMMON_MODEL_DIR}/SmsSubscriptionData_1.cpp
	${COMMON_MODEL_DIR}/SmsManagementSubscriptionData_1.cpp
	${COMMON_MODEL_DIR}/SessionManagementSubscriptionData_1.cpp
	${COMMON_MODEL_DIR}/EcsAddrConfigInfo_1.cpp
	${COMMON_MODEL_DIR}/EcsAddrConfigInfo_1.cpp
	${COMMON_MODEL_DIR}/SqnScheme_anyOf.cpp
	${COMMON_MODEL_DIR}/UeContextInAmfData.cpp
	${COMMON_MODEL_DIR}/SmSubsData.cpp
	${COMMON_MODEL_DIR}/LcsPrivacyData.cpp
	${COMMON_MODEL_DIR}/V2xSubscriptionData.cpp
	${COMMON_MODEL_DIR}/LcsBroadcastAssistanceTypesData.cpp
	${COMMON_MODEL_DIR}/ProseSubscriptionData.cpp
	${COMMON_MODEL_DIR}/MbsSubscriptionData.cpp
	${COMMON_MODEL_DIR}/UcSubscriptionData.cpp
	${COMMON_MODEL_DIR}/UeContextInAmfData.cpp
	${COMMON_MODEL_DIR}/GNbId.cpp
	${COMMON_MODEL_DIR}/UeContext.cpp
	${COMMON_MODEL_DIR}/RegistrationContextContainer.cpp
	${COMMON_MODEL_DIR}/GlobalRanNodeId.cpp
	${COMMON_MODEL_DIR}/UeN1N2InfoSubscriptionCreatedData.cpp
	${COMMON_MODEL_DIR}/NonUeN2InfoSubscriptionCreatedData.cpp
	${COMMON_MODEL_DIR}/UeN1N2InfoSubscriptionCreateData.cpp
	${COMMON_MODEL_DIR}/UEAuthenticationCtx.cpp
	${COMMON_MODEL_DIR}/AuthenticationInfo.cpp
	${COMMON_MODEL_DIR}/ConfirmationDataResponse.cpp
	${COMMON_MODEL_DIR}/AmfEventState.cpp
	${COMMON_MODEL_DIR}/AmfEventReport.cpp
	${COMMON_MODEL_DIR}/AmfEventType.cpp
	${COMMON_MODEL_DIR}/LossOfConnectivityReason.cpp
	${COMMON_MODEL_DIR}/AuthorizedNetworkSliceInfo.cpp

        )
        

## CONFIG used in NF_TARGET (main)
if (TARGET ${NF_TARGET})
    target_include_directories(${NF_TARGET} PUBLIC ${NRF_MODEL_DIR})
    target_sources(${NF_TARGET} PRIVATE
            ${NRF_MODEL_SRC_FILES}
            )
endif()
