################################################################################
#Licensed to the OpenAirInterface(OAI) Software Alliance under one or more
#contributor license agreements.See the NOTICE file distributed with
#this work for additional information regarding copyright ownership.
#The OpenAirInterface Software Alliance licenses this file to You under
#the OAI Public License, Version 1.1(the "License"); you may not use this file
#except in compliance with the License.
#You may obtain a copy of the License at
#
#http:  // www.openairinterface.org/?page_id=698
#
#Unless required by applicable law or agreed to in writing, software
#distributed under the License is distributed on an "AS IS" BASIS,
#WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#See the License for the specific language governing permissions and
#limitations under the License.
#-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -
#For more information about the OpenAirInterface(OAI) Software Alliance:
#contact @openairinterface.org
################################################################################

include(${SRC_TOP_DIR}/${MOUNTED_COMMON}/model/common_model.cmake)

SET(NRF_MODEL_DIR ${SRC_TOP_DIR}/${MOUNTED_COMMON}/model)

include_directories(${NRF_MODEL_DIR})

file(GLOB NRF_MODEL_SRC_FILES
    ${NRF_MODEL_DIR}/AanfInfo.cpp
    ${NRF_MODEL_DIR}/AccessTokenErr.cpp
    ${NRF_MODEL_DIR}/AccessTokenReq.cpp
    ${NRF_MODEL_DIR}/AccessTokenRsp.cpp
    ${NRF_MODEL_DIR}/AccessType.cpp
    ${NRF_MODEL_DIR}/AfEvent.cpp
    ${NRF_MODEL_DIR}/AfEventExposureData.cpp
    ${NRF_MODEL_DIR}/AfEvent_anyOf.cpp
    ${NRF_MODEL_DIR}/AmfCond.cpp
    ${NRF_MODEL_DIR}/AmfInfo.cpp
    ${NRF_MODEL_DIR}/AnNodeType.cpp
    ${NRF_MODEL_DIR}/AnNodeType_anyOf.cpp
    ${NRF_MODEL_DIR}/Atom.cpp
    ${NRF_MODEL_DIR}/AtsssCapability.cpp
    ${NRF_MODEL_DIR}/AusfInfo.cpp
    ${NRF_MODEL_DIR}/BootstrappingInfo.cpp
    ${NRF_MODEL_DIR}/BsfInfo.cpp
    ${NRF_MODEL_DIR}/ChangeItem.cpp
    ${NRF_MODEL_DIR}/ChangeType.cpp
    ${NRF_MODEL_DIR}/ChangeType_anyOf.cpp
    ${NRF_MODEL_DIR}/ChfInfo.cpp
    ${NRF_MODEL_DIR}/Cnf.cpp
    ${NRF_MODEL_DIR}/CnfUnit.cpp
    ${NRF_MODEL_DIR}/CollocatedNfInstance.cpp
    ${NRF_MODEL_DIR}/CollocatedNfType.cpp
    ${NRF_MODEL_DIR}/CollocatedNfType_anyOf.cpp
    ${NRF_MODEL_DIR}/ComplexQuery.cpp
    ${NRF_MODEL_DIR}/ConditionEventType.cpp
    ${NRF_MODEL_DIR}/ConditionEventType_anyOf.cpp
    ${NRF_MODEL_DIR}/DataSetId.cpp
    ${NRF_MODEL_DIR}/DataSetId_anyOf.cpp
    ${NRF_MODEL_DIR}/DccfCond.cpp
    ${NRF_MODEL_DIR}/DccfInfo.cpp
    ${NRF_MODEL_DIR}/DefSubServiceInfo.cpp
    ${NRF_MODEL_DIR}/DefaultNotificationSubscription.cpp
    ${NRF_MODEL_DIR}/Dnf.cpp
    ${NRF_MODEL_DIR}/DnfUnit.cpp
    ${NRF_MODEL_DIR}/DnnEasdfInfoItem.cpp
    ${NRF_MODEL_DIR}/DnnInfoItem.cpp
    ${NRF_MODEL_DIR}/DnnMbSmfInfoItem.cpp
    ${NRF_MODEL_DIR}/DnnSmfInfoItem.cpp
    ${NRF_MODEL_DIR}/DnnSmfInfoItem_dnaiList_inner.cpp
    ${NRF_MODEL_DIR}/DnnSmfInfoItem_dnn.cpp
    ${NRF_MODEL_DIR}/DnnTsctsfInfoItem.cpp
    ${NRF_MODEL_DIR}/DnnUpfInfoItem.cpp
    ${NRF_MODEL_DIR}/EasdfInfo.cpp
    ${NRF_MODEL_DIR}/EventId.cpp
    ${NRF_MODEL_DIR}/EventId_anyOf.cpp
    ${NRF_MODEL_DIR}/ExtSnssai.cpp
    ${NRF_MODEL_DIR}/ExternalClientType.cpp
    ${NRF_MODEL_DIR}/ExternalClientType_anyOf.cpp
    ${NRF_MODEL_DIR}/ExternalMbsServiceArea.cpp
    ${NRF_MODEL_DIR}/GmlcInfo.cpp
    ${NRF_MODEL_DIR}/Guami.cpp
    ${NRF_MODEL_DIR}/GuamiListCond.cpp
    ${NRF_MODEL_DIR}/HssInfo.cpp
    ${NRF_MODEL_DIR}/IdentityRange.cpp
    ${NRF_MODEL_DIR}/ImsiRange.cpp
    ${NRF_MODEL_DIR}/InterfaceUpfInfoItem.cpp
    ${NRF_MODEL_DIR}/InternalGroupIdRange.cpp
    ${NRF_MODEL_DIR}/InvalidParam.cpp
    ${NRF_MODEL_DIR}/IpAddr.cpp
    ${NRF_MODEL_DIR}/IpEndPoint.cpp
    ${NRF_MODEL_DIR}/IpIndex.cpp
    ${NRF_MODEL_DIR}/IpReachability.cpp
    ${NRF_MODEL_DIR}/IpReachability_anyOf.cpp
    ${NRF_MODEL_DIR}/Ipv4AddressRange.cpp
    ${NRF_MODEL_DIR}/Ipv6Addr.cpp
    ${NRF_MODEL_DIR}/Ipv6Prefix.cpp
    ${NRF_MODEL_DIR}/Ipv6PrefixRange.cpp
    ${NRF_MODEL_DIR}/IwmscInfo.cpp
    ${NRF_MODEL_DIR}/Link.cpp
    ${NRF_MODEL_DIR}/LinksValueSchema.cpp
    ${NRF_MODEL_DIR}/LmfInfo.cpp
    ${NRF_MODEL_DIR}/MbSmfInfo.cpp
    ${NRF_MODEL_DIR}/MbUpfInfo.cpp
    ${NRF_MODEL_DIR}/MbsServiceArea.cpp
    ${NRF_MODEL_DIR}/MbsServiceAreaInfo.cpp
    ${NRF_MODEL_DIR}/MbsServiceInfo.cpp
    ${NRF_MODEL_DIR}/MbsServiceType.cpp
    ${NRF_MODEL_DIR}/MbsSession.cpp
    ${NRF_MODEL_DIR}/MbsSessionActivityStatus.cpp
    ${NRF_MODEL_DIR}/MbsSessionId.cpp
    ${NRF_MODEL_DIR}/MbsSessionSubscription.cpp
    ${NRF_MODEL_DIR}/MfafInfo.cpp
    ${NRF_MODEL_DIR}/MlAnalyticsInfo.cpp
    ${NRF_MODEL_DIR}/MnpfInfo.cpp
    ${NRF_MODEL_DIR}/N1MessageClass.cpp
    ${NRF_MODEL_DIR}/N1MessageClass_anyOf.cpp
    ${NRF_MODEL_DIR}/N2InformationClass.cpp
    ${NRF_MODEL_DIR}/N2InformationClass_anyOf.cpp
    ${NRF_MODEL_DIR}/N2InterfaceAmfInfo.cpp
    ${NRF_MODEL_DIR}/NFProfile.cpp
    ${NRF_MODEL_DIR}/NFService.cpp
    ${NRF_MODEL_DIR}/NFServiceStatus.cpp
    ${NRF_MODEL_DIR}/NFServiceVersion.cpp
    ${NRF_MODEL_DIR}/NFStatus.cpp
    ${NRF_MODEL_DIR}/NFStatus_anyOf.cpp
    ${NRF_MODEL_DIR}/NFType.cpp
    ${NRF_MODEL_DIR}/NFType_anyOf.cpp
    ${NRF_MODEL_DIR}/Ncgi.cpp
    ${NRF_MODEL_DIR}/NcgiTai.cpp
    ${NRF_MODEL_DIR}/NefCond.cpp
    ${NRF_MODEL_DIR}/NefInfo.cpp
    ${NRF_MODEL_DIR}/NetworkNodeDiameterAddress.cpp
    ${NRF_MODEL_DIR}/NetworkSliceCond.cpp
    ${NRF_MODEL_DIR}/NfGroupCond.cpp
    ${NRF_MODEL_DIR}/NfGroupListCond.cpp
    ${NRF_MODEL_DIR}/NfInfo.cpp
    ${NRF_MODEL_DIR}/NfInstanceIdCond.cpp
    ${NRF_MODEL_DIR}/NfInstanceIdListCond.cpp
    ${NRF_MODEL_DIR}/NfInstanceInfo.cpp
    ${NRF_MODEL_DIR}/NfServiceInstance.cpp
    ${NRF_MODEL_DIR}/NfServiceSetCond.cpp
    ${NRF_MODEL_DIR}/NfSetCond.cpp
    ${NRF_MODEL_DIR}/NfTypeCond.cpp
    ${NRF_MODEL_DIR}/NoProfileMatchInfo.cpp
    ${NRF_MODEL_DIR}/NoProfileMatchReason.cpp
    ${NRF_MODEL_DIR}/NoProfileMatchReason_anyOf.cpp
    ${NRF_MODEL_DIR}/NotifCondition.cpp
    ${NRF_MODEL_DIR}/NotificationData.cpp
    ${NRF_MODEL_DIR}/NotificationEventType.cpp
    ${NRF_MODEL_DIR}/NotificationEventType_anyOf.cpp
    ${NRF_MODEL_DIR}/NotificationType.cpp
    ${NRF_MODEL_DIR}/NotificationType_anyOf.cpp
    ${NRF_MODEL_DIR}/NrfInfo.cpp
    ${NRF_MODEL_DIR}/NrfInfo_servedAanfInfoList_value_value.cpp
    ${NRF_MODEL_DIR}/NrfInfo_servedAmfInfo_value.cpp
    ${NRF_MODEL_DIR}/NrfInfo_servedAusfInfo_value.cpp
    ${NRF_MODEL_DIR}/NrfInfo_servedBsfInfo_value.cpp
    ${NRF_MODEL_DIR}/NrfInfo_servedChfInfo_value.cpp
    ${NRF_MODEL_DIR}/NrfInfo_servedGmlcInfo_value.cpp
    ${NRF_MODEL_DIR}/NrfInfo_servedHssInfoList_value_value.cpp
    ${NRF_MODEL_DIR}/NrfInfo_servedLmfInfo_value.cpp
    ${NRF_MODEL_DIR}/NrfInfo_servedMbSmfInfoList_value_value.cpp
    ${NRF_MODEL_DIR}/NrfInfo_servedNefInfo_value.cpp
    ${NRF_MODEL_DIR}/NrfInfo_servedNwdafInfo_value.cpp
    ${NRF_MODEL_DIR}/NrfInfo_servedPcfInfo_value.cpp
    ${NRF_MODEL_DIR}/NrfInfo_servedPcscfInfoList_value_value.cpp
    ${NRF_MODEL_DIR}/NrfInfo_servedScpInfoList_value.cpp
    ${NRF_MODEL_DIR}/NrfInfo_servedSeppInfoList_value.cpp
    ${NRF_MODEL_DIR}/NrfInfo_servedSmfInfo_value.cpp
    ${NRF_MODEL_DIR}/NrfInfo_servedUdmInfo_value.cpp
    ${NRF_MODEL_DIR}/NrfInfo_servedUdrInfo_value.cpp
    ${NRF_MODEL_DIR}/NrfInfo_servedUdsfInfo_value.cpp
    ${NRF_MODEL_DIR}/NrfInfo_servedUpfInfo_value.cpp
    ${NRF_MODEL_DIR}/NsacfCapability.cpp
    ${NRF_MODEL_DIR}/NsacfInfo.cpp
    ${NRF_MODEL_DIR}/NssaafInfo.cpp
    ${NRF_MODEL_DIR}/NwdafCapability.cpp
    ${NRF_MODEL_DIR}/NwdafCond.cpp
    ${NRF_MODEL_DIR}/NwdafEvent.cpp
    ${NRF_MODEL_DIR}/NwdafEvent_anyOf.cpp
    ${NRF_MODEL_DIR}/NwdafInfo.cpp
    ${NRF_MODEL_DIR}/OptionsResponse.cpp
    ${NRF_MODEL_DIR}/PatchItem.cpp
    ${NRF_MODEL_DIR}/PatchOperation.cpp
    ${NRF_MODEL_DIR}/PatchOperation_anyOf.cpp
    ${NRF_MODEL_DIR}/PcfInfo.cpp
    ${NRF_MODEL_DIR}/PcscfInfo.cpp
    ${NRF_MODEL_DIR}/PduSessionType.cpp
    ${NRF_MODEL_DIR}/PduSessionType_anyOf.cpp
    ${NRF_MODEL_DIR}/PfdData.cpp
    ${NRF_MODEL_DIR}/PlmnId.cpp
    ${NRF_MODEL_DIR}/PlmnIdNid.cpp
    ${NRF_MODEL_DIR}/PlmnOauth2.cpp
    ${NRF_MODEL_DIR}/PlmnRange.cpp
    ${NRF_MODEL_DIR}/PlmnSnssai.cpp
    ${NRF_MODEL_DIR}/PreferredSearch.cpp
    ${NRF_MODEL_DIR}/ProSeCapability.cpp
    ${NRF_MODEL_DIR}/ProblemDetails.cpp
    ${NRF_MODEL_DIR}/QueryParamCombination.cpp
    ${NRF_MODEL_DIR}/QueryParameter.cpp
    ${NRF_MODEL_DIR}/RatType.cpp
    ${NRF_MODEL_DIR}/RatType_anyOf.cpp
    ${NRF_MODEL_DIR}/RedirectResponse.cpp
    ${NRF_MODEL_DIR}/ScpCapability.cpp
    ${NRF_MODEL_DIR}/ScpCapability_anyOf.cpp
    ${NRF_MODEL_DIR}/ScpDomainCond.cpp
    ${NRF_MODEL_DIR}/ScpDomainConnectivity.cpp
    ${NRF_MODEL_DIR}/ScpDomainInfo.cpp
    ${NRF_MODEL_DIR}/ScpDomainRoutingInfoNotification.cpp
    ${NRF_MODEL_DIR}/ScpDomainRoutingInfoSubscription.cpp
    ${NRF_MODEL_DIR}/ScpDomainRoutingInformation.cpp
    ${NRF_MODEL_DIR}/ScpInfo.cpp
    ${NRF_MODEL_DIR}/SdRange.cpp
    ${NRF_MODEL_DIR}/SearchResult.cpp
    ${NRF_MODEL_DIR}/SeppInfo.cpp
    ${NRF_MODEL_DIR}/ServiceName.cpp
    ${NRF_MODEL_DIR}/ServiceNameCond.cpp
    ${NRF_MODEL_DIR}/ServiceNameListCond.cpp
    ${NRF_MODEL_DIR}/ServiceName_anyOf.cpp
    ${NRF_MODEL_DIR}/SharedDataIdRange.cpp
    ${NRF_MODEL_DIR}/SmfInfo.cpp
    ${NRF_MODEL_DIR}/Snssai.cpp
    ${NRF_MODEL_DIR}/SnssaiEasdfInfoItem.cpp
    ${NRF_MODEL_DIR}/SnssaiExtension.cpp
    ${NRF_MODEL_DIR}/SnssaiInfoItem.cpp
    ${NRF_MODEL_DIR}/SnssaiMbSmfInfoItem.cpp
    ${NRF_MODEL_DIR}/SnssaiSmfInfoItem.cpp
    ${NRF_MODEL_DIR}/SnssaiTsctsfInfoItem.cpp
    ${NRF_MODEL_DIR}/SnssaiUpfInfoItem.cpp
    ${NRF_MODEL_DIR}/Ssm.cpp
    ${NRF_MODEL_DIR}/Status.cpp
    ${NRF_MODEL_DIR}/Status_anyOf.cpp
    ${NRF_MODEL_DIR}/StoredSearchResult.cpp
    ${NRF_MODEL_DIR}/SubscrCond.cpp
    ${NRF_MODEL_DIR}/SubscriptionContext.cpp
    ${NRF_MODEL_DIR}/SubscriptionData.cpp
    ${NRF_MODEL_DIR}/SuciInfo.cpp
    ${NRF_MODEL_DIR}/SupiRange.cpp
    ${NRF_MODEL_DIR}/SupportedGADShapes.cpp
    ${NRF_MODEL_DIR}/SupportedGADShapes_anyOf.cpp
    ${NRF_MODEL_DIR}/TacRange.cpp
    ${NRF_MODEL_DIR}/Tai.cpp
    ${NRF_MODEL_DIR}/TaiRange.cpp
    ${NRF_MODEL_DIR}/Tmgi.cpp
    ${NRF_MODEL_DIR}/TmgiRange.cpp
    ${NRF_MODEL_DIR}/TngfInfo.cpp
    ${NRF_MODEL_DIR}/TransportProtocol.cpp
    ${NRF_MODEL_DIR}/TransportProtocol_anyOf.cpp
    ${NRF_MODEL_DIR}/TrustAfInfo.cpp
    ${NRF_MODEL_DIR}/TsctsfInfo.cpp
    ${NRF_MODEL_DIR}/TunnelAddress.cpp
    ${NRF_MODEL_DIR}/TwifInfo.cpp
    ${NRF_MODEL_DIR}/UPInterfaceType.cpp
    ${NRF_MODEL_DIR}/UPInterfaceType_anyOf.cpp
    ${NRF_MODEL_DIR}/UdmInfo.cpp
    ${NRF_MODEL_DIR}/UdrInfo.cpp
    ${NRF_MODEL_DIR}/UdsfInfo.cpp
    ${NRF_MODEL_DIR}/UnTrustAfInfo.cpp
    ${NRF_MODEL_DIR}/UpfCond.cpp
    ${NRF_MODEL_DIR}/UpfInfo.cpp
    ${NRF_MODEL_DIR}/UriList.cpp
    ${NRF_MODEL_DIR}/UriScheme.cpp
    ${NRF_MODEL_DIR}/UriScheme_anyOf.cpp
    ${NRF_MODEL_DIR}/V2xCapability.cpp
    ${NRF_MODEL_DIR}/VendorSpecificFeature.cpp
    ${NRF_MODEL_DIR}/WAgfInfo.cpp
    ${NRF_MODEL_DIR}/r_5GDdnmfInfo.cpp
)

if (TARGET ${NF_TARGET})
    target_include_directories(${NF_TARGET} PUBLIC ${NRF_MODEL_DIR})
    target_sources(${NF_TARGET} PRIVATE
            ${NRF_MODEL_SRC_FILES}
            )
endif()
