/**
* Nudr_DataRepository API OpenAPI file
* Unified Data Repository Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
*
* The version of the OpenAPI document: 2.2.4
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * Nssai_1.h
 *
 * 
 */

#ifndef Nssai_1_H_
#define Nssai_1_H_


#include "AdditionalSnssaiData_1.h"
#include <string>
#include <map>
#include "Snssai.h"
#include <vector>
#include <nlohmann/json.hpp>

namespace oai::model
{

/// <summary>
/// 
/// </summary>
class  Nssai_1
{
public:
    Nssai_1();
    virtual ~Nssai_1() = default;


    /// <summary>
    /// Validate the current data in the model. Throws a ValidationException on failure.
    /// </summary>
    void validate() const;

    /// <summary>
    /// Validate the current data in the model. Returns false on error and writes an error
    /// message into the given stringstream.
    /// </summary>
    bool validate(std::stringstream& msg) const;

    /// <summary>
    /// Helper overload for validate. Used when one model stores another model and calls it's validate.
    /// Not meant to be called outside that case.
    /// </summary>
    bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

    bool operator==(const Nssai_1& rhs) const;
    bool operator!=(const Nssai_1& rhs) const;

    /////////////////////////////////////////////
    /// Nssai_1 members

    /// <summary>
    /// A string used to indicate the features supported by an API that is used as defined in clause  6.6 in 3GPP TS 29.500. The string shall contain a bitmask indicating supported features in  hexadecimal representation Each character in the string shall take a value of \&quot;0\&quot; to \&quot;9\&quot;,  \&quot;a\&quot; to \&quot;f\&quot; or \&quot;A\&quot; to \&quot;F\&quot; and shall represent the support of 4 features as described in  table 5.2.2-3. The most significant character representing the highest-numbered features shall  appear first in the string, and the character representing features 1 to 4 shall appear last  in the string. The list of features and their numbering (starting with 1) are defined  separately for each API. If the string contains a lower number of characters than there are  defined features for an API, all features that would be represented by characters that are not  present in the string are not supported. 
    /// </summary>
    std::string getSupportedFeatures() const;
    void setSupportedFeatures(std::string const& value);
    bool supportedFeaturesIsSet() const;
    void unsetSupportedFeatures();
    /// <summary>
    /// 
    /// </summary>
    std::vector<oai::model::Snssai> getDefaultSingleNssais() const;
    void setDefaultSingleNssais(std::vector<oai::model::Snssai> const& value);
    /// <summary>
    /// 
    /// </summary>
    std::vector<oai::model::Snssai> getSingleNssais() const;
    void setSingleNssais(std::vector<oai::model::Snssai> const& value);
    bool singleNssaisIsSet() const;
    void unsetSingleNssais();
    /// <summary>
    /// string with format &#39;date-time&#39; as defined in OpenAPI.
    /// </summary>
    std::string getProvisioningTime() const;
    void setProvisioningTime(std::string const& value);
    bool provisioningTimeIsSet() const;
    void unsetProvisioningTime();
    /// <summary>
    /// A map(list of key-value pairs) where singleNssai serves as key of AdditionalSnssaiData
    /// </summary>
    std::map<std::string, oai::model::AdditionalSnssaiData_1> getAdditionalSnssaiData() const;
    void setAdditionalSnssaiData(std::map<std::string, oai::model::AdditionalSnssaiData_1> const& value);
    bool additionalSnssaiDataIsSet() const;
    void unsetAdditionalSnssaiData();
    /// <summary>
    /// 
    /// </summary>
    bool isSuppressNssrgInd() const;
    void setSuppressNssrgInd(bool const value);
    bool suppressNssrgIndIsSet() const;
    void unsetSuppressNssrgInd();

    friend  void to_json(nlohmann::json& j, const Nssai_1& o);
    friend  void from_json(const nlohmann::json& j, Nssai_1& o);
protected:
    std::string m_SupportedFeatures;
    bool m_SupportedFeaturesIsSet;
    std::vector<oai::model::Snssai> m_DefaultSingleNssais;

    std::vector<oai::model::Snssai> m_SingleNssais;
    bool m_SingleNssaisIsSet;
    std::string m_ProvisioningTime;
    bool m_ProvisioningTimeIsSet;
    std::map<std::string, oai::model::AdditionalSnssaiData_1> m_AdditionalSnssaiData;
    bool m_AdditionalSnssaiDataIsSet;
    bool m_SuppressNssrgInd;
    bool m_SuppressNssrgIndIsSet;
    
};

} // namespace oai::model

#endif /* Nssai_1_H_ */
