/**
* Namf_Communication
* AMF Communication Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
*
* The version of the OpenAPI document: 1.2.4
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "NwdafFailureCode.h"
#include "Helpers.h"

#include <sstream>

namespace oai::model
{

NwdafFailureCode::NwdafFailureCode()
{
    
}

void NwdafFailureCode::validate() const
{
    std::stringstream msg;
    if (!validate(msg))
    {
        throw org::openapitools::server::helpers::ValidationException(msg.str());
    }
}

bool NwdafFailureCode::validate(std::stringstream& msg) const
{
    return validate(msg, "");
}

bool NwdafFailureCode::validate(std::stringstream& msg, const std::string& pathPrefix) const
{
    bool success = true;
    const std::string _pathPrefix = pathPrefix.empty() ? "NwdafFailureCode" : pathPrefix;

    
    return success;
}

bool NwdafFailureCode::operator==(const NwdafFailureCode& rhs) const
{
    return
    
    
    ;
}

bool NwdafFailureCode::operator!=(const NwdafFailureCode& rhs) const
{
    return !(*this == rhs);
}

void to_json(nlohmann::json& j, const NwdafFailureCode& o)
{
    j = nlohmann::json::object();
    
}

void from_json(const nlohmann::json& j, NwdafFailureCode& o)
{
    
}



} // namespace oai::model

