/**
* Npcf_BDTPolicyControl Service API
* PCF BDT Policy Control Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
*
* The version of the OpenAPI document: 1.2.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * PatchBdtPolicy.h
 *
 * Describes the updates in authorization data of an Individual BDT Policy created by the PCF. 
 */

#ifndef PatchBdtPolicy_H_
#define PatchBdtPolicy_H_


#include "BdtPolicyDataPatch.h"
#include "BdtReqDataPatch.h"
#include <nlohmann/json.hpp>

namespace oai::model
{

/// <summary>
/// Describes the updates in authorization data of an Individual BDT Policy created by the PCF. 
/// </summary>
class  PatchBdtPolicy
{
public:
    PatchBdtPolicy();
    virtual ~PatchBdtPolicy() = default;


    /// <summary>
    /// Validate the current data in the model. Throws a ValidationException on failure.
    /// </summary>
    void validate() const;

    /// <summary>
    /// Validate the current data in the model. Returns false on error and writes an error
    /// message into the given stringstream.
    /// </summary>
    bool validate(std::stringstream& msg) const;

    /// <summary>
    /// Helper overload for validate. Used when one model stores another model and calls it's validate.
    /// Not meant to be called outside that case.
    /// </summary>
    bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

    bool operator==(const PatchBdtPolicy& rhs) const;
    bool operator!=(const PatchBdtPolicy& rhs) const;

    /////////////////////////////////////////////
    /// PatchBdtPolicy members

    /// <summary>
    /// 
    /// </summary>
    oai::model::BdtPolicyDataPatch getBdtPolData() const;
    void setBdtPolData(oai::model::BdtPolicyDataPatch const& value);
    bool bdtPolDataIsSet() const;
    void unsetBdtPolData();
    /// <summary>
    /// 
    /// </summary>
    oai::model::BdtReqDataPatch getBdtReqData() const;
    void setBdtReqData(oai::model::BdtReqDataPatch const& value);
    bool bdtReqDataIsSet() const;
    void unsetBdtReqData();

    friend  void to_json(nlohmann::json& j, const PatchBdtPolicy& o);
    friend  void from_json(const nlohmann::json& j, PatchBdtPolicy& o);
protected:
    oai::model::BdtPolicyDataPatch m_BdtPolData;
    bool m_BdtPolDataIsSet;
    oai::model::BdtReqDataPatch m_BdtReqData;
    bool m_BdtReqDataIsSet;
    
};

} // namespace oai::model

#endif /* PatchBdtPolicy_H_ */
