# SPDX-License-Identifier: LicenseRef-CSSL-1.0

include(${SRC_TOP_DIR}/${MOUNTED_COMMON}/model/common_model.cmake)

SET(PCF_MODEL_DIR ${SRC_TOP_DIR}/${MOUNTED_COMMON}/model)

include_directories(${PCF_MODEL_DIR})

file(GLOB PCF_MODEL_SRC_FILES
    ${PCF_MODEL_DIR}/AccNetChId.cpp
    ${PCF_MODEL_DIR}/AccNetChargingAddress.cpp
    ${PCF_MODEL_DIR}/AcceptableServiceInfo.cpp
    ${PCF_MODEL_DIR}/AccessNetChargingIdentifier.cpp
    ${PCF_MODEL_DIR}/AccessTokenErr.cpp
    ${PCF_MODEL_DIR}/AccessTokenReq.cpp
    ${PCF_MODEL_DIR}/AccessType.cpp
    ${PCF_MODEL_DIR}/AccessTypeRm.cpp
    ${PCF_MODEL_DIR}/AccuUsageReport.cpp
    ${PCF_MODEL_DIR}/AccumulatedUsage.cpp
    ${PCF_MODEL_DIR}/AdditionalAccessInfo.cpp
    ${PCF_MODEL_DIR}/AfEvent.cpp
    ${PCF_MODEL_DIR}/AfEventNotification.cpp
    ${PCF_MODEL_DIR}/AfEventSubscription.cpp
    ${PCF_MODEL_DIR}/AfEvent_anyOf.cpp
    ${PCF_MODEL_DIR}/AfNotifMethod.cpp
    ${PCF_MODEL_DIR}/AfNotifMethod_anyOf.cpp
    ${PCF_MODEL_DIR}/AfRequestedData.cpp
    ${PCF_MODEL_DIR}/AfRequestedData_anyOf.cpp
    ${PCF_MODEL_DIR}/AfRoutingRequirement.cpp
    ${PCF_MODEL_DIR}/AfRoutingRequirementRm.cpp
    ${PCF_MODEL_DIR}/AfSigProtocol.cpp
    ${PCF_MODEL_DIR}/AfSigProtocol_anyOf.cpp
    ${PCF_MODEL_DIR}/AlternativeServiceRequirementsData.cpp
    ${PCF_MODEL_DIR}/AmRequestedValueRep.cpp
    ${PCF_MODEL_DIR}/Ambr.cpp
    ${PCF_MODEL_DIR}/AnGwAddress.cpp
    ${PCF_MODEL_DIR}/AppDetectionInfo.cpp
    ${PCF_MODEL_DIR}/AppDetectionNotifType.cpp
    ${PCF_MODEL_DIR}/AppDetectionNotifType_anyOf.cpp
    ${PCF_MODEL_DIR}/AppDetectionReport.cpp
    ${PCF_MODEL_DIR}/AppSessionContext.cpp
    ${PCF_MODEL_DIR}/AppSessionContextReqData.cpp
    ${PCF_MODEL_DIR}/AppSessionContextRespData.cpp
    ${PCF_MODEL_DIR}/AppSessionContextUpdateData.cpp
    ${PCF_MODEL_DIR}/AppSessionContextUpdateDataPatch.cpp
    ${PCF_MODEL_DIR}/Area.cpp
    ${PCF_MODEL_DIR}/Arp.cpp
    ${PCF_MODEL_DIR}/AsTimeDistributionParam.cpp
    ${PCF_MODEL_DIR}/AtsssCapability.cpp
    ${PCF_MODEL_DIR}/AuthorizedDefaultQos.cpp
    ${PCF_MODEL_DIR}/BdtPolicy.cpp
    ${PCF_MODEL_DIR}/BdtPolicyData.cpp
    ${PCF_MODEL_DIR}/BdtPolicyDataPatch.cpp
    ${PCF_MODEL_DIR}/BdtReqData.cpp
    ${PCF_MODEL_DIR}/BdtReqDataPatch.cpp
    ${PCF_MODEL_DIR}/BridgeManagementContainer.cpp
    ${PCF_MODEL_DIR}/CandidateForReplacement.cpp
    ${PCF_MODEL_DIR}/CellGlobalId.cpp
    ${PCF_MODEL_DIR}/ChargingData.cpp
    ${PCF_MODEL_DIR}/ChargingInformation.cpp
    ${PCF_MODEL_DIR}/CollectiveBehaviourInfo.cpp
    ${PCF_MODEL_DIR}/ConditionData.cpp
    ${PCF_MODEL_DIR}/CreditManagementStatus.cpp
    ${PCF_MODEL_DIR}/CreditManagementStatus_anyOf.cpp
    ${PCF_MODEL_DIR}/DddTrafficDescriptor.cpp
    ${PCF_MODEL_DIR}/DispersionCollection.cpp
    ${PCF_MODEL_DIR}/DlDataDeliveryStatus.cpp
    ${PCF_MODEL_DIR}/DlDataDeliveryStatus_anyOf.cpp
    ${PCF_MODEL_DIR}/DnaiChangeType.cpp
    ${PCF_MODEL_DIR}/DnaiChangeType_anyOf.cpp
    ${PCF_MODEL_DIR}/DnnSelectionMode.cpp
    ${PCF_MODEL_DIR}/DnnSelectionMode_anyOf.cpp
    ${PCF_MODEL_DIR}/DownlinkDataNotificationControl.cpp
    ${PCF_MODEL_DIR}/DownlinkDataNotificationControlRm.cpp
    ${PCF_MODEL_DIR}/EasIpReplacementInfo.cpp
    ${PCF_MODEL_DIR}/EasServerAddress.cpp
    ${PCF_MODEL_DIR}/Ecgi.cpp
    ${PCF_MODEL_DIR}/ErrorReport.cpp
    ${PCF_MODEL_DIR}/EthFlowDescription.cpp
    ${PCF_MODEL_DIR}/EthernetFlowInfo.cpp
    ${PCF_MODEL_DIR}/EutraLocation.cpp
    ${PCF_MODEL_DIR}/EventsNotification.cpp
    ${PCF_MODEL_DIR}/EventsSubscPutData.cpp
    ${PCF_MODEL_DIR}/EventsSubscReqData.cpp
    ${PCF_MODEL_DIR}/EventsSubscReqDataRm.cpp
    ${PCF_MODEL_DIR}/ExceptionInfo.cpp
    ${PCF_MODEL_DIR}/ExtendedProblemDetails.cpp
    ${PCF_MODEL_DIR}/Failure.cpp
    ${PCF_MODEL_DIR}/FailureCause.cpp
    ${PCF_MODEL_DIR}/FailureCause_anyOf.cpp
    ${PCF_MODEL_DIR}/FailureCode.cpp
    ${PCF_MODEL_DIR}/FailureCode_anyOf.cpp
    ${PCF_MODEL_DIR}/Failure_oneOf.cpp
    ${PCF_MODEL_DIR}/FinalUnitAction.cpp
    ${PCF_MODEL_DIR}/FinalUnitAction_anyOf.cpp
    ${PCF_MODEL_DIR}/FlowDirection.cpp
    ${PCF_MODEL_DIR}/FlowDirectionRm.cpp
    ${PCF_MODEL_DIR}/FlowDirection_anyOf.cpp
    ${PCF_MODEL_DIR}/FlowInformation.cpp
    ${PCF_MODEL_DIR}/FlowStatus.cpp
    ${PCF_MODEL_DIR}/FlowStatus_anyOf.cpp
    ${PCF_MODEL_DIR}/FlowUsage.cpp
    ${PCF_MODEL_DIR}/FlowUsage_anyOf.cpp
    ${PCF_MODEL_DIR}/Flows.cpp
    ${PCF_MODEL_DIR}/GNbId.cpp
    ${PCF_MODEL_DIR}/GeraLocation.cpp
    ${PCF_MODEL_DIR}/GlobalRanNodeId.cpp
    ${PCF_MODEL_DIR}/Guami.cpp
    ${PCF_MODEL_DIR}/HfcNodeId.cpp
    ${PCF_MODEL_DIR}/InvalidParam.cpp
    ${PCF_MODEL_DIR}/IpAddr.cpp
    ${PCF_MODEL_DIR}/IpEndPoint.cpp
    ${PCF_MODEL_DIR}/IpFlowInfo.cpp
    ${PCF_MODEL_DIR}/IpIndex.cpp
    ${PCF_MODEL_DIR}/IpMulticastAddressInfo.cpp
    ${PCF_MODEL_DIR}/Ipv6Addr.cpp
    ${PCF_MODEL_DIR}/Ipv6Prefix.cpp
    ${PCF_MODEL_DIR}/LineType.cpp
    ${PCF_MODEL_DIR}/LineType_anyOf.cpp
    ${PCF_MODEL_DIR}/LocationAreaId.cpp
    ${PCF_MODEL_DIR}/MSAccessActivityCollection.cpp
    ${PCF_MODEL_DIR}/MaPduIndication.cpp
    ${PCF_MODEL_DIR}/MaPduIndication_anyOf.cpp
    ${PCF_MODEL_DIR}/MappingOfSnssai.cpp
    ${PCF_MODEL_DIR}/MediaComponent.cpp
    ${PCF_MODEL_DIR}/MediaComponentResourcesStatus.cpp
    ${PCF_MODEL_DIR}/MediaComponentResourcesStatus_anyOf.cpp
    ${PCF_MODEL_DIR}/MediaComponentRm.cpp
    ${PCF_MODEL_DIR}/MediaSubComponent.cpp
    ${PCF_MODEL_DIR}/MediaSubComponentRm.cpp
    ${PCF_MODEL_DIR}/MediaType.cpp
    ${PCF_MODEL_DIR}/MediaType_anyOf.cpp
    ${PCF_MODEL_DIR}/MeteringMethod.cpp
    ${PCF_MODEL_DIR}/MeteringMethod_anyOf.cpp
    ${PCF_MODEL_DIR}/MpsAction.cpp
    ${PCF_MODEL_DIR}/MpsAction_anyOf.cpp
    ${PCF_MODEL_DIR}/MsConsumptionCollection.cpp
    ${PCF_MODEL_DIR}/MsDynPolicyInvocationCollection.cpp
    ${PCF_MODEL_DIR}/MsNetAssInvocationCollection.cpp
    ${PCF_MODEL_DIR}/MsQoeMetricsCollection.cpp
    ${PCF_MODEL_DIR}/MulticastAccessControl.cpp
    ${PCF_MODEL_DIR}/MulticastAccessControl_anyOf.cpp
    ${PCF_MODEL_DIR}/N3gaLocation.cpp
    ${PCF_MODEL_DIR}/NFType.cpp
    ${PCF_MODEL_DIR}/NFType_anyOf.cpp
    ${PCF_MODEL_DIR}/Ncgi.cpp
    ${PCF_MODEL_DIR}/NetLocAccessSupport.cpp
    ${PCF_MODEL_DIR}/NetLocAccessSupport_anyOf.cpp
    ${PCF_MODEL_DIR}/NetworkAreaInfo.cpp
    ${PCF_MODEL_DIR}/NgApCause.cpp
    ${PCF_MODEL_DIR}/Notification.cpp
    ${PCF_MODEL_DIR}/NotificationControlIndication.cpp
    ${PCF_MODEL_DIR}/NotificationControlIndication_anyOf.cpp
    ${PCF_MODEL_DIR}/NotificationFlag.cpp
    ${PCF_MODEL_DIR}/NotificationFlag_anyOf.cpp
    ${PCF_MODEL_DIR}/NotificationMethod.cpp
    ${PCF_MODEL_DIR}/NotificationMethod_anyOf.cpp
    ${PCF_MODEL_DIR}/NrLocation.cpp
    ${PCF_MODEL_DIR}/NwdafData.cpp
    ${PCF_MODEL_DIR}/NwdafEvent.cpp
    ${PCF_MODEL_DIR}/NwdafEvent_anyOf.cpp
    ${PCF_MODEL_DIR}/OutOfCreditInformation.cpp
    ${PCF_MODEL_DIR}/PacketFilterInfo.cpp
    ${PCF_MODEL_DIR}/PartialSuccessReport.cpp
    ${PCF_MODEL_DIR}/PartitioningCriteria.cpp
    ${PCF_MODEL_DIR}/PartitioningCriteria_anyOf.cpp
    ${PCF_MODEL_DIR}/PatchBdtPolicy.cpp
    ${PCF_MODEL_DIR}/PcEvent.cpp
    ${PCF_MODEL_DIR}/PcEventExposureNotif.cpp
    ${PCF_MODEL_DIR}/PcEventExposureSubsc.cpp
    ${PCF_MODEL_DIR}/PcEventNotification.cpp
    ${PCF_MODEL_DIR}/PcEvent_anyOf.cpp
    ${PCF_MODEL_DIR}/PccRule.cpp
    ${PCF_MODEL_DIR}/PcfAddressingInfo.cpp
    ${PCF_MODEL_DIR}/PcfUeCallbackInfo.cpp
    ${PCF_MODEL_DIR}/PcscfRestorationRequestData.cpp
    ${PCF_MODEL_DIR}/PduSessionEventNotification.cpp
    ${PCF_MODEL_DIR}/PduSessionInfo.cpp
    ${PCF_MODEL_DIR}/PduSessionInformation.cpp
    ${PCF_MODEL_DIR}/PduSessionRelCause.cpp
    ${PCF_MODEL_DIR}/PduSessionRelCause_anyOf.cpp
    ${PCF_MODEL_DIR}/PduSessionStatus.cpp
    ${PCF_MODEL_DIR}/PduSessionStatus_anyOf.cpp
    ${PCF_MODEL_DIR}/PduSessionTsnBridge.cpp
    ${PCF_MODEL_DIR}/PduSessionType.cpp
    ${PCF_MODEL_DIR}/PduSessionType_anyOf.cpp
    ${PCF_MODEL_DIR}/PerformanceDataCollection.cpp
    ${PCF_MODEL_DIR}/PlmnId.cpp
    ${PCF_MODEL_DIR}/PlmnIdNid.cpp
    ${PCF_MODEL_DIR}/PolicyAssociation.cpp
    ${PCF_MODEL_DIR}/PolicyAssociationReleaseCause.cpp
    ${PCF_MODEL_DIR}/PolicyAssociationReleaseCause_anyOf.cpp
    ${PCF_MODEL_DIR}/PolicyAssociationRequest.cpp
    ${PCF_MODEL_DIR}/PolicyAssociationUpdateRequest.cpp
    ${PCF_MODEL_DIR}/PolicyControlRequestTrigger.cpp
    ${PCF_MODEL_DIR}/PolicyControlRequestTrigger_anyOf.cpp
    ${PCF_MODEL_DIR}/PolicyDecisionFailureCode.cpp
    ${PCF_MODEL_DIR}/PolicyDecisionFailureCode_anyOf.cpp
    ${PCF_MODEL_DIR}/PolicyUpdate.cpp
    ${PCF_MODEL_DIR}/PortManagementContainer.cpp
    ${PCF_MODEL_DIR}/PreemptionCapability.cpp
    ${PCF_MODEL_DIR}/PreemptionCapabilityRm.cpp
    ${PCF_MODEL_DIR}/PreemptionCapability_anyOf.cpp
    ${PCF_MODEL_DIR}/PreemptionControlInformation.cpp
    ${PCF_MODEL_DIR}/PreemptionControlInformationRm.cpp
    ${PCF_MODEL_DIR}/PreemptionControlInformation_anyOf.cpp
    ${PCF_MODEL_DIR}/PreemptionVulnerability.cpp
    ${PCF_MODEL_DIR}/PreemptionVulnerabilityRm.cpp
    ${PCF_MODEL_DIR}/PreemptionVulnerability_anyOf.cpp
    ${PCF_MODEL_DIR}/PresenceInfo.cpp
    ${PCF_MODEL_DIR}/PresenceInfoRm.cpp
    ${PCF_MODEL_DIR}/PresenceState.cpp
    ${PCF_MODEL_DIR}/PresenceState_anyOf.cpp
    ${PCF_MODEL_DIR}/PrioritySharingIndicator.cpp
    ${PCF_MODEL_DIR}/PrioritySharingIndicator_anyOf.cpp
    ${PCF_MODEL_DIR}/ProblemDetails.cpp
    ${PCF_MODEL_DIR}/QosCharacteristics.cpp
    ${PCF_MODEL_DIR}/QosData.cpp
    ${PCF_MODEL_DIR}/QosFlowUsage.cpp
    ${PCF_MODEL_DIR}/QosFlowUsage_anyOf.cpp
    ${PCF_MODEL_DIR}/QosMonitoringData.cpp
    ${PCF_MODEL_DIR}/QosMonitoringInformation.cpp
    ${PCF_MODEL_DIR}/QosMonitoringInformationRm.cpp
    ${PCF_MODEL_DIR}/QosMonitoringReport.cpp
    ${PCF_MODEL_DIR}/QosNotifType.cpp
    ${PCF_MODEL_DIR}/QosNotifType_anyOf.cpp
    ${PCF_MODEL_DIR}/QosNotificationControlInfo.cpp
    ${PCF_MODEL_DIR}/QosResourceType.cpp
    ${PCF_MODEL_DIR}/QosResourceType_anyOf.cpp
    ${PCF_MODEL_DIR}/RanNasRelCause.cpp
    ${PCF_MODEL_DIR}/RatType.cpp
    ${PCF_MODEL_DIR}/RatType_anyOf.cpp
    ${PCF_MODEL_DIR}/RedirectAddressType.cpp
    ${PCF_MODEL_DIR}/RedirectAddressType_anyOf.cpp
    ${PCF_MODEL_DIR}/RedirectInformation.cpp
    ${PCF_MODEL_DIR}/RedirectResponse.cpp
    ${PCF_MODEL_DIR}/ReportingFrequency.cpp
    ${PCF_MODEL_DIR}/ReportingFrequency_anyOf.cpp
    ${PCF_MODEL_DIR}/ReportingInformation.cpp
    ${PCF_MODEL_DIR}/ReportingLevel.cpp
    ${PCF_MODEL_DIR}/ReportingLevel_anyOf.cpp
    ${PCF_MODEL_DIR}/RequestTrigger.cpp
    ${PCF_MODEL_DIR}/RequestTrigger_anyOf.cpp
    ${PCF_MODEL_DIR}/RequestedQos.cpp
    ${PCF_MODEL_DIR}/RequestedQosMonitoringParameter.cpp
    ${PCF_MODEL_DIR}/RequestedQosMonitoringParameter_anyOf.cpp
    ${PCF_MODEL_DIR}/RequestedRuleData.cpp
    ${PCF_MODEL_DIR}/RequestedRuleDataType.cpp
    ${PCF_MODEL_DIR}/RequestedRuleDataType_anyOf.cpp
    ${PCF_MODEL_DIR}/RequestedUsageData.cpp
    ${PCF_MODEL_DIR}/RequiredAccessInfo.cpp
    ${PCF_MODEL_DIR}/RequiredAccessInfo_anyOf.cpp
    ${PCF_MODEL_DIR}/ReservPriority.cpp
    ${PCF_MODEL_DIR}/ReservPriority_anyOf.cpp
    ${PCF_MODEL_DIR}/ResourcesAllocationInfo.cpp
    ${PCF_MODEL_DIR}/RestrictionType.cpp
    ${PCF_MODEL_DIR}/RestrictionType_anyOf.cpp
    ${PCF_MODEL_DIR}/RouteInformation.cpp
    ${PCF_MODEL_DIR}/RouteToLocation.cpp
    ${PCF_MODEL_DIR}/RoutingAreaId.cpp
    ${PCF_MODEL_DIR}/RuleOperation.cpp
    ${PCF_MODEL_DIR}/RuleOperation_anyOf.cpp
    ${PCF_MODEL_DIR}/RuleReport.cpp
    ${PCF_MODEL_DIR}/RuleStatus.cpp
    ${PCF_MODEL_DIR}/RuleStatus_anyOf.cpp
    ${PCF_MODEL_DIR}/SatelliteBackhaulCategory.cpp
    ${PCF_MODEL_DIR}/SatelliteBackhaulCategory_anyOf.cpp
    ${PCF_MODEL_DIR}/ServAuthInfo.cpp
    ${PCF_MODEL_DIR}/ServAuthInfo_anyOf.cpp
    ${PCF_MODEL_DIR}/ServerAddressingInfo.cpp
    ${PCF_MODEL_DIR}/ServiceAreaCoverageInfo.cpp
    ${PCF_MODEL_DIR}/ServiceAreaId.cpp
    ${PCF_MODEL_DIR}/ServiceAreaRestriction.cpp
    ${PCF_MODEL_DIR}/ServiceExperienceInfoPerApp.cpp
    ${PCF_MODEL_DIR}/ServiceIdentification.cpp
    ${PCF_MODEL_DIR}/ServiceInfoStatus.cpp
    ${PCF_MODEL_DIR}/ServiceInfoStatus_anyOf.cpp
    ${PCF_MODEL_DIR}/ServiceName.cpp
    ${PCF_MODEL_DIR}/ServiceName_anyOf.cpp
    ${PCF_MODEL_DIR}/ServingNfIdentity.cpp
    ${PCF_MODEL_DIR}/SessionRule.cpp
    ${PCF_MODEL_DIR}/SessionRuleFailureCode.cpp
    ${PCF_MODEL_DIR}/SessionRuleFailureCode_anyOf.cpp
    ${PCF_MODEL_DIR}/SessionRuleReport.cpp
    ${PCF_MODEL_DIR}/SgsnAddress.cpp
    ${PCF_MODEL_DIR}/SipForkingIndication.cpp
    ${PCF_MODEL_DIR}/SipForkingIndication_anyOf.cpp
    ${PCF_MODEL_DIR}/SliceMbr.cpp
    ${PCF_MODEL_DIR}/SmPolicyAssociationReleaseCause.cpp
    ${PCF_MODEL_DIR}/SmPolicyAssociationReleaseCause_anyOf.cpp
    ${PCF_MODEL_DIR}/SmPolicyContextData.cpp
    ${PCF_MODEL_DIR}/SmPolicyControl.cpp
    ${PCF_MODEL_DIR}/SmPolicyDecision.cpp
    ${PCF_MODEL_DIR}/SmPolicyDeleteData.cpp
    ${PCF_MODEL_DIR}/SmPolicyNotification.cpp
    ${PCF_MODEL_DIR}/SmPolicyUpdateContextData.cpp
    ${PCF_MODEL_DIR}/SmfSelectionData.cpp
    ${PCF_MODEL_DIR}/Snssai.cpp
    ${PCF_MODEL_DIR}/SnssaiDnnCombination.cpp
    ${PCF_MODEL_DIR}/SpatialValidity.cpp
    ${PCF_MODEL_DIR}/SpatialValidityRm.cpp
    ${PCF_MODEL_DIR}/SponsoringStatus.cpp
    ${PCF_MODEL_DIR}/SponsoringStatus_anyOf.cpp
    ${PCF_MODEL_DIR}/SteerModeIndicator.cpp
    ${PCF_MODEL_DIR}/SteerModeIndicator_anyOf.cpp
    ${PCF_MODEL_DIR}/SteerModeValue.cpp
    ${PCF_MODEL_DIR}/SteerModeValue_anyOf.cpp
    ${PCF_MODEL_DIR}/SteeringFunctionality.cpp
    ${PCF_MODEL_DIR}/SteeringFunctionality_anyOf.cpp
    ${PCF_MODEL_DIR}/SteeringMode.cpp
    ${PCF_MODEL_DIR}/SubscribedDefaultQos.cpp
    ${PCF_MODEL_DIR}/Tai.cpp
    ${PCF_MODEL_DIR}/TemporalValidity.cpp
    ${PCF_MODEL_DIR}/TerminationCause.cpp
    ${PCF_MODEL_DIR}/TerminationCause_anyOf.cpp
    ${PCF_MODEL_DIR}/TerminationInfo.cpp
    ${PCF_MODEL_DIR}/TerminationNotification.cpp
    ${PCF_MODEL_DIR}/ThresholdValue.cpp
    ${PCF_MODEL_DIR}/TimeWindow.cpp
    ${PCF_MODEL_DIR}/TnapId.cpp
    ${PCF_MODEL_DIR}/TraceData.cpp
    ${PCF_MODEL_DIR}/TraceDepth.cpp
    ${PCF_MODEL_DIR}/TraceDepth_anyOf.cpp
    ${PCF_MODEL_DIR}/TrafficControlData.cpp
    ${PCF_MODEL_DIR}/TrafficDescriptor.cpp
    ${PCF_MODEL_DIR}/TransferPolicy.cpp
    ${PCF_MODEL_DIR}/TransportProtocol.cpp
    ${PCF_MODEL_DIR}/TransportProtocol_anyOf.cpp
    ${PCF_MODEL_DIR}/TscaiInputContainer.cpp
    ${PCF_MODEL_DIR}/TsnBridgeInfo.cpp
    ${PCF_MODEL_DIR}/TsnQosContainer.cpp
    ${PCF_MODEL_DIR}/TsnQosContainerRm.cpp
    ${PCF_MODEL_DIR}/TwapId.cpp
    ${PCF_MODEL_DIR}/UeCampingRep.cpp
    ${PCF_MODEL_DIR}/UeCommunicationCollection.cpp
    ${PCF_MODEL_DIR}/UeIdentityInfo.cpp
    ${PCF_MODEL_DIR}/UeInitiatedResourceRequest.cpp
    ${PCF_MODEL_DIR}/UeMobilityCollection.cpp
    ${PCF_MODEL_DIR}/UeSliceMbr.cpp
    ${PCF_MODEL_DIR}/UpPathChgEvent.cpp
    ${PCF_MODEL_DIR}/UsageMonitoringData.cpp
    ${PCF_MODEL_DIR}/UsageThreshold.cpp
    ${PCF_MODEL_DIR}/UsageThresholdRm.cpp
    ${PCF_MODEL_DIR}/UserDataCongestionCollection.cpp
    ${PCF_MODEL_DIR}/UserLocation.cpp
    ${PCF_MODEL_DIR}/UtraLocation.cpp
    ${PCF_MODEL_DIR}/VplmnQos.cpp
    ${PCF_MODEL_DIR}/WirelineArea.cpp
    ${PCF_MODEL_DIR}/WirelineServiceAreaRestriction.cpp
)

if (TARGET ${NF_TARGET})
    target_include_directories(${NF_TARGET} PUBLIC ${PCF_MODEL_DIR})
    target_sources(${NF_TARGET} PRIVATE
            ${PCF_MODEL_SRC_FILES}
            )
endif()
