/**
* Nudr_DataRepository API OpenAPI file
* Unified Data Repository Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
*
* The version of the OpenAPI document: 2.2.4
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "PduSessionTypes_1.h"
#include "Helpers.h"

#include <sstream>

namespace oai::model
{

PduSessionTypes_1::PduSessionTypes_1()
{
    m_DefaultSessionTypeIsSet = false;
    m_AllowedSessionTypesIsSet = false;
    
}

void PduSessionTypes_1::validate() const
{
    std::stringstream msg;
    if (!validate(msg))
    {
        throw org::openapitools::server::helpers::ValidationException(msg.str());
    }
}

bool PduSessionTypes_1::validate(std::stringstream& msg) const
{
    return validate(msg, "");
}

bool PduSessionTypes_1::validate(std::stringstream& msg, const std::string& pathPrefix) const
{
    bool success = true;
    const std::string _pathPrefix = pathPrefix.empty() ? "PduSessionTypes_1" : pathPrefix;

             
    if (allowedSessionTypesIsSet())
    {
        const std::vector<oai::model::PduSessionType>& value = m_AllowedSessionTypes;
        const std::string currentValuePath = _pathPrefix + ".allowedSessionTypes";
                
        
        if (value.size() < 1)
        {
            success = false;
            msg << currentValuePath << ": must have at least 1 elements;";
        }
        { // Recursive validation of array elements
            const std::string oldValuePath = currentValuePath;
            int i = 0;
            for (const oai::model::PduSessionType& value : value)
            { 
                const std::string currentValuePath = oldValuePath + "[" + std::to_string(i) + "]";
                        
        success = value.validate(msg, currentValuePath + ".allowedSessionTypes") && success;
 
                i++;
            }
        }

    }
    
    return success;
}

bool PduSessionTypes_1::operator==(const PduSessionTypes_1& rhs) const
{
    return
    
    
    
    ((!defaultSessionTypeIsSet() && !rhs.defaultSessionTypeIsSet()) || (defaultSessionTypeIsSet() && rhs.defaultSessionTypeIsSet() && getDefaultSessionType() == rhs.getDefaultSessionType())) &&
    
    
    ((!allowedSessionTypesIsSet() && !rhs.allowedSessionTypesIsSet()) || (allowedSessionTypesIsSet() && rhs.allowedSessionTypesIsSet() && getAllowedSessionTypes() == rhs.getAllowedSessionTypes()))
    
    ;
}

bool PduSessionTypes_1::operator!=(const PduSessionTypes_1& rhs) const
{
    return !(*this == rhs);
}

void to_json(nlohmann::json& j, const PduSessionTypes_1& o)
{
    j = nlohmann::json::object();
    if(o.defaultSessionTypeIsSet())
        j["defaultSessionType"] = o.m_DefaultSessionType;
    if(o.allowedSessionTypesIsSet() || !o.m_AllowedSessionTypes.empty())
        j["allowedSessionTypes"] = o.m_AllowedSessionTypes;
    
}

void from_json(const nlohmann::json& j, PduSessionTypes_1& o)
{
    if(j.find("defaultSessionType") != j.end())
    {
        j.at("defaultSessionType").get_to(o.m_DefaultSessionType);
        o.m_DefaultSessionTypeIsSet = true;
    } 
    if(j.find("allowedSessionTypes") != j.end())
    {
        j.at("allowedSessionTypes").get_to(o.m_AllowedSessionTypes);
        o.m_AllowedSessionTypesIsSet = true;
    } 
    
}

oai::model::PduSessionType PduSessionTypes_1::getDefaultSessionType() const
{
    return m_DefaultSessionType;
}
void PduSessionTypes_1::setDefaultSessionType(oai::model::PduSessionType const& value)
{
    m_DefaultSessionType = value;
    m_DefaultSessionTypeIsSet = true;
}
bool PduSessionTypes_1::defaultSessionTypeIsSet() const
{
    return m_DefaultSessionTypeIsSet;
}
void PduSessionTypes_1::unsetDefaultSessionType()
{
    m_DefaultSessionTypeIsSet = false;
}
std::vector<oai::model::PduSessionType> PduSessionTypes_1::getAllowedSessionTypes() const
{
    return m_AllowedSessionTypes;
}
void PduSessionTypes_1::setAllowedSessionTypes(std::vector<oai::model::PduSessionType> const& value)
{
    m_AllowedSessionTypes = value;
    m_AllowedSessionTypesIsSet = true;
}
bool PduSessionTypes_1::allowedSessionTypesIsSet() const
{
    return m_AllowedSessionTypesIsSet;
}
void PduSessionTypes_1::unsetAllowedSessionTypes()
{
    m_AllowedSessionTypesIsSet = false;
}


} // namespace oai::model

