/**
* Npcf_EventExposure
* PCF Event Exposure Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
*
* The version of the OpenAPI document: 1.2.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "PduSessionInformation.h"
#include "Helpers.h"

#include <sstream>

namespace oai::model
{

PduSessionInformation::PduSessionInformation()
{
    
}

void PduSessionInformation::validate() const
{
    std::stringstream msg;
    if (!validate(msg))
    {
        throw org::openapitools::server::helpers::ValidationException(msg.str());
    }
}

bool PduSessionInformation::validate(std::stringstream& msg) const
{
    return validate(msg, "");
}

bool PduSessionInformation::validate(std::stringstream& msg, const std::string& pathPrefix) const
{
    bool success = true;
    const std::string _pathPrefix = pathPrefix.empty() ? "PduSessionInformation" : pathPrefix;

    
    return success;
}

bool PduSessionInformation::operator==(const PduSessionInformation& rhs) const
{
    return
    
    
    ;
}

bool PduSessionInformation::operator!=(const PduSessionInformation& rhs) const
{
    return !(*this == rhs);
}

void to_json(nlohmann::json& j, const PduSessionInformation& o)
{
    j = nlohmann::json::object();
    
}

void from_json(const nlohmann::json& j, PduSessionInformation& o)
{
    
}



} // namespace oai::model

