/**
* Unified Data Repository Service API file for policy data
* The API version is defined in 3GPP TS 29.504   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
*
* The version of the OpenAPI document: -
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "PlmnRouteSelectionDescriptor.h"
#include "Helpers.h"

#include <sstream>

namespace oai::model
{

PlmnRouteSelectionDescriptor::PlmnRouteSelectionDescriptor()
{
    m_SnssaiRouteSelDescsIsSet = false;
    
}

void PlmnRouteSelectionDescriptor::validate() const
{
    std::stringstream msg;
    if (!validate(msg))
    {
        throw org::openapitools::server::helpers::ValidationException(msg.str());
    }
}

bool PlmnRouteSelectionDescriptor::validate(std::stringstream& msg) const
{
    return validate(msg, "");
}

bool PlmnRouteSelectionDescriptor::validate(std::stringstream& msg, const std::string& pathPrefix) const
{
    bool success = true;
    const std::string _pathPrefix = pathPrefix.empty() ? "PlmnRouteSelectionDescriptor" : pathPrefix;

        
    if (!m_ServingPlmn.validate(msg, _pathPrefix + ".servingPlmn")) {
        msg << _pathPrefix << ": ServingPlmn is invalid;";
        success = false;
    }     
    if (snssaiRouteSelDescsIsSet())
    {
        const std::vector<oai::model::SnssaiRouteSelectionDescriptor>& value = m_SnssaiRouteSelDescs;
        const std::string currentValuePath = _pathPrefix + ".snssaiRouteSelDescs";
                
        
        if (value.size() < 1)
        {
            success = false;
            msg << currentValuePath << ": must have at least 1 elements;";
        }
        { // Recursive validation of array elements
            const std::string oldValuePath = currentValuePath;
            int i = 0;
            for (const oai::model::SnssaiRouteSelectionDescriptor& value : value)
            { 
                const std::string currentValuePath = oldValuePath + "[" + std::to_string(i) + "]";
                        
        success = value.validate(msg, currentValuePath + ".snssaiRouteSelDescs") && success;
 
                i++;
            }
        }

    }
    
    return success;
}

bool PlmnRouteSelectionDescriptor::operator==(const PlmnRouteSelectionDescriptor& rhs) const
{
    return
    
    
    (getServingPlmn() == rhs.getServingPlmn())
     &&
    
    
    ((!snssaiRouteSelDescsIsSet() && !rhs.snssaiRouteSelDescsIsSet()) || (snssaiRouteSelDescsIsSet() && rhs.snssaiRouteSelDescsIsSet() && getSnssaiRouteSelDescs() == rhs.getSnssaiRouteSelDescs()))
    
    ;
}

bool PlmnRouteSelectionDescriptor::operator!=(const PlmnRouteSelectionDescriptor& rhs) const
{
    return !(*this == rhs);
}

void to_json(nlohmann::json& j, const PlmnRouteSelectionDescriptor& o)
{
    j = nlohmann::json::object();
    j["servingPlmn"] = o.m_ServingPlmn;
    if(o.snssaiRouteSelDescsIsSet() || !o.m_SnssaiRouteSelDescs.empty())
        j["snssaiRouteSelDescs"] = o.m_SnssaiRouteSelDescs;
    
}

void from_json(const nlohmann::json& j, PlmnRouteSelectionDescriptor& o)
{
    j.at("servingPlmn").get_to(o.m_ServingPlmn);
    if(j.find("snssaiRouteSelDescs") != j.end())
    {
        j.at("snssaiRouteSelDescs").get_to(o.m_SnssaiRouteSelDescs);
        o.m_SnssaiRouteSelDescsIsSet = true;
    } 
    
}

oai::model::PlmnId PlmnRouteSelectionDescriptor::getServingPlmn() const
{
    return m_ServingPlmn;
}
void PlmnRouteSelectionDescriptor::setServingPlmn(oai::model::PlmnId const& value)
{
    m_ServingPlmn = value;
}
std::vector<oai::model::SnssaiRouteSelectionDescriptor> PlmnRouteSelectionDescriptor::getSnssaiRouteSelDescs() const
{
    return m_SnssaiRouteSelDescs;
}
void PlmnRouteSelectionDescriptor::setSnssaiRouteSelDescs(std::vector<oai::model::SnssaiRouteSelectionDescriptor> const& value)
{
    m_SnssaiRouteSelDescs = value;
    m_SnssaiRouteSelDescsIsSet = true;
}
bool PlmnRouteSelectionDescriptor::snssaiRouteSelDescsIsSet() const
{
    return m_SnssaiRouteSelDescsIsSet;
}
void PlmnRouteSelectionDescriptor::unsetSnssaiRouteSelDescs()
{
    m_SnssaiRouteSelDescsIsSet = false;
}


} // namespace oai::model

