/**
* Common Data Types
* Common Data Types for Service Based Interfaces.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.   
*
* The version of the OpenAPI document: 1.4.4
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * PreemptionCapability.h
 *
 * The enumeration PreemptionCapability indicates the pre-emption capability of a request on other QoS flows. See clause 5.7.2.2 of 3GPP TS 23.501. It shall comply with the provisions defined in table 5.5.3.1-1. 
 */

#ifndef PreemptionCapability_H_
#define PreemptionCapability_H_


#include <nlohmann/json.hpp>

namespace oai::model
{

/// <summary>
/// The enumeration PreemptionCapability indicates the pre-emption capability of a request on other QoS flows. See clause 5.7.2.2 of 3GPP TS 23.501. It shall comply with the provisions defined in table 5.5.3.1-1. 
/// </summary>
class  PreemptionCapability
{
public:
    PreemptionCapability();
    virtual ~PreemptionCapability() = default;


    /// <summary>
    /// Validate the current data in the model. Throws a ValidationException on failure.
    /// </summary>
    void validate() const;

    /// <summary>
    /// Validate the current data in the model. Returns false on error and writes an error
    /// message into the given stringstream.
    /// </summary>
    bool validate(std::stringstream& msg) const;

    /// <summary>
    /// Helper overload for validate. Used when one model stores another model and calls it's validate.
    /// Not meant to be called outside that case.
    /// </summary>
    bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

    bool operator==(const PreemptionCapability& rhs) const;
    bool operator!=(const PreemptionCapability& rhs) const;

    /////////////////////////////////////////////
    /// PreemptionCapability members


    friend  void to_json(nlohmann::json& j, const PreemptionCapability& o);
    friend  void from_json(const nlohmann::json& j, PreemptionCapability& o);
protected:
    
};

} // namespace oai::model

#endif /* PreemptionCapability_H_ */
