/**
* Nudr_DataRepository API OpenAPI file
* Unified Data Repository Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
*
* The version of the OpenAPI document: 2.2.4
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "RegistrationReason.h"
#include "Helpers.h"

#include <sstream>

namespace oai::model
{

RegistrationReason::RegistrationReason()
{
    
}

void RegistrationReason::validate() const
{
    std::stringstream msg;
    if (!validate(msg))
    {
        throw org::openapitools::server::helpers::ValidationException(msg.str());
    }
}

bool RegistrationReason::validate(std::stringstream& msg) const
{
    return validate(msg, "");
}

bool RegistrationReason::validate(std::stringstream& msg, const std::string& pathPrefix) const
{
    bool success = true;
    const std::string _pathPrefix = pathPrefix.empty() ? "RegistrationReason" : pathPrefix;

    
    return success;
}

bool RegistrationReason::operator==(const RegistrationReason& rhs) const
{
    return
    
    
    ;
}

bool RegistrationReason::operator!=(const RegistrationReason& rhs) const
{
    return !(*this == rhs);
}

void to_json(nlohmann::json& j, const RegistrationReason& o)
{
    j = nlohmann::json::object();
    
}

void from_json(const nlohmann::json& j, RegistrationReason& o)
{
    
}



} // namespace oai::model

