/**
* Npcf_AMPolicyControl
* Access and Mobility Policy Control Service.   © 2025, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
*
* The version of the OpenAPI document: 1.2.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "RequestTrigger.h"
#include "Helpers.h"

#include <sstream>

namespace oai::model
{

RequestTrigger::RequestTrigger()
{
    
}

void RequestTrigger::validate() const
{
    std::stringstream msg;
    if (!validate(msg))
    {
        throw org::openapitools::server::helpers::ValidationException(msg.str());
    }
}

bool RequestTrigger::validate(std::stringstream& msg) const
{
    return validate(msg, "");
}

bool RequestTrigger::validate(std::stringstream& msg, const std::string& pathPrefix) const
{
    bool success = true;
    const std::string _pathPrefix = pathPrefix.empty() ? "RequestTrigger" : pathPrefix;

    
    return success;
}

bool RequestTrigger::operator==(const RequestTrigger& rhs) const
{
    return
    
    
    ;
}

bool RequestTrigger::operator!=(const RequestTrigger& rhs) const
{
    return !(*this == rhs);
}

void to_json(nlohmann::json& j, const RequestTrigger& o)
{
    j = nlohmann::json::object();
    
}

void from_json(const nlohmann::json& j, RequestTrigger& o)
{
    
}



} // namespace oai::model

