/**
* Npcf_SMPolicyControl API
* Session Management Policy Control Service   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
*
* The version of the OpenAPI document: 1.2.4
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "RequestedRuleDataType.h"
#include "Helpers.h"

#include <sstream>

namespace oai::model
{

RequestedRuleDataType::RequestedRuleDataType()
{
    
}

void RequestedRuleDataType::validate() const
{
    std::stringstream msg;
    if (!validate(msg))
    {
        throw org::openapitools::server::helpers::ValidationException(msg.str());
    }
}

bool RequestedRuleDataType::validate(std::stringstream& msg) const
{
    return validate(msg, "");
}

bool RequestedRuleDataType::validate(std::stringstream& msg, const std::string& pathPrefix) const
{
    bool success = true;
    const std::string _pathPrefix = pathPrefix.empty() ? "RequestedRuleDataType" : pathPrefix;

    
    return success;
}

bool RequestedRuleDataType::operator==(const RequestedRuleDataType& rhs) const
{
    return
    
    
    ;
}

bool RequestedRuleDataType::operator!=(const RequestedRuleDataType& rhs) const
{
    return !(*this == rhs);
}

void to_json(nlohmann::json& j, const RequestedRuleDataType& o)
{
    j = nlohmann::json::object();
    
}

void from_json(const nlohmann::json& j, RequestedRuleDataType& o)
{
    
}



} // namespace oai::model

