/**
* Unified Data Repository Service API file for structured data for exposure
* The API version is defined in 3GPP TS 29.504   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
*
* The version of the OpenAPI document: -
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * RmInfo.h
 *
 * Represents the registration state of a UE for an access type
 */

#ifndef RmInfo_H_
#define RmInfo_H_


#include "RmState.h"
#include "AccessType.h"
#include <nlohmann/json.hpp>

namespace oai::model
{

/// <summary>
/// Represents the registration state of a UE for an access type
/// </summary>
class  RmInfo
{
public:
    RmInfo();
    virtual ~RmInfo() = default;


    /// <summary>
    /// Validate the current data in the model. Throws a ValidationException on failure.
    /// </summary>
    void validate() const;

    /// <summary>
    /// Validate the current data in the model. Returns false on error and writes an error
    /// message into the given stringstream.
    /// </summary>
    bool validate(std::stringstream& msg) const;

    /// <summary>
    /// Helper overload for validate. Used when one model stores another model and calls it's validate.
    /// Not meant to be called outside that case.
    /// </summary>
    bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

    bool operator==(const RmInfo& rhs) const;
    bool operator!=(const RmInfo& rhs) const;

    /////////////////////////////////////////////
    /// RmInfo members

    /// <summary>
    /// 
    /// </summary>
    oai::model::RmState getRmState() const;
    void setRmState(oai::model::RmState const& value);
    /// <summary>
    /// 
    /// </summary>
    oai::model::AccessType getAccessType() const;
    void setAccessType(oai::model::AccessType const& value);

    friend  void to_json(nlohmann::json& j, const RmInfo& o);
    friend  void from_json(const nlohmann::json& j, RmInfo& o);
protected:
    oai::model::RmState m_RmState;

    oai::model::AccessType m_AccessType;

    
};

} // namespace oai::model

#endif /* RmInfo_H_ */
