/**
 * Nudr_DataRepository API OpenAPI file
 * Unified Data Repository Service.   © 2023, 3GPP Organizational Partners
 * (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * The version of the OpenAPI document: 2.2.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * SharedData.h
 *
 *
 */

#ifndef SharedData_H_
#define SharedData_H_

#include "EcsAddrConfigInfo_1.h"
#include "SessionManagementSubscriptionData_1.h"
#include "VnGroupData.h"
#include "SmsManagementSubscriptionData_1.h"
#include "DnnConfiguration_1.h"
#include <string>
#include "SmsSubscriptionData_1.h"
#include "SnssaiInfo.h"
#include "SharedDataTreatmentInstruction.h"
#include <map>
#include "TraceData.h"
#include "AccessAndMobilitySubscriptionData_1.h"
#include <nlohmann/json.hpp>

namespace oai::_3gpp::model {

/// <summary>
///
/// </summary>
class SharedData {
 public:
  SharedData();
  virtual ~SharedData() = default;

  /// <summary>
  /// Validate the current data in the model. Throws a ValidationException on
  /// failure.
  /// </summary>
  void validate() const;

  /// <summary>
  /// Validate the current data in the model. Returns false on error and writes
  /// an error message into the given stringstream.
  /// </summary>
  bool validate(std::stringstream& msg) const;

  /// <summary>
  /// Helper overload for validate. Used when one model stores another model and
  /// calls it's validate. Not meant to be called outside that case.
  /// </summary>
  bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

  bool operator==(const SharedData& rhs) const;
  bool operator!=(const SharedData& rhs) const;

  /////////////////////////////////////////////
  /// SharedData members

  /// <summary>
  ///
  /// </summary>
  std::string getSharedDataId() const;
  void setSharedDataId(std::string const& value);
  /// <summary>
  ///
  /// </summary>
  oai::_3gpp::model::AccessAndMobilitySubscriptionData_1 getSharedAmData()
      const;
  void setSharedAmData(
      oai::_3gpp::model::AccessAndMobilitySubscriptionData_1 const& value);
  bool sharedAmDataIsSet() const;
  void unsetSharedAmData();
  /// <summary>
  ///
  /// </summary>
  oai::_3gpp::model::SmsSubscriptionData_1 getSharedSmsSubsData() const;
  void setSharedSmsSubsData(
      oai::_3gpp::model::SmsSubscriptionData_1 const& value);
  bool sharedSmsSubsDataIsSet() const;
  void unsetSharedSmsSubsData();
  /// <summary>
  ///
  /// </summary>
  oai::_3gpp::model::SmsManagementSubscriptionData_1 getSharedSmsMngSubsData()
      const;
  void setSharedSmsMngSubsData(
      oai::_3gpp::model::SmsManagementSubscriptionData_1 const& value);
  bool sharedSmsMngSubsDataIsSet() const;
  void unsetSharedSmsMngSubsData();
  /// <summary>
  /// A map(list of key-value pairs) where Dnn, or optionally the Wildcard DNN,
  /// serves as key of DnnConfiguration
  /// </summary>
  std::map<std::string, oai::_3gpp::model::DnnConfiguration_1>
  getSharedDnnConfigurations() const;
  void setSharedDnnConfigurations(
      std::map<std::string, oai::_3gpp::model::DnnConfiguration_1> const&
          value);
  bool sharedDnnConfigurationsIsSet() const;
  void unsetSharedDnnConfigurations();
  /// <summary>
  ///
  /// </summary>
  oai::_3gpp::model::TraceData getSharedTraceData() const;
  void setSharedTraceData(oai::_3gpp::model::TraceData const& value);
  bool sharedTraceDataIsSet() const;
  void unsetSharedTraceData();
  /// <summary>
  /// A map(list of key-value pairs) where singleNssai serves as key of
  /// SnssaiInfo
  /// </summary>
  std::map<std::string, oai::_3gpp::model::SnssaiInfo> getSharedSnssaiInfos()
      const;
  void setSharedSnssaiInfos(
      std::map<std::string, oai::_3gpp::model::SnssaiInfo> const& value);
  bool sharedSnssaiInfosIsSet() const;
  void unsetSharedSnssaiInfos();
  /// <summary>
  /// A map(list of key-value pairs) where GroupId serves as key of VnGroupData
  /// </summary>
  std::map<std::string, oai::_3gpp::model::VnGroupData> getSharedVnGroupDatas()
      const;
  void setSharedVnGroupDatas(
      std::map<std::string, oai::_3gpp::model::VnGroupData> const& value);
  bool sharedVnGroupDatasIsSet() const;
  void unsetSharedVnGroupDatas();
  /// <summary>
  /// A map(list of key-value pairs) where JSON pointer pointing to an attribute
  /// within the SharedData serves as key of SharedDataTreatmentInstruction
  /// </summary>
  std::map<std::string, oai::_3gpp::model::SharedDataTreatmentInstruction>
  getTreatmentInstructions() const;
  void setTreatmentInstructions(
      std::map<
          std::string, oai::_3gpp::model::SharedDataTreatmentInstruction> const&
          value);
  bool treatmentInstructionsIsSet() const;
  void unsetTreatmentInstructions();
  /// <summary>
  ///
  /// </summary>
  oai::_3gpp::model::SessionManagementSubscriptionData_1 getSharedSmSubsData()
      const;
  void setSharedSmSubsData(
      oai::_3gpp::model::SessionManagementSubscriptionData_1 const& value);
  bool sharedSmSubsDataIsSet() const;
  void unsetSharedSmSubsData();
  /// <summary>
  ///
  /// </summary>
  oai::_3gpp::model::EcsAddrConfigInfo_1 getSharedEcsAddrConfigInfo() const;
  void setSharedEcsAddrConfigInfo(
      oai::_3gpp::model::EcsAddrConfigInfo_1 const& value);
  bool sharedEcsAddrConfigInfoIsSet() const;
  void unsetSharedEcsAddrConfigInfo();

  friend void to_json(nlohmann::json& j, const SharedData& o);
  friend void from_json(const nlohmann::json& j, SharedData& o);

 protected:
  std::string m_SharedDataId;

  oai::_3gpp::model::AccessAndMobilitySubscriptionData_1 m_SharedAmData;
  bool m_SharedAmDataIsSet;
  oai::_3gpp::model::SmsSubscriptionData_1 m_SharedSmsSubsData;
  bool m_SharedSmsSubsDataIsSet;
  oai::_3gpp::model::SmsManagementSubscriptionData_1 m_SharedSmsMngSubsData;
  bool m_SharedSmsMngSubsDataIsSet;
  std::map<std::string, oai::_3gpp::model::DnnConfiguration_1>
      m_SharedDnnConfigurations;
  bool m_SharedDnnConfigurationsIsSet;
  oai::_3gpp::model::TraceData m_SharedTraceData;
  bool m_SharedTraceDataIsSet;
  std::map<std::string, oai::_3gpp::model::SnssaiInfo> m_SharedSnssaiInfos;
  bool m_SharedSnssaiInfosIsSet;
  std::map<std::string, oai::_3gpp::model::VnGroupData> m_SharedVnGroupDatas;
  bool m_SharedVnGroupDatasIsSet;
  std::map<std::string, oai::_3gpp::model::SharedDataTreatmentInstruction>
      m_TreatmentInstructions;
  bool m_TreatmentInstructionsIsSet;
  oai::_3gpp::model::SessionManagementSubscriptionData_1 m_SharedSmSubsData;
  bool m_SharedSmSubsDataIsSet;
  oai::_3gpp::model::EcsAddrConfigInfo_1 m_SharedEcsAddrConfigInfo;
  bool m_SharedEcsAddrConfigInfoIsSet;
};

}  // namespace oai::_3gpp::model

#endif /* SharedData_H_ */
