/**
* Nudr_DataRepository API OpenAPI file
* Unified Data Repository Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
*
* The version of the OpenAPI document: 2.2.4
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * SliceMbr_1.h
 *
 * MBR related to slice
 */

#ifndef SliceMbr_1_H_
#define SliceMbr_1_H_


#include <string>
#include <nlohmann/json.hpp>

namespace oai::_3gpp::model
{

/// <summary>
/// MBR related to slice
/// </summary>
class  SliceMbr_1
{
public:
    SliceMbr_1();
    virtual ~SliceMbr_1() = default;


    /// <summary>
    /// Validate the current data in the model. Throws a ValidationException on failure.
    /// </summary>
    void validate() const;

    /// <summary>
    /// Validate the current data in the model. Returns false on error and writes an error
    /// message into the given stringstream.
    /// </summary>
    bool validate(std::stringstream& msg) const;

    /// <summary>
    /// Helper overload for validate. Used when one model stores another model and calls it's validate.
    /// Not meant to be called outside that case.
    /// </summary>
    bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

    bool operator==(const SliceMbr_1& rhs) const;
    bool operator!=(const SliceMbr_1& rhs) const;

    /////////////////////////////////////////////
    /// SliceMbr_1 members

    /// <summary>
    /// String representing a bit rate; the prefixes follow the standard symbols from The International System of Units, and represent x1000 multipliers, with the exception that prefix \&quot;K\&quot; is used to represent the standard symbol \&quot;k\&quot;. 
    /// </summary>
    std::string getUplink() const;
    void setUplink(std::string const& value);
    /// <summary>
    /// String representing a bit rate; the prefixes follow the standard symbols from The International System of Units, and represent x1000 multipliers, with the exception that prefix \&quot;K\&quot; is used to represent the standard symbol \&quot;k\&quot;. 
    /// </summary>
    std::string getDownlink() const;
    void setDownlink(std::string const& value);

    friend void to_json(nlohmann::json& j, const SliceMbr_1& o);
    friend void from_json(const nlohmann::json& j, SliceMbr_1& o);
protected:
    std::string m_Uplink;

    std::string m_Downlink;

    
};

} // namespace oai::_3gpp::model

#endif /* SliceMbr_1_H_ */
