/**
* Nsmf_PDUSession
* SMF PDU Session Service.   © 2025, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
*
* The version of the OpenAPI document: 1.2.7
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "SmContextType.h"
#include "Helpers.h"

#include <sstream>

namespace oai::model
{

SmContextType::SmContextType()
{
    
}

void SmContextType::validate() const
{
    std::stringstream msg;
    if (!validate(msg))
    {
        throw org::openapitools::server::helpers::ValidationException(msg.str());
    }
}

bool SmContextType::validate(std::stringstream& msg) const
{
    return validate(msg, "");
}

bool SmContextType::validate(std::stringstream& msg, const std::string& pathPrefix) const
{
    bool success = true;
    const std::string _pathPrefix = pathPrefix.empty() ? "SmContextType" : pathPrefix;

    
    return success;
}

bool SmContextType::operator==(const SmContextType& rhs) const
{
    return
    
    
    ;
}

bool SmContextType::operator!=(const SmContextType& rhs) const
{
    return !(*this == rhs);
}

void to_json(nlohmann::json& j, const SmContextType& o)
{
    j = nlohmann::json::object();
    
}

void from_json(const nlohmann::json& j, SmContextType& o)
{
    
}



} // namespace oai::model

