################################################################################
# Licensed to the OpenAirInterface (OAI) Software Alliance under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The OpenAirInterface Software Alliance licenses this file to You under
# the OAI Public License, Version 1.1  (the "License"); you may not use this file
# except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.openairinterface.org/?page_id=698
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#-------------------------------------------------------------------------------
# For more information about the OpenAirInterface (OAI) Software Alliance:
#      contact@openairinterface.org
################################################################################

include(${SRC_TOP_DIR}/${MOUNTED_COMMON}/model/common_model.cmake)

SET(SMF_MODEL_DIR ${SRC_TOP_DIR}/${MOUNTED_COMMON}/model)

include_directories(${SMF_MODEL_DIR})

file(GLOB SMF_MODEL_SRC_FILES
    ${SMF_MODEL_DIR}/AbnormalBehaviour.cpp
    ${SMF_MODEL_DIR}/AccessTokenErr.cpp
    ${SMF_MODEL_DIR}/AccessTokenReq.cpp
    ${SMF_MODEL_DIR}/AccessType.cpp
    ${SMF_MODEL_DIR}/AckOfNotify.cpp
    ${SMF_MODEL_DIR}/AdditionalQosFlowInfo.cpp
    ${SMF_MODEL_DIR}/AddrFqdn.cpp
    ${SMF_MODEL_DIR}/AfCoordinationInfo.cpp
    ${SMF_MODEL_DIR}/AfResultInfo.cpp
    ${SMF_MODEL_DIR}/AfResultStatus.cpp
    ${SMF_MODEL_DIR}/AfResultStatus_anyOf.cpp
    ${SMF_MODEL_DIR}/AlternativeQosProfile.cpp
    ${SMF_MODEL_DIR}/Ambr.cpp
    ${SMF_MODEL_DIR}/AnalyticsMetadataInfo.cpp
    ${SMF_MODEL_DIR}/AnalyticsSubset.cpp
    ${SMF_MODEL_DIR}/AnchorSmfFeatures.cpp
    ${SMF_MODEL_DIR}/ApnRateStatus.cpp
    ${SMF_MODEL_DIR}/AppliedSmccType.cpp
    ${SMF_MODEL_DIR}/AppliedSmccType_anyOf.cpp
    ${SMF_MODEL_DIR}/Arp.cpp
    ${SMF_MODEL_DIR}/BackupAmfInfo.cpp
    ${SMF_MODEL_DIR}/BatteryIndication.cpp
    ${SMF_MODEL_DIR}/BwRequirement.cpp
    ${SMF_MODEL_DIR}/Cause.cpp
    ${SMF_MODEL_DIR}/Cause_anyOf.cpp
    ${SMF_MODEL_DIR}/CellGlobalId.cpp
    ${SMF_MODEL_DIR}/ChargingInformation.cpp
    ${SMF_MODEL_DIR}/CnAssistedRanPara.cpp
    ${SMF_MODEL_DIR}/CommunicationFailure.cpp
    ${SMF_MODEL_DIR}/DddTrafficDescriptor.cpp
    ${SMF_MODEL_DIR}/DdnFailureSubInfo.cpp
    ${SMF_MODEL_DIR}/DdnFailureSubs.cpp
    ${SMF_MODEL_DIR}/DispersionInfo.cpp
    ${SMF_MODEL_DIR}/DispersionRequirement.cpp
    ${SMF_MODEL_DIR}/DlDataDeliveryStatus.cpp
    ${SMF_MODEL_DIR}/DlDataDeliveryStatus_anyOf.cpp
    ${SMF_MODEL_DIR}/DnPerfInfo.cpp
    ${SMF_MODEL_DIR}/DnPerformanceReq.cpp
    ${SMF_MODEL_DIR}/DnaiChangeType.cpp
    ${SMF_MODEL_DIR}/DnaiChangeType_anyOf.cpp
    ${SMF_MODEL_DIR}/DnaiInformation.cpp
    ${SMF_MODEL_DIR}/DnnSelectionMode.cpp
    ${SMF_MODEL_DIR}/DnnSelectionMode_anyOf.cpp
    ${SMF_MODEL_DIR}/DnsServerIdentifier.cpp
    ${SMF_MODEL_DIR}/Dynamic5Qi.cpp
    ${SMF_MODEL_DIR}/EasIpReplacementInfo.cpp
    ${SMF_MODEL_DIR}/EasServerAddress.cpp
    ${SMF_MODEL_DIR}/EbiArpMapping.cpp
    ${SMF_MODEL_DIR}/Ecgi.cpp
    ${SMF_MODEL_DIR}/EpsBearerInfo.cpp
    ${SMF_MODEL_DIR}/EpsInterworkingIndication.cpp
    ${SMF_MODEL_DIR}/EpsInterworkingIndication_anyOf.cpp
    ${SMF_MODEL_DIR}/EpsPdnCnxInfo.cpp
    ${SMF_MODEL_DIR}/EthFlowDescription.cpp
    ${SMF_MODEL_DIR}/EutraLocation.cpp
    ${SMF_MODEL_DIR}/EventNotification.cpp
    ${SMF_MODEL_DIR}/EventReportingRequirement.cpp
    ${SMF_MODEL_DIR}/EventSubscription.cpp
    ${SMF_MODEL_DIR}/Exception.cpp
    ${SMF_MODEL_DIR}/ExemptionInd.cpp
    ${SMF_MODEL_DIR}/ExpectedAnalyticsType.cpp
    ${SMF_MODEL_DIR}/ExpectedUeBehaviourData.cpp
    ${SMF_MODEL_DIR}/ExtProblemDetails.cpp
    ${SMF_MODEL_DIR}/FlowDirection.cpp
    ${SMF_MODEL_DIR}/FlowDirection_anyOf.cpp
    ${SMF_MODEL_DIR}/GNbId.cpp
    ${SMF_MODEL_DIR}/GbrQosFlowInformation.cpp
    ${SMF_MODEL_DIR}/GeraLocation.cpp
    ${SMF_MODEL_DIR}/GlobalRanNodeId.cpp
    ${SMF_MODEL_DIR}/Guami.cpp
    ${SMF_MODEL_DIR}/HfcNodeId.cpp
    ${SMF_MODEL_DIR}/HoState.cpp
    ${SMF_MODEL_DIR}/HoState_anyOf.cpp
    ${SMF_MODEL_DIR}/HsmfUpdateData.cpp
    ${SMF_MODEL_DIR}/HsmfUpdateError.cpp
    ${SMF_MODEL_DIR}/HsmfUpdatedData.cpp
    ${SMF_MODEL_DIR}/IndirectDataForwardingTunnelInfo.cpp
    ${SMF_MODEL_DIR}/InvalidParam.cpp
    ${SMF_MODEL_DIR}/IpAddr.cpp
    ${SMF_MODEL_DIR}/IpAddress.cpp
    ${SMF_MODEL_DIR}/IpIndex.cpp
    ${SMF_MODEL_DIR}/Ipv6Addr.cpp
    ${SMF_MODEL_DIR}/Ipv6Prefix.cpp
    ${SMF_MODEL_DIR}/LineType.cpp
    ${SMF_MODEL_DIR}/LineType_anyOf.cpp
    ${SMF_MODEL_DIR}/LocationAreaId.cpp
    ${SMF_MODEL_DIR}/MaReleaseIndication.cpp
    ${SMF_MODEL_DIR}/MaReleaseIndication_anyOf.cpp
    ${SMF_MODEL_DIR}/MatchingDirection.cpp
    ${SMF_MODEL_DIR}/MaxIntegrityProtectedDataRate.cpp
    ${SMF_MODEL_DIR}/MaxIntegrityProtectedDataRate_anyOf.cpp
    ${SMF_MODEL_DIR}/MmeCapabilities.cpp
    ${SMF_MODEL_DIR}/MoExpDataCounter.cpp
    ${SMF_MODEL_DIR}/N2SmInfoType.cpp
    ${SMF_MODEL_DIR}/N2SmInfoType_anyOf.cpp
    ${SMF_MODEL_DIR}/N3gaLocation.cpp
    ${SMF_MODEL_DIR}/N4Information.cpp
    ${SMF_MODEL_DIR}/N4MessageType.cpp
    ${SMF_MODEL_DIR}/N4MessageType_anyOf.cpp
    ${SMF_MODEL_DIR}/NFType.cpp
    ${SMF_MODEL_DIR}/NFType_anyOf.cpp
    ${SMF_MODEL_DIR}/Ncgi.cpp
    ${SMF_MODEL_DIR}/NetworkAreaInfo.cpp
    ${SMF_MODEL_DIR}/NetworkPerfInfo.cpp
    ${SMF_MODEL_DIR}/NetworkPerfRequirement.cpp
    ${SMF_MODEL_DIR}/NfLoadLevelInformation.cpp
    ${SMF_MODEL_DIR}/NgApCause.cpp
    ${SMF_MODEL_DIR}/NgRanTargetId.cpp
    ${SMF_MODEL_DIR}/NiddInformation.cpp
    ${SMF_MODEL_DIR}/NonDynamic5Qi.cpp
    ${SMF_MODEL_DIR}/NotificationCause.cpp
    ${SMF_MODEL_DIR}/NotificationCause_anyOf.cpp
    ${SMF_MODEL_DIR}/NotificationControl.cpp
    ${SMF_MODEL_DIR}/NotificationControl_anyOf.cpp
    ${SMF_MODEL_DIR}/NotificationFlag.cpp
    ${SMF_MODEL_DIR}/NotificationFlag_anyOf.cpp
    ${SMF_MODEL_DIR}/NotificationInfo.cpp
    ${SMF_MODEL_DIR}/NotificationMethod.cpp
    ${SMF_MODEL_DIR}/NotificationMethod_anyOf.cpp
    ${SMF_MODEL_DIR}/NrLocation.cpp
    ${SMF_MODEL_DIR}/NsiIdInfo.cpp
    ${SMF_MODEL_DIR}/NsiLoadLevelInfo.cpp
    ${SMF_MODEL_DIR}/NsmfEventExposure.cpp
    ${SMF_MODEL_DIR}/NsmfEventExposureNotification.cpp
    ${SMF_MODEL_DIR}/NwdafEvent.cpp
    ${SMF_MODEL_DIR}/NwdafFailureCode.cpp
    ${SMF_MODEL_DIR}/PartialRecordMethod.cpp
    ${SMF_MODEL_DIR}/PartialRecordMethod_anyOf.cpp
    ${SMF_MODEL_DIR}/PartitioningCriteria.cpp
    ${SMF_MODEL_DIR}/PartitioningCriteria_anyOf.cpp
    ${SMF_MODEL_DIR}/PcfUeCallbackInfo.cpp
    ${SMF_MODEL_DIR}/PduSessionContextType.cpp
    ${SMF_MODEL_DIR}/PduSessionContextType_anyOf.cpp
    ${SMF_MODEL_DIR}/PduSessionCreateData.cpp
    ${SMF_MODEL_DIR}/PduSessionCreateError.cpp
    ${SMF_MODEL_DIR}/PduSessionCreatedData.cpp
    ${SMF_MODEL_DIR}/PduSessionInfo.cpp
    ${SMF_MODEL_DIR}/PduSessionInformation.cpp
    ${SMF_MODEL_DIR}/PduSessionNotifyItem.cpp
    ${SMF_MODEL_DIR}/PduSessionStatus.cpp
    ${SMF_MODEL_DIR}/PduSessionStatus_anyOf.cpp
    ${SMF_MODEL_DIR}/PduSessionType.cpp
    ${SMF_MODEL_DIR}/PduSessionType_anyOf.cpp
    ${SMF_MODEL_DIR}/PlmnId.cpp
    ${SMF_MODEL_DIR}/PlmnIdNid.cpp
    ${SMF_MODEL_DIR}/PreemptionCapability.cpp
    ${SMF_MODEL_DIR}/PreemptionCapability_anyOf.cpp
    ${SMF_MODEL_DIR}/PreemptionVulnerability.cpp
    ${SMF_MODEL_DIR}/PreemptionVulnerability_anyOf.cpp
    ${SMF_MODEL_DIR}/PresenceState.cpp
    ${SMF_MODEL_DIR}/PresenceState_anyOf.cpp
    ${SMF_MODEL_DIR}/ProblemDetails.cpp
    ${SMF_MODEL_DIR}/ProblemDetailsAddInfo.cpp
    ${SMF_MODEL_DIR}/ProtectionResult.cpp
    ${SMF_MODEL_DIR}/ProtectionResult_anyOf.cpp
    ${SMF_MODEL_DIR}/PsaIndication.cpp
    ${SMF_MODEL_DIR}/PsaIndication_anyOf.cpp
    ${SMF_MODEL_DIR}/PsaInformation.cpp
    ${SMF_MODEL_DIR}/QosFlowAccessType.cpp
    ${SMF_MODEL_DIR}/QosFlowAccessType_anyOf.cpp
    ${SMF_MODEL_DIR}/QosFlowAddModifyRequestItem.cpp
    ${SMF_MODEL_DIR}/QosFlowItem.cpp
    ${SMF_MODEL_DIR}/QosFlowNotifyItem.cpp
    ${SMF_MODEL_DIR}/QosFlowProfile.cpp
    ${SMF_MODEL_DIR}/QosFlowReleaseRequestItem.cpp
    ${SMF_MODEL_DIR}/QosFlowSetupItem.cpp
    ${SMF_MODEL_DIR}/QosFlowTunnel.cpp
    ${SMF_MODEL_DIR}/QosFlowUsageReport.cpp
    ${SMF_MODEL_DIR}/QosMonitoringInfo.cpp
    ${SMF_MODEL_DIR}/QosMonitoringReq.cpp
    ${SMF_MODEL_DIR}/QosMonitoringReq_anyOf.cpp
    ${SMF_MODEL_DIR}/QosRequirement.cpp
    ${SMF_MODEL_DIR}/QosResourceType.cpp
    ${SMF_MODEL_DIR}/QosResourceType_anyOf.cpp
    ${SMF_MODEL_DIR}/QosSustainabilityInfo.cpp
    ${SMF_MODEL_DIR}/RatFreqInformation.cpp
    ${SMF_MODEL_DIR}/RatType.cpp
    ${SMF_MODEL_DIR}/RatType_anyOf.cpp
    ${SMF_MODEL_DIR}/RedirectResponse.cpp
    ${SMF_MODEL_DIR}/RedundantPduSessionInformation.cpp
    ${SMF_MODEL_DIR}/RedundantTransmissionExpInfo.cpp
    ${SMF_MODEL_DIR}/RedundantTransmissionExpReq.cpp
    ${SMF_MODEL_DIR}/RefToBinaryData.cpp
    ${SMF_MODEL_DIR}/ReflectiveQoSAttribute.cpp
    ${SMF_MODEL_DIR}/ReflectiveQoSAttribute_anyOf.cpp
    ${SMF_MODEL_DIR}/ReleaseCause.cpp
    ${SMF_MODEL_DIR}/ReleaseData.cpp
    ${SMF_MODEL_DIR}/ReleasedData.cpp
    ${SMF_MODEL_DIR}/RequestIndication.cpp
    ${SMF_MODEL_DIR}/RequestIndication_anyOf.cpp
    ${SMF_MODEL_DIR}/RequestType.cpp
    ${SMF_MODEL_DIR}/RequestType_anyOf.cpp
    ${SMF_MODEL_DIR}/ResourceStatus.cpp
    ${SMF_MODEL_DIR}/ResourceStatus_anyOf.cpp
    ${SMF_MODEL_DIR}/RetainabilityThreshold.cpp
    ${SMF_MODEL_DIR}/RetrieveData.cpp
    ${SMF_MODEL_DIR}/RetrievedData.cpp
    ${SMF_MODEL_DIR}/RoamingChargingProfile.cpp
    ${SMF_MODEL_DIR}/RouteInformation.cpp
    ${SMF_MODEL_DIR}/RouteToLocation.cpp
    ${SMF_MODEL_DIR}/RoutingAreaId.cpp
    ${SMF_MODEL_DIR}/Rsn.cpp
    ${SMF_MODEL_DIR}/Rsn_anyOf.cpp
    ${SMF_MODEL_DIR}/SatelliteBackhaulCategory.cpp
    ${SMF_MODEL_DIR}/SatelliteBackhaulCategory_anyOf.cpp
    ${SMF_MODEL_DIR}/SbiBindingLevel.cpp
    ${SMF_MODEL_DIR}/SbiBindingLevel_anyOf.cpp
    ${SMF_MODEL_DIR}/ScheduledCommunicationTime.cpp
    ${SMF_MODEL_DIR}/ScheduledCommunicationType.cpp
    ${SMF_MODEL_DIR}/ScheduledCommunicationType_anyOf.cpp
    ${SMF_MODEL_DIR}/SecondaryRatUsageInfo.cpp
    ${SMF_MODEL_DIR}/SecondaryRatUsageReport.cpp
    ${SMF_MODEL_DIR}/SecurityResult.cpp
    ${SMF_MODEL_DIR}/SendMoDataReqData.cpp
    ${SMF_MODEL_DIR}/ServerAddressingInfo.cpp
    ${SMF_MODEL_DIR}/ServiceAreaId.cpp
    ${SMF_MODEL_DIR}/ServiceExperienceInfo.cpp
    ${SMF_MODEL_DIR}/ServiceName.cpp
    ${SMF_MODEL_DIR}/ServiceName_anyOf.cpp
    ${SMF_MODEL_DIR}/SliceLoadLevelInformation.cpp
    ${SMF_MODEL_DIR}/SmContext.cpp
    ${SMF_MODEL_DIR}/SmContextConfiguration.cpp
    ${SMF_MODEL_DIR}/SmContextCreateData.cpp
    ${SMF_MODEL_DIR}/SmContextCreateError.cpp
    ${SMF_MODEL_DIR}/SmContextCreatedData.cpp
    ${SMF_MODEL_DIR}/SmContextReleaseData.cpp
    ${SMF_MODEL_DIR}/SmContextReleasedData.cpp
    ${SMF_MODEL_DIR}/SmContextRetrieveData.cpp
    ${SMF_MODEL_DIR}/SmContextRetrievedData.cpp
    ${SMF_MODEL_DIR}/SmContextStatus.cpp
    ${SMF_MODEL_DIR}/SmContextStatusNotification.cpp
    ${SMF_MODEL_DIR}/SmContextType.cpp
    ${SMF_MODEL_DIR}/SmContextType_anyOf.cpp
    ${SMF_MODEL_DIR}/SmContextUpdateData.cpp
    ${SMF_MODEL_DIR}/SmContextUpdateError.cpp
    ${SMF_MODEL_DIR}/SmContextUpdatedData.cpp
    ${SMF_MODEL_DIR}/SmNasFromSmf.cpp
    ${SMF_MODEL_DIR}/SmNasFromUe.cpp
    ${SMF_MODEL_DIR}/SmallDataRateStatus.cpp
    ${SMF_MODEL_DIR}/SmcceInfo.cpp
    ${SMF_MODEL_DIR}/SmfEvent.cpp
    ${SMF_MODEL_DIR}/SmfEvent_anyOf.cpp
    ${SMF_MODEL_DIR}/SmfEventSubscription.cpp
    ${SMF_MODEL_DIR}/SmfSelectionType.cpp
    ${SMF_MODEL_DIR}/SmfSelectionType_anyOf.cpp
    ${SMF_MODEL_DIR}/Snssai.cpp
    ${SMF_MODEL_DIR}/StationaryIndication.cpp
    ${SMF_MODEL_DIR}/StationaryIndication_anyOf.cpp
    ${SMF_MODEL_DIR}/StatusInfo.cpp
    ${SMF_MODEL_DIR}/StatusNotification.cpp
    ${SMF_MODEL_DIR}/Tai.cpp
    ${SMF_MODEL_DIR}/TargetDnaiInfo.cpp
    ${SMF_MODEL_DIR}/TargetUeInformation.cpp
    ${SMF_MODEL_DIR}/ThresholdLevel.cpp
    ${SMF_MODEL_DIR}/TimeWindow.cpp
    ${SMF_MODEL_DIR}/TnapId.cpp
    ${SMF_MODEL_DIR}/TngfInfo.cpp
    ${SMF_MODEL_DIR}/TraceData.cpp
    ${SMF_MODEL_DIR}/TraceDepth.cpp
    ${SMF_MODEL_DIR}/TraceDepth_anyOf.cpp
    ${SMF_MODEL_DIR}/TrafficProfile.cpp
    ${SMF_MODEL_DIR}/TrafficProfile_anyOf.cpp
    ${SMF_MODEL_DIR}/TransactionInfo.cpp
    ${SMF_MODEL_DIR}/TransactionMetric.cpp
    ${SMF_MODEL_DIR}/TransactionMetric_anyOf.cpp
    ${SMF_MODEL_DIR}/TransferMoDataReqData.cpp
    ${SMF_MODEL_DIR}/TransferMtDataAddInfo.cpp
    ${SMF_MODEL_DIR}/TransferMtDataError.cpp
    ${SMF_MODEL_DIR}/TransferMtDataReqData.cpp
    ${SMF_MODEL_DIR}/TransportProtocol.cpp
    ${SMF_MODEL_DIR}/TransportProtocol_anyOf.cpp
    ${SMF_MODEL_DIR}/Trigger.cpp
    ${SMF_MODEL_DIR}/TriggerCategory.cpp
    ${SMF_MODEL_DIR}/TriggerCategory_anyOf.cpp
    ${SMF_MODEL_DIR}/TriggerType.cpp
    ${SMF_MODEL_DIR}/TriggerType_anyOf.cpp
    ${SMF_MODEL_DIR}/TunnelInfo.cpp
    ${SMF_MODEL_DIR}/TwapId.cpp
    ${SMF_MODEL_DIR}/TwifInfo.cpp
    ${SMF_MODEL_DIR}/UeCommunication.cpp
    ${SMF_MODEL_DIR}/UeMobility.cpp
    ${SMF_MODEL_DIR}/UlclBpInformation.cpp
    ${SMF_MODEL_DIR}/UnavailableAccessIndication.cpp
    ${SMF_MODEL_DIR}/UnavailableAccessIndication_anyOf.cpp
    ${SMF_MODEL_DIR}/UpCnxState.cpp
    ${SMF_MODEL_DIR}/UpCnxState_anyOf.cpp
    ${SMF_MODEL_DIR}/UpConfidentiality.cpp
    ${SMF_MODEL_DIR}/UpIntegrity.cpp
    ${SMF_MODEL_DIR}/UpIntegrity_anyOf.cpp
    ${SMF_MODEL_DIR}/UpSecurity.cpp
    ${SMF_MODEL_DIR}/UpSecurityInfo.cpp
    ${SMF_MODEL_DIR}/UpfInformation.cpp
    ${SMF_MODEL_DIR}/UserDataCongestionInfo.cpp
    ${SMF_MODEL_DIR}/UserLocation.cpp
    ${SMF_MODEL_DIR}/UtraLocation.cpp
    ${SMF_MODEL_DIR}/VolumeTimedReport.cpp
    ${SMF_MODEL_DIR}/VplmnQos.cpp
    ${SMF_MODEL_DIR}/VsmfUpdateData.cpp
    ${SMF_MODEL_DIR}/VsmfUpdateError.cpp
    ${SMF_MODEL_DIR}/VsmfUpdatedData.cpp
    ${SMF_MODEL_DIR}/WAgfInfo.cpp
    ${SMF_MODEL_DIR}/WlanPerformanceInfo.cpp
    ${SMF_MODEL_DIR}/WlanPerformanceReq.cpp
    ${SMF_MODEL_DIR}/ConditionEventType.cpp
    ${SMF_MODEL_DIR}/ConditionEventType_anyOf.cpp
    ${SMF_MODEL_DIR}/DddStatus.cpp
    ${SMF_MODEL_DIR}/SmContextMessage.cpp
    ${SMF_MODEL_DIR}/SmContextReleaseMessage.cpp
    ${SMF_MODEL_DIR}/SmContextUpdateMessage.cpp
${SMF_MODEL_DIR}/Accuracy.cpp
    ${SMF_MODEL_DIR}/AdditionalMeasurement.cpp
    ${SMF_MODEL_DIR}/AnalyticsMetadata.cpp
    ${SMF_MODEL_DIR}/AnalyticsMetadataIndication.cpp
    ${SMF_MODEL_DIR}/AnalyticsSubset_anyOf.cpp
    ${SMF_MODEL_DIR}/AppListForUeComm.cpp
    ${SMF_MODEL_DIR}/AuthorizedDefaultQos.cpp
    ${SMF_MODEL_DIR}/ClassCriterion.cpp
    ${SMF_MODEL_DIR}/DatasetStatisticalProperty.cpp
    ${SMF_MODEL_DIR}/DispersionCollection.cpp
    ${SMF_MODEL_DIR}/DispersionOrderingCriterion.cpp
    ${SMF_MODEL_DIR}/DispersionType.cpp
    ${SMF_MODEL_DIR}/DnnSmfInfoItem.cpp
    ${SMF_MODEL_DIR}/DnnUpfInfoItem.cpp
    ${SMF_MODEL_DIR}/DnPerf.cpp
    ${SMF_MODEL_DIR}/DnPerfOrderingCriterion.cpp
    ${SMF_MODEL_DIR}/ExceptionId.cpp
    ${SMF_MODEL_DIR}/ExceptionTrend.cpp
    ${SMF_MODEL_DIR}/ExpectedAnalyticsType_anyOf.cpp
    ${SMF_MODEL_DIR}/FlowDirectionRm.cpp
    ${SMF_MODEL_DIR}/InterfaceUpfInfoItem.cpp
    ${SMF_MODEL_DIR}/LocationArea.cpp
    ${SMF_MODEL_DIR}/LocationInfo.cpp
    ${SMF_MODEL_DIR}/MatchingDirection_anyOf.cpp
    ${SMF_MODEL_DIR}/NetworkPerfType.cpp
    ${SMF_MODEL_DIR}/NFProfile.cpp
    ${SMF_MODEL_DIR}/NfStatus.cpp
    ${SMF_MODEL_DIR}/NotificationData.cpp
    ${SMF_MODEL_DIR}/NotificationEventType.cpp
    ${SMF_MODEL_DIR}/NumberAverage.cpp
    ${SMF_MODEL_DIR}/NwdafEvent_anyOf.cpp
    ${SMF_MODEL_DIR}/NwdafFailureCode_anyOf.cpp
    ${SMF_MODEL_DIR}/OutputStrategy.cpp
    ${SMF_MODEL_DIR}/PatchItem.cpp
    ${SMF_MODEL_DIR}/PatchOperation.cpp
    ${SMF_MODEL_DIR}/PatchOperation_anyOf.cpp
    ${SMF_MODEL_DIR}/PccRule.cpp
    ${SMF_MODEL_DIR}/QosData.cpp
    ${SMF_MODEL_DIR}/RankingCriterion.cpp
    ${SMF_MODEL_DIR}/RedirectAddressType.cpp
    ${SMF_MODEL_DIR}/RedirectInformation.cpp
    ${SMF_MODEL_DIR}/RedTransExpOrderingCriterion.cpp
    ${SMF_MODEL_DIR}/RedundantTransmissionExpPerTS.cpp
    ${SMF_MODEL_DIR}/ReleaseCause_anyOf.cpp
    ${SMF_MODEL_DIR}/ResourceUsage.cpp
    ${SMF_MODEL_DIR}/SdmSubscription.cpp
    ${SMF_MODEL_DIR}/SearchResult.cpp
    ${SMF_MODEL_DIR}/ServiceExperienceType.cpp
    ${SMF_MODEL_DIR}/SessInactTimerForUeComm.cpp
    ${SMF_MODEL_DIR}/SessionRule.cpp
    ${SMF_MODEL_DIR}/SmallDataRateControl.cpp
    ${SMF_MODEL_DIR}/SmcceUeList.cpp
    ${SMF_MODEL_DIR}/SmContextStatus_anyOf.cpp
    ${SMF_MODEL_DIR}/SmfInfo.cpp
    ${SMF_MODEL_DIR}/SmfRegistration.cpp
    ${SMF_MODEL_DIR}/SmPolicyContextData.cpp
    ${SMF_MODEL_DIR}/SmPolicyControl.cpp
    ${SMF_MODEL_DIR}/SmPolicyDecision.cpp
    ${SMF_MODEL_DIR}/SmPolicyDeleteData.cpp
    ${SMF_MODEL_DIR}/SmPolicyNotification.cpp
    ${SMF_MODEL_DIR}/SmPolicyUpdateContextData.cpp
    ${SMF_MODEL_DIR}/SnssaiSmfInfoItem.cpp
    ${SMF_MODEL_DIR}/SnssaiUpfInfoItem.cpp
    ${SMF_MODEL_DIR}/SubscribedDefaultQos.cpp
    ${SMF_MODEL_DIR}/SvcExperience.cpp
    ${SMF_MODEL_DIR}/TerminationNotification.cpp
    ${SMF_MODEL_DIR}/TimeUnit.cpp
    ${SMF_MODEL_DIR}/TrafficCharacterization.cpp
    ${SMF_MODEL_DIR}/TrafficControlData.cpp
    ${SMF_MODEL_DIR}/UpfInfo.cpp
    ${SMF_MODEL_DIR}/UPInterfaceType.cpp
    ${SMF_MODEL_DIR}/UPInterfaceType_anyOf.cpp
    ${SMF_MODEL_DIR}/WlanOrderingCriterion.cpp
    ${SMF_MODEL_DIR}/WlanPerSsIdPerformanceInfo.cpp
    ${SMF_MODEL_DIR}/UsageReport.cpp
)

if (TARGET ${NF_TARGET})
    target_include_directories(${NF_TARGET} PUBLIC ${SMF_MODEL_DIR})
    target_sources(${NF_TARGET} PRIVATE
            ${SMF_MODEL_SRC_FILES}
            )
endif()
