/**
* Namf_Communication
* AMF Communication Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
*
* The version of the OpenAPI document: 1.2.4
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * SmfChangeIndication.h
 *
 * Indicates the I-SMF or V-SMF change or removal
 */

#ifndef SmfChangeIndication_H_
#define SmfChangeIndication_H_


#include <nlohmann/json.hpp>

namespace oai::model
{

/// <summary>
/// Indicates the I-SMF or V-SMF change or removal
/// </summary>
class  SmfChangeIndication
{
public:
    SmfChangeIndication();
    virtual ~SmfChangeIndication() = default;


    /// <summary>
    /// Validate the current data in the model. Throws a ValidationException on failure.
    /// </summary>
    void validate() const;

    /// <summary>
    /// Validate the current data in the model. Returns false on error and writes an error
    /// message into the given stringstream.
    /// </summary>
    bool validate(std::stringstream& msg) const;

    /// <summary>
    /// Helper overload for validate. Used when one model stores another model and calls it's validate.
    /// Not meant to be called outside that case.
    /// </summary>
    bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

    bool operator==(const SmfChangeIndication& rhs) const;
    bool operator!=(const SmfChangeIndication& rhs) const;

    /////////////////////////////////////////////
    /// SmfChangeIndication members


    friend  void to_json(nlohmann::json& j, const SmfChangeIndication& o);
    friend  void from_json(const nlohmann::json& j, SmfChangeIndication& o);
protected:
    
};

} // namespace oai::model

#endif /* SmfChangeIndication_H_ */
