/**
* Nudr_DataRepository API OpenAPI file
* Unified Data Repository Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
*
* The version of the OpenAPI document: 2.2.4
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "SmsSubscriptionData_1.h"
#include "Helpers.h"

#include <sstream>

namespace oai::_3gpp::model
{

SmsSubscriptionData_1::SmsSubscriptionData_1()
{
    m_SmsSubscribed = false;
    m_SmsSubscribedIsSet = false;
    m_SharedSmsSubsDataId = "";
    m_SharedSmsSubsDataIdIsSet = false;
    m_SupportedFeatures = "";
    m_SupportedFeaturesIsSet = false;
    
}

void SmsSubscriptionData_1::validate() const
{
    std::stringstream msg;
    if (!validate(msg))
    {
        throw oai::_3gpp::model::helpers::ValidationException(msg.str());
    }
}

bool SmsSubscriptionData_1::validate(std::stringstream& msg) const
{
    return validate(msg, "");
}

bool SmsSubscriptionData_1::validate(std::stringstream& msg, const std::string& pathPrefix) const
{
    bool success = true;
    const std::string _pathPrefix = pathPrefix.empty() ? "SmsSubscriptionData_1" : pathPrefix;

             
    if (sharedSmsSubsDataIdIsSet())
    {
        const std::string& value = m_SharedSmsSubsDataId;
        const std::string currentValuePath = _pathPrefix + ".sharedSmsSubsDataId";
                
        

    }
         
    if (supportedFeaturesIsSet())
    {
        const std::string& value = m_SupportedFeatures;
        const std::string currentValuePath = _pathPrefix + ".supportedFeatures";
                
        

    }
    
    return success;
}

bool SmsSubscriptionData_1::operator==(const SmsSubscriptionData_1& rhs) const
{
    return
    
    
    
    ((!smsSubscribedIsSet() && !rhs.smsSubscribedIsSet()) || (smsSubscribedIsSet() && rhs.smsSubscribedIsSet() && isSmsSubscribed() == rhs.isSmsSubscribed())) &&
    
    
    ((!sharedSmsSubsDataIdIsSet() && !rhs.sharedSmsSubsDataIdIsSet()) || (sharedSmsSubsDataIdIsSet() && rhs.sharedSmsSubsDataIdIsSet() && getSharedSmsSubsDataId() == rhs.getSharedSmsSubsDataId())) &&
    
    
    ((!supportedFeaturesIsSet() && !rhs.supportedFeaturesIsSet()) || (supportedFeaturesIsSet() && rhs.supportedFeaturesIsSet() && getSupportedFeatures() == rhs.getSupportedFeatures()))
    
    ;
}

bool SmsSubscriptionData_1::operator!=(const SmsSubscriptionData_1& rhs) const
{
    return !(*this == rhs);
}

void to_json(nlohmann::json& j, const SmsSubscriptionData_1& o)
{
    j = nlohmann::json();
    if(o.smsSubscribedIsSet())
        j["smsSubscribed"] = o.m_SmsSubscribed;
    if(o.sharedSmsSubsDataIdIsSet())
        j["sharedSmsSubsDataId"] = o.m_SharedSmsSubsDataId;
    if(o.supportedFeaturesIsSet())
        j["supportedFeatures"] = o.m_SupportedFeatures;
    
}

void from_json(const nlohmann::json& j, SmsSubscriptionData_1& o)
{
    if(j.find("smsSubscribed") != j.end())
    {
        j.at("smsSubscribed").get_to(o.m_SmsSubscribed);
        o.m_SmsSubscribedIsSet = true;
    } 
    if(j.find("sharedSmsSubsDataId") != j.end())
    {
        j.at("sharedSmsSubsDataId").get_to(o.m_SharedSmsSubsDataId);
        o.m_SharedSmsSubsDataIdIsSet = true;
    } 
    if(j.find("supportedFeatures") != j.end())
    {
        j.at("supportedFeatures").get_to(o.m_SupportedFeatures);
        o.m_SupportedFeaturesIsSet = true;
    } 
    
}

bool SmsSubscriptionData_1::isSmsSubscribed() const
{
    return m_SmsSubscribed;
}
void SmsSubscriptionData_1::setSmsSubscribed(bool const value)
{
    m_SmsSubscribed = value;
    m_SmsSubscribedIsSet = true;
}
bool SmsSubscriptionData_1::smsSubscribedIsSet() const
{
    return m_SmsSubscribedIsSet;
}
void SmsSubscriptionData_1::unsetSmsSubscribed()
{
    m_SmsSubscribedIsSet = false;
}
std::string SmsSubscriptionData_1::getSharedSmsSubsDataId() const
{
    return m_SharedSmsSubsDataId;
}
void SmsSubscriptionData_1::setSharedSmsSubsDataId(std::string const& value)
{
    m_SharedSmsSubsDataId = value;
    m_SharedSmsSubsDataIdIsSet = true;
}
bool SmsSubscriptionData_1::sharedSmsSubsDataIdIsSet() const
{
    return m_SharedSmsSubsDataIdIsSet;
}
void SmsSubscriptionData_1::unsetSharedSmsSubsDataId()
{
    m_SharedSmsSubsDataIdIsSet = false;
}
std::string SmsSubscriptionData_1::getSupportedFeatures() const
{
    return m_SupportedFeatures;
}
void SmsSubscriptionData_1::setSupportedFeatures(std::string const& value)
{
    m_SupportedFeatures = value;
    m_SupportedFeaturesIsSet = true;
}
bool SmsSubscriptionData_1::supportedFeaturesIsSet() const
{
    return m_SupportedFeaturesIsSet;
}
void SmsSubscriptionData_1::unsetSupportedFeatures()
{
    m_SupportedFeaturesIsSet = false;
}


} // namespace oai::_3gpp::model

