/**
* NRF NFManagement Service
* NRF NFManagement Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
*
* The version of the OpenAPI document: 1.2.7
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "SnssaiEasdfInfoItem.h"
#include "Helpers.h"

#include <sstream>

namespace oai::model
{

SnssaiEasdfInfoItem::SnssaiEasdfInfoItem()
{
    
}

void SnssaiEasdfInfoItem::validate() const
{
    std::stringstream msg;
    if (!validate(msg))
    {
        throw org::openapitools::server::helpers::ValidationException(msg.str());
    }
}

bool SnssaiEasdfInfoItem::validate(std::stringstream& msg) const
{
    return validate(msg, "");
}

bool SnssaiEasdfInfoItem::validate(std::stringstream& msg, const std::string& pathPrefix) const
{
    bool success = true;
    const std::string _pathPrefix = pathPrefix.empty() ? "SnssaiEasdfInfoItem" : pathPrefix;

        
    if (!m_SNssai.validate(msg, _pathPrefix + ".sNssai")) {
        msg << _pathPrefix << ": SNssai is invalid;";
        success = false;
    }     
    
    /* DnnEasdfInfoList */ {
        const std::vector<oai::model::DnnEasdfInfoItem>& value = m_DnnEasdfInfoList;
        const std::string currentValuePath = _pathPrefix + ".dnnEasdfInfoList";
                
        
        if (value.size() < 1)
        {
            success = false;
            msg << currentValuePath << ": must have at least 1 elements;";
        }
        { // Recursive validation of array elements
            const std::string oldValuePath = currentValuePath;
            int i = 0;
            for (const oai::model::DnnEasdfInfoItem& value : value)
            { 
                const std::string currentValuePath = oldValuePath + "[" + std::to_string(i) + "]";
                        
        success = value.validate(msg, currentValuePath + ".dnnEasdfInfoList") && success;
 
                i++;
            }
        }

    }
    
    return success;
}

bool SnssaiEasdfInfoItem::operator==(const SnssaiEasdfInfoItem& rhs) const
{
    return
    
    
    (getSNssai() == rhs.getSNssai())
     &&
    
    (getDnnEasdfInfoList() == rhs.getDnnEasdfInfoList())
    
    
    ;
}

bool SnssaiEasdfInfoItem::operator!=(const SnssaiEasdfInfoItem& rhs) const
{
    return !(*this == rhs);
}

void to_json(nlohmann::json& j, const SnssaiEasdfInfoItem& o)
{
    j = nlohmann::json::object();
    j["sNssai"] = o.m_SNssai;
    j["dnnEasdfInfoList"] = o.m_DnnEasdfInfoList;
    
}

void from_json(const nlohmann::json& j, SnssaiEasdfInfoItem& o)
{
    j.at("sNssai").get_to(o.m_SNssai);
    j.at("dnnEasdfInfoList").get_to(o.m_DnnEasdfInfoList);
    
}

oai::model::ExtSnssai SnssaiEasdfInfoItem::getSNssai() const
{
    return m_SNssai;
}
void SnssaiEasdfInfoItem::setSNssai(oai::model::ExtSnssai const& value)
{
    m_SNssai = value;
}
std::vector<oai::model::DnnEasdfInfoItem> SnssaiEasdfInfoItem::getDnnEasdfInfoList() const
{
    return m_DnnEasdfInfoList;
}
void SnssaiEasdfInfoItem::setDnnEasdfInfoList(std::vector<oai::model::DnnEasdfInfoItem> const& value)
{
    m_DnnEasdfInfoList = value;
}


} // namespace oai::model

