/**
* Unified Data Repository Service API file for Application Data
* The API version is defined in 3GPP TS 29.504   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
*
* The version of the OpenAPI document: -
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "TrafficDescriptorComponents.h"
#include "Helpers.h"

#include <sstream>

namespace oai::model
{

TrafficDescriptorComponents::TrafficDescriptorComponents()
{
    m_AppDescsIsSet = false;
    m_FlowDescsIsSet = false;
    m_DomainDescsIsSet = false;
    m_EthFlowDescsIsSet = false;
    m_DnnsIsSet = false;
    m_ConnCapsIsSet = false;
    
}

void TrafficDescriptorComponents::validate() const
{
    std::stringstream msg;
    if (!validate(msg))
    {
        throw org::openapitools::server::helpers::ValidationException(msg.str());
    }
}

bool TrafficDescriptorComponents::validate(std::stringstream& msg) const
{
    return validate(msg, "");
}

bool TrafficDescriptorComponents::validate(std::stringstream& msg, const std::string& pathPrefix) const
{
    bool success = true;
    const std::string _pathPrefix = pathPrefix.empty() ? "TrafficDescriptorComponents" : pathPrefix;

         
    if (appDescsIsSet())
    {
        const std::map<std::string, oai::model::AppDescriptor>& value = m_AppDescs;
        const std::string currentValuePath = _pathPrefix + ".appDescs";
                
        

    }
         
    if (flowDescsIsSet())
    {
        const std::vector<std::string>& value = m_FlowDescs;
        const std::string currentValuePath = _pathPrefix + ".flowDescs";
                
        
        if (value.size() < 1)
        {
            success = false;
            msg << currentValuePath << ": must have at least 1 elements;";
        }
        { // Recursive validation of array elements
            const std::string oldValuePath = currentValuePath;
            int i = 0;
            for (const std::string& value : value)
            { 
                const std::string currentValuePath = oldValuePath + "[" + std::to_string(i) + "]";
                        
        
 
                i++;
            }
        }

    }
         
    if (domainDescsIsSet())
    {
        const std::vector<std::string>& value = m_DomainDescs;
        const std::string currentValuePath = _pathPrefix + ".domainDescs";
                
        
        if (value.size() < 1)
        {
            success = false;
            msg << currentValuePath << ": must have at least 1 elements;";
        }
        { // Recursive validation of array elements
            const std::string oldValuePath = currentValuePath;
            int i = 0;
            for (const std::string& value : value)
            { 
                const std::string currentValuePath = oldValuePath + "[" + std::to_string(i) + "]";
                        
        
 
                i++;
            }
        }

    }
         
    if (ethFlowDescsIsSet())
    {
        const std::vector<oai::model::EthFlowDescription>& value = m_EthFlowDescs;
        const std::string currentValuePath = _pathPrefix + ".ethFlowDescs";
                
        
        if (value.size() < 1)
        {
            success = false;
            msg << currentValuePath << ": must have at least 1 elements;";
        }
        { // Recursive validation of array elements
            const std::string oldValuePath = currentValuePath;
            int i = 0;
            for (const oai::model::EthFlowDescription& value : value)
            { 
                const std::string currentValuePath = oldValuePath + "[" + std::to_string(i) + "]";
                        
        success = value.validate(msg, currentValuePath + ".ethFlowDescs") && success;
 
                i++;
            }
        }

    }
         
    if (dnnsIsSet())
    {
        const std::vector<std::string>& value = m_Dnns;
        const std::string currentValuePath = _pathPrefix + ".dnns";
                
        
        if (value.size() < 1)
        {
            success = false;
            msg << currentValuePath << ": must have at least 1 elements;";
        }
        { // Recursive validation of array elements
            const std::string oldValuePath = currentValuePath;
            int i = 0;
            for (const std::string& value : value)
            { 
                const std::string currentValuePath = oldValuePath + "[" + std::to_string(i) + "]";
                        
        
 
                i++;
            }
        }

    }
         
    if (connCapsIsSet())
    {
        const std::vector<oai::model::ConnectionCapabilities>& value = m_ConnCaps;
        const std::string currentValuePath = _pathPrefix + ".connCaps";
                
        
        if (value.size() < 1)
        {
            success = false;
            msg << currentValuePath << ": must have at least 1 elements;";
        }
        { // Recursive validation of array elements
            const std::string oldValuePath = currentValuePath;
            int i = 0;
            for (const oai::model::ConnectionCapabilities& value : value)
            { 
                const std::string currentValuePath = oldValuePath + "[" + std::to_string(i) + "]";
                        
        success = value.validate(msg, currentValuePath + ".connCaps") && success;
 
                i++;
            }
        }

    }
    
    return success;
}

bool TrafficDescriptorComponents::operator==(const TrafficDescriptorComponents& rhs) const
{
    return
    
    
    
    ((!appDescsIsSet() && !rhs.appDescsIsSet()) || (appDescsIsSet() && rhs.appDescsIsSet() && getAppDescs() == rhs.getAppDescs())) &&
    
    
    ((!flowDescsIsSet() && !rhs.flowDescsIsSet()) || (flowDescsIsSet() && rhs.flowDescsIsSet() && getFlowDescs() == rhs.getFlowDescs())) &&
    
    
    ((!domainDescsIsSet() && !rhs.domainDescsIsSet()) || (domainDescsIsSet() && rhs.domainDescsIsSet() && getDomainDescs() == rhs.getDomainDescs())) &&
    
    
    ((!ethFlowDescsIsSet() && !rhs.ethFlowDescsIsSet()) || (ethFlowDescsIsSet() && rhs.ethFlowDescsIsSet() && getEthFlowDescs() == rhs.getEthFlowDescs())) &&
    
    
    ((!dnnsIsSet() && !rhs.dnnsIsSet()) || (dnnsIsSet() && rhs.dnnsIsSet() && getDnns() == rhs.getDnns())) &&
    
    
    ((!connCapsIsSet() && !rhs.connCapsIsSet()) || (connCapsIsSet() && rhs.connCapsIsSet() && getConnCaps() == rhs.getConnCaps()))
    
    ;
}

bool TrafficDescriptorComponents::operator!=(const TrafficDescriptorComponents& rhs) const
{
    return !(*this == rhs);
}

void to_json(nlohmann::json& j, const TrafficDescriptorComponents& o)
{
    j = nlohmann::json::object();
    if(o.appDescsIsSet() || !o.m_AppDescs.empty())
        j["appDescs"] = o.m_AppDescs;
    if(o.flowDescsIsSet() || !o.m_FlowDescs.empty())
        j["flowDescs"] = o.m_FlowDescs;
    if(o.domainDescsIsSet() || !o.m_DomainDescs.empty())
        j["domainDescs"] = o.m_DomainDescs;
    if(o.ethFlowDescsIsSet() || !o.m_EthFlowDescs.empty())
        j["ethFlowDescs"] = o.m_EthFlowDescs;
    if(o.dnnsIsSet() || !o.m_Dnns.empty())
        j["dnns"] = o.m_Dnns;
    if(o.connCapsIsSet() || !o.m_ConnCaps.empty())
        j["connCaps"] = o.m_ConnCaps;
    
}

void from_json(const nlohmann::json& j, TrafficDescriptorComponents& o)
{
    if(j.find("appDescs") != j.end())
    {
        j.at("appDescs").get_to(o.m_AppDescs);
        o.m_AppDescsIsSet = true;
    } 
    if(j.find("flowDescs") != j.end())
    {
        j.at("flowDescs").get_to(o.m_FlowDescs);
        o.m_FlowDescsIsSet = true;
    } 
    if(j.find("domainDescs") != j.end())
    {
        j.at("domainDescs").get_to(o.m_DomainDescs);
        o.m_DomainDescsIsSet = true;
    } 
    if(j.find("ethFlowDescs") != j.end())
    {
        j.at("ethFlowDescs").get_to(o.m_EthFlowDescs);
        o.m_EthFlowDescsIsSet = true;
    } 
    if(j.find("dnns") != j.end())
    {
        j.at("dnns").get_to(o.m_Dnns);
        o.m_DnnsIsSet = true;
    } 
    if(j.find("connCaps") != j.end())
    {
        j.at("connCaps").get_to(o.m_ConnCaps);
        o.m_ConnCapsIsSet = true;
    } 
    
}

std::map<std::string, oai::model::AppDescriptor> TrafficDescriptorComponents::getAppDescs() const
{
    return m_AppDescs;
}
void TrafficDescriptorComponents::setAppDescs(std::map<std::string, oai::model::AppDescriptor> const& value)
{
    m_AppDescs = value;
    m_AppDescsIsSet = true;
}
bool TrafficDescriptorComponents::appDescsIsSet() const
{
    return m_AppDescsIsSet;
}
void TrafficDescriptorComponents::unsetAppDescs()
{
    m_AppDescsIsSet = false;
}
std::vector<std::string> TrafficDescriptorComponents::getFlowDescs() const
{
    return m_FlowDescs;
}
void TrafficDescriptorComponents::setFlowDescs(std::vector<std::string> const& value)
{
    m_FlowDescs = value;
    m_FlowDescsIsSet = true;
}
bool TrafficDescriptorComponents::flowDescsIsSet() const
{
    return m_FlowDescsIsSet;
}
void TrafficDescriptorComponents::unsetFlowDescs()
{
    m_FlowDescsIsSet = false;
}
std::vector<std::string> TrafficDescriptorComponents::getDomainDescs() const
{
    return m_DomainDescs;
}
void TrafficDescriptorComponents::setDomainDescs(std::vector<std::string> const& value)
{
    m_DomainDescs = value;
    m_DomainDescsIsSet = true;
}
bool TrafficDescriptorComponents::domainDescsIsSet() const
{
    return m_DomainDescsIsSet;
}
void TrafficDescriptorComponents::unsetDomainDescs()
{
    m_DomainDescsIsSet = false;
}
std::vector<oai::model::EthFlowDescription> TrafficDescriptorComponents::getEthFlowDescs() const
{
    return m_EthFlowDescs;
}
void TrafficDescriptorComponents::setEthFlowDescs(std::vector<oai::model::EthFlowDescription> const& value)
{
    m_EthFlowDescs = value;
    m_EthFlowDescsIsSet = true;
}
bool TrafficDescriptorComponents::ethFlowDescsIsSet() const
{
    return m_EthFlowDescsIsSet;
}
void TrafficDescriptorComponents::unsetEthFlowDescs()
{
    m_EthFlowDescsIsSet = false;
}
std::vector<std::string> TrafficDescriptorComponents::getDnns() const
{
    return m_Dnns;
}
void TrafficDescriptorComponents::setDnns(std::vector<std::string> const& value)
{
    m_Dnns = value;
    m_DnnsIsSet = true;
}
bool TrafficDescriptorComponents::dnnsIsSet() const
{
    return m_DnnsIsSet;
}
void TrafficDescriptorComponents::unsetDnns()
{
    m_DnnsIsSet = false;
}
std::vector<oai::model::ConnectionCapabilities> TrafficDescriptorComponents::getConnCaps() const
{
    return m_ConnCaps;
}
void TrafficDescriptorComponents::setConnCaps(std::vector<oai::model::ConnectionCapabilities> const& value)
{
    m_ConnCaps = value;
    m_ConnCapsIsSet = true;
}
bool TrafficDescriptorComponents::connCapsIsSet() const
{
    return m_ConnCapsIsSet;
}
void TrafficDescriptorComponents::unsetConnCaps()
{
    m_ConnCapsIsSet = false;
}


} // namespace oai::model

