/**
* Npcf_PolicyAuthorization Service API
* PCF Policy Authorization Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
*
* The version of the OpenAPI document: 1.2.3
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "TransportProtocol_1.h"
#include "Helpers.h"

#include <sstream>

namespace oai::_3gpp::model
{

TransportProtocol_1::TransportProtocol_1()
{
    
}

void TransportProtocol_1::validate() const
{
    std::stringstream msg;
    if (!validate(msg))
    {
        throw oai::_3gpp::model::helpers::ValidationException(msg.str());
    }
}

bool TransportProtocol_1::validate(std::stringstream& msg) const
{
    return validate(msg, "");
}

bool TransportProtocol_1::validate(std::stringstream& msg, const std::string& pathPrefix) const
{
    bool success = true;
    const std::string _pathPrefix = pathPrefix.empty() ? "TransportProtocol_1" : pathPrefix;

    
    if (!m_value.validate(msg))
    {
        success = false;
    }
    return success;
}

bool TransportProtocol_1::operator==(const TransportProtocol_1& rhs) const
{
    return
    
    getValue() == rhs.getValue()
    ;
}

bool TransportProtocol_1::operator!=(const TransportProtocol_1& rhs) const
{
    return !(*this == rhs);
}

void to_json(nlohmann::json& j, const TransportProtocol_1& o)
{
    j = nlohmann::json();
    to_json(j, o.m_value);
}

void from_json(const nlohmann::json& j, TransportProtocol_1& o)
{
    from_json(j, o.m_value);
}

TransportProtocol_1_anyOf TransportProtocol_1::getValue() const
{
    return m_value;
}

void TransportProtocol_1::setValue(TransportProtocol_1_anyOf value)
{
    m_value = value;
}

TransportProtocol_1_anyOf::eTransportProtocol_1_anyOf TransportProtocol_1::getEnumValue() const
{
    return m_value.getValue();
}

void TransportProtocol_1::setEnumValue(TransportProtocol_1_anyOf::eTransportProtocol_1_anyOf  value)
{
    m_value.setValue(value);
}

} // namespace oai::_3gpp::model

