/**
* Namf_Communication
* AMF Communication Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
*
* The version of the OpenAPI document: 1.2.4
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "TransferReason.h"
#include "Helpers.h"

#include <sstream>

namespace oai::model
{

TransferReason::TransferReason()
{
    
}

void TransferReason::validate() const
{
    std::stringstream msg;
    if (!validate(msg))
    {
        throw org::openapitools::server::helpers::ValidationException(msg.str());
    }
}

bool TransferReason::validate(std::stringstream& msg) const
{
    return validate(msg, "");
}

bool TransferReason::validate(std::stringstream& msg, const std::string& pathPrefix) const
{
    bool success = true;
    const std::string _pathPrefix = pathPrefix.empty() ? "TransferReason" : pathPrefix;

    
    return success;
}

bool TransferReason::operator==(const TransferReason& rhs) const
{
    return
    
    
    ;
}

bool TransferReason::operator!=(const TransferReason& rhs) const
{
    return !(*this == rhs);
}

void to_json(nlohmann::json& j, const TransferReason& o)
{
    j = nlohmann::json::object();
    
}

void from_json(const nlohmann::json& j, TransferReason& o)
{
    
}



} // namespace oai::model

