################################################################################
# Licensed to the OpenAirInterface (OAI) Software Alliance under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The OpenAirInterface Software Alliance licenses this file to You under
# the OAI Public License, Version 1.1  (the "License"); you may not use this file
# except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.openairinterface.org/?page_id=698
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#-------------------------------------------------------------------------------
# For more information about the OpenAirInterface (OAI) Software Alliance:
#      contact@openairinterface.org
################################################################################

SET(UDM_MODEL_DIR ${SRC_TOP_DIR}/${MOUNTED_COMMON}/model)

include_directories(${UDM_MODEL_DIR})

file(GLOB UDM_MODEL_SRC_FILES
    ${UDM_MODEL_DIR}/AccessAndMobilitySubscriptionData.cpp
    ${UDM_MODEL_DIR}/AccessAndMobilitySubscriptionData_subscribedDnnList_inner.cpp
    ${UDM_MODEL_DIR}/AccessNetworkId.cpp
    ${UDM_MODEL_DIR}/AccessNetworkId_anyOf.cpp
    ${UDM_MODEL_DIR}/AccessTech.cpp
    ${UDM_MODEL_DIR}/AccessTech_anyOf.cpp
    ${UDM_MODEL_DIR}/AccessTokenErr.cpp
    ${UDM_MODEL_DIR}/AccessTokenReq.cpp
    ${UDM_MODEL_DIR}/AccessType.cpp
    ${UDM_MODEL_DIR}/AcknowledgeInfo.cpp
    ${UDM_MODEL_DIR}/AcsInfo.cpp
    ${UDM_MODEL_DIR}/AcsInfoRm.cpp
    ${UDM_MODEL_DIR}/AdditionalSnssaiData.cpp
    ${UDM_MODEL_DIR}/AerialUeIndication.cpp
    ${UDM_MODEL_DIR}/AerialUeIndication_anyOf.cpp
    ${UDM_MODEL_DIR}/AerialUeSubscriptionInfo.cpp
    ${UDM_MODEL_DIR}/AfExternal.cpp
    ${UDM_MODEL_DIR}/Ambr.cpp
    ${UDM_MODEL_DIR}/AmbrRm.cpp
    ${UDM_MODEL_DIR}/Amf3GppAccessRegistration.cpp
    ${UDM_MODEL_DIR}/Amf3GppAccessRegistrationModification.cpp
    ${UDM_MODEL_DIR}/AmfDeregInfo.cpp
    ${UDM_MODEL_DIR}/AmfInfo.cpp
    ${UDM_MODEL_DIR}/AmfNon3GppAccessRegistration.cpp
    ${UDM_MODEL_DIR}/AmfNon3GppAccessRegistrationModification.cpp
    ${UDM_MODEL_DIR}/AppDescriptor.cpp
    ${UDM_MODEL_DIR}/AppPortId.cpp
    ${UDM_MODEL_DIR}/Area.cpp
    ${UDM_MODEL_DIR}/AreaScope.cpp
    ${UDM_MODEL_DIR}/Arp.cpp
    ${UDM_MODEL_DIR}/AssociationType.cpp
    ${UDM_MODEL_DIR}/AssociationType_anyOf.cpp
    ${UDM_MODEL_DIR}/AtsssCapability.cpp
    ${UDM_MODEL_DIR}/AuthEvent.cpp
    ${UDM_MODEL_DIR}/AuthResult.cpp
    ${UDM_MODEL_DIR}/AuthType.cpp
    ${UDM_MODEL_DIR}/AuthType_anyOf.cpp
    ${UDM_MODEL_DIR}/AuthUpdateInfo.cpp
    ${UDM_MODEL_DIR}/AuthUpdateNotification.cpp
    ${UDM_MODEL_DIR}/AuthenticationInfoRequest.cpp
    ${UDM_MODEL_DIR}/AuthenticationInfoResult.cpp
    ${UDM_MODEL_DIR}/AuthenticationVector.cpp
    ${UDM_MODEL_DIR}/AuthorizationData.cpp
    ${UDM_MODEL_DIR}/AuthorizationInfo.cpp
    ${UDM_MODEL_DIR}/AuthorizationUeId.cpp
    ${UDM_MODEL_DIR}/Av5GHeAka.cpp
    ${UDM_MODEL_DIR}/AvEapAkaPrime.cpp
    ${UDM_MODEL_DIR}/AvEpsAka.cpp
    ${UDM_MODEL_DIR}/AvImsGbaEapAka.cpp
    ${UDM_MODEL_DIR}/AvType.cpp
    ${UDM_MODEL_DIR}/AvType_anyOf.cpp
    ${UDM_MODEL_DIR}/BackupAmfInfo.cpp
    ${UDM_MODEL_DIR}/BatteryIndication.cpp
    ${UDM_MODEL_DIR}/BatteryIndicationRm.cpp
    ${UDM_MODEL_DIR}/CagData.cpp
    ${UDM_MODEL_DIR}/CagInfo.cpp
    ${UDM_MODEL_DIR}/CellGlobalId.cpp
    ${UDM_MODEL_DIR}/ChangeItem.cpp
    ${UDM_MODEL_DIR}/ChangeOfSupiPeiAssociationReport.cpp
    ${UDM_MODEL_DIR}/ChangeType.cpp
    ${UDM_MODEL_DIR}/ChangeType_anyOf.cpp
    ${UDM_MODEL_DIR}/CivicAddress.cpp
    ${UDM_MODEL_DIR}/CmInfo.cpp
    ${UDM_MODEL_DIR}/CmInfoReport.cpp
    ${UDM_MODEL_DIR}/CmState.cpp
    ${UDM_MODEL_DIR}/CmState_anyOf.cpp
    ${UDM_MODEL_DIR}/CnType.cpp
    ${UDM_MODEL_DIR}/CnTypeChangeReport.cpp
    ${UDM_MODEL_DIR}/CnType_anyOf.cpp
    ${UDM_MODEL_DIR}/CodeWordInd.cpp
    ${UDM_MODEL_DIR}/CodeWordInd_anyOf.cpp
    ${UDM_MODEL_DIR}/CollectionPeriodRmmLteMdt.cpp
    ${UDM_MODEL_DIR}/CollectionPeriodRmmLteMdt_anyOf.cpp
    ${UDM_MODEL_DIR}/CollectionPeriodRmmNrMdt.cpp
    ${UDM_MODEL_DIR}/CollectionPeriodRmmNrMdt_anyOf.cpp
    ${UDM_MODEL_DIR}/CommunicationCharacteristics.cpp
    ${UDM_MODEL_DIR}/CommunicationCharacteristicsAF.cpp
    ${UDM_MODEL_DIR}/ContextInfo.cpp
    ${UDM_MODEL_DIR}/CoreNetworkType.cpp
    ${UDM_MODEL_DIR}/CoreNetworkType_anyOf.cpp
    ${UDM_MODEL_DIR}/CreatedEeSubscription.cpp
    ${UDM_MODEL_DIR}/DataRestorationNotification.cpp
    ${UDM_MODEL_DIR}/DataSetName.cpp
    ${UDM_MODEL_DIR}/DataSetName_anyOf.cpp
    ${UDM_MODEL_DIR}/DatalinkReportingConfiguration.cpp
    ${UDM_MODEL_DIR}/DddTrafficDescriptor.cpp
    ${UDM_MODEL_DIR}/DeconcealReqData.cpp
    ${UDM_MODEL_DIR}/DeconcealRspData.cpp
    ${UDM_MODEL_DIR}/DefaultUnrelatedClass.cpp
    ${UDM_MODEL_DIR}/DeregistrationData.cpp
    ${UDM_MODEL_DIR}/DeregistrationReason.cpp
    ${UDM_MODEL_DIR}/DeregistrationReason_anyOf.cpp
    ${UDM_MODEL_DIR}/DlDataDeliveryStatus.cpp
    ${UDM_MODEL_DIR}/DlDataDeliveryStatus_anyOf.cpp
    ${UDM_MODEL_DIR}/DnnConfiguration.cpp
    ${UDM_MODEL_DIR}/DnnInfo.cpp
    ${UDM_MODEL_DIR}/EcRestriction.cpp
    ${UDM_MODEL_DIR}/EcRestrictionDataWb.cpp
    ${UDM_MODEL_DIR}/Ecgi.cpp
    ${UDM_MODEL_DIR}/EcsAddrConfigInfo.cpp
    ${UDM_MODEL_DIR}/EcsServerAddr.cpp
    ${UDM_MODEL_DIR}/EdrxParameters.cpp
    ${UDM_MODEL_DIR}/EeMonitoringRevoked.cpp
    ${UDM_MODEL_DIR}/EeSubscription.cpp
    ${UDM_MODEL_DIR}/EllipsoidArc.cpp
    ${UDM_MODEL_DIR}/EmergencyInfo.cpp
    ${UDM_MODEL_DIR}/EnhancedCoverageRestrictionData.cpp
    ${UDM_MODEL_DIR}/EpsInterworkingInfo.cpp
    ${UDM_MODEL_DIR}/EpsIwkPgw.cpp
    ${UDM_MODEL_DIR}/EutraLocation.cpp
    ${UDM_MODEL_DIR}/EventForMdt.cpp
    ${UDM_MODEL_DIR}/EventForMdt_anyOf.cpp
    ${UDM_MODEL_DIR}/EventId.cpp
    ${UDM_MODEL_DIR}/EventId_anyOf.cpp
    ${UDM_MODEL_DIR}/EventReportMode.cpp
    ${UDM_MODEL_DIR}/EventReportMode_anyOf.cpp
    ${UDM_MODEL_DIR}/EventType.cpp
    ${UDM_MODEL_DIR}/EventType_anyOf.cpp
    ${UDM_MODEL_DIR}/ExpectedUeBehaviour.cpp
    ${UDM_MODEL_DIR}/ExpectedUeBehaviourData.cpp
    ${UDM_MODEL_DIR}/ExtendedSmSubsData.cpp
    ${UDM_MODEL_DIR}/ExternalUnrelatedClass.cpp
    ${UDM_MODEL_DIR}/FailedCause.cpp
    ${UDM_MODEL_DIR}/FailedCause_anyOf.cpp
    ${UDM_MODEL_DIR}/FailedMonitoringConfiguration.cpp
    ${UDM_MODEL_DIR}/FqdnRm.cpp
    ${UDM_MODEL_DIR}/FrameRouteInfo.cpp
    ${UDM_MODEL_DIR}/GADShape.cpp
    ${UDM_MODEL_DIR}/GNbId.cpp
    ${UDM_MODEL_DIR}/GbaAuthType.cpp
    ${UDM_MODEL_DIR}/GbaAuthType_anyOf.cpp
    ${UDM_MODEL_DIR}/GbaAuthenticationInfoRequest.cpp
    ${UDM_MODEL_DIR}/GbaAuthenticationInfoResult.cpp
    ${UDM_MODEL_DIR}/GeoServiceArea.cpp
    ${UDM_MODEL_DIR}/GeographicArea.cpp
    ${UDM_MODEL_DIR}/GeographicalCoordinates.cpp
    ${UDM_MODEL_DIR}/GeraLocation.cpp
    ${UDM_MODEL_DIR}/GlobalRanNodeId.cpp
    ${UDM_MODEL_DIR}/GpsiType.cpp
    ${UDM_MODEL_DIR}/GpsiType_anyOf.cpp
    ${UDM_MODEL_DIR}/GroupIdentifiers.cpp
    ${UDM_MODEL_DIR}/Guami.cpp
    ${UDM_MODEL_DIR}/HfcNodeId.cpp
    ${UDM_MODEL_DIR}/HssAuthType.cpp
    ${UDM_MODEL_DIR}/HssAuthTypeInUri.cpp
    ${UDM_MODEL_DIR}/HssAuthTypeInUri_anyOf.cpp
    ${UDM_MODEL_DIR}/HssAuthType_anyOf.cpp
    ${UDM_MODEL_DIR}/HssAuthenticationInfoRequest.cpp
    ${UDM_MODEL_DIR}/HssAuthenticationInfoResult.cpp
    ${UDM_MODEL_DIR}/HssAuthenticationVectors.cpp
    ${UDM_MODEL_DIR}/HssAvType.cpp
    ${UDM_MODEL_DIR}/HssAvType_anyOf.cpp
    ${UDM_MODEL_DIR}/IdTranslationResult.cpp
    ${UDM_MODEL_DIR}/IdentityRange.cpp
    ${UDM_MODEL_DIR}/IdleStatusIndication.cpp
    ${UDM_MODEL_DIR}/ImmediateReport.cpp
    ${UDM_MODEL_DIR}/ImsVoPs.cpp
    ${UDM_MODEL_DIR}/ImsVoPs_anyOf.cpp
    ${UDM_MODEL_DIR}/InterFreqTargetInfo.cpp
    ${UDM_MODEL_DIR}/InvalidCause.cpp
    ${UDM_MODEL_DIR}/InvalidCause_anyOf.cpp
    ${UDM_MODEL_DIR}/InvalidParam.cpp
    ${UDM_MODEL_DIR}/IpAddr.cpp
    ${UDM_MODEL_DIR}/IpAddress.cpp
    ${UDM_MODEL_DIR}/IpIndex.cpp
    ${UDM_MODEL_DIR}/IpSmGwGuidance.cpp
    ${UDM_MODEL_DIR}/IpSmGwInfo.cpp
    ${UDM_MODEL_DIR}/IpSmGwRegistration.cpp
    ${UDM_MODEL_DIR}/Ipv6Addr.cpp
    ${UDM_MODEL_DIR}/Ipv6Prefix.cpp
    ${UDM_MODEL_DIR}/JobType.cpp
    ${UDM_MODEL_DIR}/JobType_anyOf.cpp
    ${UDM_MODEL_DIR}/LcsBroadcastAssistanceTypesData.cpp
    ${UDM_MODEL_DIR}/LcsClientClass.cpp
    ${UDM_MODEL_DIR}/LcsClientClass_anyOf.cpp
    ${UDM_MODEL_DIR}/LcsClientExternal.cpp
    ${UDM_MODEL_DIR}/LcsClientGroupExternal.cpp
    ${UDM_MODEL_DIR}/LcsMoData.cpp
    ${UDM_MODEL_DIR}/LcsMoServiceClass.cpp
    ${UDM_MODEL_DIR}/LcsMoServiceClass_anyOf.cpp
    ${UDM_MODEL_DIR}/LcsPrivacy.cpp
    ${UDM_MODEL_DIR}/LcsPrivacyData.cpp
    ${UDM_MODEL_DIR}/LineType.cpp
    ${UDM_MODEL_DIR}/LineType_anyOf.cpp
    ${UDM_MODEL_DIR}/LocationAccuracy.cpp
    ${UDM_MODEL_DIR}/LocationAccuracy_anyOf.cpp
    ${UDM_MODEL_DIR}/LocationArea.cpp
    ${UDM_MODEL_DIR}/LocationAreaId.cpp
    ${UDM_MODEL_DIR}/LocationInfo.cpp
    ${UDM_MODEL_DIR}/LocationInfoRequest.cpp
    ${UDM_MODEL_DIR}/LocationInfoResult.cpp
    ${UDM_MODEL_DIR}/LocationPrivacyInd.cpp
    ${UDM_MODEL_DIR}/LocationPrivacyInd_anyOf.cpp
    ${UDM_MODEL_DIR}/LocationReport.cpp
    ${UDM_MODEL_DIR}/LocationReportingConfiguration.cpp
    ${UDM_MODEL_DIR}/LoggingDurationMdt.cpp
    ${UDM_MODEL_DIR}/LoggingDurationMdt_anyOf.cpp
    ${UDM_MODEL_DIR}/LoggingDurationNrMdt.cpp
    ${UDM_MODEL_DIR}/LoggingIntervalMdt.cpp
    ${UDM_MODEL_DIR}/LoggingIntervalMdt_anyOf.cpp
    ${UDM_MODEL_DIR}/LoggingIntervalNrMdt.cpp
    ${UDM_MODEL_DIR}/LoggingIntervalNrMdt_anyOf.cpp
    ${UDM_MODEL_DIR}/LossConnectivityCfg.cpp
    ${UDM_MODEL_DIR}/LossConnectivityReport.cpp
    ${UDM_MODEL_DIR}/LossOfConnectivityReason.cpp
    ${UDM_MODEL_DIR}/LossOfConnectivityReason_anyOf.cpp
    ${UDM_MODEL_DIR}/Lpi.cpp
    ${UDM_MODEL_DIR}/LteV2xAuth.cpp
    ${UDM_MODEL_DIR}/MbsMediaCompRm.cpp
    ${UDM_MODEL_DIR}/MbsQoSReq.cpp
    ${UDM_MODEL_DIR}/MbsMediaInfo.cpp
    ${UDM_MODEL_DIR}/MbsSessionActivityStatus_anyOf.cpp
    ${UDM_MODEL_DIR}/MbsSessionEvent.cpp
    ${UDM_MODEL_DIR}/MbsSessionEventType.cpp
    ${UDM_MODEL_DIR}/MbsSessionEventType_anyOf.cpp
    ${UDM_MODEL_DIR}/MbsSessionId.cpp
    ${UDM_MODEL_DIR}/MbsServiceType_anyOf.cpp    
    ${UDM_MODEL_DIR}/MbsSubscriptionData.cpp
    ${UDM_MODEL_DIR}/MbsfnArea.cpp
    ${UDM_MODEL_DIR}/MdtConfiguration.cpp
    ${UDM_MODEL_DIR}/MdtUserConsent.cpp
    ${UDM_MODEL_DIR}/MdtUserConsent_anyOf.cpp
    ${UDM_MODEL_DIR}/MeasurementLteForMdt.cpp
    ${UDM_MODEL_DIR}/MeasurementLteForMdt_anyOf.cpp
    ${UDM_MODEL_DIR}/MeasurementNrForMdt.cpp
    ${UDM_MODEL_DIR}/MeasurementPeriodLteMdt.cpp
    ${UDM_MODEL_DIR}/MediaType.cpp
    ${UDM_MODEL_DIR}/MediaType_anyOf.cpp
    ${UDM_MODEL_DIR}/ModificationNotification.cpp
    ${UDM_MODEL_DIR}/MonitoringConfiguration.cpp
    ${UDM_MODEL_DIR}/MonitoringEvent.cpp
    ${UDM_MODEL_DIR}/MonitoringReport.cpp
    ${UDM_MODEL_DIR}/MtcProvider.cpp
    ${UDM_MODEL_DIR}/N2InterfaceAmfInfo.cpp
    ${UDM_MODEL_DIR}/N3gaLocation.cpp
    ${UDM_MODEL_DIR}/NFType.cpp
    ${UDM_MODEL_DIR}/NFType_anyOf.cpp
    ${UDM_MODEL_DIR}/Ncgi.cpp
    ${UDM_MODEL_DIR}/NetworkAreaInfo.cpp
    ${UDM_MODEL_DIR}/NetworkNodeDiameterAddress.cpp
    ${UDM_MODEL_DIR}/NiddAuthUpdateInfo.cpp
    ${UDM_MODEL_DIR}/NiddAuthUpdateNotification.cpp
    ${UDM_MODEL_DIR}/NiddCause.cpp
    ${UDM_MODEL_DIR}/NiddCause_anyOf.cpp
    ${UDM_MODEL_DIR}/NiddInformation.cpp
    ${UDM_MODEL_DIR}/NodeType.cpp
    ${UDM_MODEL_DIR}/NodeType_anyOf.cpp
    ${UDM_MODEL_DIR}/NotificationFlag.cpp
    ${UDM_MODEL_DIR}/NotificationFlag_anyOf.cpp
    ${UDM_MODEL_DIR}/NotifyItem.cpp
    ${UDM_MODEL_DIR}/NrLocation.cpp
    ${UDM_MODEL_DIR}/NrV2xAuth.cpp
    ${UDM_MODEL_DIR}/Nssai.cpp
    ${UDM_MODEL_DIR}/NwdafRegistration.cpp
    ${UDM_MODEL_DIR}/NwdafRegistrationInfo.cpp
    ${UDM_MODEL_DIR}/NwdafRegistrationModification.cpp
    ${UDM_MODEL_DIR}/OdbPacketServices.cpp
    ${UDM_MODEL_DIR}/OdbPacketServices_anyOf.cpp
    ${UDM_MODEL_DIR}/OperationMode.cpp
    ${UDM_MODEL_DIR}/OperationMode_anyOf.cpp  
    ${UDM_MODEL_DIR}/PatchItem.cpp
    ${UDM_MODEL_DIR}/PatchOperation.cpp
    ${UDM_MODEL_DIR}/PatchOperation_anyOf.cpp
    ${UDM_MODEL_DIR}/PatchResult.cpp
    ${UDM_MODEL_DIR}/PcfSelectionAssistanceInfo.cpp
    ${UDM_MODEL_DIR}/PcscfAddress.cpp
    ${UDM_MODEL_DIR}/PcscfRestorationNotification.cpp
    ${UDM_MODEL_DIR}/PdnConnectivityStatReport.cpp
    ${UDM_MODEL_DIR}/PdnConnectivityStatus.cpp
    ${UDM_MODEL_DIR}/PdnConnectivityStatus_anyOf.cpp
    ${UDM_MODEL_DIR}/PduSession.cpp
    ${UDM_MODEL_DIR}/PduSessionContinuityInd.cpp
    ${UDM_MODEL_DIR}/PduSessionContinuityInd_anyOf.cpp
    ${UDM_MODEL_DIR}/PduSessionStatusCfg.cpp
    ${UDM_MODEL_DIR}/PduSessionType.cpp
    ${UDM_MODEL_DIR}/PduSessionType_anyOf.cpp
    ${UDM_MODEL_DIR}/PduSessionTypes.cpp
    ${UDM_MODEL_DIR}/PeiUpdateInfo.cpp
    ${UDM_MODEL_DIR}/PgwInfo.cpp
    ${UDM_MODEL_DIR}/PlmnEcInfo.cpp
    ${UDM_MODEL_DIR}/PlmnId.cpp
    ${UDM_MODEL_DIR}/PlmnIdNid.cpp
    ${UDM_MODEL_DIR}/PlmnOperatorClass.cpp
    ${UDM_MODEL_DIR}/PlmnRestriction.cpp
    ${UDM_MODEL_DIR}/Point.cpp
    ${UDM_MODEL_DIR}/PointAltitude.cpp
    ${UDM_MODEL_DIR}/PointAltitudeUncertainty.cpp
    ${UDM_MODEL_DIR}/PointUncertaintyCircle.cpp
    ${UDM_MODEL_DIR}/PointUncertaintyEllipse.cpp
    ${UDM_MODEL_DIR}/Polygon.cpp
    ${UDM_MODEL_DIR}/PositioningMethodMdt.cpp
    ${UDM_MODEL_DIR}/PositioningMethodMdt_anyOf.cpp
    ${UDM_MODEL_DIR}/PpActiveTime.cpp
    ${UDM_MODEL_DIR}/PpData.cpp
    ${UDM_MODEL_DIR}/PpDataEntry.cpp
    ${UDM_MODEL_DIR}/PpDlPacketCountExt.cpp
    ${UDM_MODEL_DIR}/PpMaximumLatency.cpp
    ${UDM_MODEL_DIR}/PpMaximumResponseTime.cpp
    ${UDM_MODEL_DIR}/PpSubsRegTimer.cpp
    ${UDM_MODEL_DIR}/PreemptionCapability.cpp
    ${UDM_MODEL_DIR}/PreemptionCapability_anyOf.cpp
    ${UDM_MODEL_DIR}/PreemptionVulnerability.cpp
    ${UDM_MODEL_DIR}/PreemptionVulnerability_anyOf.cpp
    ${UDM_MODEL_DIR}/PrivacyCheckRelatedAction.cpp
    ${UDM_MODEL_DIR}/PrivacyCheckRelatedAction_anyOf.cpp
    ${UDM_MODEL_DIR}/ProSeAllowedPlmn.cpp
    ${UDM_MODEL_DIR}/ProSeAuthenticationInfoRequest.cpp
    ${UDM_MODEL_DIR}/ProSeAuthenticationInfoResult.cpp
    ${UDM_MODEL_DIR}/ProSeAuthenticationVectors.cpp
    ${UDM_MODEL_DIR}/ProblemDetails.cpp
    ${UDM_MODEL_DIR}/ProseDirectAllowed.cpp
    ${UDM_MODEL_DIR}/ProseDirectAllowed_anyOf.cpp
    ${UDM_MODEL_DIR}/ProseServiceAuth.cpp
    ${UDM_MODEL_DIR}/ProseSubscriptionData.cpp
    ${UDM_MODEL_DIR}/PtwParameters.cpp
    ${UDM_MODEL_DIR}/RatType.cpp
    ${UDM_MODEL_DIR}/RatType_anyOf.cpp
    ${UDM_MODEL_DIR}/ReachabilityForDataConfiguration.cpp
    ${UDM_MODEL_DIR}/ReachabilityForDataReportConfig.cpp
    ${UDM_MODEL_DIR}/ReachabilityForDataReportConfig_anyOf.cpp
    ${UDM_MODEL_DIR}/ReachabilityForSmsConfiguration.cpp
    ${UDM_MODEL_DIR}/ReachabilityForSmsConfiguration_anyOf.cpp
    ${UDM_MODEL_DIR}/ReachabilityForSmsReport.cpp
    ${UDM_MODEL_DIR}/ReachabilityReport.cpp
    ${UDM_MODEL_DIR}/RedirectResponse.cpp
    ${UDM_MODEL_DIR}/RegistrationDataSetName.cpp
    ${UDM_MODEL_DIR}/RegistrationDataSetName_anyOf.cpp
    ${UDM_MODEL_DIR}/RegistrationDataSets.cpp
    ${UDM_MODEL_DIR}/RegistrationLocationInfo.cpp
    ${UDM_MODEL_DIR}/RegistrationReason.cpp
    ${UDM_MODEL_DIR}/RegistrationReason_anyOf.cpp
    ${UDM_MODEL_DIR}/Report.cpp
    ${UDM_MODEL_DIR}/ReportAmountMdt.cpp
    ${UDM_MODEL_DIR}/ReportAmountMdt_anyOf.cpp
    ${UDM_MODEL_DIR}/ReportIntervalMdt.cpp
    ${UDM_MODEL_DIR}/ReportIntervalMdt_anyOf.cpp
    ${UDM_MODEL_DIR}/ReportIntervalNrMdt.cpp
    ${UDM_MODEL_DIR}/ReportIntervalNrMdt_anyOf.cpp
    ${UDM_MODEL_DIR}/ReportItem.cpp
    ${UDM_MODEL_DIR}/ReportTypeMdt.cpp
    ${UDM_MODEL_DIR}/ReportTypeMdt_anyOf.cpp
    ${UDM_MODEL_DIR}/ReportingOptions.cpp
    ${UDM_MODEL_DIR}/ReportingTrigger.cpp
    ${UDM_MODEL_DIR}/ReportingTrigger_anyOf.cpp
    ${UDM_MODEL_DIR}/RestrictionType.cpp
    ${UDM_MODEL_DIR}/RestrictionType_anyOf.cpp
    ${UDM_MODEL_DIR}/ResynchronizationInfo.cpp
    ${UDM_MODEL_DIR}/RevokedCause.cpp
    ${UDM_MODEL_DIR}/RevokedCause_anyOf.cpp
    ${UDM_MODEL_DIR}/RgAuthCtx.cpp
    ${UDM_MODEL_DIR}/RoamingInfoUpdate.cpp
    ${UDM_MODEL_DIR}/RoamingRestrictions.cpp
    ${UDM_MODEL_DIR}/RoamingStatusReport.cpp
    ${UDM_MODEL_DIR}/RoutingAreaId.cpp
    ${UDM_MODEL_DIR}/RoutingInfoSmRequest.cpp
    ${UDM_MODEL_DIR}/RoutingInfoSmResponse.cpp
    ${UDM_MODEL_DIR}/ScheduledCommunicationTime.cpp
    ${UDM_MODEL_DIR}/ScheduledCommunicationTimeRm.cpp
    ${UDM_MODEL_DIR}/ScheduledCommunicationType.cpp
    ${UDM_MODEL_DIR}/ScheduledCommunicationTypeRm.cpp
    ${UDM_MODEL_DIR}/ScheduledCommunicationType_anyOf.cpp
    ${UDM_MODEL_DIR}/SdmSubsModification.cpp
    ${UDM_MODEL_DIR}/SdmSubscription.cpp
    ${UDM_MODEL_DIR}/SensorMeasurement.cpp
    ${UDM_MODEL_DIR}/SensorMeasurement_anyOf.cpp
    ${UDM_MODEL_DIR}/SequenceNumber.cpp
    ${UDM_MODEL_DIR}/ServerAddressingInfo.cpp
    ${UDM_MODEL_DIR}/ServiceAreaId.cpp
    ${UDM_MODEL_DIR}/ServiceAreaRestriction.cpp
    ${UDM_MODEL_DIR}/ServiceName.cpp
    ${UDM_MODEL_DIR}/ServiceName_anyOf.cpp
    ${UDM_MODEL_DIR}/ServiceSpecificAuthorizationData.cpp
    ${UDM_MODEL_DIR}/ServiceSpecificAuthorizationInfo.cpp
    ${UDM_MODEL_DIR}/ServiceSpecificAuthorizationRemoveData.cpp
    ${UDM_MODEL_DIR}/ServiceType.cpp
    ${UDM_MODEL_DIR}/ServiceTypeUnrelatedClass.cpp
    ${UDM_MODEL_DIR}/ServiceType_anyOf.cpp
    ${UDM_MODEL_DIR}/SessionManagementSubscriptionData.cpp   
    ${UDM_MODEL_DIR}/SharedData.cpp
    ${UDM_MODEL_DIR}/SharedDataTreatmentInstruction.cpp
    ${UDM_MODEL_DIR}/SharedDataTreatmentInstruction_anyOf.cpp
    ${UDM_MODEL_DIR}/Sign.cpp   
    ${UDM_MODEL_DIR}/SliceMbr.cpp
    ${UDM_MODEL_DIR}/SliceMbrRm.cpp
    ${UDM_MODEL_DIR}/SmDeliveryStatus.cpp
    ${UDM_MODEL_DIR}/SmSubsData.cpp
    ${UDM_MODEL_DIR}/SmfRegistration.cpp
    ${UDM_MODEL_DIR}/SmfRegistrationInfo.cpp
    ${UDM_MODEL_DIR}/SmfRegistrationModification.cpp
    ${UDM_MODEL_DIR}/SmfSelectionSubscriptionData.cpp
    ${UDM_MODEL_DIR}/SmsManagementSubscriptionData.cpp
    ${UDM_MODEL_DIR}/SmsRouterInfo.cpp
    ${UDM_MODEL_DIR}/SmsSubscriptionData.cpp
    ${UDM_MODEL_DIR}/SmsfInfo.cpp
    ${UDM_MODEL_DIR}/SmsfRegistration.cpp
    ${UDM_MODEL_DIR}/Snssai.cpp
    ${UDM_MODEL_DIR}/SnssaiInfo.cpp
    ${UDM_MODEL_DIR}/SorInfo.cpp
    ${UDM_MODEL_DIR}/SorUpdateIndicator.cpp
    ${UDM_MODEL_DIR}/SorUpdateIndicator_anyOf.cpp
    ${UDM_MODEL_DIR}/SorUpdateInfo.cpp
    ${UDM_MODEL_DIR}/SpatialValidityCond.cpp
    ${UDM_MODEL_DIR}/SqnScheme.cpp
    ${UDM_MODEL_DIR}/SqnScheme_anyOf.cpp
    ${UDM_MODEL_DIR}/SscMode.cpp
    ${UDM_MODEL_DIR}/SscMode_anyOf.cpp
    ${UDM_MODEL_DIR}/SscModes.cpp
    ${UDM_MODEL_DIR}/Ssm.cpp
    ${UDM_MODEL_DIR}/StationaryIndication.cpp
    ${UDM_MODEL_DIR}/StationaryIndicationRm.cpp
    ${UDM_MODEL_DIR}/StationaryIndication_anyOf.cpp
    ${UDM_MODEL_DIR}/SteeringContainer.cpp
    ${UDM_MODEL_DIR}/SteeringInfo.cpp
    ${UDM_MODEL_DIR}/SubscribedDefaultQos.cpp
    ${UDM_MODEL_DIR}/SubscriptionDataSets.cpp
    ${UDM_MODEL_DIR}/SuggestedPacketNumDl.cpp
    ${UDM_MODEL_DIR}/SupiInfo.cpp
    ${UDM_MODEL_DIR}/SupiRange.cpp
    ${UDM_MODEL_DIR}/SupportedGADShapes.cpp
    ${UDM_MODEL_DIR}/SupportedGADShapes_anyOf.cpp
    ${UDM_MODEL_DIR}/TacInfo.cpp
    ${UDM_MODEL_DIR}/TacRange.cpp
    ${UDM_MODEL_DIR}/Tai.cpp
    ${UDM_MODEL_DIR}/TaiRange.cpp
    ${UDM_MODEL_DIR}/Tmgi.cpp
    ${UDM_MODEL_DIR}/TnapId.cpp
    ${UDM_MODEL_DIR}/TraceData.cpp
    ${UDM_MODEL_DIR}/TraceDataResponse.cpp
    ${UDM_MODEL_DIR}/TraceDepth.cpp
    ${UDM_MODEL_DIR}/TraceDepth_anyOf.cpp
    ${UDM_MODEL_DIR}/TrafficProfile.cpp
    ${UDM_MODEL_DIR}/TrafficProfileRm.cpp
    ${UDM_MODEL_DIR}/TrafficProfile_anyOf.cpp
    ${UDM_MODEL_DIR}/TransportProtocol.cpp
    ${UDM_MODEL_DIR}/TransportProtocol_anyOf.cpp
    ${UDM_MODEL_DIR}/TriggerRequest.cpp
    ${UDM_MODEL_DIR}/TwapId.cpp
    ${UDM_MODEL_DIR}/ReservPriority.cpp
    ${UDM_MODEL_DIR}/ReservPriority_anyOf.cpp
    ${UDM_MODEL_DIR}/UcPurpose.cpp
    ${UDM_MODEL_DIR}/UcPurpose_anyOf.cpp
    ${UDM_MODEL_DIR}/UcSubscriptionData.cpp
    ${UDM_MODEL_DIR}/UeAuth.cpp
    ${UDM_MODEL_DIR}/UeAuth_anyOf.cpp
    ${UDM_MODEL_DIR}/UeContextInAmfData.cpp
    ${UDM_MODEL_DIR}/UeContextInSmfData.cpp
    ${UDM_MODEL_DIR}/UeContextInSmfDataSubFilter.cpp
    ${UDM_MODEL_DIR}/UeContextInSmsfData.cpp
    ${UDM_MODEL_DIR}/UeContextInfo.cpp
    ${UDM_MODEL_DIR}/UeContextInfoClass.cpp
    ${UDM_MODEL_DIR}/UeContextInfoClass_anyOf.cpp
    ${UDM_MODEL_DIR}/UeId.cpp
    ${UDM_MODEL_DIR}/UeInfo.cpp
    ${UDM_MODEL_DIR}/UeReachability.cpp
    ${UDM_MODEL_DIR}/UeReachability_anyOf.cpp
    ${UDM_MODEL_DIR}/UeReachableInd.cpp
    ${UDM_MODEL_DIR}/UeReachableInd_anyOf.cpp    
    ${UDM_MODEL_DIR}/UmtTime.cpp
    ${UDM_MODEL_DIR}/UncertaintyEllipse.cpp
    ${UDM_MODEL_DIR}/UnrelatedClass.cpp
    ${UDM_MODEL_DIR}/UpConfidentiality.cpp
    ${UDM_MODEL_DIR}/UpIntegrity.cpp
    ${UDM_MODEL_DIR}/UpIntegrity_anyOf.cpp
    ${UDM_MODEL_DIR}/UpSecurity.cpp
    ${UDM_MODEL_DIR}/UpuData.cpp
    ${UDM_MODEL_DIR}/UpuInfo.cpp
    ${UDM_MODEL_DIR}/UserConsent.cpp
    ${UDM_MODEL_DIR}/UserIdentifier.cpp
    ${UDM_MODEL_DIR}/UserLocation.cpp
    ${UDM_MODEL_DIR}/UtraLocation.cpp
    ${UDM_MODEL_DIR}/V2xSubscriptionData.cpp
    ${UDM_MODEL_DIR}/ValidTimePeriod.cpp
    ${UDM_MODEL_DIR}/VgmlcAddress.cpp
    ${UDM_MODEL_DIR}/VnGroupData.cpp
    ${UDM_MODEL_DIR}/WirelineArea.cpp
    ${UDM_MODEL_DIR}/WirelineServiceAreaRestriction.cpp
    ${UDM_MODEL_DIR}/_5GsUserState_anyOf.cpp
    ${UDM_MODEL_DIR}/r_3GAkaAv.cpp
    ${UDM_MODEL_DIR}/r_5GSrvccInfo.cpp
    ${UDM_MODEL_DIR}/r_5GVnGroupConfiguration.cpp
    ${UDM_MODEL_DIR}/r_5GVnGroupData.cpp
    ${UDM_MODEL_DIR}/r_5GsUserState.cpp
    ${UDM_MODEL_DIR}/r_5MbsAuthorizationInfo.cpp
    ${UDM_MODEL_DIR}/Helpers.cpp

)

if (TARGET ${NF_TARGET})
    target_include_directories(${NF_TARGET} PUBLIC ${UDM_MODEL_DIR})
    target_sources(${NF_TARGET} PRIVATE
            ${UDM_MODEL_SRC_FILES}
            )
endif()
