# SPDX-License-Identifier: LicenseRef-CSSL-1.0

SET(UDR_MODEL_DIR ${SRC_TOP_DIR}/${MOUNTED_COMMON}/model)

include_directories(${UDR_MODEL_DIR})

file(GLOB UDR_MODEL_SRC_FILES
    ${UDR_MODEL_DIR}/AccessAndMobilityData.cpp
    ${UDR_MODEL_DIR}/AccessAndMobilitySubscriptionData.cpp
    ${UDR_MODEL_DIR}/AccessAndMobilitySubscriptionData_subscribedDnnList_inner.cpp
    ${UDR_MODEL_DIR}/AccessTech.cpp
    ${UDR_MODEL_DIR}/AccessTech_anyOf.cpp
    ${UDR_MODEL_DIR}/AccessTokenErr.cpp
    ${UDR_MODEL_DIR}/AccessTokenReq.cpp
    ${UDR_MODEL_DIR}/AccessType.cpp
    ${UDR_MODEL_DIR}/AcsInfo.cpp
    ${UDR_MODEL_DIR}/AcsInfoRm.cpp
    ${UDR_MODEL_DIR}/AdditionalSnssaiData.cpp
    ${UDR_MODEL_DIR}/AerialUeIndication.cpp
    ${UDR_MODEL_DIR}/AerialUeIndication_anyOf.cpp
    ${UDR_MODEL_DIR}/AerialUeSubscriptionInfo.cpp
    ${UDR_MODEL_DIR}/AfExternal.cpp
    ${UDR_MODEL_DIR}/AllowedMtcProviderInfo.cpp
    ${UDR_MODEL_DIR}/AmInfluData.cpp
    ${UDR_MODEL_DIR}/AmInfluEvent.cpp
    ${UDR_MODEL_DIR}/AmInfluEvent_anyOf.cpp
    ${UDR_MODEL_DIR}/AmPolicyData.cpp
    ${UDR_MODEL_DIR}/Ambr.cpp
    ${UDR_MODEL_DIR}/AmbrRm.cpp
    ${UDR_MODEL_DIR}/Amf3GppAccessRegistration.cpp
    ${UDR_MODEL_DIR}/AmfInfo.cpp
    ${UDR_MODEL_DIR}/AmfNon3GppAccessRegistration.cpp
    ${UDR_MODEL_DIR}/AmfSubscriptionInfo.cpp
    ${UDR_MODEL_DIR}/AppDescriptor.cpp
    ${UDR_MODEL_DIR}/AppPortId.cpp
    ${UDR_MODEL_DIR}/ApplicationDataSubs.cpp
    ${UDR_MODEL_DIR}/Area.cpp
    ${UDR_MODEL_DIR}/AreaScope.cpp
    ${UDR_MODEL_DIR}/Arp.cpp
    ${UDR_MODEL_DIR}/AssociationType.cpp
    ${UDR_MODEL_DIR}/AssociationType_anyOf.cpp
    ${UDR_MODEL_DIR}/AuthEvent.cpp
    ${UDR_MODEL_DIR}/AuthMethod.cpp
    ${UDR_MODEL_DIR}/AuthMethod_anyOf.cpp
    ${UDR_MODEL_DIR}/AuthType.cpp
    ${UDR_MODEL_DIR}/AuthType_anyOf.cpp
    ${UDR_MODEL_DIR}/AuthenticationSubscription.cpp
    ${UDR_MODEL_DIR}/AuthorizationData.cpp
    ${UDR_MODEL_DIR}/BackupAmfInfo.cpp
    ${UDR_MODEL_DIR}/BatteryIndication.cpp
    ${UDR_MODEL_DIR}/BatteryIndicationRm.cpp
    ${UDR_MODEL_DIR}/BdtData.cpp
    ${UDR_MODEL_DIR}/BdtDataPatch.cpp
    ${UDR_MODEL_DIR}/BdtPolicyData.cpp
    ${UDR_MODEL_DIR}/BdtPolicyDataPatch.cpp
    ${UDR_MODEL_DIR}/BdtPolicyStatus.cpp
    ${UDR_MODEL_DIR}/BdtPolicyStatus_anyOf.cpp
    ${UDR_MODEL_DIR}/CagAckData.cpp
    ${UDR_MODEL_DIR}/CagData.cpp
    ${UDR_MODEL_DIR}/CagInfo.cpp
    ${UDR_MODEL_DIR}/CellGlobalId.cpp
    ${UDR_MODEL_DIR}/ChargingInformation.cpp
    ${UDR_MODEL_DIR}/CivicAddress.cpp
    ${UDR_MODEL_DIR}/CmInfo.cpp
    ${UDR_MODEL_DIR}/CmState.cpp
    ${UDR_MODEL_DIR}/CmState_anyOf.cpp
    ${UDR_MODEL_DIR}/CodeWordInd.cpp
    ${UDR_MODEL_DIR}/CodeWordInd_anyOf.cpp
    ${UDR_MODEL_DIR}/CollectionPeriodRmmLteMdt.cpp
    ${UDR_MODEL_DIR}/CollectionPeriodRmmLteMdt_anyOf.cpp
    ${UDR_MODEL_DIR}/CollectionPeriodRmmNrMdt.cpp
    ${UDR_MODEL_DIR}/CollectionPeriodRmmNrMdt_anyOf.cpp
    ${UDR_MODEL_DIR}/CommunicationCharacteristics.cpp
    ${UDR_MODEL_DIR}/ContextDataSetName.cpp
    ${UDR_MODEL_DIR}/ContextDataSetName_anyOf.cpp
    ${UDR_MODEL_DIR}/ContextDataSets.cpp
    ${UDR_MODEL_DIR}/ContextInfo.cpp
    ${UDR_MODEL_DIR}/CoreNetworkType.cpp
    ${UDR_MODEL_DIR}/CoreNetworkType_anyOf.cpp
    ${UDR_MODEL_DIR}/DataFilter.cpp
    ${UDR_MODEL_DIR}/DataInd.cpp
    ${UDR_MODEL_DIR}/DataInd_anyOf.cpp
    ${UDR_MODEL_DIR}/DataSetName.cpp
    ${UDR_MODEL_DIR}/DataSetName_anyOf.cpp
    ${UDR_MODEL_DIR}/DatalinkReportingConfiguration.cpp
    ${UDR_MODEL_DIR}/DddTrafficDescriptor.cpp
    ${UDR_MODEL_DIR}/DefaultUnrelatedClass.cpp
    ${UDR_MODEL_DIR}/DlDataDeliveryStatus.cpp
    ${UDR_MODEL_DIR}/DlDataDeliveryStatus_anyOf.cpp
    ${UDR_MODEL_DIR}/DnaiChangeType.cpp
    ${UDR_MODEL_DIR}/DnaiChangeType_anyOf.cpp
    ${UDR_MODEL_DIR}/DnnConfiguration.cpp
    ${UDR_MODEL_DIR}/DnnRouteSelectionDescriptor.cpp
    ${UDR_MODEL_DIR}/DnnSnssaiInformation.cpp
    ${UDR_MODEL_DIR}/DomainNameProtocol.cpp
    ${UDR_MODEL_DIR}/DomainNameProtocol_anyOf.cpp
    ${UDR_MODEL_DIR}/EcRestriction.cpp
    ${UDR_MODEL_DIR}/EcRestrictionDataWb.cpp
    ${UDR_MODEL_DIR}/Ecgi.cpp
    ${UDR_MODEL_DIR}/EcsAddrConfigInfo.cpp
    ${UDR_MODEL_DIR}/EcsServerAddr.cpp
    ${UDR_MODEL_DIR}/EdrxParameters.cpp
    ${UDR_MODEL_DIR}/EeProfileData.cpp
    ${UDR_MODEL_DIR}/EeSubscription.cpp
    ${UDR_MODEL_DIR}/EllipsoidArc.cpp
    ${UDR_MODEL_DIR}/EmergencyInfo.cpp
    ${UDR_MODEL_DIR}/EnhancedCoverageRestrictionData.cpp
    ${UDR_MODEL_DIR}/EpsInterworkingInfo.cpp
    ${UDR_MODEL_DIR}/EpsIwkPgw.cpp
    ${UDR_MODEL_DIR}/EthFlowDescription.cpp
    ${UDR_MODEL_DIR}/EutraLocation.cpp
    ${UDR_MODEL_DIR}/EventForMdt.cpp
    ${UDR_MODEL_DIR}/EventForMdt_anyOf.cpp
    ${UDR_MODEL_DIR}/EventReportMode.cpp
    ${UDR_MODEL_DIR}/EventReportMode_anyOf.cpp
    ${UDR_MODEL_DIR}/EventType.cpp
    ${UDR_MODEL_DIR}/EventType_anyOf.cpp
    ${UDR_MODEL_DIR}/ExpectedUeBehaviour.cpp
    ${UDR_MODEL_DIR}/ExpectedUeBehaviourData.cpp
    ${UDR_MODEL_DIR}/ExposureDataSubscription.cpp
    ${UDR_MODEL_DIR}/ExtendedSmSubsData.cpp
    ${UDR_MODEL_DIR}/ExternalUnrelatedClass.cpp
    ${UDR_MODEL_DIR}/FlowDirection.cpp
    ${UDR_MODEL_DIR}/FlowDirection_anyOf.cpp
    ${UDR_MODEL_DIR}/FlowInfo.cpp
    ${UDR_MODEL_DIR}/FrameRouteInfo.cpp
    ${UDR_MODEL_DIR}/GADShape.cpp
    ${UDR_MODEL_DIR}/GNbId.cpp
    ${UDR_MODEL_DIR}/GeoServiceArea.cpp
    ${UDR_MODEL_DIR}/GeographicArea.cpp
    ${UDR_MODEL_DIR}/GeographicalCoordinates.cpp
    ${UDR_MODEL_DIR}/GeraLocation.cpp
    ${UDR_MODEL_DIR}/GlobalRanNodeId.cpp
    ${UDR_MODEL_DIR}/GroupIdentifiers.cpp
    ${UDR_MODEL_DIR}/Guami.cpp
    ${UDR_MODEL_DIR}/Helpers.cpp
    ${UDR_MODEL_DIR}/HfcNodeId.cpp
    ${UDR_MODEL_DIR}/HssSubscriptionInfo.cpp
    ${UDR_MODEL_DIR}/HssSubscriptionItem.cpp
    ${UDR_MODEL_DIR}/IdentityData.cpp
    ${UDR_MODEL_DIR}/ImmediateReport.cpp
    ${UDR_MODEL_DIR}/ImsVoPs.cpp
    ${UDR_MODEL_DIR}/ImsVoPs_anyOf.cpp
    ${UDR_MODEL_DIR}/InterFreqTargetInfo.cpp
    ${UDR_MODEL_DIR}/InvalidParam.cpp
    ${UDR_MODEL_DIR}/IpAddr.cpp
    ${UDR_MODEL_DIR}/IpAddress.cpp
    ${UDR_MODEL_DIR}/IpIndex.cpp
    ${UDR_MODEL_DIR}/IpSmGwRegistration.cpp
    ${UDR_MODEL_DIR}/IptvConfigData.cpp
    ${UDR_MODEL_DIR}/IptvConfigDataPatch.cpp
    ${UDR_MODEL_DIR}/Ipv6Addr.cpp
    ${UDR_MODEL_DIR}/Ipv6Prefix.cpp
    ${UDR_MODEL_DIR}/JobType.cpp
    ${UDR_MODEL_DIR}/JobType_anyOf.cpp
    ${UDR_MODEL_DIR}/LcsBroadcastAssistanceTypesData.cpp
    ${UDR_MODEL_DIR}/LcsClientClass.cpp
    ${UDR_MODEL_DIR}/LcsClientClass_anyOf.cpp
    ${UDR_MODEL_DIR}/LcsClientExternal.cpp
    ${UDR_MODEL_DIR}/LcsClientGroupExternal.cpp
    ${UDR_MODEL_DIR}/LcsMoData.cpp
    ${UDR_MODEL_DIR}/LcsMoServiceClass.cpp
    ${UDR_MODEL_DIR}/LcsMoServiceClass_anyOf.cpp
    ${UDR_MODEL_DIR}/LcsPrivacy.cpp
    ${UDR_MODEL_DIR}/LcsPrivacyData.cpp
    ${UDR_MODEL_DIR}/LimitIdToMonitoringKey.cpp
    ${UDR_MODEL_DIR}/LineType.cpp
    ${UDR_MODEL_DIR}/LineType_anyOf.cpp
    ${UDR_MODEL_DIR}/LocationAccuracy.cpp
    ${UDR_MODEL_DIR}/LocationAccuracy_anyOf.cpp
    ${UDR_MODEL_DIR}/LocationArea.cpp
    ${UDR_MODEL_DIR}/LocationAreaId.cpp
    ${UDR_MODEL_DIR}/LocationInfo.cpp
    ${UDR_MODEL_DIR}/LocationPrivacyInd.cpp
    ${UDR_MODEL_DIR}/LocationPrivacyInd_anyOf.cpp
    ${UDR_MODEL_DIR}/LocationReportingConfiguration.cpp
    ${UDR_MODEL_DIR}/LoggingDurationMdt.cpp
    ${UDR_MODEL_DIR}/LoggingDurationMdt_anyOf.cpp
    ${UDR_MODEL_DIR}/LoggingDurationNrMdt.cpp
    ${UDR_MODEL_DIR}/LoggingIntervalMdt.cpp
    ${UDR_MODEL_DIR}/LoggingIntervalMdt_anyOf.cpp
    ${UDR_MODEL_DIR}/LoggingIntervalNrMdt.cpp
    ${UDR_MODEL_DIR}/LoggingIntervalNrMdt_anyOf.cpp
    ${UDR_MODEL_DIR}/LossConnectivityCfg.cpp
    ${UDR_MODEL_DIR}/Lpi.cpp
    ${UDR_MODEL_DIR}/LteV2xAuth.cpp
    ${UDR_MODEL_DIR}/MbsSessionId.cpp
    ${UDR_MODEL_DIR}/MbsSubscriptionData.cpp
    ${UDR_MODEL_DIR}/MbsfnArea.cpp
    ${UDR_MODEL_DIR}/MdtConfiguration.cpp
    ${UDR_MODEL_DIR}/MdtUserConsent.cpp
    ${UDR_MODEL_DIR}/MdtUserConsent_anyOf.cpp
    ${UDR_MODEL_DIR}/MeasurementLteForMdt.cpp
    ${UDR_MODEL_DIR}/MeasurementLteForMdt_anyOf.cpp
    ${UDR_MODEL_DIR}/MeasurementNrForMdt.cpp
    ${UDR_MODEL_DIR}/MeasurementPeriodLteMdt.cpp
    ${UDR_MODEL_DIR}/MessageWaitingData.cpp
    ${UDR_MODEL_DIR}/MonitoringConfiguration.cpp
    ${UDR_MODEL_DIR}/MtcProvider.cpp
    ${UDR_MODEL_DIR}/MulticastAccessControl.cpp
    ${UDR_MODEL_DIR}/MulticastAccessControl_anyOf.cpp
    ${UDR_MODEL_DIR}/N2InterfaceAmfInfo.cpp
    ${UDR_MODEL_DIR}/N3gaLocation.cpp
    ${UDR_MODEL_DIR}/NFType.cpp
    ${UDR_MODEL_DIR}/NFType_anyOf.cpp
    ${UDR_MODEL_DIR}/Ncgi.cpp
    ${UDR_MODEL_DIR}/NetworkAreaInfo.cpp
    ${UDR_MODEL_DIR}/NetworkNodeDiameterAddress.cpp
    ${UDR_MODEL_DIR}/NiddInformation.cpp
    ${UDR_MODEL_DIR}/NotificationFlag.cpp
    ${UDR_MODEL_DIR}/NotificationFlag_anyOf.cpp
    ${UDR_MODEL_DIR}/NrLocation.cpp
    ${UDR_MODEL_DIR}/NrV2xAuth.cpp
    ${UDR_MODEL_DIR}/Nssai.cpp
    ${UDR_MODEL_DIR}/NssaiAckData.cpp
    ${UDR_MODEL_DIR}/OdbData.cpp
    ${UDR_MODEL_DIR}/OdbPacketServices.cpp
    ${UDR_MODEL_DIR}/OperationMode.cpp
    ${UDR_MODEL_DIR}/OperationMode_anyOf.cpp
    ${UDR_MODEL_DIR}/OperatorSpecificDataContainer.cpp
    ${UDR_MODEL_DIR}/OperatorSpecificDataContainer_value.cpp
    ${UDR_MODEL_DIR}/PatchItem.cpp
    ${UDR_MODEL_DIR}/PatchOperation.cpp
    ${UDR_MODEL_DIR}/PatchOperation_anyOf.cpp
    ${UDR_MODEL_DIR}/PatchResult.cpp
    ${UDR_MODEL_DIR}/PcfSelectionAssistanceInfo.cpp
    ${UDR_MODEL_DIR}/PduSession.cpp
    ${UDR_MODEL_DIR}/PduSessionContinuityInd.cpp
    ${UDR_MODEL_DIR}/PduSessionContinuityInd_anyOf.cpp
    ${UDR_MODEL_DIR}/PduSessionManagementData.cpp
    ${UDR_MODEL_DIR}/PduSessionStatus.cpp
    ${UDR_MODEL_DIR}/PduSessionStatusCfg.cpp
    ${UDR_MODEL_DIR}/PduSessionStatus_anyOf.cpp
    ${UDR_MODEL_DIR}/PduSessionType.cpp
    ${UDR_MODEL_DIR}/PduSessionType_anyOf.cpp
    ${UDR_MODEL_DIR}/PduSessionTypes.cpp
    ${UDR_MODEL_DIR}/PeiUpdateInfo.cpp
    ${UDR_MODEL_DIR}/Periodicity.cpp
    ${UDR_MODEL_DIR}/Periodicity_anyOf.cpp
    ${UDR_MODEL_DIR}/PfdContent.cpp
    ${UDR_MODEL_DIR}/PfdDataForAppExt.cpp
    ${UDR_MODEL_DIR}/PgwInfo.cpp
    ${UDR_MODEL_DIR}/PlmnEcInfo.cpp
    ${UDR_MODEL_DIR}/PlmnId.cpp
    ${UDR_MODEL_DIR}/PlmnIdNid.cpp
    ${UDR_MODEL_DIR}/PlmnOperatorClass.cpp
    ${UDR_MODEL_DIR}/PlmnRestriction.cpp
    ${UDR_MODEL_DIR}/PlmnRouteSelectionDescriptor.cpp
    ${UDR_MODEL_DIR}/Point.cpp
    ${UDR_MODEL_DIR}/PointAltitude.cpp
    ${UDR_MODEL_DIR}/PointAltitudeUncertainty.cpp
    ${UDR_MODEL_DIR}/PointUncertaintyCircle.cpp
    ${UDR_MODEL_DIR}/PointUncertaintyEllipse.cpp
    ${UDR_MODEL_DIR}/PolicyDataSubscription.cpp
    ${UDR_MODEL_DIR}/Polygon.cpp
    ${UDR_MODEL_DIR}/PositioningMethodMdt.cpp
    ${UDR_MODEL_DIR}/PositioningMethodMdt_anyOf.cpp
    ${UDR_MODEL_DIR}/PpActiveTime.cpp
    ${UDR_MODEL_DIR}/PpData.cpp
    ${UDR_MODEL_DIR}/PpDlPacketCountExt.cpp
    ${UDR_MODEL_DIR}/PpMaximumLatency.cpp
    ${UDR_MODEL_DIR}/PpMaximumResponseTime.cpp
    ${UDR_MODEL_DIR}/PpProfileData.cpp
    ${UDR_MODEL_DIR}/PpSubsRegTimer.cpp
    ${UDR_MODEL_DIR}/PreemptionCapability.cpp
    ${UDR_MODEL_DIR}/PreemptionCapability_anyOf.cpp
    ${UDR_MODEL_DIR}/PreemptionVulnerability.cpp
    ${UDR_MODEL_DIR}/PreemptionVulnerability_anyOf.cpp
    ${UDR_MODEL_DIR}/PresenceInfo.cpp
    ${UDR_MODEL_DIR}/PresenceState.cpp
    ${UDR_MODEL_DIR}/PresenceState_anyOf.cpp
    ${UDR_MODEL_DIR}/PrivacyCheckRelatedAction.cpp
    ${UDR_MODEL_DIR}/PrivacyCheckRelatedAction_anyOf.cpp
    ${UDR_MODEL_DIR}/ProSeAllowedPlmn.cpp
    ${UDR_MODEL_DIR}/ProblemDetails.cpp
    ${UDR_MODEL_DIR}/ProseDirectAllowed.cpp
    ${UDR_MODEL_DIR}/ProseDirectAllowed_anyOf.cpp
    ${UDR_MODEL_DIR}/ProseServiceAuth.cpp
    ${UDR_MODEL_DIR}/ProseSubscriptionData.cpp
    ${UDR_MODEL_DIR}/ProvisionedDataSets.cpp
    ${UDR_MODEL_DIR}/PtwParameters.cpp
    ${UDR_MODEL_DIR}/RatType.cpp
    ${UDR_MODEL_DIR}/RatType_anyOf.cpp
    ${UDR_MODEL_DIR}/ReachabilityForDataConfiguration.cpp
    ${UDR_MODEL_DIR}/ReachabilityForDataReportConfig.cpp
    ${UDR_MODEL_DIR}/ReachabilityForDataReportConfig_anyOf.cpp
    ${UDR_MODEL_DIR}/ReachabilityForSmsConfiguration.cpp
    ${UDR_MODEL_DIR}/ReachabilityForSmsConfiguration_anyOf.cpp
    ${UDR_MODEL_DIR}/RegistrationReason.cpp
    ${UDR_MODEL_DIR}/RegistrationReason_anyOf.cpp
    ${UDR_MODEL_DIR}/ReportAmountMdt.cpp
    ${UDR_MODEL_DIR}/ReportAmountMdt_anyOf.cpp
    ${UDR_MODEL_DIR}/ReportIntervalMdt.cpp
    ${UDR_MODEL_DIR}/ReportIntervalMdt_anyOf.cpp
    ${UDR_MODEL_DIR}/ReportIntervalNrMdt.cpp
    ${UDR_MODEL_DIR}/ReportIntervalNrMdt_anyOf.cpp
    ${UDR_MODEL_DIR}/ReportItem.cpp
    ${UDR_MODEL_DIR}/ReportTypeMdt.cpp
    ${UDR_MODEL_DIR}/ReportTypeMdt_anyOf.cpp
    ${UDR_MODEL_DIR}/ReportingOptions.cpp
    ${UDR_MODEL_DIR}/ReportingTrigger.cpp
    ${UDR_MODEL_DIR}/ReportingTrigger_anyOf.cpp
    ${UDR_MODEL_DIR}/ResourceItem.cpp
    ${UDR_MODEL_DIR}/RestrictionType.cpp
    ${UDR_MODEL_DIR}/RestrictionType_anyOf.cpp
    ${UDR_MODEL_DIR}/RmInfo.cpp
    ${UDR_MODEL_DIR}/RmState.cpp
    ${UDR_MODEL_DIR}/RmState_anyOf.cpp
    ${UDR_MODEL_DIR}/RoamingInfoUpdate.cpp
    ${UDR_MODEL_DIR}/RoamingOdb.cpp
    ${UDR_MODEL_DIR}/RoamingOdb_anyOf.cpp
    ${UDR_MODEL_DIR}/RoamingRestrictions.cpp
    ${UDR_MODEL_DIR}/RouteInformation.cpp
    ${UDR_MODEL_DIR}/RouteToLocation.cpp
    ${UDR_MODEL_DIR}/RoutingAreaId.cpp
    ${UDR_MODEL_DIR}/ScheduledCommunicationTime.cpp
    ${UDR_MODEL_DIR}/ScheduledCommunicationTimeRm.cpp
    ${UDR_MODEL_DIR}/ScheduledCommunicationType.cpp
    ${UDR_MODEL_DIR}/ScheduledCommunicationTypeRm.cpp
    ${UDR_MODEL_DIR}/ScheduledCommunicationType_anyOf.cpp
    ${UDR_MODEL_DIR}/SdmSubscription.cpp
    ${UDR_MODEL_DIR}/SensorMeasurement.cpp
    ${UDR_MODEL_DIR}/SensorMeasurement_anyOf.cpp
    ${UDR_MODEL_DIR}/SequenceNumber.cpp
    ${UDR_MODEL_DIR}/ServiceAreaCoverageInfo.cpp
    ${UDR_MODEL_DIR}/ServiceAreaId.cpp
    ${UDR_MODEL_DIR}/ServiceAreaRestriction.cpp
    ${UDR_MODEL_DIR}/ServiceName.cpp
    ${UDR_MODEL_DIR}/ServiceName_anyOf.cpp
    ${UDR_MODEL_DIR}/ServiceTypeUnrelatedClass.cpp
    ${UDR_MODEL_DIR}/SessionManagementSubscriptionData.cpp
    ${UDR_MODEL_DIR}/SharedData.cpp
    ${UDR_MODEL_DIR}/SharedDataTreatmentInstruction.cpp
    ${UDR_MODEL_DIR}/SharedDataTreatmentInstruction_anyOf.cpp
    ${UDR_MODEL_DIR}/Sign.cpp
    ${UDR_MODEL_DIR}/SliceMbr.cpp
    ${UDR_MODEL_DIR}/SliceMbrRm.cpp
    ${UDR_MODEL_DIR}/SmPolicyData.cpp
    ${UDR_MODEL_DIR}/SmPolicyDataPatch.cpp
    ${UDR_MODEL_DIR}/SmPolicyDnnData.cpp
    ${UDR_MODEL_DIR}/SmPolicyDnnDataPatch.cpp
    ${UDR_MODEL_DIR}/SmPolicySnssaiData.cpp
    ${UDR_MODEL_DIR}/SmPolicySnssaiDataPatch.cpp
    ${UDR_MODEL_DIR}/SmSubsData.cpp
    ${UDR_MODEL_DIR}/SmfRegistration.cpp
    ${UDR_MODEL_DIR}/SmfSelectionSubscriptionData.cpp
    ${UDR_MODEL_DIR}/SmsManagementSubscriptionData.cpp
    ${UDR_MODEL_DIR}/SmsSubscriptionData.cpp
    ${UDR_MODEL_DIR}/SmsSupport.cpp
    ${UDR_MODEL_DIR}/SmsSupport_anyOf.cpp
    ${UDR_MODEL_DIR}/SmscData.cpp
    ${UDR_MODEL_DIR}/SmsfInfo.cpp
    ${UDR_MODEL_DIR}/SmsfRegistration.cpp
    ${UDR_MODEL_DIR}/Snssai.cpp
    ${UDR_MODEL_DIR}/SnssaiInfo.cpp
    ${UDR_MODEL_DIR}/SnssaiRouteSelectionDescriptor.cpp
    ${UDR_MODEL_DIR}/SorData.cpp
    ${UDR_MODEL_DIR}/SorInfo.cpp
    ${UDR_MODEL_DIR}/SorUpdateIndicator.cpp
    ${UDR_MODEL_DIR}/SorUpdateIndicator_anyOf.cpp
    ${UDR_MODEL_DIR}/SpatialValidityCond.cpp
    ${UDR_MODEL_DIR}/SponsorConnectivityData.cpp
    ${UDR_MODEL_DIR}/SqnScheme.cpp
    ${UDR_MODEL_DIR}/SqnScheme_anyOf.cpp
    ${UDR_MODEL_DIR}/SscMode.cpp
    ${UDR_MODEL_DIR}/SscMode_anyOf.cpp
    ${UDR_MODEL_DIR}/SscModes.cpp
    ${UDR_MODEL_DIR}/Ssm.cpp
    ${UDR_MODEL_DIR}/StationaryIndication.cpp
    ${UDR_MODEL_DIR}/StationaryIndicationRm.cpp
    ${UDR_MODEL_DIR}/StationaryIndication_anyOf.cpp
    ${UDR_MODEL_DIR}/SteeringContainer.cpp
    ${UDR_MODEL_DIR}/SteeringInfo.cpp
    ${UDR_MODEL_DIR}/SubscribedDefaultQos.cpp
    ${UDR_MODEL_DIR}/SubscribedEvent.cpp
    ${UDR_MODEL_DIR}/SubscribedEvent_anyOf.cpp
    ${UDR_MODEL_DIR}/SubscriptionDataSets.cpp
    ${UDR_MODEL_DIR}/SubscriptionDataSubscriptions.cpp
    ${UDR_MODEL_DIR}/SuggestedPacketNumDl.cpp
    ${UDR_MODEL_DIR}/SupportedGADShapes.cpp
    ${UDR_MODEL_DIR}/SupportedGADShapes_anyOf.cpp
    ${UDR_MODEL_DIR}/TacInfo.cpp
    ${UDR_MODEL_DIR}/TacRange.cpp
    ${UDR_MODEL_DIR}/Tai.cpp
    ${UDR_MODEL_DIR}/TaiRange.cpp
    ${UDR_MODEL_DIR}/TemporalValidity.cpp
    ${UDR_MODEL_DIR}/TimePeriod.cpp
    ${UDR_MODEL_DIR}/TimeWindow.cpp
    ${UDR_MODEL_DIR}/Tmgi.cpp
    ${UDR_MODEL_DIR}/TnapId.cpp
    ${UDR_MODEL_DIR}/TraceData.cpp
    ${UDR_MODEL_DIR}/TraceDepth.cpp
    ${UDR_MODEL_DIR}/TraceDepth_anyOf.cpp
    ${UDR_MODEL_DIR}/TrafficInfluData.cpp
    ${UDR_MODEL_DIR}/TrafficInfluDataPatch.cpp
    ${UDR_MODEL_DIR}/TrafficInfluSub.cpp
    ${UDR_MODEL_DIR}/TrafficProfile.cpp
    ${UDR_MODEL_DIR}/TrafficProfileRm.cpp
    ${UDR_MODEL_DIR}/TrafficProfile_anyOf.cpp
    ${UDR_MODEL_DIR}/TransferPolicy.cpp
    ${UDR_MODEL_DIR}/TransportProtocol.cpp
    ${UDR_MODEL_DIR}/TransportProtocol_anyOf.cpp
    ${UDR_MODEL_DIR}/TwapId.cpp
    ${UDR_MODEL_DIR}/UcSubscriptionData.cpp
    ${UDR_MODEL_DIR}/UeAuth.cpp
    ${UDR_MODEL_DIR}/UeAuth_anyOf.cpp
    ${UDR_MODEL_DIR}/UeContextInAmfData.cpp
    ${UDR_MODEL_DIR}/UeContextInSmfData.cpp
    ${UDR_MODEL_DIR}/UeContextInSmfDataSubFilter.cpp
    ${UDR_MODEL_DIR}/UeContextInSmsfData.cpp
    ${UDR_MODEL_DIR}/UeContextInfoClass.cpp
    ${UDR_MODEL_DIR}/UeContextInfoClass_anyOf.cpp
    ${UDR_MODEL_DIR}/UeId.cpp
    ${UDR_MODEL_DIR}/UePolicySection.cpp
    ${UDR_MODEL_DIR}/UePolicySet.cpp
    ${UDR_MODEL_DIR}/UePolicySetPatch.cpp
    ${UDR_MODEL_DIR}/UeReachability.cpp
    ${UDR_MODEL_DIR}/UeReachability_anyOf.cpp
    ${UDR_MODEL_DIR}/UeReachableInd.cpp
    ${UDR_MODEL_DIR}/UeReachableInd_anyOf.cpp
    ${UDR_MODEL_DIR}/UeUpdateStatus.cpp
    ${UDR_MODEL_DIR}/UmtTime.cpp
    ${UDR_MODEL_DIR}/UncertaintyEllipse.cpp
    ${UDR_MODEL_DIR}/UnrelatedClass.cpp
    ${UDR_MODEL_DIR}/UpConfidentiality.cpp
    ${UDR_MODEL_DIR}/UpIntegrity.cpp
    ${UDR_MODEL_DIR}/UpIntegrity_anyOf.cpp
    ${UDR_MODEL_DIR}/UpSecurity.cpp
    ${UDR_MODEL_DIR}/UpuData.cpp
    ${UDR_MODEL_DIR}/UpuInfo.cpp
    ${UDR_MODEL_DIR}/UsageMonData.cpp
    ${UDR_MODEL_DIR}/UsageMonDataLimit.cpp
    ${UDR_MODEL_DIR}/UsageMonDataScope.cpp
    ${UDR_MODEL_DIR}/UsageMonLevel.cpp
    ${UDR_MODEL_DIR}/UsageMonLevel_anyOf.cpp
    ${UDR_MODEL_DIR}/UsageThreshold.cpp
    ${UDR_MODEL_DIR}/UserConsent.cpp
    ${UDR_MODEL_DIR}/UserIdentifier.cpp
    ${UDR_MODEL_DIR}/UserLocation.cpp
    ${UDR_MODEL_DIR}/UtraLocation.cpp
    ${UDR_MODEL_DIR}/V2xSubscriptionData.cpp
    ${UDR_MODEL_DIR}/ValidTimePeriod.cpp
    ${UDR_MODEL_DIR}/VgmlcAddress.cpp
    ${UDR_MODEL_DIR}/VnGroupData.cpp
    ${UDR_MODEL_DIR}/WirelineArea.cpp
    ${UDR_MODEL_DIR}/WirelineServiceAreaRestriction.cpp
    ${UDR_MODEL_DIR}/r_5MbsAuthorizationInfo.cpp
)

## CONFIG used in NF_TARGET (main)
if (TARGET ${NF_TARGET})
    target_include_directories(${NF_TARGET} PUBLIC ${UDR_MODEL_DIR})
    target_sources(${NF_TARGET} PRIVATE
            ${UDR_MODEL_SRC_FILES}
            )
endif()
