/**
* Nudr_DataRepository API OpenAPI file
* Unified Data Repository Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
*
* The version of the OpenAPI document: 2.2.4
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "UeContextInSmfDataSubFilter_1.h"
#include "Helpers.h"

#include <sstream>

namespace oai::model
{

UeContextInSmfDataSubFilter_1::UeContextInSmfDataSubFilter_1()
{
    m_DnnListIsSet = false;
    m_SnssaiListIsSet = false;
    m_EmergencyInd = false;
    m_EmergencyIndIsSet = false;
    
}

void UeContextInSmfDataSubFilter_1::validate() const
{
    std::stringstream msg;
    if (!validate(msg))
    {
        throw org::openapitools::server::helpers::ValidationException(msg.str());
    }
}

bool UeContextInSmfDataSubFilter_1::validate(std::stringstream& msg) const
{
    return validate(msg, "");
}

bool UeContextInSmfDataSubFilter_1::validate(std::stringstream& msg, const std::string& pathPrefix) const
{
    bool success = true;
    const std::string _pathPrefix = pathPrefix.empty() ? "UeContextInSmfDataSubFilter_1" : pathPrefix;

         
    if (dnnListIsSet())
    {
        const std::vector<std::string>& value = m_DnnList;
        const std::string currentValuePath = _pathPrefix + ".dnnList";
                
        
        if (value.size() < 1)
        {
            success = false;
            msg << currentValuePath << ": must have at least 1 elements;";
        }
        { // Recursive validation of array elements
            const std::string oldValuePath = currentValuePath;
            int i = 0;
            for (const std::string& value : value)
            { 
                const std::string currentValuePath = oldValuePath + "[" + std::to_string(i) + "]";
                        
        
 
                i++;
            }
        }

    }
         
    if (snssaiListIsSet())
    {
        const std::vector<oai::model::Snssai>& value = m_SnssaiList;
        const std::string currentValuePath = _pathPrefix + ".snssaiList";
                
        
        if (value.size() < 1)
        {
            success = false;
            msg << currentValuePath << ": must have at least 1 elements;";
        }
        { // Recursive validation of array elements
            const std::string oldValuePath = currentValuePath;
            int i = 0;
            for (const oai::model::Snssai& value : value)
            { 
                const std::string currentValuePath = oldValuePath + "[" + std::to_string(i) + "]";
                        
        success = value.validate(msg, currentValuePath + ".snssaiList") && success;
 
                i++;
            }
        }

    }
        
    return success;
}

bool UeContextInSmfDataSubFilter_1::operator==(const UeContextInSmfDataSubFilter_1& rhs) const
{
    return
    
    
    
    ((!dnnListIsSet() && !rhs.dnnListIsSet()) || (dnnListIsSet() && rhs.dnnListIsSet() && getDnnList() == rhs.getDnnList())) &&
    
    
    ((!snssaiListIsSet() && !rhs.snssaiListIsSet()) || (snssaiListIsSet() && rhs.snssaiListIsSet() && getSnssaiList() == rhs.getSnssaiList())) &&
    
    
    ((!emergencyIndIsSet() && !rhs.emergencyIndIsSet()) || (emergencyIndIsSet() && rhs.emergencyIndIsSet() && isEmergencyInd() == rhs.isEmergencyInd()))
    
    ;
}

bool UeContextInSmfDataSubFilter_1::operator!=(const UeContextInSmfDataSubFilter_1& rhs) const
{
    return !(*this == rhs);
}

void to_json(nlohmann::json& j, const UeContextInSmfDataSubFilter_1& o)
{
    j = nlohmann::json::object();
    if(o.dnnListIsSet() || !o.m_DnnList.empty())
        j["dnnList"] = o.m_DnnList;
    if(o.snssaiListIsSet() || !o.m_SnssaiList.empty())
        j["snssaiList"] = o.m_SnssaiList;
    if(o.emergencyIndIsSet())
        j["emergencyInd"] = o.m_EmergencyInd;
    
}

void from_json(const nlohmann::json& j, UeContextInSmfDataSubFilter_1& o)
{
    if(j.find("dnnList") != j.end())
    {
        j.at("dnnList").get_to(o.m_DnnList);
        o.m_DnnListIsSet = true;
    } 
    if(j.find("snssaiList") != j.end())
    {
        j.at("snssaiList").get_to(o.m_SnssaiList);
        o.m_SnssaiListIsSet = true;
    } 
    if(j.find("emergencyInd") != j.end())
    {
        j.at("emergencyInd").get_to(o.m_EmergencyInd);
        o.m_EmergencyIndIsSet = true;
    } 
    
}

std::vector<std::string> UeContextInSmfDataSubFilter_1::getDnnList() const
{
    return m_DnnList;
}
void UeContextInSmfDataSubFilter_1::setDnnList(std::vector<std::string> const& value)
{
    m_DnnList = value;
    m_DnnListIsSet = true;
}
bool UeContextInSmfDataSubFilter_1::dnnListIsSet() const
{
    return m_DnnListIsSet;
}
void UeContextInSmfDataSubFilter_1::unsetDnnList()
{
    m_DnnListIsSet = false;
}
std::vector<oai::model::Snssai> UeContextInSmfDataSubFilter_1::getSnssaiList() const
{
    return m_SnssaiList;
}
void UeContextInSmfDataSubFilter_1::setSnssaiList(std::vector<oai::model::Snssai> const& value)
{
    m_SnssaiList = value;
    m_SnssaiListIsSet = true;
}
bool UeContextInSmfDataSubFilter_1::snssaiListIsSet() const
{
    return m_SnssaiListIsSet;
}
void UeContextInSmfDataSubFilter_1::unsetSnssaiList()
{
    m_SnssaiListIsSet = false;
}
bool UeContextInSmfDataSubFilter_1::isEmergencyInd() const
{
    return m_EmergencyInd;
}
void UeContextInSmfDataSubFilter_1::setEmergencyInd(bool const value)
{
    m_EmergencyInd = value;
    m_EmergencyIndIsSet = true;
}
bool UeContextInSmfDataSubFilter_1::emergencyIndIsSet() const
{
    return m_EmergencyIndIsSet;
}
void UeContextInSmfDataSubFilter_1::unsetEmergencyInd()
{
    m_EmergencyIndIsSet = false;
}


} // namespace oai::model

