/**
* Nnef_EventExposure
* NEF Event Exposure Service.   © 2022 , 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
*
* The version of the OpenAPI document: 1.2.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "UeTrajectoryInfo.h"
#include "Helpers.h"

#include <sstream>

namespace oai::model
{

UeTrajectoryInfo::UeTrajectoryInfo()
{
    m_Ts = "";
    
}

void UeTrajectoryInfo::validate() const
{
    std::stringstream msg;
    if (!validate(msg))
    {
        throw org::openapitools::server::helpers::ValidationException(msg.str());
    }
}

bool UeTrajectoryInfo::validate(std::stringstream& msg) const
{
    return validate(msg, "");
}

bool UeTrajectoryInfo::validate(std::stringstream& msg, const std::string& pathPrefix) const
{
    bool success = true;
    const std::string _pathPrefix = pathPrefix.empty() ? "UeTrajectoryInfo" : pathPrefix;

            
    if (!m_Location.validate(msg, _pathPrefix + ".location")) {
        msg << _pathPrefix << ": Location is invalid;";
        success = false;
    }
    return success;
}

bool UeTrajectoryInfo::operator==(const UeTrajectoryInfo& rhs) const
{
    return
    
    
    (getTs() == rhs.getTs())
     &&
    
    (getLocation() == rhs.getLocation())
    
    
    ;
}

bool UeTrajectoryInfo::operator!=(const UeTrajectoryInfo& rhs) const
{
    return !(*this == rhs);
}

void to_json(nlohmann::json& j, const UeTrajectoryInfo& o)
{
    j = nlohmann::json::object();
    j["ts"] = o.m_Ts;
    j["location"] = o.m_Location;
    
}

void from_json(const nlohmann::json& j, UeTrajectoryInfo& o)
{
    j.at("ts").get_to(o.m_Ts);
    j.at("location").get_to(o.m_Location);
    
}

std::string UeTrajectoryInfo::getTs() const
{
    return m_Ts;
}
void UeTrajectoryInfo::setTs(std::string const& value)
{
    m_Ts = value;
}
oai::model::UserLocation UeTrajectoryInfo::getLocation() const
{
    return m_Location;
}
void UeTrajectoryInfo::setLocation(oai::model::UserLocation const& value)
{
    m_Location = value;
}


} // namespace oai::model

