/**
* Nudr_DataRepository API OpenAPI file
* Unified Data Repository Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
*
* The version of the OpenAPI document: 2.2.4
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * UpuInfo_1.h
 *
 * 
 */

#ifndef UpuInfo_1_H_
#define UpuInfo_1_H_


#include <string>
#include "UpuData_2.h"
#include <vector>
#include <nlohmann/json.hpp>

namespace oai::_3gpp::model
{

/// <summary>
/// 
/// </summary>
class  UpuInfo_1
{
public:
    UpuInfo_1();
    virtual ~UpuInfo_1() = default;


    /// <summary>
    /// Validate the current data in the model. Throws a ValidationException on failure.
    /// </summary>
    void validate() const;

    /// <summary>
    /// Validate the current data in the model. Returns false on error and writes an error
    /// message into the given stringstream.
    /// </summary>
    bool validate(std::stringstream& msg) const;

    /// <summary>
    /// Helper overload for validate. Used when one model stores another model and calls it's validate.
    /// Not meant to be called outside that case.
    /// </summary>
    bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

    bool operator==(const UpuInfo_1& rhs) const;
    bool operator!=(const UpuInfo_1& rhs) const;

    /////////////////////////////////////////////
    /// UpuInfo_1 members

    /// <summary>
    /// 
    /// </summary>
    std::vector<oai::_3gpp::model::UpuData_2> getUpuDataList() const;
    void setUpuDataList(std::vector<oai::_3gpp::model::UpuData_2> const& value);
    bool upuDataListIsSet() const;
    void unsetUpuDataList();
    /// <summary>
    /// 
    /// </summary>
    bool isUpuRegInd() const;
    void setUpuRegInd(bool const value);
    bool upuRegIndIsSet() const;
    void unsetUpuRegInd();
    /// <summary>
    /// Contains the indication of whether the acknowledgement from UE is needed.
    /// </summary>
    bool isUpuAckInd() const;
    void setUpuAckInd(bool const value);
    bool upuAckIndIsSet() const;
    void unsetUpuAckInd();
    /// <summary>
    /// MAC value for protecting UPU procedure (UPU-MAC-IAUSF and UPU-MAC-IUE).
    /// </summary>
    std::string getUpuMacIausf() const;
    void setUpuMacIausf(std::string const& value);
    bool upuMacIausfIsSet() const;
    void unsetUpuMacIausf();
    /// <summary>
    /// CounterUPU.
    /// </summary>
    std::string getCounterUpu() const;
    void setCounterUpu(std::string const& value);
    bool counterUpuIsSet() const;
    void unsetCounterUpu();
    /// <summary>
    /// string with format &#39;date-time&#39; as defined in OpenAPI.
    /// </summary>
    std::string getProvisioningTime() const;
    void setProvisioningTime(std::string const& value);
    /// <summary>
    /// string with format &#39;bytes&#39; as defined in OpenAPI
    /// </summary>
    std::string getUpuTransparentContainer() const;
    void setUpuTransparentContainer(std::string const& value);
    bool upuTransparentContainerIsSet() const;
    void unsetUpuTransparentContainer();

    friend void to_json(nlohmann::json& j, const UpuInfo_1& o);
    friend void from_json(const nlohmann::json& j, UpuInfo_1& o);
protected:
    std::vector<oai::_3gpp::model::UpuData_2> m_UpuDataList;
    bool m_UpuDataListIsSet;
    bool m_UpuRegInd;
    bool m_UpuRegIndIsSet;
    bool m_UpuAckInd;
    bool m_UpuAckIndIsSet;
    std::string m_UpuMacIausf;
    bool m_UpuMacIausfIsSet;
    std::string m_CounterUpu;
    bool m_CounterUpuIsSet;
    std::string m_ProvisioningTime;

    std::string m_UpuTransparentContainer;
    bool m_UpuTransparentContainerIsSet;
    
};

} // namespace oai::_3gpp::model

#endif /* UpuInfo_1_H_ */
