/**
* Unified Data Repository Service API file for policy data
* The API version is defined in 3GPP TS 29.504   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
*
* The version of the OpenAPI document: -
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * UsageMonDataLimit.h
 *
 * Contains usage monitoring control data for a subscriber.
 */

#ifndef UsageMonDataLimit_H_
#define UsageMonDataLimit_H_


#include "TimePeriod.h"
#include "UsageMonDataScope.h"
#include "UsageThreshold.h"
#include <string>
#include "UsageMonLevel.h"
#include <map>
#include <nlohmann/json.hpp>

namespace oai::model
{

/// <summary>
/// Contains usage monitoring control data for a subscriber.
/// </summary>
class  UsageMonDataLimit
{
public:
    UsageMonDataLimit();
    virtual ~UsageMonDataLimit() = default;


    /// <summary>
    /// Validate the current data in the model. Throws a ValidationException on failure.
    /// </summary>
    void validate() const;

    /// <summary>
    /// Validate the current data in the model. Returns false on error and writes an error
    /// message into the given stringstream.
    /// </summary>
    bool validate(std::stringstream& msg) const;

    /// <summary>
    /// Helper overload for validate. Used when one model stores another model and calls it's validate.
    /// Not meant to be called outside that case.
    /// </summary>
    bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

    bool operator==(const UsageMonDataLimit& rhs) const;
    bool operator!=(const UsageMonDataLimit& rhs) const;

    /////////////////////////////////////////////
    /// UsageMonDataLimit members

    /// <summary>
    /// 
    /// </summary>
    std::string getLimitId() const;
    void setLimitId(std::string const& value);
    /// <summary>
    /// Identifies the SNSSAI and DNN combinations to which the usage monitoring data limit applies. The S-NSSAI is the key of the map. 
    /// </summary>
    std::map<std::string, oai::model::UsageMonDataScope> getScopes() const;
    void setScopes(std::map<std::string, oai::model::UsageMonDataScope> const& value);
    bool scopesIsSet() const;
    void unsetScopes();
    /// <summary>
    /// 
    /// </summary>
    oai::model::UsageMonLevel getUmLevel() const;
    void setUmLevel(oai::model::UsageMonLevel const& value);
    bool umLevelIsSet() const;
    void unsetUmLevel();
    /// <summary>
    /// string with format &#39;date-time&#39; as defined in OpenAPI.
    /// </summary>
    std::string getStartDate() const;
    void setStartDate(std::string const& value);
    bool startDateIsSet() const;
    void unsetStartDate();
    /// <summary>
    /// string with format &#39;date-time&#39; as defined in OpenAPI.
    /// </summary>
    std::string getEndDate() const;
    void setEndDate(std::string const& value);
    bool endDateIsSet() const;
    void unsetEndDate();
    /// <summary>
    /// 
    /// </summary>
    oai::model::UsageThreshold getUsageLimit() const;
    void setUsageLimit(oai::model::UsageThreshold const& value);
    bool usageLimitIsSet() const;
    void unsetUsageLimit();
    /// <summary>
    /// 
    /// </summary>
    oai::model::TimePeriod getResetPeriod() const;
    void setResetPeriod(oai::model::TimePeriod const& value);
    bool resetPeriodIsSet() const;
    void unsetResetPeriod();

    friend  void to_json(nlohmann::json& j, const UsageMonDataLimit& o);
    friend  void from_json(const nlohmann::json& j, UsageMonDataLimit& o);
protected:
    std::string m_LimitId;

    std::map<std::string, oai::model::UsageMonDataScope> m_Scopes;
    bool m_ScopesIsSet;
    oai::model::UsageMonLevel m_UmLevel;
    bool m_UmLevelIsSet;
    std::string m_StartDate;
    bool m_StartDateIsSet;
    std::string m_EndDate;
    bool m_EndDateIsSet;
    oai::model::UsageThreshold m_UsageLimit;
    bool m_UsageLimitIsSet;
    oai::model::TimePeriod m_ResetPeriod;
    bool m_ResetPeriodIsSet;
    
};

} // namespace oai::model

#endif /* UsageMonDataLimit_H_ */
