/**
* Unified Data Repository Service API file for policy data
* The API version is defined in 3GPP TS 29.504   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
*
* The version of the OpenAPI document: -
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * UsageMonDataScope.h
 *
 * Contains a SNSSAI and DNN combinations to which the UsageMonData instance belongs to. 
 */

#ifndef UsageMonDataScope_H_
#define UsageMonDataScope_H_


#include <string>
#include "Snssai.h"
#include <vector>
#include <nlohmann/json.hpp>

namespace oai::model
{

/// <summary>
/// Contains a SNSSAI and DNN combinations to which the UsageMonData instance belongs to. 
/// </summary>
class  UsageMonDataScope
{
public:
    UsageMonDataScope();
    virtual ~UsageMonDataScope() = default;


    /// <summary>
    /// Validate the current data in the model. Throws a ValidationException on failure.
    /// </summary>
    void validate() const;

    /// <summary>
    /// Validate the current data in the model. Returns false on error and writes an error
    /// message into the given stringstream.
    /// </summary>
    bool validate(std::stringstream& msg) const;

    /// <summary>
    /// Helper overload for validate. Used when one model stores another model and calls it's validate.
    /// Not meant to be called outside that case.
    /// </summary>
    bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

    bool operator==(const UsageMonDataScope& rhs) const;
    bool operator!=(const UsageMonDataScope& rhs) const;

    /////////////////////////////////////////////
    /// UsageMonDataScope members

    /// <summary>
    /// 
    /// </summary>
    oai::model::Snssai getSnssai() const;
    void setSnssai(oai::model::Snssai const& value);
    /// <summary>
    /// 
    /// </summary>
    std::vector<std::string> getDnn() const;
    void setDnn(std::vector<std::string> const& value);
    bool dnnIsSet() const;
    void unsetDnn();

    friend  void to_json(nlohmann::json& j, const UsageMonDataScope& o);
    friend  void from_json(const nlohmann::json& j, UsageMonDataScope& o);
protected:
    oai::model::Snssai m_Snssai;

    std::vector<std::string> m_Dnn;
    bool m_DnnIsSet;
    
};

} // namespace oai::model

#endif /* UsageMonDataScope_H_ */
