/**
 * 3gpp-as-session-with-qos
 * API for AsSessionWithQoS.   © 2023, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "UserPlaneEventReport.h"
#include "Helpers.h"

#include <sstream>

namespace oai::_3gpp::model {

UserPlaneEventReport::UserPlaneEventReport() {
  m_EventIsSet            = false;
  m_AccumulatedUsageIsSet = false;
  m_FlowIdsIsSet          = false;
  m_AppliedQosRef         = "";
  m_AppliedQosRefIsSet    = false;
  m_PlmnIdIsSet           = false;
  m_QosMonReportsIsSet    = false;
  m_RatTypeIsSet          = false;
}

void UserPlaneEventReport::validate() const {
  std::stringstream msg;
  if (!validate(msg)) {
    throw oai::_3gpp::model::helpers::ValidationException(msg.str());
  }
}

bool UserPlaneEventReport::validate(std::stringstream& msg) const {
  return validate(msg, "");
}

bool UserPlaneEventReport::validate(
    std::stringstream& msg, const std::string& pathPrefix) const {
  bool success = true;
  const std::string _pathPrefix =
      pathPrefix.empty() ? "UserPlaneEventReport" : pathPrefix;

  if (!eventIsSet()) {
    success = false;
    msg << _pathPrefix << ".event: is required but not set;";
  } else {
    const oai::_3gpp::model::UserPlaneEvent& value = m_Event;
    const std::string currentValuePath             = _pathPrefix + ".event";

    success = value.validate(msg, currentValuePath) && success;
  }

  if (accumulatedUsageIsSet()) {
    const oai::_3gpp::model::AccumulatedUsage& value = m_AccumulatedUsage;
    const std::string currentValuePath = _pathPrefix + ".accumulatedUsage";

    success = value.validate(msg, currentValuePath) && success;
  }

  if (flowIdsIsSet()) {
    const std::vector<int32_t>& value  = m_FlowIds;
    const std::string currentValuePath = _pathPrefix + ".flowIds";

    {  // Recursive validation of array elements
      const std::string oldValuePath = currentValuePath;
      int i                          = 0;
      for (const int32_t& value : value) {
        const std::string currentValuePath =
            oldValuePath + "[" + std::to_string(i) + "]";

        i++;
      }
    }
  }

  if (plmnIdIsSet()) {
    const oai::_3gpp::model::PlmnIdNid& value = m_PlmnId;
    const std::string currentValuePath        = _pathPrefix + ".plmnId";

    success = value.validate(msg, currentValuePath) && success;
  }

  if (qosMonReportsIsSet()) {
    const std::vector<oai::_3gpp::model::QosMonitoringReport>& value =
        m_QosMonReports;
    const std::string currentValuePath = _pathPrefix + ".qosMonReports";

    if (value.size() < 1) {
      success = false;
      msg << currentValuePath << ": must have at least 1 elements;";
    }
    {  // Recursive validation of array elements
      const std::string oldValuePath = currentValuePath;
      int i                          = 0;
      for (const oai::_3gpp::model::QosMonitoringReport& value : value) {
        const std::string currentValuePath =
            oldValuePath + "[" + std::to_string(i) + "]";

        success = value.validate(msg, currentValuePath) && success;

        i++;
      }
    }
  }

  if (ratTypeIsSet()) {
    const oai::_3gpp::model::RatType& value = m_RatType;
    const std::string currentValuePath      = _pathPrefix + ".ratType";

    success = value.validate(msg, currentValuePath) && success;
  }

  return success;
}

bool UserPlaneEventReport::operator==(const UserPlaneEventReport& rhs) const {
  return

      ((!eventIsSet() && !rhs.eventIsSet()) ||
       (eventIsSet() && rhs.eventIsSet() && getEvent() == rhs.getEvent())) &&

      ((!accumulatedUsageIsSet() && !rhs.accumulatedUsageIsSet()) ||
       (accumulatedUsageIsSet() && rhs.accumulatedUsageIsSet() &&
        getAccumulatedUsage() == rhs.getAccumulatedUsage())) &&

      ((!flowIdsIsSet() && !rhs.flowIdsIsSet()) ||
       (flowIdsIsSet() && rhs.flowIdsIsSet() &&
        getFlowIds() == rhs.getFlowIds())) &&

      ((!appliedQosRefIsSet() && !rhs.appliedQosRefIsSet()) ||
       (appliedQosRefIsSet() && rhs.appliedQosRefIsSet() &&
        getAppliedQosRef() == rhs.getAppliedQosRef())) &&

      ((!plmnIdIsSet() && !rhs.plmnIdIsSet()) ||
       (plmnIdIsSet() && rhs.plmnIdIsSet() &&
        getPlmnId() == rhs.getPlmnId())) &&

      ((!qosMonReportsIsSet() && !rhs.qosMonReportsIsSet()) ||
       (qosMonReportsIsSet() && rhs.qosMonReportsIsSet() &&
        getQosMonReports() == rhs.getQosMonReports())) &&

      ((!ratTypeIsSet() && !rhs.ratTypeIsSet()) ||
       (ratTypeIsSet() && rhs.ratTypeIsSet() &&
        getRatType() == rhs.getRatType()))

          ;
}

bool UserPlaneEventReport::operator!=(const UserPlaneEventReport& rhs) const {
  return !(*this == rhs);
}

void to_json(nlohmann::json& j, const UserPlaneEventReport& o) {
  j = nlohmann::json();
  if (o.eventIsSet()) j["event"] = o.m_Event;
  if (o.accumulatedUsageIsSet()) j["accumulatedUsage"] = o.m_AccumulatedUsage;
  if (o.flowIdsIsSet() || !o.m_FlowIds.empty()) j["flowIds"] = o.m_FlowIds;
  if (o.appliedQosRefIsSet()) j["appliedQosRef"] = o.m_AppliedQosRef;
  if (o.plmnIdIsSet()) j["plmnId"] = o.m_PlmnId;
  if (o.qosMonReportsIsSet() || !o.m_QosMonReports.empty())
    j["qosMonReports"] = o.m_QosMonReports;
  if (o.ratTypeIsSet()) j["ratType"] = o.m_RatType;
}

void from_json(const nlohmann::json& j, UserPlaneEventReport& o) {
  if (j.find("event") != j.end()) {
    j.at("event").get_to(o.m_Event);
    o.m_EventIsSet = true;
  }
  if (j.find("accumulatedUsage") != j.end()) {
    j.at("accumulatedUsage").get_to(o.m_AccumulatedUsage);
    o.m_AccumulatedUsageIsSet = true;
  }
  if (j.find("flowIds") != j.end()) {
    j.at("flowIds").get_to(o.m_FlowIds);
    o.m_FlowIdsIsSet = true;
  }
  if (j.find("appliedQosRef") != j.end()) {
    j.at("appliedQosRef").get_to(o.m_AppliedQosRef);
    o.m_AppliedQosRefIsSet = true;
  }
  if (j.find("plmnId") != j.end()) {
    j.at("plmnId").get_to(o.m_PlmnId);
    o.m_PlmnIdIsSet = true;
  }
  if (j.find("qosMonReports") != j.end()) {
    j.at("qosMonReports").get_to(o.m_QosMonReports);
    o.m_QosMonReportsIsSet = true;
  }
  if (j.find("ratType") != j.end()) {
    j.at("ratType").get_to(o.m_RatType);
    o.m_RatTypeIsSet = true;
  }
}

oai::_3gpp::model::UserPlaneEvent UserPlaneEventReport::getEvent() const {
  return m_Event;
}
void UserPlaneEventReport::setEvent(
    oai::_3gpp::model::UserPlaneEvent const& value) {
  m_Event      = value;
  m_EventIsSet = true;
}
bool UserPlaneEventReport::eventIsSet() const {
  return m_EventIsSet;
}
void UserPlaneEventReport::unsetEvent() {
  m_EventIsSet = false;
}
oai::_3gpp::model::AccumulatedUsage UserPlaneEventReport::getAccumulatedUsage()
    const {
  return m_AccumulatedUsage;
}
void UserPlaneEventReport::setAccumulatedUsage(
    oai::_3gpp::model::AccumulatedUsage const& value) {
  m_AccumulatedUsage      = value;
  m_AccumulatedUsageIsSet = true;
}
bool UserPlaneEventReport::accumulatedUsageIsSet() const {
  return m_AccumulatedUsageIsSet;
}
void UserPlaneEventReport::unsetAccumulatedUsage() {
  m_AccumulatedUsageIsSet = false;
}
std::vector<int32_t> UserPlaneEventReport::getFlowIds() const {
  return m_FlowIds;
}
void UserPlaneEventReport::setFlowIds(std::vector<int32_t> const& value) {
  m_FlowIds      = value;
  m_FlowIdsIsSet = true;
}
bool UserPlaneEventReport::flowIdsIsSet() const {
  return m_FlowIdsIsSet;
}
void UserPlaneEventReport::unsetFlowIds() {
  m_FlowIdsIsSet = false;
}
std::string UserPlaneEventReport::getAppliedQosRef() const {
  return m_AppliedQosRef;
}
void UserPlaneEventReport::setAppliedQosRef(std::string const& value) {
  m_AppliedQosRef      = value;
  m_AppliedQosRefIsSet = true;
}
bool UserPlaneEventReport::appliedQosRefIsSet() const {
  return m_AppliedQosRefIsSet;
}
void UserPlaneEventReport::unsetAppliedQosRef() {
  m_AppliedQosRefIsSet = false;
}
oai::_3gpp::model::PlmnIdNid UserPlaneEventReport::getPlmnId() const {
  return m_PlmnId;
}
void UserPlaneEventReport::setPlmnId(
    oai::_3gpp::model::PlmnIdNid const& value) {
  m_PlmnId      = value;
  m_PlmnIdIsSet = true;
}
bool UserPlaneEventReport::plmnIdIsSet() const {
  return m_PlmnIdIsSet;
}
void UserPlaneEventReport::unsetPlmnId() {
  m_PlmnIdIsSet = false;
}
std::vector<oai::_3gpp::model::QosMonitoringReport>
UserPlaneEventReport::getQosMonReports() const {
  return m_QosMonReports;
}
void UserPlaneEventReport::setQosMonReports(
    std::vector<oai::_3gpp::model::QosMonitoringReport> const& value) {
  m_QosMonReports      = value;
  m_QosMonReportsIsSet = true;
}
bool UserPlaneEventReport::qosMonReportsIsSet() const {
  return m_QosMonReportsIsSet;
}
void UserPlaneEventReport::unsetQosMonReports() {
  m_QosMonReportsIsSet = false;
}
oai::_3gpp::model::RatType UserPlaneEventReport::getRatType() const {
  return m_RatType;
}
void UserPlaneEventReport::setRatType(oai::_3gpp::model::RatType const& value) {
  m_RatType      = value;
  m_RatTypeIsSet = true;
}
bool UserPlaneEventReport::ratTypeIsSet() const {
  return m_RatTypeIsSet;
}
void UserPlaneEventReport::unsetRatType() {
  m_RatTypeIsSet = false;
}

}  // namespace oai::_3gpp::model
