/**
 * Common Data Types
 * Common Data Types for Service Based Interfaces. © 2020, 3GPP Organizational
 * Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "Snssai.h"
#include "Helpers.h"
#include "config.hpp"

#include <sstream>
#include <fmt/format.h>

namespace oai::model::common {

Snssai::Snssai() {
  m_Sst     = 0;
  m_Sd      = "";
  m_SdIsSet = false;
}

void Snssai::validate() const {
  std::stringstream msg;
  if (!validate(msg)) {
    throw oai::model::common::helpers::ValidationException(msg.str());
  }
}

bool Snssai::validate(std::stringstream& msg) const {
  return validate(msg, "");
}

bool Snssai::validate(
    std::stringstream& msg, const std::string& pathPrefix) const {
  bool success                  = true;
  const std::string _pathPrefix = pathPrefix.empty() ? "Snssai" : pathPrefix;

  /* Sst */ {
    const int32_t& value               = m_Sst;
    const std::string currentValuePath = _pathPrefix + ".sst";

    if (value < 0) {
      success = false;
      msg << currentValuePath << ": must be greater than or equal to 0;";
    }
    if (value > 255) {
      success = false;
      msg << currentValuePath << ": must be less than or equal to 255;";
    }
  }
  if (sdIsSet()) {
    const std::string& value           = m_Sd;
    const std::string currentValuePath = _pathPrefix + ".sd";
    int32_t int_val                    = std::stoi(value, nullptr, 16);
    if (int_val < 0) {
      success = false;
      msg << currentValuePath << ": must be greater than or equal to 0;";
    } else if (int_val > 16777215) {
      success = false;
      msg << currentValuePath
          << ": must be less than or equal to 0xFFFFFF (16777215)";
    }
  }
  return success;
}

bool Snssai::operator==(const Snssai& rhs) const {
  return

      (getSst() == rhs.getSst()) &&

      ((!sdIsSet() && !rhs.sdIsSet()) ||
       (sdIsSet() && rhs.sdIsSet() && getSd() == rhs.getSd()))

          ;
}

bool Snssai::operator!=(const Snssai& rhs) const {
  return !(*this == rhs);
}

void to_json(nlohmann::json& j, const Snssai& o) {
  j        = nlohmann::json();
  j["sst"] = o.m_Sst;
  if (o.sdIsSet()) j["sd"] = o.m_Sd;
}

void from_json(const nlohmann::json& j, Snssai& o) {
  j.at("sst").get_to(o.m_Sst);
  if (j.find("sd") != j.end()) {
    // Here, we allow a more lenient API definition because we also allow it in
    // the config
    if (j.at("sd").is_number_integer()) {
      int val = j.at("sd");
      o.m_Sd  = fmt::format("{:X}", val);
    } else {
      j.at("sd").get_to(o.m_Sd);
    }
    o.m_SdIsSet = true;
  } else {
    // TODO this is not strictly standard-compliant
    o.m_Sd      = "FFFFFF";
    o.m_SdIsSet = true;
    // we set the default SD value to 0xFFFFFF
  }
}

int32_t Snssai::getSst() const {
  return m_Sst;
}
void Snssai::setSst(int32_t const value) {
  m_Sst = value;
}
std::string Snssai::getSd() const {
  return m_Sd;
}
void Snssai::setSd(std::string const& value) {
  m_Sd      = value;
  m_SdIsSet = true;
}

bool Snssai::sdIsSet() const {
  return m_SdIsSet;
}

void Snssai::unsetSd() {
  m_SdIsSet = false;
}

std::string Snssai::to_string(const int indent_level) const {
  std::string out;
  std::string fmt_title = oai::config::get_title_formatter(indent_level);
  std::string fmt_value = oai::config::get_value_formatter(indent_level + 1);
  out.append(fmt::format(fmt_title, "snssai:"));

  std::string sd_val =
      fmt::format("0x{} ({})", m_Sd, std::stoi(m_Sd, nullptr, 16));

  out.append(fmt::format(fmt_value, "sst", m_Sst));
  out.append(fmt::format(fmt_value, "sd", sd_val));
  return out;
}

}  // namespace oai::model::common
