/*
 * SPDX-License-Identifier: LicenseRef-CSSL-1.0
 */
/**
 * Nudr_DataRepository API OpenAPI file
 * Unified Data Repository Service. © 2020, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 2.1.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * RmInfo.h
 *
 *
 */

#ifndef RmInfo_H_
#define RmInfo_H_

#include <nlohmann/json.hpp>

#include "AccessType.h"
#include "RmState.h"

namespace oai::udr::model {

/// <summary>
///
/// </summary>
class RmInfo {
 public:
  RmInfo();
  virtual ~RmInfo();

  void validate();

  /////////////////////////////////////////////
  /// RmInfo members

  /// <summary>
  ///
  /// </summary>
  RmState getRmState() const;
  void setRmState(RmState const& value);
  /// <summary>
  ///
  /// </summary>
  oai::model::common::AccessType getAccessType() const;
  void setAccessType(oai::model::common::AccessType const& value);

  friend void to_json(nlohmann::json& j, const RmInfo& o);
  friend void from_json(const nlohmann::json& j, RmInfo& o);

 protected:
  RmState m_RmState;

  oai::model::common::AccessType m_AccessType;
};

}  // namespace oai::udr::model

#endif /* RmInfo_H_ */
