/*
 * Generated by asn1c-v1.5.1-0-gf96ad593-2026-06-25 (https://github.com/mouse07410/asn1c)
 */

#ifndef	_Ngap_ExtendedUEIdentityIndexValue_H_
#define	_Ngap_ExtendedUEIdentityIndexValue_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Ngap_ExtendedUEIdentityIndexValue */
typedef BIT_STRING_t	 Ngap_ExtendedUEIdentityIndexValue_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_Ngap_ExtendedUEIdentityIndexValue_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ExtendedUEIdentityIndexValue;
asn_struct_free_f Ngap_ExtendedUEIdentityIndexValue_free;
asn_struct_print_f Ngap_ExtendedUEIdentityIndexValue_print;
asn_constr_check_f Ngap_ExtendedUEIdentityIndexValue_constraint;
per_type_decoder_f Ngap_ExtendedUEIdentityIndexValue_decode_uper;
per_type_encoder_f Ngap_ExtendedUEIdentityIndexValue_encode_uper;
per_type_decoder_f Ngap_ExtendedUEIdentityIndexValue_decode_aper;
per_type_encoder_f Ngap_ExtendedUEIdentityIndexValue_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _Ngap_ExtendedUEIdentityIndexValue_H_ */
#include <asn_internal.h>
