/*
 * Generated by asn1c-v1.5.1-0-gf96ad593-2026-06-25 (https://github.com/mouse07410/asn1c)
 */

#ifndef	_Ngap_LastVisitedGERANCellInformation_H_
#define	_Ngap_LastVisitedGERANCellInformation_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Ngap_LastVisitedGERANCellInformation */
typedef OCTET_STRING_t	 Ngap_LastVisitedGERANCellInformation_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Ngap_LastVisitedGERANCellInformation;
asn_struct_free_f Ngap_LastVisitedGERANCellInformation_free;
asn_struct_print_f Ngap_LastVisitedGERANCellInformation_print;
asn_constr_check_f Ngap_LastVisitedGERANCellInformation_constraint;
per_type_decoder_f Ngap_LastVisitedGERANCellInformation_decode_uper;
per_type_encoder_f Ngap_LastVisitedGERANCellInformation_encode_uper;
per_type_decoder_f Ngap_LastVisitedGERANCellInformation_decode_aper;
per_type_encoder_f Ngap_LastVisitedGERANCellInformation_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _Ngap_LastVisitedGERANCellInformation_H_ */
#include <asn_internal.h>
