/*
 * Generated by asn1c-3cb9573-2026-05-12 (https://github.com/mouse07410/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "src/common-src/ngap/asn_r17/ts_38_413_v17_10_0.asn1"
 * 	`asn1c -pdu=all -fcompound-names -fno-include-deps -no-gen-example
 * -no-gen-JER -no-gen-BER -no-gen-UPER -S /tmp/mouse_asn1c/skeletons -D
 * /tmp/ngap_r17_gen`
 */

#ifndef _Ngap_FromEUTRANtoNGRAN_H_
#define _Ngap_FromEUTRANtoNGRAN_H_

#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Ngap_IntersystemSONeNBID;
struct Ngap_IntersystemSONNGRANnodeID;
struct Ngap_ProtocolExtensionContainer_12929P94;
struct Ngap_ProtocolExtensionContainer;

/* Ngap_FromEUTRANtoNGRAN */
typedef struct Ngap_FromEUTRANtoNGRAN {
  struct Ngap_IntersystemSONeNBID* sourceeNBID;
  struct Ngap_IntersystemSONNGRANnodeID* targetNGRANnodeID;
  struct Ngap_ProtocolExtensionContainer* iE_Extensions; /* OPTIONAL */

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_FromEUTRANtoNGRAN_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Ngap_FromEUTRANtoNGRAN;
extern asn_SEQUENCE_specifics_t asn_SPC_Ngap_FromEUTRANtoNGRAN_specs_1;
extern asn_TYPE_member_t asn_MBR_Ngap_FromEUTRANtoNGRAN_1[3];

#ifdef __cplusplus
}
#endif

#endif /* _Ngap_FromEUTRANtoNGRAN_H_ */
#include <asn_internal.h>
