/*
 * Generated by asn1c-3cb9573-2026-05-12 (https://github.com/mouse07410/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "src/common-src/ngap/asn_r17/ts_38_413_v17_10_0.asn1"
 * 	`asn1c -pdu=all -fcompound-names -fno-include-deps -no-gen-example -no-gen-JER -no-gen-BER -no-gen-UPER -S /tmp/mouse_asn1c/skeletons -D /tmp/ngap_r17_gen`
 */

#ifndef	_Ngap_PrivacyIndicator_H_
#define	_Ngap_PrivacyIndicator_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Ngap_PrivacyIndicator {
	Ngap_PrivacyIndicator_immediate_MDT	= 0,
	Ngap_PrivacyIndicator_logged_MDT	= 1
	/*
	 * Enumeration is extensible
	 */
} e_Ngap_PrivacyIndicator;

/* Ngap_PrivacyIndicator */
typedef long	 Ngap_PrivacyIndicator_t;

/* Implementation */
extern asn_oer_constraints_t asn_OER_type_Ngap_PrivacyIndicator_constr_1;
extern asn_per_constraints_t asn_PER_type_Ngap_PrivacyIndicator_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_PrivacyIndicator;
extern const asn_INTEGER_specifics_t asn_SPC_Ngap_PrivacyIndicator_specs_1;
asn_struct_free_f Ngap_PrivacyIndicator_free;
asn_struct_print_f Ngap_PrivacyIndicator_print;
asn_constr_check_f Ngap_PrivacyIndicator_constraint;
xer_type_decoder_f Ngap_PrivacyIndicator_decode_xer;
xer_type_encoder_f Ngap_PrivacyIndicator_encode_xer;
cbor_type_decoder_f Ngap_PrivacyIndicator_decode_cbor;
cbor_type_encoder_f Ngap_PrivacyIndicator_encode_cbor;
oer_type_decoder_f Ngap_PrivacyIndicator_decode_oer;
oer_type_encoder_f Ngap_PrivacyIndicator_encode_oer;
per_type_decoder_f Ngap_PrivacyIndicator_decode_aper;
per_type_encoder_f Ngap_PrivacyIndicator_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _Ngap_PrivacyIndicator_H_ */
#include <asn_internal.h>
