/*
 * Generated by asn1c-3cb9573-2026-05-12 (https://github.com/mouse07410/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "src/common-src/ngap/asn_r17/ts_38_413_v17_10_0.asn1"
 * 	`asn1c -pdu=all -fcompound-names -fno-include-deps -no-gen-example
 * -no-gen-JER -no-gen-BER -no-gen-UPER -S /tmp/mouse_asn1c/skeletons -D
 * /tmp/ngap_r17_gen`
 */

#ifndef _Ngap_CompletedCellsInTAI_NR_H_
#define _Ngap_CompletedCellsInTAI_NR_H_

#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Ngap_CompletedCellsInTAI_NR_Item;

/* Ngap_CompletedCellsInTAI-NR */
typedef struct Ngap_CompletedCellsInTAI_NR {
  A_SEQUENCE_OF(struct Ngap_CompletedCellsInTAI_NR_Item) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_CompletedCellsInTAI_NR_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Ngap_CompletedCellsInTAI_NR;
extern asn_SET_OF_specifics_t asn_SPC_Ngap_CompletedCellsInTAI_NR_specs_1;
extern asn_TYPE_member_t asn_MBR_Ngap_CompletedCellsInTAI_NR_1[1];
extern asn_oer_constraints_t asn_OER_type_Ngap_CompletedCellsInTAI_NR_constr_1;
extern asn_per_constraints_t asn_PER_type_Ngap_CompletedCellsInTAI_NR_constr_1;

#ifdef __cplusplus
}
#endif

#endif /* _Ngap_CompletedCellsInTAI_NR_H_ */
#include <asn_internal.h>
