/*
 * Generated by asn1c-v1.5.1-0-gf96ad593-2026-06-25
 * (https://github.com/mouse07410/asn1c)
 */

#ifndef _Ngap_CauseNas_H_
#define _Ngap_CauseNas_H_

#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Ngap_CauseNas {
  Ngap_CauseNas_normal_release         = 0,
  Ngap_CauseNas_authentication_failure = 1,
  Ngap_CauseNas_deregister             = 2,
  Ngap_CauseNas_unspecified            = 3,
  /*
   * Enumeration is extensible
   */
  Ngap_CauseNas_uE_not_in_PLMN_serving_area = 4
} e_Ngap_CauseNas;

/* Ngap_CauseNas */
typedef long Ngap_CauseNas_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_Ngap_CauseNas_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_CauseNas;
extern const asn_INTEGER_specifics_t asn_SPC_Ngap_CauseNas_specs_1;
asn_struct_free_f Ngap_CauseNas_free;
asn_struct_print_f Ngap_CauseNas_print;
asn_constr_check_f Ngap_CauseNas_constraint;
per_type_decoder_f Ngap_CauseNas_decode_uper;
per_type_encoder_f Ngap_CauseNas_encode_uper;
per_type_decoder_f Ngap_CauseNas_decode_aper;
per_type_encoder_f Ngap_CauseNas_encode_aper;

#ifdef __cplusplus
}
#endif

#endif /* _Ngap_CauseNas_H_ */
#include <asn_internal.h>
