/*
 * Generated by asn1c-v1.5.1-0-gf96ad593-2026-06-25
 * (https://github.com/mouse07410/asn1c)
 */

#ifndef _Ngap_ProtocolIE_Container_H_
#define _Ngap_ProtocolIE_Container_H_

#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/*
 * asn1c emits NGAP PDU content headers with protocolIEs declared as
 * struct Ngap_ProtocolIE_Container*, but the generated container header only
 * defines the numbered concrete Ngap_ProtocolIE_Container_* types.  Those
 * numbered containers share the same leading sequence/list layout, so provide
 * the generic definition too for C++ code that accesses protocolIEs->list.
 */
#ifndef NGAP_PROTOCOLIE_CONTAINER_GENERIC_STRUCT_DEFINED
#define NGAP_PROTOCOLIE_CONTAINER_GENERIC_STRUCT_DEFINED
struct Ngap_ProtocolIE_Container {
  asn_anonymous_sequence_ list;
  asn_struct_ctx_t _asn_ctx;
};
#endif

/* Forward declarations */
struct Ngap_PDUSessionResourceSetupRequestIEs;
struct Ngap_PDUSessionResourceSetupResponseIEs;
struct Ngap_PDUSessionResourceReleaseCommandIEs;
struct Ngap_PDUSessionResourceReleaseResponseIEs;
struct Ngap_PDUSessionResourceModifyRequestIEs;
struct Ngap_PDUSessionResourceModifyResponseIEs;
struct Ngap_PDUSessionResourceNotifyIEs;
struct Ngap_PDUSessionResourceModifyIndicationIEs;
struct Ngap_PDUSessionResourceModifyConfirmIEs;
struct Ngap_InitialContextSetupRequestIEs;
struct Ngap_InitialContextSetupResponseIEs;
struct Ngap_InitialContextSetupFailureIEs;
struct Ngap_UEContextReleaseRequest_IEs;
struct Ngap_UEContextReleaseCommand_IEs;
struct Ngap_UEContextReleaseComplete_IEs;
struct Ngap_UEContextResumeRequestIEs;
struct Ngap_UEContextResumeResponseIEs;
struct Ngap_UEContextResumeFailureIEs;
struct Ngap_UEContextSuspendRequestIEs;
struct Ngap_UEContextSuspendResponseIEs;
struct Ngap_UEContextSuspendFailureIEs;
struct Ngap_UEContextModificationRequestIEs;
struct Ngap_UEContextModificationResponseIEs;
struct Ngap_UEContextModificationFailureIEs;
struct Ngap_RRCInactiveTransitionReportIEs;
struct Ngap_RetrieveUEInformationIEs;
struct Ngap_UEInformationTransferIEs;
struct Ngap_RANCPRelocationIndicationIEs;
struct Ngap_HandoverRequiredIEs;
struct Ngap_HandoverCommandIEs;
struct Ngap_HandoverPreparationFailureIEs;
struct Ngap_HandoverRequestIEs;
struct Ngap_HandoverRequestAcknowledgeIEs;
struct Ngap_HandoverFailureIEs;
struct Ngap_HandoverNotifyIEs;
struct Ngap_PathSwitchRequestIEs;
struct Ngap_PathSwitchRequestAcknowledgeIEs;
struct Ngap_PathSwitchRequestFailureIEs;
struct Ngap_HandoverCancelIEs;
struct Ngap_HandoverCancelAcknowledgeIEs;
struct Ngap_HandoverSuccessIEs;
struct Ngap_UplinkRANEarlyStatusTransferIEs;
struct Ngap_DownlinkRANEarlyStatusTransferIEs;
struct Ngap_UplinkRANStatusTransferIEs;
struct Ngap_DownlinkRANStatusTransferIEs;
struct Ngap_PagingIEs;
struct Ngap_InitialUEMessage_IEs;
struct Ngap_DownlinkNASTransport_IEs;
struct Ngap_UplinkNASTransport_IEs;
struct Ngap_NASNonDeliveryIndication_IEs;
struct Ngap_RerouteNASRequest_IEs;
struct Ngap_NGSetupRequestIEs;
struct Ngap_NGSetupResponseIEs;
struct Ngap_NGSetupFailureIEs;
struct Ngap_RANConfigurationUpdateIEs;
struct Ngap_RANConfigurationUpdateAcknowledgeIEs;
struct Ngap_RANConfigurationUpdateFailureIEs;
struct Ngap_AMFConfigurationUpdateIEs;
struct Ngap_AMFConfigurationUpdateAcknowledgeIEs;
struct Ngap_AMFConfigurationUpdateFailureIEs;
struct Ngap_AMFStatusIndicationIEs;
struct Ngap_NGResetIEs;
struct Ngap_NGResetAcknowledgeIEs;
struct Ngap_ErrorIndicationIEs;
struct Ngap_OverloadStartIEs;
struct Ngap_OverloadStopIEs;
struct Ngap_UplinkRANConfigurationTransferIEs;
struct Ngap_DownlinkRANConfigurationTransferIEs;
struct Ngap_WriteReplaceWarningRequestIEs;
struct Ngap_WriteReplaceWarningResponseIEs;
struct Ngap_PWSCancelRequestIEs;
struct Ngap_PWSCancelResponseIEs;
struct Ngap_PWSRestartIndicationIEs;
struct Ngap_PWSFailureIndicationIEs;
struct Ngap_DownlinkUEAssociatedNRPPaTransportIEs;
struct Ngap_UplinkUEAssociatedNRPPaTransportIEs;
struct Ngap_DownlinkNonUEAssociatedNRPPaTransportIEs;
struct Ngap_UplinkNonUEAssociatedNRPPaTransportIEs;
struct Ngap_TraceStartIEs;
struct Ngap_TraceFailureIndicationIEs;
struct Ngap_DeactivateTraceIEs;
struct Ngap_CellTrafficTraceIEs;
struct Ngap_LocationReportingControlIEs;
struct Ngap_LocationReportingFailureIndicationIEs;
struct Ngap_LocationReportIEs;
struct Ngap_UETNLABindingReleaseRequestIEs;
struct Ngap_UERadioCapabilityInfoIndicationIEs;
struct Ngap_UERadioCapabilityCheckRequestIEs;
struct Ngap_UERadioCapabilityCheckResponseIEs;
struct Ngap_SecondaryRATDataUsageReportIEs;
struct Ngap_UplinkRIMInformationTransferIEs;
struct Ngap_DownlinkRIMInformationTransferIEs;
struct Ngap_ConnectionEstablishmentIndicationIEs;
struct Ngap_UERadioCapabilityIDMappingRequestIEs;
struct Ngap_UERadioCapabilityIDMappingResponseIEs;
struct Ngap_AMFCPRelocationIndicationIEs;
struct Ngap_BroadcastSessionSetupRequestIEs;
struct Ngap_BroadcastSessionSetupResponseIEs;
struct Ngap_BroadcastSessionSetupFailureIEs;
struct Ngap_BroadcastSessionModificationRequestIEs;
struct Ngap_BroadcastSessionModificationResponseIEs;
struct Ngap_BroadcastSessionModificationFailureIEs;
struct Ngap_BroadcastSessionReleaseRequestIEs;
struct Ngap_BroadcastSessionReleaseRequiredIEs;
struct Ngap_BroadcastSessionReleaseResponseIEs;
struct Ngap_DistributionSetupRequestIEs;
struct Ngap_DistributionSetupResponseIEs;
struct Ngap_DistributionSetupFailureIEs;
struct Ngap_DistributionReleaseRequestIEs;
struct Ngap_DistributionReleaseResponseIEs;
struct Ngap_MulticastSessionActivationRequestIEs;
struct Ngap_MulticastSessionActivationResponseIEs;
struct Ngap_MulticastSessionActivationFailureIEs;
struct Ngap_MulticastSessionDeactivationRequestIEs;
struct Ngap_MulticastSessionDeactivationResponseIEs;
struct Ngap_MulticastSessionUpdateRequestIEs;
struct Ngap_MulticastSessionUpdateResponseIEs;
struct Ngap_MulticastSessionUpdateFailureIEs;
struct Ngap_MulticastGroupPagingIEs;
struct Ngap_MBSSessionSetupOrModRequestTransferIEs;
struct Ngap_MulticastSessionUpdateRequestTransferIEs;
struct Ngap_PDUSessionResourceModifyRequestTransferIEs;
struct Ngap_PDUSessionResourceSetupRequestTransferIEs;

/* Ngap_ProtocolIE-Container */
typedef struct Ngap_ProtocolIE_Container_11929P0 {
  A_SEQUENCE_OF(struct Ngap_PDUSessionResourceSetupRequestIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_11929P0_t;
typedef struct Ngap_ProtocolIE_Container_11929P1 {
  A_SEQUENCE_OF(struct Ngap_PDUSessionResourceSetupResponseIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_11929P1_t;
typedef struct Ngap_ProtocolIE_Container_11929P2 {
  A_SEQUENCE_OF(struct Ngap_PDUSessionResourceReleaseCommandIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_11929P2_t;
typedef struct Ngap_ProtocolIE_Container_11929P3 {
  A_SEQUENCE_OF(struct Ngap_PDUSessionResourceReleaseResponseIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_11929P3_t;
typedef struct Ngap_ProtocolIE_Container_11929P4 {
  A_SEQUENCE_OF(struct Ngap_PDUSessionResourceModifyRequestIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_11929P4_t;
typedef struct Ngap_ProtocolIE_Container_11929P5 {
  A_SEQUENCE_OF(struct Ngap_PDUSessionResourceModifyResponseIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_11929P5_t;
typedef struct Ngap_ProtocolIE_Container_11929P6 {
  A_SEQUENCE_OF(struct Ngap_PDUSessionResourceNotifyIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_11929P6_t;
typedef struct Ngap_ProtocolIE_Container_11929P7 {
  A_SEQUENCE_OF(struct Ngap_PDUSessionResourceModifyIndicationIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_11929P7_t;
typedef struct Ngap_ProtocolIE_Container_11929P8 {
  A_SEQUENCE_OF(struct Ngap_PDUSessionResourceModifyConfirmIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_11929P8_t;
typedef struct Ngap_ProtocolIE_Container_11929P9 {
  A_SEQUENCE_OF(struct Ngap_InitialContextSetupRequestIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_11929P9_t;
typedef struct Ngap_ProtocolIE_Container_11929P10 {
  A_SEQUENCE_OF(struct Ngap_InitialContextSetupResponseIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_11929P10_t;
typedef struct Ngap_ProtocolIE_Container_11929P11 {
  A_SEQUENCE_OF(struct Ngap_InitialContextSetupFailureIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_11929P11_t;
typedef struct Ngap_ProtocolIE_Container_11929P12 {
  A_SEQUENCE_OF(struct Ngap_UEContextReleaseRequest_IEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_11929P12_t;
typedef struct Ngap_ProtocolIE_Container_11929P13 {
  A_SEQUENCE_OF(struct Ngap_UEContextReleaseCommand_IEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_11929P13_t;
typedef struct Ngap_ProtocolIE_Container_11929P14 {
  A_SEQUENCE_OF(struct Ngap_UEContextReleaseComplete_IEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_11929P14_t;
typedef struct Ngap_ProtocolIE_Container_11929P15 {
  A_SEQUENCE_OF(struct Ngap_UEContextResumeRequestIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_11929P15_t;
typedef struct Ngap_ProtocolIE_Container_11929P16 {
  A_SEQUENCE_OF(struct Ngap_UEContextResumeResponseIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_11929P16_t;
typedef struct Ngap_ProtocolIE_Container_11929P17 {
  A_SEQUENCE_OF(struct Ngap_UEContextResumeFailureIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_11929P17_t;
typedef struct Ngap_ProtocolIE_Container_11929P18 {
  A_SEQUENCE_OF(struct Ngap_UEContextSuspendRequestIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_11929P18_t;
typedef struct Ngap_ProtocolIE_Container_11929P19 {
  A_SEQUENCE_OF(struct Ngap_UEContextSuspendResponseIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_11929P19_t;
typedef struct Ngap_ProtocolIE_Container_11929P20 {
  A_SEQUENCE_OF(struct Ngap_UEContextSuspendFailureIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_11929P20_t;
typedef struct Ngap_ProtocolIE_Container_11929P21 {
  A_SEQUENCE_OF(struct Ngap_UEContextModificationRequestIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_11929P21_t;
typedef struct Ngap_ProtocolIE_Container_11929P22 {
  A_SEQUENCE_OF(struct Ngap_UEContextModificationResponseIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_11929P22_t;
typedef struct Ngap_ProtocolIE_Container_11929P23 {
  A_SEQUENCE_OF(struct Ngap_UEContextModificationFailureIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_11929P23_t;
typedef struct Ngap_ProtocolIE_Container_11929P24 {
  A_SEQUENCE_OF(struct Ngap_RRCInactiveTransitionReportIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_11929P24_t;
typedef struct Ngap_ProtocolIE_Container_11929P25 {
  A_SEQUENCE_OF(struct Ngap_RetrieveUEInformationIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_11929P25_t;
typedef struct Ngap_ProtocolIE_Container_11929P26 {
  A_SEQUENCE_OF(struct Ngap_UEInformationTransferIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_11929P26_t;
typedef struct Ngap_ProtocolIE_Container_11929P27 {
  A_SEQUENCE_OF(struct Ngap_RANCPRelocationIndicationIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_11929P27_t;
typedef struct Ngap_ProtocolIE_Container_11929P28 {
  A_SEQUENCE_OF(struct Ngap_HandoverRequiredIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_11929P28_t;
typedef struct Ngap_ProtocolIE_Container_11929P29 {
  A_SEQUENCE_OF(struct Ngap_HandoverCommandIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_11929P29_t;
typedef struct Ngap_ProtocolIE_Container_11929P30 {
  A_SEQUENCE_OF(struct Ngap_HandoverPreparationFailureIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_11929P30_t;
typedef struct Ngap_ProtocolIE_Container_11929P31 {
  A_SEQUENCE_OF(struct Ngap_HandoverRequestIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_11929P31_t;
typedef struct Ngap_ProtocolIE_Container_11929P32 {
  A_SEQUENCE_OF(struct Ngap_HandoverRequestAcknowledgeIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_11929P32_t;
typedef struct Ngap_ProtocolIE_Container_11929P33 {
  A_SEQUENCE_OF(struct Ngap_HandoverFailureIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_11929P33_t;
typedef struct Ngap_ProtocolIE_Container_11929P34 {
  A_SEQUENCE_OF(struct Ngap_HandoverNotifyIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_11929P34_t;
typedef struct Ngap_ProtocolIE_Container_11929P35 {
  A_SEQUENCE_OF(struct Ngap_PathSwitchRequestIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_11929P35_t;
typedef struct Ngap_ProtocolIE_Container_11929P36 {
  A_SEQUENCE_OF(struct Ngap_PathSwitchRequestAcknowledgeIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_11929P36_t;
typedef struct Ngap_ProtocolIE_Container_11929P37 {
  A_SEQUENCE_OF(struct Ngap_PathSwitchRequestFailureIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_11929P37_t;
typedef struct Ngap_ProtocolIE_Container_11929P38 {
  A_SEQUENCE_OF(struct Ngap_HandoverCancelIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_11929P38_t;
typedef struct Ngap_ProtocolIE_Container_11929P39 {
  A_SEQUENCE_OF(struct Ngap_HandoverCancelAcknowledgeIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_11929P39_t;
typedef struct Ngap_ProtocolIE_Container_11929P40 {
  A_SEQUENCE_OF(struct Ngap_HandoverSuccessIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_11929P40_t;
typedef struct Ngap_ProtocolIE_Container_11929P41 {
  A_SEQUENCE_OF(struct Ngap_UplinkRANEarlyStatusTransferIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_11929P41_t;
typedef struct Ngap_ProtocolIE_Container_11929P42 {
  A_SEQUENCE_OF(struct Ngap_DownlinkRANEarlyStatusTransferIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_11929P42_t;
typedef struct Ngap_ProtocolIE_Container_11929P43 {
  A_SEQUENCE_OF(struct Ngap_UplinkRANStatusTransferIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_11929P43_t;
typedef struct Ngap_ProtocolIE_Container_11929P44 {
  A_SEQUENCE_OF(struct Ngap_DownlinkRANStatusTransferIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_11929P44_t;
typedef struct Ngap_ProtocolIE_Container_11929P45 {
  A_SEQUENCE_OF(struct Ngap_PagingIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_11929P45_t;
typedef struct Ngap_ProtocolIE_Container_11929P46 {
  A_SEQUENCE_OF(struct Ngap_InitialUEMessage_IEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_11929P46_t;
typedef struct Ngap_ProtocolIE_Container_11929P47 {
  A_SEQUENCE_OF(struct Ngap_DownlinkNASTransport_IEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_11929P47_t;
typedef struct Ngap_ProtocolIE_Container_11929P48 {
  A_SEQUENCE_OF(struct Ngap_UplinkNASTransport_IEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_11929P48_t;
typedef struct Ngap_ProtocolIE_Container_11929P49 {
  A_SEQUENCE_OF(struct Ngap_NASNonDeliveryIndication_IEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_11929P49_t;
typedef struct Ngap_ProtocolIE_Container_11929P50 {
  A_SEQUENCE_OF(struct Ngap_RerouteNASRequest_IEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_11929P50_t;
typedef struct Ngap_ProtocolIE_Container_11929P51 {
  A_SEQUENCE_OF(struct Ngap_NGSetupRequestIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_11929P51_t;
typedef struct Ngap_ProtocolIE_Container_11929P52 {
  A_SEQUENCE_OF(struct Ngap_NGSetupResponseIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_11929P52_t;
typedef struct Ngap_ProtocolIE_Container_11929P53 {
  A_SEQUENCE_OF(struct Ngap_NGSetupFailureIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_11929P53_t;
typedef struct Ngap_ProtocolIE_Container_11929P54 {
  A_SEQUENCE_OF(struct Ngap_RANConfigurationUpdateIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_11929P54_t;
typedef struct Ngap_ProtocolIE_Container_11929P55 {
  A_SEQUENCE_OF(struct Ngap_RANConfigurationUpdateAcknowledgeIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_11929P55_t;
typedef struct Ngap_ProtocolIE_Container_11929P56 {
  A_SEQUENCE_OF(struct Ngap_RANConfigurationUpdateFailureIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_11929P56_t;
typedef struct Ngap_ProtocolIE_Container_11929P57 {
  A_SEQUENCE_OF(struct Ngap_AMFConfigurationUpdateIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_11929P57_t;
typedef struct Ngap_ProtocolIE_Container_11929P58 {
  A_SEQUENCE_OF(struct Ngap_AMFConfigurationUpdateAcknowledgeIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_11929P58_t;
typedef struct Ngap_ProtocolIE_Container_11929P59 {
  A_SEQUENCE_OF(struct Ngap_AMFConfigurationUpdateFailureIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_11929P59_t;
typedef struct Ngap_ProtocolIE_Container_11929P60 {
  A_SEQUENCE_OF(struct Ngap_AMFStatusIndicationIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_11929P60_t;
typedef struct Ngap_ProtocolIE_Container_11929P61 {
  A_SEQUENCE_OF(struct Ngap_NGResetIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_11929P61_t;
typedef struct Ngap_ProtocolIE_Container_11929P62 {
  A_SEQUENCE_OF(struct Ngap_NGResetAcknowledgeIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_11929P62_t;
typedef struct Ngap_ProtocolIE_Container_11929P63 {
  A_SEQUENCE_OF(struct Ngap_ErrorIndicationIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_11929P63_t;
typedef struct Ngap_ProtocolIE_Container_11929P64 {
  A_SEQUENCE_OF(struct Ngap_OverloadStartIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_11929P64_t;
typedef struct Ngap_ProtocolIE_Container_11929P65 {
  A_SEQUENCE_OF(struct Ngap_OverloadStopIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_11929P65_t;
typedef struct Ngap_ProtocolIE_Container_11929P66 {
  A_SEQUENCE_OF(struct Ngap_UplinkRANConfigurationTransferIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_11929P66_t;
typedef struct Ngap_ProtocolIE_Container_11929P67 {
  A_SEQUENCE_OF(struct Ngap_DownlinkRANConfigurationTransferIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_11929P67_t;
typedef struct Ngap_ProtocolIE_Container_11929P68 {
  A_SEQUENCE_OF(struct Ngap_WriteReplaceWarningRequestIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_11929P68_t;
typedef struct Ngap_ProtocolIE_Container_11929P69 {
  A_SEQUENCE_OF(struct Ngap_WriteReplaceWarningResponseIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_11929P69_t;
typedef struct Ngap_ProtocolIE_Container_11929P70 {
  A_SEQUENCE_OF(struct Ngap_PWSCancelRequestIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_11929P70_t;
typedef struct Ngap_ProtocolIE_Container_11929P71 {
  A_SEQUENCE_OF(struct Ngap_PWSCancelResponseIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_11929P71_t;
typedef struct Ngap_ProtocolIE_Container_11929P72 {
  A_SEQUENCE_OF(struct Ngap_PWSRestartIndicationIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_11929P72_t;
typedef struct Ngap_ProtocolIE_Container_11929P73 {
  A_SEQUENCE_OF(struct Ngap_PWSFailureIndicationIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_11929P73_t;
typedef struct Ngap_ProtocolIE_Container_11929P74 {
  A_SEQUENCE_OF(struct Ngap_DownlinkUEAssociatedNRPPaTransportIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_11929P74_t;
typedef struct Ngap_ProtocolIE_Container_11929P75 {
  A_SEQUENCE_OF(struct Ngap_UplinkUEAssociatedNRPPaTransportIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_11929P75_t;
typedef struct Ngap_ProtocolIE_Container_11929P76 {
  A_SEQUENCE_OF(struct Ngap_DownlinkNonUEAssociatedNRPPaTransportIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_11929P76_t;
typedef struct Ngap_ProtocolIE_Container_11929P77 {
  A_SEQUENCE_OF(struct Ngap_UplinkNonUEAssociatedNRPPaTransportIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_11929P77_t;
typedef struct Ngap_ProtocolIE_Container_11929P78 {
  A_SEQUENCE_OF(struct Ngap_TraceStartIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_11929P78_t;
typedef struct Ngap_ProtocolIE_Container_11929P79 {
  A_SEQUENCE_OF(struct Ngap_TraceFailureIndicationIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_11929P79_t;
typedef struct Ngap_ProtocolIE_Container_11929P80 {
  A_SEQUENCE_OF(struct Ngap_DeactivateTraceIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_11929P80_t;
typedef struct Ngap_ProtocolIE_Container_11929P81 {
  A_SEQUENCE_OF(struct Ngap_CellTrafficTraceIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_11929P81_t;
typedef struct Ngap_ProtocolIE_Container_11929P82 {
  A_SEQUENCE_OF(struct Ngap_LocationReportingControlIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_11929P82_t;
typedef struct Ngap_ProtocolIE_Container_11929P83 {
  A_SEQUENCE_OF(struct Ngap_LocationReportingFailureIndicationIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_11929P83_t;
typedef struct Ngap_ProtocolIE_Container_11929P84 {
  A_SEQUENCE_OF(struct Ngap_LocationReportIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_11929P84_t;
typedef struct Ngap_ProtocolIE_Container_11929P85 {
  A_SEQUENCE_OF(struct Ngap_UETNLABindingReleaseRequestIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_11929P85_t;
typedef struct Ngap_ProtocolIE_Container_11929P86 {
  A_SEQUENCE_OF(struct Ngap_UERadioCapabilityInfoIndicationIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_11929P86_t;
typedef struct Ngap_ProtocolIE_Container_11929P87 {
  A_SEQUENCE_OF(struct Ngap_UERadioCapabilityCheckRequestIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_11929P87_t;
typedef struct Ngap_ProtocolIE_Container_11929P88 {
  A_SEQUENCE_OF(struct Ngap_UERadioCapabilityCheckResponseIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_11929P88_t;
typedef struct Ngap_ProtocolIE_Container_11929P89 {
  A_SEQUENCE_OF(struct Ngap_SecondaryRATDataUsageReportIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_11929P89_t;
typedef struct Ngap_ProtocolIE_Container_11929P90 {
  A_SEQUENCE_OF(struct Ngap_UplinkRIMInformationTransferIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_11929P90_t;
typedef struct Ngap_ProtocolIE_Container_11929P91 {
  A_SEQUENCE_OF(struct Ngap_DownlinkRIMInformationTransferIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_11929P91_t;
typedef struct Ngap_ProtocolIE_Container_11929P92 {
  A_SEQUENCE_OF(struct Ngap_ConnectionEstablishmentIndicationIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_11929P92_t;
typedef struct Ngap_ProtocolIE_Container_11929P93 {
  A_SEQUENCE_OF(struct Ngap_UERadioCapabilityIDMappingRequestIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_11929P93_t;
typedef struct Ngap_ProtocolIE_Container_11929P94 {
  A_SEQUENCE_OF(struct Ngap_UERadioCapabilityIDMappingResponseIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_11929P94_t;
typedef struct Ngap_ProtocolIE_Container_11929P95 {
  A_SEQUENCE_OF(struct Ngap_AMFCPRelocationIndicationIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_11929P95_t;
typedef struct Ngap_ProtocolIE_Container_11929P96 {
  A_SEQUENCE_OF(struct Ngap_BroadcastSessionSetupRequestIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_11929P96_t;
typedef struct Ngap_ProtocolIE_Container_11929P97 {
  A_SEQUENCE_OF(struct Ngap_BroadcastSessionSetupResponseIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_11929P97_t;
typedef struct Ngap_ProtocolIE_Container_11929P98 {
  A_SEQUENCE_OF(struct Ngap_BroadcastSessionSetupFailureIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_11929P98_t;
typedef struct Ngap_ProtocolIE_Container_11929P99 {
  A_SEQUENCE_OF(struct Ngap_BroadcastSessionModificationRequestIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_11929P99_t;
typedef struct Ngap_ProtocolIE_Container_11929P100 {
  A_SEQUENCE_OF(struct Ngap_BroadcastSessionModificationResponseIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_11929P100_t;
typedef struct Ngap_ProtocolIE_Container_11929P101 {
  A_SEQUENCE_OF(struct Ngap_BroadcastSessionModificationFailureIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_11929P101_t;
typedef struct Ngap_ProtocolIE_Container_11929P102 {
  A_SEQUENCE_OF(struct Ngap_BroadcastSessionReleaseRequestIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_11929P102_t;
typedef struct Ngap_ProtocolIE_Container_11929P103 {
  A_SEQUENCE_OF(struct Ngap_BroadcastSessionReleaseRequiredIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_11929P103_t;
typedef struct Ngap_ProtocolIE_Container_11929P104 {
  A_SEQUENCE_OF(struct Ngap_BroadcastSessionReleaseResponseIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_11929P104_t;
typedef struct Ngap_ProtocolIE_Container_11929P105 {
  A_SEQUENCE_OF(struct Ngap_DistributionSetupRequestIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_11929P105_t;
typedef struct Ngap_ProtocolIE_Container_11929P106 {
  A_SEQUENCE_OF(struct Ngap_DistributionSetupResponseIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_11929P106_t;
typedef struct Ngap_ProtocolIE_Container_11929P107 {
  A_SEQUENCE_OF(struct Ngap_DistributionSetupFailureIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_11929P107_t;
typedef struct Ngap_ProtocolIE_Container_11929P108 {
  A_SEQUENCE_OF(struct Ngap_DistributionReleaseRequestIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_11929P108_t;
typedef struct Ngap_ProtocolIE_Container_11929P109 {
  A_SEQUENCE_OF(struct Ngap_DistributionReleaseResponseIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_11929P109_t;
typedef struct Ngap_ProtocolIE_Container_11929P110 {
  A_SEQUENCE_OF(struct Ngap_MulticastSessionActivationRequestIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_11929P110_t;
typedef struct Ngap_ProtocolIE_Container_11929P111 {
  A_SEQUENCE_OF(struct Ngap_MulticastSessionActivationResponseIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_11929P111_t;
typedef struct Ngap_ProtocolIE_Container_11929P112 {
  A_SEQUENCE_OF(struct Ngap_MulticastSessionActivationFailureIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_11929P112_t;
typedef struct Ngap_ProtocolIE_Container_11929P113 {
  A_SEQUENCE_OF(struct Ngap_MulticastSessionDeactivationRequestIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_11929P113_t;
typedef struct Ngap_ProtocolIE_Container_11929P114 {
  A_SEQUENCE_OF(struct Ngap_MulticastSessionDeactivationResponseIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_11929P114_t;
typedef struct Ngap_ProtocolIE_Container_11929P115 {
  A_SEQUENCE_OF(struct Ngap_MulticastSessionUpdateRequestIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_11929P115_t;
typedef struct Ngap_ProtocolIE_Container_11929P116 {
  A_SEQUENCE_OF(struct Ngap_MulticastSessionUpdateResponseIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_11929P116_t;
typedef struct Ngap_ProtocolIE_Container_11929P117 {
  A_SEQUENCE_OF(struct Ngap_MulticastSessionUpdateFailureIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_11929P117_t;
typedef struct Ngap_ProtocolIE_Container_11929P118 {
  A_SEQUENCE_OF(struct Ngap_MulticastGroupPagingIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_11929P118_t;
typedef struct Ngap_ProtocolIE_Container_11929P119 {
  A_SEQUENCE_OF(struct Ngap_MBSSessionSetupOrModRequestTransferIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_11929P119_t;
typedef struct Ngap_ProtocolIE_Container_11929P120 {
  A_SEQUENCE_OF(struct Ngap_MulticastSessionUpdateRequestTransferIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_11929P120_t;
typedef struct Ngap_ProtocolIE_Container_11929P121 {
  A_SEQUENCE_OF(struct Ngap_PDUSessionResourceModifyRequestTransferIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_11929P121_t;
typedef struct Ngap_ProtocolIE_Container_11929P122 {
  A_SEQUENCE_OF(struct Ngap_PDUSessionResourceSetupRequestTransferIEs) list;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_ProtocolIE_Container_11929P122_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_11929P0;
extern asn_SET_OF_specifics_t asn_SPC_Ngap_ProtocolIE_Container_11929P0_specs_1;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_11929P0_1[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_11929P0_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_11929P1;
extern asn_SET_OF_specifics_t asn_SPC_Ngap_ProtocolIE_Container_11929P1_specs_3;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_11929P1_3[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_11929P1_constr_3;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_11929P2;
extern asn_SET_OF_specifics_t asn_SPC_Ngap_ProtocolIE_Container_11929P2_specs_5;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_11929P2_5[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_11929P2_constr_5;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_11929P3;
extern asn_SET_OF_specifics_t asn_SPC_Ngap_ProtocolIE_Container_11929P3_specs_7;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_11929P3_7[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_11929P3_constr_7;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_11929P4;
extern asn_SET_OF_specifics_t asn_SPC_Ngap_ProtocolIE_Container_11929P4_specs_9;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_11929P4_9[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_11929P4_constr_9;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_11929P5;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_11929P5_specs_11;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_11929P5_11[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_11929P5_constr_11;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_11929P6;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_11929P6_specs_13;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_11929P6_13[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_11929P6_constr_13;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_11929P7;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_11929P7_specs_15;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_11929P7_15[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_11929P7_constr_15;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_11929P8;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_11929P8_specs_17;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_11929P8_17[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_11929P8_constr_17;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_11929P9;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_11929P9_specs_19;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_11929P9_19[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_11929P9_constr_19;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_11929P10;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_11929P10_specs_21;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_11929P10_21[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_11929P10_constr_21;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_11929P11;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_11929P11_specs_23;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_11929P11_23[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_11929P11_constr_23;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_11929P12;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_11929P12_specs_25;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_11929P12_25[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_11929P12_constr_25;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_11929P13;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_11929P13_specs_27;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_11929P13_27[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_11929P13_constr_27;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_11929P14;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_11929P14_specs_29;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_11929P14_29[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_11929P14_constr_29;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_11929P15;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_11929P15_specs_31;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_11929P15_31[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_11929P15_constr_31;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_11929P16;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_11929P16_specs_33;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_11929P16_33[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_11929P16_constr_33;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_11929P17;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_11929P17_specs_35;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_11929P17_35[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_11929P17_constr_35;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_11929P18;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_11929P18_specs_37;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_11929P18_37[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_11929P18_constr_37;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_11929P19;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_11929P19_specs_39;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_11929P19_39[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_11929P19_constr_39;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_11929P20;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_11929P20_specs_41;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_11929P20_41[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_11929P20_constr_41;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_11929P21;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_11929P21_specs_43;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_11929P21_43[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_11929P21_constr_43;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_11929P22;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_11929P22_specs_45;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_11929P22_45[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_11929P22_constr_45;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_11929P23;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_11929P23_specs_47;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_11929P23_47[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_11929P23_constr_47;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_11929P24;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_11929P24_specs_49;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_11929P24_49[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_11929P24_constr_49;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_11929P25;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_11929P25_specs_51;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_11929P25_51[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_11929P25_constr_51;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_11929P26;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_11929P26_specs_53;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_11929P26_53[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_11929P26_constr_53;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_11929P27;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_11929P27_specs_55;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_11929P27_55[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_11929P27_constr_55;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_11929P28;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_11929P28_specs_57;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_11929P28_57[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_11929P28_constr_57;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_11929P29;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_11929P29_specs_59;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_11929P29_59[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_11929P29_constr_59;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_11929P30;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_11929P30_specs_61;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_11929P30_61[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_11929P30_constr_61;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_11929P31;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_11929P31_specs_63;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_11929P31_63[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_11929P31_constr_63;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_11929P32;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_11929P32_specs_65;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_11929P32_65[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_11929P32_constr_65;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_11929P33;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_11929P33_specs_67;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_11929P33_67[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_11929P33_constr_67;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_11929P34;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_11929P34_specs_69;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_11929P34_69[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_11929P34_constr_69;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_11929P35;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_11929P35_specs_71;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_11929P35_71[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_11929P35_constr_71;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_11929P36;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_11929P36_specs_73;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_11929P36_73[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_11929P36_constr_73;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_11929P37;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_11929P37_specs_75;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_11929P37_75[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_11929P37_constr_75;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_11929P38;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_11929P38_specs_77;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_11929P38_77[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_11929P38_constr_77;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_11929P39;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_11929P39_specs_79;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_11929P39_79[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_11929P39_constr_79;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_11929P40;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_11929P40_specs_81;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_11929P40_81[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_11929P40_constr_81;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_11929P41;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_11929P41_specs_83;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_11929P41_83[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_11929P41_constr_83;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_11929P42;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_11929P42_specs_85;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_11929P42_85[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_11929P42_constr_85;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_11929P43;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_11929P43_specs_87;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_11929P43_87[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_11929P43_constr_87;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_11929P44;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_11929P44_specs_89;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_11929P44_89[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_11929P44_constr_89;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_11929P45;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_11929P45_specs_91;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_11929P45_91[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_11929P45_constr_91;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_11929P46;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_11929P46_specs_93;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_11929P46_93[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_11929P46_constr_93;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_11929P47;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_11929P47_specs_95;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_11929P47_95[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_11929P47_constr_95;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_11929P48;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_11929P48_specs_97;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_11929P48_97[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_11929P48_constr_97;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_11929P49;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_11929P49_specs_99;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_11929P49_99[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_11929P49_constr_99;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_11929P50;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_11929P50_specs_101;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_11929P50_101[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_11929P50_constr_101;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_11929P51;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_11929P51_specs_103;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_11929P51_103[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_11929P51_constr_103;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_11929P52;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_11929P52_specs_105;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_11929P52_105[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_11929P52_constr_105;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_11929P53;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_11929P53_specs_107;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_11929P53_107[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_11929P53_constr_107;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_11929P54;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_11929P54_specs_109;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_11929P54_109[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_11929P54_constr_109;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_11929P55;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_11929P55_specs_111;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_11929P55_111[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_11929P55_constr_111;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_11929P56;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_11929P56_specs_113;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_11929P56_113[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_11929P56_constr_113;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_11929P57;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_11929P57_specs_115;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_11929P57_115[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_11929P57_constr_115;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_11929P58;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_11929P58_specs_117;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_11929P58_117[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_11929P58_constr_117;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_11929P59;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_11929P59_specs_119;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_11929P59_119[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_11929P59_constr_119;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_11929P60;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_11929P60_specs_121;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_11929P60_121[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_11929P60_constr_121;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_11929P61;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_11929P61_specs_123;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_11929P61_123[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_11929P61_constr_123;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_11929P62;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_11929P62_specs_125;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_11929P62_125[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_11929P62_constr_125;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_11929P63;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_11929P63_specs_127;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_11929P63_127[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_11929P63_constr_127;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_11929P64;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_11929P64_specs_129;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_11929P64_129[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_11929P64_constr_129;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_11929P65;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_11929P65_specs_131;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_11929P65_131[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_11929P65_constr_131;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_11929P66;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_11929P66_specs_133;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_11929P66_133[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_11929P66_constr_133;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_11929P67;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_11929P67_specs_135;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_11929P67_135[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_11929P67_constr_135;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_11929P68;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_11929P68_specs_137;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_11929P68_137[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_11929P68_constr_137;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_11929P69;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_11929P69_specs_139;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_11929P69_139[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_11929P69_constr_139;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_11929P70;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_11929P70_specs_141;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_11929P70_141[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_11929P70_constr_141;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_11929P71;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_11929P71_specs_143;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_11929P71_143[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_11929P71_constr_143;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_11929P72;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_11929P72_specs_145;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_11929P72_145[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_11929P72_constr_145;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_11929P73;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_11929P73_specs_147;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_11929P73_147[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_11929P73_constr_147;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_11929P74;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_11929P74_specs_149;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_11929P74_149[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_11929P74_constr_149;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_11929P75;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_11929P75_specs_151;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_11929P75_151[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_11929P75_constr_151;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_11929P76;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_11929P76_specs_153;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_11929P76_153[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_11929P76_constr_153;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_11929P77;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_11929P77_specs_155;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_11929P77_155[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_11929P77_constr_155;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_11929P78;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_11929P78_specs_157;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_11929P78_157[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_11929P78_constr_157;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_11929P79;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_11929P79_specs_159;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_11929P79_159[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_11929P79_constr_159;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_11929P80;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_11929P80_specs_161;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_11929P80_161[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_11929P80_constr_161;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_11929P81;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_11929P81_specs_163;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_11929P81_163[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_11929P81_constr_163;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_11929P82;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_11929P82_specs_165;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_11929P82_165[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_11929P82_constr_165;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_11929P83;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_11929P83_specs_167;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_11929P83_167[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_11929P83_constr_167;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_11929P84;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_11929P84_specs_169;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_11929P84_169[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_11929P84_constr_169;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_11929P85;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_11929P85_specs_171;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_11929P85_171[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_11929P85_constr_171;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_11929P86;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_11929P86_specs_173;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_11929P86_173[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_11929P86_constr_173;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_11929P87;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_11929P87_specs_175;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_11929P87_175[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_11929P87_constr_175;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_11929P88;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_11929P88_specs_177;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_11929P88_177[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_11929P88_constr_177;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_11929P89;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_11929P89_specs_179;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_11929P89_179[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_11929P89_constr_179;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_11929P90;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_11929P90_specs_181;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_11929P90_181[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_11929P90_constr_181;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_11929P91;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_11929P91_specs_183;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_11929P91_183[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_11929P91_constr_183;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_11929P92;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_11929P92_specs_185;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_11929P92_185[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_11929P92_constr_185;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_11929P93;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_11929P93_specs_187;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_11929P93_187[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_11929P93_constr_187;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_11929P94;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_11929P94_specs_189;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_11929P94_189[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_11929P94_constr_189;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_11929P95;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_11929P95_specs_191;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_11929P95_191[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_11929P95_constr_191;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_11929P96;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_11929P96_specs_193;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_11929P96_193[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_11929P96_constr_193;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_11929P97;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_11929P97_specs_195;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_11929P97_195[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_11929P97_constr_195;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_11929P98;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_11929P98_specs_197;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_11929P98_197[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_11929P98_constr_197;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_11929P99;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_11929P99_specs_199;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_11929P99_199[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_11929P99_constr_199;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_11929P100;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_11929P100_specs_201;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_11929P100_201[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_11929P100_constr_201;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_11929P101;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_11929P101_specs_203;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_11929P101_203[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_11929P101_constr_203;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_11929P102;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_11929P102_specs_205;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_11929P102_205[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_11929P102_constr_205;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_11929P103;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_11929P103_specs_207;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_11929P103_207[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_11929P103_constr_207;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_11929P104;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_11929P104_specs_209;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_11929P104_209[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_11929P104_constr_209;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_11929P105;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_11929P105_specs_211;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_11929P105_211[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_11929P105_constr_211;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_11929P106;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_11929P106_specs_213;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_11929P106_213[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_11929P106_constr_213;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_11929P107;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_11929P107_specs_215;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_11929P107_215[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_11929P107_constr_215;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_11929P108;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_11929P108_specs_217;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_11929P108_217[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_11929P108_constr_217;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_11929P109;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_11929P109_specs_219;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_11929P109_219[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_11929P109_constr_219;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_11929P110;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_11929P110_specs_221;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_11929P110_221[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_11929P110_constr_221;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_11929P111;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_11929P111_specs_223;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_11929P111_223[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_11929P111_constr_223;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_11929P112;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_11929P112_specs_225;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_11929P112_225[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_11929P112_constr_225;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_11929P113;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_11929P113_specs_227;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_11929P113_227[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_11929P113_constr_227;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_11929P114;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_11929P114_specs_229;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_11929P114_229[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_11929P114_constr_229;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_11929P115;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_11929P115_specs_231;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_11929P115_231[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_11929P115_constr_231;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_11929P116;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_11929P116_specs_233;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_11929P116_233[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_11929P116_constr_233;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_11929P117;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_11929P117_specs_235;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_11929P117_235[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_11929P117_constr_235;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_11929P118;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_11929P118_specs_237;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_11929P118_237[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_11929P118_constr_237;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_11929P119;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_11929P119_specs_239;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_11929P119_239[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_11929P119_constr_239;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_11929P120;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_11929P120_specs_241;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_11929P120_241[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_11929P120_constr_241;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_11929P121;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_11929P121_specs_243;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_11929P121_243[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_11929P121_constr_243;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ProtocolIE_Container_11929P122;
extern asn_SET_OF_specifics_t
    asn_SPC_Ngap_ProtocolIE_Container_11929P122_specs_245;
extern asn_TYPE_member_t asn_MBR_Ngap_ProtocolIE_Container_11929P122_245[1];
extern asn_per_constraints_t
    asn_PER_type_Ngap_ProtocolIE_Container_11929P122_constr_245;

#ifdef __cplusplus
}
#endif

#endif /* _Ngap_ProtocolIE_Container_H_ */
#include <asn_internal.h>
