/*
 * Generated by asn1c-v1.5.1-0-gf96ad593-2026-06-25
 * (https://github.com/mouse07410/asn1c)
 */

#ifndef _Ngap_PathSwitchRequestUnsuccessfulTransfer_H_
#define _Ngap_PathSwitchRequestUnsuccessfulTransfer_H_

#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Ngap_Cause;
struct Ngap_ProtocolExtensionContainer_11980P210;
struct Ngap_ProtocolExtensionContainer;

/* Ngap_PathSwitchRequestUnsuccessfulTransfer */
typedef struct Ngap_PathSwitchRequestUnsuccessfulTransfer {
  struct Ngap_Cause* cause;
  struct Ngap_ProtocolExtensionContainer* iE_Extensions; /* OPTIONAL */
  /*
   * This type is extensible,
   * possible extensions are below.
   */

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_PathSwitchRequestUnsuccessfulTransfer_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Ngap_PathSwitchRequestUnsuccessfulTransfer;

#ifdef __cplusplus
}
#endif

#endif /* _Ngap_PathSwitchRequestUnsuccessfulTransfer_H_ */
#include <asn_internal.h>
