/*
 * Generated by asn1c-v1.5.1-0-gf96ad593-2026-06-25 (https://github.com/mouse07410/asn1c)
 */

#ifndef	_Ngap_RecommendedRANNodesForPaging_H_
#define	_Ngap_RecommendedRANNodesForPaging_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Ngap_RecommendedRANNodeList;
struct Ngap_ProtocolExtensionContainer_11980P290;
struct Ngap_ProtocolExtensionContainer;

/* Ngap_RecommendedRANNodesForPaging */
typedef struct Ngap_RecommendedRANNodesForPaging {
	struct Ngap_RecommendedRANNodeList	*recommendedRANNodeList;
	struct Ngap_ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Ngap_RecommendedRANNodesForPaging_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Ngap_RecommendedRANNodesForPaging;
extern asn_SEQUENCE_specifics_t asn_SPC_Ngap_RecommendedRANNodesForPaging_specs_1;
extern asn_TYPE_member_t asn_MBR_Ngap_RecommendedRANNodesForPaging_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _Ngap_RecommendedRANNodesForPaging_H_ */
#include <asn_internal.h>
