/*
 * Generated by asn1c-v1.5.1-0-gf96ad593-2026-06-25
 * (https://github.com/mouse07410/asn1c)
 */

#ifndef _Ngap_UEPresence_H_
#define _Ngap_UEPresence_H_

#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Ngap_UEPresence {
  Ngap_UEPresence_in      = 0,
  Ngap_UEPresence_out     = 1,
  Ngap_UEPresence_unknown = 2
  /*
   * Enumeration is extensible
   */
} e_Ngap_UEPresence;

/* Ngap_UEPresence */
typedef long Ngap_UEPresence_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_Ngap_UEPresence_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_UEPresence;
extern const asn_INTEGER_specifics_t asn_SPC_Ngap_UEPresence_specs_1;
asn_struct_free_f Ngap_UEPresence_free;
asn_struct_print_f Ngap_UEPresence_print;
asn_constr_check_f Ngap_UEPresence_constraint;
per_type_decoder_f Ngap_UEPresence_decode_uper;
per_type_encoder_f Ngap_UEPresence_encode_uper;
per_type_decoder_f Ngap_UEPresence_decode_aper;
per_type_encoder_f Ngap_UEPresence_encode_aper;

#ifdef __cplusplus
}
#endif

#endif /* _Ngap_UEPresence_H_ */
#include <asn_internal.h>
