/*
 * Generated by asn1c-v1.5.1-0-gf96ad593-2026-06-25
 * (https://github.com/mouse07410/asn1c)
 */

#include "Ngap_PDUSessionResourceModifyIndicationTransfer.h"

#include "Ngap_QosFlowPerTNLInformation.h"
#include "Ngap_QosFlowPerTNLInformationList.h"
#include "Ngap_ProtocolExtensionContainer.h"
static asn_TYPE_member_t
    asn_MBR_Ngap_PDUSessionResourceModifyIndicationTransfer_1[] = {
        {ATF_POINTER,
         0,
         offsetof(
             struct Ngap_PDUSessionResourceModifyIndicationTransfer,
             dLQosFlowPerTNLInformation),
         (ASN_TAG_CLASS_CONTEXT | (0 << 2)),
         -1, /* IMPLICIT tag at current level */
         &asn_DEF_Ngap_QosFlowPerTNLInformation,
         0,
         {
#if !defined(ASN_DISABLE_OER_SUPPORT)
             0,
#endif /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
             0,
#endif /* !defined(ASN_DISABLE_UPER_SUPPORT) ||                                \
          !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
             0,
#endif /* !defined(ASN_DISABLE_JER_SUPPORT) */
             0},
         0,
         0, /* No default value */
         "dLQosFlowPerTNLInformation"},
        {ATF_POINTER,
         2,
         offsetof(
             struct Ngap_PDUSessionResourceModifyIndicationTransfer,
             additionalDLQosFlowPerTNLInformation),
         (ASN_TAG_CLASS_CONTEXT | (1 << 2)),
         -1, /* IMPLICIT tag at current level */
         &asn_DEF_Ngap_QosFlowPerTNLInformationList,
         0,
         {
#if !defined(ASN_DISABLE_OER_SUPPORT)
             0,
#endif /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
             0,
#endif /* !defined(ASN_DISABLE_UPER_SUPPORT) ||                                \
          !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
             0,
#endif /* !defined(ASN_DISABLE_JER_SUPPORT) */
             0},
         0,
         0, /* No default value */
         "additionalDLQosFlowPerTNLInformation"},
        {ATF_POINTER,
         1,
         offsetof(
             struct Ngap_PDUSessionResourceModifyIndicationTransfer,
             iE_Extensions),
         (ASN_TAG_CLASS_CONTEXT | (2 << 2)),
         -1, /* IMPLICIT tag at current level */
         &asn_DEF_Ngap_ProtocolExtensionContainer_11980P233,
         0,
         {
#if !defined(ASN_DISABLE_OER_SUPPORT)
             0,
#endif /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
             0,
#endif /* !defined(ASN_DISABLE_UPER_SUPPORT) ||                                \
          !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
             0,
#endif /* !defined(ASN_DISABLE_JER_SUPPORT) */
             0},
         0,
         0, /* No default value */
         "iE-Extensions"},
};
static const int
    asn_MAP_Ngap_PDUSessionResourceModifyIndicationTransfer_oms_1[] = {1, 2};
static const ber_tlv_tag_t
    asn_DEF_Ngap_PDUSessionResourceModifyIndicationTransfer_tags_1[] = {
        (ASN_TAG_CLASS_UNIVERSAL | (16 << 2))};
static const asn_TYPE_tag2member_t
    asn_MAP_Ngap_PDUSessionResourceModifyIndicationTransfer_tag2el_1[] = {
        {(ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0,
         0}, /* dLQosFlowPerTNLInformation */
        {(ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0,
         0}, /* additionalDLQosFlowPerTNLInformation */
        {(ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0} /* iE-Extensions */
};
static asn_SEQUENCE_specifics_t
    asn_SPC_Ngap_PDUSessionResourceModifyIndicationTransfer_specs_1 = {
        sizeof(struct Ngap_PDUSessionResourceModifyIndicationTransfer),
        offsetof(
            struct Ngap_PDUSessionResourceModifyIndicationTransfer, _asn_ctx),
        asn_MAP_Ngap_PDUSessionResourceModifyIndicationTransfer_tag2el_1,
        3, /* Count of tags in the map */
        asn_MAP_Ngap_PDUSessionResourceModifyIndicationTransfer_oms_1, /* Optional
                                                                          members
                                                                        */
        2,
        0, /* Root/Additions */
        3, /* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_Ngap_PDUSessionResourceModifyIndicationTransfer = {
    "PDUSessionResourceModifyIndicationTransfer",
    "PDUSessionResourceModifyIndicationTransfer",
    &asn_OP_SEQUENCE,
    asn_DEF_Ngap_PDUSessionResourceModifyIndicationTransfer_tags_1,
    sizeof(asn_DEF_Ngap_PDUSessionResourceModifyIndicationTransfer_tags_1) /
        sizeof(asn_DEF_Ngap_PDUSessionResourceModifyIndicationTransfer_tags_1
                   [0]),                                            /* 1 */
    asn_DEF_Ngap_PDUSessionResourceModifyIndicationTransfer_tags_1, /* Same
                                                                       as
                                                                       above
                                                                     */
    sizeof(asn_DEF_Ngap_PDUSessionResourceModifyIndicationTransfer_tags_1) /
        sizeof(asn_DEF_Ngap_PDUSessionResourceModifyIndicationTransfer_tags_1
                   [0]), /* 1 */
    {
#if !defined(ASN_DISABLE_OER_SUPPORT)
        0,
#endif /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
        0,
#endif /* !defined(ASN_DISABLE_UPER_SUPPORT) ||                                \
          !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
        0,
#endif /* !defined(ASN_DISABLE_JER_SUPPORT) */
        SEQUENCE_constraint},
    asn_MBR_Ngap_PDUSessionResourceModifyIndicationTransfer_1,
    3, /* Elements count */
    &asn_SPC_Ngap_PDUSessionResourceModifyIndicationTransfer_specs_1 /* Additional
                                                                        specs
                                                                      */
};
