/*
 * Generated by asn1c-v1.5.1-0-gf96ad593-2026-06-25 (https://github.com/mouse07410/asn1c)
 */

#ifndef	_Ngap_S_NSSAI_H_
#define	_Ngap_S_NSSAI_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Ngap_SST.h"
#include "Ngap_SD.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Ngap_ProtocolExtensionContainer_11980P310;
struct Ngap_ProtocolExtensionContainer;

/* Ngap_S-NSSAI */
typedef struct Ngap_S_NSSAI {
	Ngap_SST_t	 sST;
	Ngap_SD_t	*sD;	/* OPTIONAL */
	struct Ngap_ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Ngap_S_NSSAI_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Ngap_S_NSSAI;
extern asn_SEQUENCE_specifics_t asn_SPC_Ngap_S_NSSAI_specs_1;
extern asn_TYPE_member_t asn_MBR_Ngap_S_NSSAI_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _Ngap_S_NSSAI_H_ */
#include <asn_internal.h>
