/*
 * Generated by asn1c-v1.5.1-0-gf96ad593-2026-06-25 (https://github.com/mouse07410/asn1c)
 */

#ifndef	_Ngap_QoEReference_H_
#define	_Ngap_QoEReference_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Ngap_QoEReference */
typedef OCTET_STRING_t	 Ngap_QoEReference_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_Ngap_QoEReference_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_QoEReference;
asn_struct_free_f Ngap_QoEReference_free;
asn_struct_print_f Ngap_QoEReference_print;
asn_constr_check_f Ngap_QoEReference_constraint;
per_type_decoder_f Ngap_QoEReference_decode_uper;
per_type_encoder_f Ngap_QoEReference_encode_uper;
per_type_decoder_f Ngap_QoEReference_decode_aper;
per_type_encoder_f Ngap_QoEReference_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _Ngap_QoEReference_H_ */
#include <asn_internal.h>
