/*
 * Generated by asn1c-v1.5.1-0-gf96ad593-2026-06-25
 * (https://github.com/mouse07410/asn1c)
 */

#ifndef _Ngap_DRBStatusUL12_H_
#define _Ngap_DRBStatusUL12_H_

#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Ngap_COUNTValueForPDCP_SN12;
struct Ngap_ProtocolExtensionContainer_11980P62;
struct Ngap_ProtocolExtensionContainer;

/* Ngap_DRBStatusUL12 */
typedef struct Ngap_DRBStatusUL12 {
  struct Ngap_COUNTValueForPDCP_SN12* uL_COUNTValue;
  BIT_STRING_t* receiveStatusOfUL_PDCP_SDUs;            /* OPTIONAL */
  struct Ngap_ProtocolExtensionContainer* iE_Extension; /* OPTIONAL */
  /*
   * This type is extensible,
   * possible extensions are below.
   */

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_DRBStatusUL12_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Ngap_DRBStatusUL12;
extern asn_SEQUENCE_specifics_t asn_SPC_Ngap_DRBStatusUL12_specs_1;
extern asn_TYPE_member_t asn_MBR_Ngap_DRBStatusUL12_1[3];

#ifdef __cplusplus
}
#endif

#endif /* _Ngap_DRBStatusUL12_H_ */
#include <asn_internal.h>
