/*
 * Generated by asn1c-3cb9573-2026-05-12 (https://github.com/mouse07410/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "src/common-src/ngap/asn_r17/ts_38_413_v17_10_0.asn1"
 * 	`asn1c -pdu=all -fcompound-names -fno-include-deps -no-gen-example
 * -no-gen-JER -no-gen-BER -no-gen-UPER -S /tmp/mouse_asn1c/skeletons -D
 * /tmp/ngap_r17_gen`
 */

#include "Ngap_RRCEstablishmentCause.h"

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
#if !defined(ASN_DISABLE_OER_SUPPORT)
asn_oer_constraints_t asn_OER_type_Ngap_RRCEstablishmentCause_constr_1
    CC_NOTUSED = {{0, 0}, -1};
#endif /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_Ngap_RRCEstablishmentCause_constr_1
    CC_NOTUSED = {
        {APC_CONSTRAINED | APC_EXTENSIBLE, 4, 4, 0, 9} /* (0..9,...) */,
        {APC_UNCONSTRAINED, -1, -1, 0, 0},
        0,
        0 /* No PER value map */
};
#endif /* !defined(ASN_DISABLE_UPER_SUPPORT) ||                                \
          !defined(ASN_DISABLE_APER_SUPPORT) */
static const asn_INTEGER_enum_map_t
    asn_MAP_Ngap_RRCEstablishmentCause_value2enum_1[] = {
        {0, 9, "emergency"},
        {1, 18, "highPriorityAccess"},
        {2, 9, "mt-Access"},
        {3, 13, "mo-Signalling"},
        {4, 7, "mo-Data"},
        {5, 12, "mo-VoiceCall"},
        {6, 12, "mo-VideoCall"},
        {7, 6, "mo-SMS"},
        {8, 18, "mps-PriorityAccess"},
        {9, 18, "mcs-PriorityAccess"},
        {10, 12, "notAvailable"},
        {11, 16, "mo-ExceptionData"}
        /* This list is extensible */
};
static int asn_validate_Ngap_RRCEstablishmentCause_1(
    const asn_TYPE_descriptor_t* td, const void* sptr,
    asn_app_constraint_failed_f* ctfailcb, void* app_key) {
  if (!sptr) {
    return -1;
  }
  e_Ngap_RRCEstablishmentCause value = *(e_Ngap_RRCEstablishmentCause*) sptr;
  switch (value) {
    case Ngap_RRCEstablishmentCause_emergency:
    case Ngap_RRCEstablishmentCause_highPriorityAccess:
    case Ngap_RRCEstablishmentCause_mt_Access:
    case Ngap_RRCEstablishmentCause_mo_Signalling:
    case Ngap_RRCEstablishmentCause_mo_Data:
    case Ngap_RRCEstablishmentCause_mo_VoiceCall:
    case Ngap_RRCEstablishmentCause_mo_VideoCall:
    case Ngap_RRCEstablishmentCause_mo_SMS:
    case Ngap_RRCEstablishmentCause_mps_PriorityAccess:
    case Ngap_RRCEstablishmentCause_mcs_PriorityAccess:
    case Ngap_RRCEstablishmentCause_notAvailable:
    case Ngap_RRCEstablishmentCause_mo_ExceptionData:
      return 0;
  }
  return -1;
}
static const unsigned int asn_MAP_Ngap_RRCEstablishmentCause_enum2value_1[] = {
    0,  /* emergency(0) */
    1,  /* highPriorityAccess(1) */
    9,  /* mcs-PriorityAccess(9) */
    4,  /* mo-Data(4) */
    11, /* mo-ExceptionData(11) */
    7,  /* mo-SMS(7) */
    3,  /* mo-Signalling(3) */
    6,  /* mo-VideoCall(6) */
    5,  /* mo-VoiceCall(5) */
    8,  /* mps-PriorityAccess(8) */
    2,  /* mt-Access(2) */
    10  /* notAvailable(10) */
        /* This list is extensible */
};
const asn_INTEGER_specifics_t asn_SPC_Ngap_RRCEstablishmentCause_specs_1 = {
    asn_MAP_Ngap_RRCEstablishmentCause_value2enum_1, /* "tag" => N; sorted by
                                                        tag */
    asn_MAP_Ngap_RRCEstablishmentCause_enum2value_1, /* N => "tag"; sorted by N
                                                      */
    12, /* Number of elements in the maps */
    11, /* Extensions before this member */
    1,  /* Strict enumeration */
    0,  /* Native long size */
    0};
static const ber_tlv_tag_t asn_DEF_Ngap_RRCEstablishmentCause_tags_1[] = {
    (ASN_TAG_CLASS_UNIVERSAL | (10 << 2))};
asn_TYPE_descriptor_t asn_DEF_Ngap_RRCEstablishmentCause = {
    "RRCEstablishmentCause",
    "RRCEstablishmentCause",
    &asn_OP_NativeEnumerated,
    asn_DEF_Ngap_RRCEstablishmentCause_tags_1,
    sizeof(asn_DEF_Ngap_RRCEstablishmentCause_tags_1) /
        sizeof(asn_DEF_Ngap_RRCEstablishmentCause_tags_1[0]), /* 1 */
    asn_DEF_Ngap_RRCEstablishmentCause_tags_1, /* Same as above */
    sizeof(asn_DEF_Ngap_RRCEstablishmentCause_tags_1) /
        sizeof(asn_DEF_Ngap_RRCEstablishmentCause_tags_1[0]), /* 1 */
    {
#if !defined(ASN_DISABLE_OER_SUPPORT)
        &asn_OER_type_Ngap_RRCEstablishmentCause_constr_1,
#endif /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
        &asn_PER_type_Ngap_RRCEstablishmentCause_constr_1,
#endif /* !defined(ASN_DISABLE_UPER_SUPPORT) ||                                \
          !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
        0,
#endif /* !defined(ASN_DISABLE_JER_SUPPORT) */
        asn_validate_Ngap_RRCEstablishmentCause_1},
    0,
    0,                                          /* Defined elsewhere */
    &asn_SPC_Ngap_RRCEstablishmentCause_specs_1 /* Additional specs */
};
