/*
 * Generated by asn1c-v1.5.1-0-gf96ad593-2026-06-25 (https://github.com/mouse07410/asn1c)
 */

#ifndef	_Ngap_TraceDepth_H_
#define	_Ngap_TraceDepth_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Ngap_TraceDepth {
	Ngap_TraceDepth_minimum	= 0,
	Ngap_TraceDepth_medium	= 1,
	Ngap_TraceDepth_maximum	= 2,
	Ngap_TraceDepth_minimumWithoutVendorSpecificExtension	= 3,
	Ngap_TraceDepth_mediumWithoutVendorSpecificExtension	= 4,
	Ngap_TraceDepth_maximumWithoutVendorSpecificExtension	= 5
	/*
	 * Enumeration is extensible
	 */
} e_Ngap_TraceDepth;

/* Ngap_TraceDepth */
typedef long	 Ngap_TraceDepth_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_Ngap_TraceDepth_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_TraceDepth;
extern const asn_INTEGER_specifics_t asn_SPC_Ngap_TraceDepth_specs_1;
asn_struct_free_f Ngap_TraceDepth_free;
asn_struct_print_f Ngap_TraceDepth_print;
asn_constr_check_f Ngap_TraceDepth_constraint;
per_type_decoder_f Ngap_TraceDepth_decode_uper;
per_type_encoder_f Ngap_TraceDepth_encode_uper;
per_type_decoder_f Ngap_TraceDepth_decode_aper;
per_type_encoder_f Ngap_TraceDepth_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _Ngap_TraceDepth_H_ */
#include <asn_internal.h>
