/*
 * Generated by asn1c-v1.5.1-0-gf96ad593-2026-06-25 (https://github.com/mouse07410/asn1c)
 */

#ifndef	_Ngap_NRintegrityProtectionAlgorithms_H_
#define	_Ngap_NRintegrityProtectionAlgorithms_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Ngap_NRintegrityProtectionAlgorithms */
typedef BIT_STRING_t	 Ngap_NRintegrityProtectionAlgorithms_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_Ngap_NRintegrityProtectionAlgorithms_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_NRintegrityProtectionAlgorithms;
asn_struct_free_f Ngap_NRintegrityProtectionAlgorithms_free;
asn_struct_print_f Ngap_NRintegrityProtectionAlgorithms_print;
asn_constr_check_f Ngap_NRintegrityProtectionAlgorithms_constraint;
per_type_decoder_f Ngap_NRintegrityProtectionAlgorithms_decode_uper;
per_type_encoder_f Ngap_NRintegrityProtectionAlgorithms_encode_uper;
per_type_decoder_f Ngap_NRintegrityProtectionAlgorithms_decode_aper;
per_type_encoder_f Ngap_NRintegrityProtectionAlgorithms_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _Ngap_NRintegrityProtectionAlgorithms_H_ */
#include <asn_internal.h>
