/*
 * Generated by asn1c-v1.5.1-0-gf96ad593-2026-06-25
 * (https://github.com/mouse07410/asn1c)
 */

#ifndef _Ngap_IntersystemResourceStatusRequest_H_
#define _Ngap_IntersystemResourceStatusRequest_H_

#include <asn_application.h>

/* Including external dependencies */
#include "Ngap_ReportCharacteristics.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Ngap_ReportingSystem;
struct Ngap_ReportType;
struct Ngap_ProtocolExtensionContainer_11980P122;
struct Ngap_ProtocolExtensionContainer;

/* Ngap_IntersystemResourceStatusRequest */
typedef struct Ngap_IntersystemResourceStatusRequest {
  struct Ngap_ReportingSystem* reportingSystem;
  Ngap_ReportCharacteristics_t reportCharacteristics;
  struct Ngap_ReportType* reportType;
  struct Ngap_ProtocolExtensionContainer* iE_Extensions; /* OPTIONAL */
  /*
   * This type is extensible,
   * possible extensions are below.
   */

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} Ngap_IntersystemResourceStatusRequest_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Ngap_IntersystemResourceStatusRequest;
extern asn_SEQUENCE_specifics_t
    asn_SPC_Ngap_IntersystemResourceStatusRequest_specs_1;
extern asn_TYPE_member_t asn_MBR_Ngap_IntersystemResourceStatusRequest_1[4];

#ifdef __cplusplus
}
#endif

#endif /* _Ngap_IntersystemResourceStatusRequest_H_ */
#include <asn_internal.h>
