/*
 * Generated by asn1c-v1.5.1-0-gf96ad593-2026-06-25 (https://github.com/mouse07410/asn1c)
 */

#ifndef	_Ngap_UEPresenceInAreaOfInterestList_H_
#define	_Ngap_UEPresenceInAreaOfInterestList_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Ngap_UEPresenceInAreaOfInterestItem;

/* Ngap_UEPresenceInAreaOfInterestList */
typedef struct Ngap_UEPresenceInAreaOfInterestList {
	A_SEQUENCE_OF(struct Ngap_UEPresenceInAreaOfInterestItem) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Ngap_UEPresenceInAreaOfInterestList_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Ngap_UEPresenceInAreaOfInterestList;
extern asn_SET_OF_specifics_t asn_SPC_Ngap_UEPresenceInAreaOfInterestList_specs_1;
extern asn_TYPE_member_t asn_MBR_Ngap_UEPresenceInAreaOfInterestList_1[1];
extern asn_per_constraints_t asn_PER_type_Ngap_UEPresenceInAreaOfInterestList_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _Ngap_UEPresenceInAreaOfInterestList_H_ */
#include <asn_internal.h>
