/*
 * Generated by asn1c-v1.5.1-0-gf96ad593-2026-06-25 (https://github.com/mouse07410/asn1c)
 */

#ifndef	_Ngap_AlternativeQoSParaSetItem_H_
#define	_Ngap_AlternativeQoSParaSetItem_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Ngap_AlternativeQoSParaSetIndex.h"
#include "Ngap_BitRate.h"
#include "Ngap_PacketDelayBudget.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Ngap_PacketErrorRate;
struct Ngap_ProtocolExtensionContainer_11980P4;
struct Ngap_ProtocolExtensionContainer;

/* Ngap_AlternativeQoSParaSetItem */
typedef struct Ngap_AlternativeQoSParaSetItem {
	Ngap_AlternativeQoSParaSetIndex_t	 alternativeQoSParaSetIndex;
	Ngap_BitRate_t	*guaranteedFlowBitRateDL;	/* OPTIONAL */
	Ngap_BitRate_t	*guaranteedFlowBitRateUL;	/* OPTIONAL */
	Ngap_PacketDelayBudget_t	*packetDelayBudget;	/* OPTIONAL */
	struct Ngap_PacketErrorRate	*packetErrorRate;	/* OPTIONAL */
	struct Ngap_ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Ngap_AlternativeQoSParaSetItem_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Ngap_AlternativeQoSParaSetItem;
extern asn_SEQUENCE_specifics_t asn_SPC_Ngap_AlternativeQoSParaSetItem_specs_1;
extern asn_TYPE_member_t asn_MBR_Ngap_AlternativeQoSParaSetItem_1[6];

#ifdef __cplusplus
}
#endif

#endif	/* _Ngap_AlternativeQoSParaSetItem_H_ */
#include <asn_internal.h>
