/*
 * Generated by asn1c-v1.5.1-0-gf96ad593-2026-06-25 (https://github.com/mouse07410/asn1c)
 */

#ifndef	_Ngap_PacketDelayBudget_H_
#define	_Ngap_PacketDelayBudget_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Ngap_PacketDelayBudget */
typedef long	 Ngap_PacketDelayBudget_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_Ngap_PacketDelayBudget_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_PacketDelayBudget;
asn_struct_free_f Ngap_PacketDelayBudget_free;
asn_struct_print_f Ngap_PacketDelayBudget_print;
asn_constr_check_f Ngap_PacketDelayBudget_constraint;
per_type_decoder_f Ngap_PacketDelayBudget_decode_uper;
per_type_encoder_f Ngap_PacketDelayBudget_encode_uper;
per_type_decoder_f Ngap_PacketDelayBudget_decode_aper;
per_type_encoder_f Ngap_PacketDelayBudget_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _Ngap_PacketDelayBudget_H_ */
#include <asn_internal.h>
