/*
 * Generated by asn1c-v1.5.1-0-gf96ad593-2026-06-25 (https://github.com/mouse07410/asn1c)
 */

#ifndef	_Ngap_ServiceType_H_
#define	_Ngap_ServiceType_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Ngap_ServiceType {
	Ngap_ServiceType_streaming	= 0,
	Ngap_ServiceType_mTSI	= 1,
	Ngap_ServiceType_vR	= 2
	/*
	 * Enumeration is extensible
	 */
} e_Ngap_ServiceType;

/* Ngap_ServiceType */
typedef long	 Ngap_ServiceType_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_Ngap_ServiceType_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_Ngap_ServiceType;
extern const asn_INTEGER_specifics_t asn_SPC_Ngap_ServiceType_specs_1;
asn_struct_free_f Ngap_ServiceType_free;
asn_struct_print_f Ngap_ServiceType_print;
asn_constr_check_f Ngap_ServiceType_constraint;
per_type_decoder_f Ngap_ServiceType_decode_uper;
per_type_encoder_f Ngap_ServiceType_encode_uper;
per_type_decoder_f Ngap_ServiceType_decode_aper;
per_type_encoder_f Ngap_ServiceType_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _Ngap_ServiceType_H_ */
#include <asn_internal.h>
